### ISSUE TITLE
Invalid remote public key

### ISSUE THREAD

**Issue by CjHare** [Consensys-Incorporated/teku#1230]
### Description
As an Teku, I want import a block so that I can sync with the Sapphire Testnet.

### Acceptance Criteria
Import block.

### Steps to Reproduce (Bug)
1. Start Teku
2. Watch log file for exception

**Expected behavior:** [What you expect to happen]
Not encounter an exception

**Actual behavior:** [What actually happens]
```
2020-02-26 09:37:37.146+10:00 | nioEventLoopGroup-3-14 | ERROR | SafeFuture | Unhandled exception
io.libp2p.etc.types.NonCompleteException: java.util.concurrent.CompletionException: io.libp2p.security.InvalidRemotePubKey
at io.libp2p.etc.types.AsyncExtKt$anyComplete$1$$special$$inlined$forEach$lambda$1.accept(AsyncExt.kt:69) [jvm-libp2p-minimal-0.3.2-RELEASE.jar:?]
at io.libp2p.etc.types.AsyncExtKt$anyComplete$1$$special$$inlined$forEach$lambda$1.accept(AsyncExt.kt:63) [jvm-libp2p-minimal-0.3.2-RELEASE.jar:?]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) [?:?]
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) [?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) [?:?]
at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) [?:?]
at io.libp2p.etc.types.AsyncExtKt$bind$1.accept(AsyncExt.kt:13) [jvm-libp2p-minimal-0.3.2-RELEASE.jar:?]
at io.libp2p.etc.types.AsyncExtKt$bind$1.accept(AsyncExt.kt) [jvm-libp2p-minimal-0.3.2-RELEASE.jar:?]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) [?:?]
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) [?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) [?:?]
at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) [?:?]
at io.libp2p.etc.types.AsyncExtKt$bind$1.accept(AsyncExt.kt:13) [jvm-libp2p-minimal-0.3.2-RELEASE.jar:?]
at io.libp2p.etc.types.AsyncExtKt$bind$1.accept(AsyncExt.kt) [jvm-libp2p-minimal-0.3.2-RELEASE.jar:?]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) [?:?]
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) [?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) [?:?]
at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) [?:?]
at io.libp2p.security.secio.SecIoHandshake.exceptionCaught(SecIoSecureChannel.kt:86) [jvm-libp2p-minimal-0.3.2-RELEASE.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:297) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.notifyHandlerException(AbstractChannelHandlerContext.java:831) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:376) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:249) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.callHandlerRemoved(AbstractChannelHandlerContext.java:972) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:638) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:481) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:421) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.libp2p.multistream.Negotiator$GenericHandler.channelRead0(Negotiator.kt:101) [jvm-libp2p-minimal-0.3.2-RELEASE.jar:?]
at io.libp2p.multistream.Negotiator$GenericHandler.channelRead0(Negotiator.kt:70) [jvm-libp2p-minimal-0.3.2-RELEASE.jar:?]
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.36.Final.jar:4.1.36.Final]
at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.util.concurrent.CompletionException: io.libp2p.security.InvalidRemotePubKey
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) [?:?]
at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) [?:?]
at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632) ~[?:?]
... 67 more
Caused by: io.libp2p.security.InvalidRemotePubKey
at io.libp2p.security.secio.SecIoNegotiator.validateRemoteKey(SecIoNegotiator.kt:144) ~[jvm-libp2p-minimal-0.3.2-RELEASE.jar:?]
at io.libp2p.security.secio.SecIoNegotiator.verifyRemoteProposal(SecIoNegotiator.kt:121) ~[jvm-libp2p-minimal-0.3.2-RELEASE.jar:?]
at io.libp2p.security.secio.SecIoNegotiator.onNewMessage(SecIoNegotiator.kt:106) ~[jvm-libp2p-minimal-0.3.2-RELEASE.jar:?]
at io.libp2p.security.secio.SecIoHandshake.channelRead0(SecIoSecureChannel.kt:61) ~[jvm-libp2p-minimal-0.3.2-RELEASE.jar:?]
at io.libp2p.security.secio.SecIoHandshake.channelRead0(SecIoSecureChannel.kt:39) ~[jvm-libp2p-minimal-0.3.2-RELEASE.jar:?]
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[netty-all-4.1.36.Final.jar:4.1.36.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[netty-all-4.1.36.Final.jar:4.1.36.Final]
... 55 more

```

**Frequency:** [What percentage of the time does it occur?]
Every time

### Versions (Add all that apply)
* Software version: [`artemis --version`]
* Java version: 
```
java version "11.0.3" 2019-04-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.3+12-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.3+12-LTS, mixed mode)
```
* Kernel Version:
```
Darwin hops.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64
```

### Additional Information
Config:
```
[node]
# networkMode options:
# "mock": use MockP2PNetwork
# "jvmlibp2p" : use JvmLibP2PNetwork
networkMode = "jvmlibp2p"
networkInterface = "127.0.0.1"
port = 13000
discovery = "static"
bootnodes = "/dns4/prylabs.net/tcp/30001/p2p/16Uiu2HAm7Qwe19vz9WzD2Mxn7fXd1vgHHp4iccuyq7TxwRXoAGfc"
advertisedPort = 13000
constants = "/code/pegasys/sapphire_testnet/local_run_config/sapphire/constants.yml"
peers = [
"/ip4/18.224.32.112/tcp/13000/p2p/16Uiu2HAmQWDaYerDBRnaNSiWMMLPUzn1GijPF1U5JDPeeK2rcU8v",
"/ip4/3.234.170.62/tcp/30000/p2p/QmfAgkmjiZNZhr2wFN9TwaRgHouMTBT6HELyzE5A3BT2wK",
"/ip4/95.216.35.247/tcp/13000/p2p/16Uiu2HAm5vgsELMSyPp7hYE1Uwsf92C8WGaG9LctC5broGMfZUk9",
"/ip4/210.54.38.228/tcp/13000/p2p/16Uiu2HAm9EqfCpXHQxYJXRkLMFn2VaJPcUHTMUDdxPqtKPkeZ49L",
"/ip4/99.242.122.114/tcp/13000/p2p/16Uiu2HAmLpabFfbMpMyZhqEevu2hCfCuiRyc2gSWaRUVP9ozSA8j",
"/ip4/39.105.108.213/tcp/13000/p2p/16Uiu2HAmEGX1QRxxNVJTqd2gaQoJ3TsGVyswKS5hBE3MjMpyV6kE",
"/ip4/194.55.12.148/tcp/64455/p2p/16Uiu2HAmTDAVj6VSk7mkZZiASMvP6XjBXZoJPyoL5DZaU56pu3z7",
"/ip4/148.251.128.119/tcp/13001/p2p/16Uiu2HAm31CrTnSqozW2o1ovsmZ6wxRXioYBpRSLvQGyq8QtfWRP",
"/ip4/82.64.46.19/tcp/13000/p2p/16Uiu2HAm2N2D88NPfP6dQrhxTMvUjzs3WPYd8gpXPPPu2YZFmKtw",
"/ip4/34.195.87.142/tcp/13000/p2p/16Uiu2HAmT6NNV8qrWRGoqZxBNiCMHSMTYikhWiyTT7ux1yocqtsx",
"/ip4/185.22.143.84/tcp/13000/p2p/16Uiu2HAmRMqPe1nR1yAwUEpBKzUh8ABHzcMBSRnnK1z4fkuARu8e",
"/ip4/148.251.128.119/tcp/13000/p2p/16Uiu2HAmAsyW714qpiYz9dNEoDyLa29SuzXwU4sY3fQrRtUxN1bT",
"/ip4/51.178.47.10/tcp/1025/p2p/16Uiu2HAm4TsWtLtCmsS4szLRUacQiNFVAcJxZPHjPiDS9XnHLRC6",
"/ip4/34.195.2.210/tcp/13000/p2p/16Uiu2HAmEhpnUJhpdzpiduRRrRCkpQAGZsUq3qJmWpvbdzFUWdeJ",
"/ip4/62.210.207.65/tcp/13000/p2p/16Uiu2HAmJNZnTxJ2U3aHr8gzLb4xZnHmVXUPTNkQQMuFcP9RPg11",
"/ip4/179.48.251.37/tcp/13000/p2p/16Uiu2HAmBdfGtWxpjoPF2Q8Jw6sT2Sm7DNGYoXt3q7nTp5vyt1GM",
"/ip4/34.77.131.239/tcp/13000/p2p/16Uiu2HAmBJzJXEcDRNTvz9NJYefrZjE5AHae4HCiaPNGEqttQTcp",
"/ip4/219.92.88.1/tcp/13000/p2p/16Uiu2HAmPDrU7HgZkzzAGDB2VKdc96iE45pisTp3sK7aw9iSFrAW",
"/ip4/82.130.11.57/tcp/9560/p2p/16Uiu2HAmMdg3RVaF4unSEdgkGxLM5uhqd7z5o1H26apNpax6EpUz",
"/ip4/213.194.183.239/tcp/1979/p2p/16Uiu2HAmS4EcqLTa8otsYa5cTkWeQaRiKdafXJCnZ9ada9MJ1fry",
"/ip4/47.42.133.159/tcp/13000/p2p/16Uiu2HAmVLccJXL98ETjv8kKXdg2C8rJcYySLZRDb9Z2yeWgedoJ",
"/ip4/87.224.87.146/tcp/38105/p2p/16Uiu2HAm1zjQZ2LLqcBagsripmNf9FpR5MzEogSp9GM8iYW59bH5",
"/ip4/83.44.75.129/tcp/13000/p2p/16Uiu2HAmR5aWj3BkJAWeAbhRwgTE4q2p7kyD9aBXheAjNXVy9Lpz",
"/ip4/50.53.143.66/tcp/1030/p2p/16Uiu2HAmVhJ98uDQEiG2VHHzTKPr3RJmFQJYB8tfRTW1CM4P4Vho",
"/ip4/86.120.164.1/tcp/13000/p2p/16Uiu2HAkziEshvBpnme6fjpUnbvMBbaVL24t21awgoVj9y9ioDFX",
"/ip4/188.2.114.131/tcp/13000/p2p/16Uiu2HAmKdV4qWm9ppgVeHPRi6tncd2Urr8KxXx5GKfHZV6z5c1W",
"/ip4/188.194.31.5/tcp/13000/p2p/16Uiu2HAkwPNFxuvK9MLYNudRTUsQWJAycbde1KBy3W3Nk43PaK9x",
"/ip4/23.98.223.68/tcp/13000/p2p/16Uiu2HAm7ruW6N9xyeJMqZwUX4wUfvMUhKRgGQadLYxaPwubVPr5",
"/ip4/5.42.129.6/tcp/13000/p2p/16Uiu2HAm6JNHfP9SWCf6JMv7pxhGeyXXHz6MuNiTrebBeRzYkQds",
"/ip4/159.65.222.193/tcp/13000/p2p/16Uiu2HAmF2Nou5jbfiRwNFyrobVAk1h4PhtXetoTXkdJrP94sHhF",
"/ip4/169.254.172.42/tcp/13000/p2p/16Uiu2HAkyQp149ph5PPvboNaZkNBBHrAyPFizipzKys2dzu7p65w",
"/ip4/91.223.175.173/tcp/13000/p2p/16Uiu2HAmJWkoLCEXFUj921Du7F2id5aQcKvnvnoZfZiZ2ECsdfUP",
"/ip4/47.93.25.82/tcp/13000/p2p/16Uiu2HAmGTMSwGoDRivZuq1DoTXEVEqWDryfkX5KZ5h33X6pH7pN",
"/ip4/134.255.174.206/tcp/1027/p2p/16Uiu2HAkyv8DVzN985pQnmio1obhEpptHDRXPYExWsMeggbftJn7",
"/ip4/97.113.128.78/tcp/13000/p2p/16Uiu2HAmFa38yLmX9fnqanTvZXgVPxDc57zWyXn6uq5nRVUoa6rs",
"/ip4/159.65.222.193/tcp/13000/p2p/16Uiu2HAmE8wajtMLTk4xrfhhLr93icGpHRGFfq74wzmciu4TkW3G",
"/ip4/34.76.128.226/tcp/12653/p2p/16Uiu2HAkw3n2n9rcRC1SRcPuE2yRG7jqFVVYQYMrMxkKJgUQUnag",
"/ip4/173.249.54.25/tcp/13000/p2p/16Uiu2HAmHgCzQPbtkqhycP7Q6AyqHVGJ3DMpzDvFjdG5LjbbU4Bm",
"/ip4/194.55.12.148/tcp/13000/p2p/16Uiu2HAkyz91Gb8F6pPpD5tDrFGnce34ozy8KSzXkWHeqKi3bAek",
"/ip4/173.212.241.121/tcp/13000/p2p/16Uiu2HAm1rJq9A5RJ9ffttTosVmYsfXXNnKkmbMQJDq3BmCdW4DC",
"/ip4/188.2.114.131/tcp/13000/p2p/16Uiu2HAkwUptTmttS1L4YoprcZiDFwDpQnRYVyk2ADz6r9B97Jbs",
"/ip4/88.10.92.84/tcp/3838/p2p/16Uiu2HAmSNpWPUVzcp2EJCCw5mWJhmVjdH61xEe4jtpyx1Pr4tL6",
"/ip4/47.93.25.82/tcp/13000/p2p/16Uiu2HAmUZsroKfRszSqtid9mnkqPEfnQn8XYiXSyNMLdxmaSoBm",
"/ip4/138.68.244.172/tcp/13000/p2p/16Uiu2HAmDeLA2TTfyrNR8LjpRXCiibcFsyth4dnzEqfxbUkf29Ef",
"/ip4/95.216.220.230/tcp/13000/p2p/16Uiu2HAmCGbW9gEH6cZMVqX6aWqViBmGrzsJduEQZfLSCnq22v9J",
"/ip4/47.75.26.167/tcp/13000/p2p/16Uiu2HAmMEtjiX1pjEX8eX8nWjhfsSMbbDQnaTfvEo9VpdGwdNbY",
"/ip4/80.15.146.215/tcp/18089/p2p/16Uiu2HAm3ZPCDXERZ1uzq8fvRC6JpnjHzxis53NKX3mbeutLwtVr",
"/ip4/209.133.192.58/tcp/13000/p2p/16Uiu2HAmJ1e4AxqtrLuY35zJ5BsZTX3rGETMC8nUEqVnp84SUqKi",
"/ip4/116.203.225.47/tcp/13000/p2p/16Uiu2HAm7uvhALaXSfa7aMxm3mSYNTUuEZB9HjaEGsuripWEAHyJ"
]


[interop]
# when genesis time is set to 0, artemis takes genesis time as currentTime + 5 seconds.
genesisTime = 0
# ownedValidatorStartIndex = 0
ownedValidatorCount = 0
startState = "/code/pegasys/sapphire_testnet/local_run_config/sapphire/genesis.ssz"
#this.privKey.bytes().toHexString() who's corresponding sha2(publicKey) == 16Uiu2HAm8cQB9DcwMtaSVuHNiJEPSq9mXM6FHho7c55M6XN2P3EQ
# privateKey = "0x08021221008166B8EF20C11F3A18F8774BF834173B07F64BAEDA981766896B4A8F53B52EDF"

[validator]
#validatorsKeyFile = "keys.yaml"

[deposit]
# normal, test, simulation
# "test" pre-production
# "simulation" to run a simulation of deposits with ganache-cli, if a inputFile is included the file will replay the deposits
# "normal" production, must include contractAddr and nodeUrl
mode = "normal"
inputFile = "" #"validator_test_data.json"
numValidators = 64
numNodes = 2
contractAddr = "0x4689a3C63CE249355C8a573B5974db21D2d1b8Ef"
nodeUrl = "http://goerli.prylabs.net/"

[output]
logPath = "."
logFile = "artemis.log"
transitionRecordDir = "/tmp/artemis"

[metrics]
enabled = false
#port = 8008
metricsNetworkInterface = "127.0.0.1"
#metricsCategories = [ "BEACONCHAIN", "JVM", "PROCESS" ]
peers = ["/dns4/prylabs.net/tcp/30001/p2p/16Uiu2HAm7Qwe19vz9WzD2Mxn7fXd1vgHHp4iccuyq7TxwRXoAGfc"]

[database]
startFromDisk = false

[beaconrestapi]
portNumber = 5051

```

**Comment by ajsutton** [comment]
One of the peers in your static list is using a different PeerId to what's in the multiaddr you've added.  We detect this difference when connecting and reject them as a fraud.  So the error is correct, but shouldn't be logged at ERROR level as it's normal behaviour.

Also:
`bootnodes = "/dns4/prylabs.net/tcp/30001/p2p/16Uiu2HAm7Qwe19vz9WzD2Mxn7fXd1vgHHp4iccuyq7TxwRXoAGfc"`

won't work because that's a libp2p Multiaddr, not a discovery v5 ENR.  Prysm's testnet is not running discv5.
