### ISSUE TITLE
SIGTERM doesn't seem to be caught when running from Gradle

### ISSUE THREAD

**Issue by jrhea** [Consensys-Incorporated/teku#132]
### Description
For some reason SIGTERM isn't caught when running Artemis from Gradle

### Acceptance Criteria
* Fix to gradle.build that makes it work

### Steps to Reproduce (Bug)
1. `/gradlew run`
2. Hit Ctrl-C

**Expected behavior:** [What you expect to happen]
You should see a message on the command line that says: 'Artemis is shutting down'

**Actual behavior:** [What actually happens]
It immediately stops Artemis without executing the stopAll tasks

**Frequency:** [What percentage of the time does it occur?]
100%

**Comment by cemozerr** [comment]
Actually, Artemis executes stopAll tasks. At the very least, I have confirmed that the run function in the shutdown hook gets called. 

To test that the shutdown hook and the run function gets called, I added a write to file call to the run function in Artemis.java, as shown below, and a similar write to file call to the stopAll function in ServiceController.java :
```
// Detect SIGTERM
Runtime.getRuntime().addShutdownHook(new Thread(){
  @Override
  public void run(){
    List<String> lines = Arrays.asList("The first line", "The second line");
    Path file = Paths.get("FIRST_FILE.txt");
    try{
      Files.write(file, lines, Charset.forName("UTF-8"));
    } 
    catch (IOException e){
      System.out.println("IO Error");
    }
    System.out.println("Artemis is shutting down");
    ServiceController.stopAll(cliArgs);
  }
});
````
Now when I ran and hit ctrl-c, I saw both of these test files being written. So I know that the shutdown hook and functions passed to it gets called. However, I don't know why print statements don't show up. 

Here is the proof:
```
 ▽ Projects/cem-artemis/artemis ls                                                                                                          master :: 1d :: ⬡
CLA.md             Dockerfile         LICENSE            build.gradle       errorprone-checks  gradle.properties  pow
CODE-OF-CONDUCT.md GOVERNANCE.md      README.md          crypto             ethereum           gradlew            settings.gradle
CONTRIBUTING.md    Jenkinsfile        artemis            docs               gradle             gradlew.bat        util

 ▽ Projects/cem-artemis/artemis ./gradlew run                                                                                               master :: 1d :: ⬡

> Task :run
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
****** New Slot at: Wed Dec 26 12:31:27 EST 2018 ******
Processing new slot: 1
Processing new block in slot: 1
java.lang.RuntimeException: java.net.ConnectException: Failed to connect to /127.0.0.1:7545
Exception in thread "pool-4-thread-1" java.lang.NullPointerException
        at tech.pegasys.artemis.pow.ValidatorRegistrationClient.listenToPoWChain(ValidatorRegistrationClient.java:62)
        at tech.pegasys.artemis.services.powchain.PowchainService.run(PowchainService.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
<============-> 96% EXECUTING [10s]
> :run
^C%                                                                                                                                                           
 △ Projects/cem-artemis/artemis ls                                                                                                     11s  master :: 1d :: ⬡
CLA.md             Dockerfile         Jenkinsfile        SECOND_FILE.txt    crypto             ethereum           gradlew            settings.gradle
CODE-OF-CONDUCT.md FIRST_FILE.txt     LICENSE            artemis            docs               gradle             gradlew.bat        util
CONTRIBUTING.md    GOVERNANCE.md      README.md          build.gradle       errorprone-checks  gradle.properties  pow
```

The FIRST_FILE.txt and SECOND_FILE.txt get created after I run Artemis and hit ctrl-c.

**Comment by jrhea** [comment]
Ok ... that's legit. I am good with that answer. Chalk another one up to @cemozerr
