### ISSUE TITLE
Generate usable error when eth1 chain deposit contract not defined

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1717]
Currently Teku spits out the following if you try and start it without an Eth1 deposit contract defined:

`Teku failed to start.
java.lang.NullPointerException
	at tech.pegasys.artemis.services.powchain.PowchainService.<init>(PowchainService.java:54)
	at tech.pegasys.artemis.services.ServiceController.<init>(ServiceController.java:37)
	at tech.pegasys.artemis.BeaconNode.<init>(BeaconNode.java:77)
	at tech.pegasys.artemis.Artemis.start(Artemis.java:38)
	at tech.pegasys.artemis.cli.BeaconNodeCommand.call(BeaconNodeCommand.java:241)
	at tech.pegasys.artemis.cli.BeaconNodeCommand.call(BeaconNodeCommand.java:61)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
	at picocli.CommandLine.execute(CommandLine.java:1904)
	at tech.pegasys.artemis.cli.BeaconNodeCommand.parse(BeaconNodeCommand.java:194)
	at tech.pegasys.artemis.Artemis.main(Artemis.java:31)`

This happens if you try to start without any options. If there is a minimum set that is required those should be presented in an error response.

**Comment by NicolasMassart** [comment]
Note that this issue is not the same as #1720 as this one focuses on the changes on the error message and the other on the NPE itself. But there's some overlap.

**Comment by bgravenorst** [comment]
Documentation states that a deposit contract address must be defined:
https://docs.teku.pegasys.tech/en/latest/Reference/CLI/CLI-Syntax/#eth1-deposit-contract-address

We don't need to document or mention the error message.
