### ISSUE TITLE
Null pointer exception when starting Teku without some options

### ISSUE THREAD

**Issue by NicolasMassart** [Consensys-Incorporated/teku#1720]
### Description
As a user, I want Teku to start without NPE even if I don't provide any options. Seeing a NPE and being told that it's a misuse of the software is not acceptable for an enterprise grade product.

### Acceptance Criteria
* Run Teku binaries and Docker image without options and have no error.
* Have a smoke test in CI to make sure Teku works when ran with minimal (no) options.
* Find a way to spot these kind of NPE in the future as manual review is not enough (a code checker rule, SonarCube ?) or at least track this need in an issue. Link the issue in this one.

### Steps to Reproduce (Bug)

With binaries built from source:

1. run Gradle installDist task `./gradlew clean installDist`
1. run the binary without options `build/install/teku/bin/teku`

or with the develop docker image:

1. `docker pull pegasyseng/teku:develop`
1. `docker run pegasyseng/teku:develop`

**Expected behavior:** [What you expect to happen]

1. no error should be thrown
1. Teku should be up and running with a viable default setup, perhaps matching the most obvious use case.

**Actual behavior:** [What actually happens]

A null pointer exception is thrown and Teku crashes.

**Frequency:** [What percentage of the time does it occur?]

100%

### Versions (Add all that apply)
* Software version: master commit 22e214d1043edcd3990e44ea02814e28e8f0b691
* Java version: 12.0.2 but also happens on the Teku develop Docker image which is openjdk:11.0.2-jre-slim-stretch
* OS Name & Version: Circle CI linux, Docker image, macOS, so probably on all OSes

### Additional Information

Stacktrace:

```
% build/install/teku/bin/teku
Teku failed to start.
java.lang.NullPointerException
	at tech.pegasys.artemis.services.powchain.PowchainService.<init>(PowchainService.java:54)
	at tech.pegasys.artemis.services.ServiceController.<init>(ServiceController.java:37)
	at tech.pegasys.artemis.BeaconNode.<init>(BeaconNode.java:77)
	at tech.pegasys.artemis.Artemis.start(Artemis.java:38)
	at tech.pegasys.artemis.cli.BeaconNodeCommand.call(BeaconNodeCommand.java:241)
	at tech.pegasys.artemis.cli.BeaconNodeCommand.call(BeaconNodeCommand.java:61)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
	at picocli.CommandLine.execute(CommandLine.java:1904)
	at tech.pegasys.artemis.cli.BeaconNodeCommand.parse(BeaconNodeCommand.java:194)
	at tech.pegasys.artemis.Artemis.main(Artemis.java:31)
```

**Comment by macfarla** [comment]
see #1717 - it is the same exception just further along

**Comment by macfarla** [comment]
ok so latest master behaves quite nicely with no args
➜  node_0 git:(master) ./bin/teku
2020-05-29 11:24:00,872 main INFO Configuring logging for destination: console and file
2020-05-29 11:24:00,877 main INFO Logging file location: /Users/sallymacfarlane/Library/teku/logs/teku.log
2020-05-29 11:24:00,877 main INFO Logging includes events: true
2020-05-29 11:24:00,877 main INFO Logging includes color: true
11:24:01.217 INFO  - Using data path: /Users/sallymacfarlane/Library/teku/data
11:24:01.233 INFO  - Initializing storage
11:24:11.248 INFO  - Storage initialization complete
ETH1 is disabled but initial state is unknown. Enable ETH1 or specify an initial state.
To display full help:
teku [COMMAND] --help

**Comment by macfarla** [comment]
I'm handing this one back to @arash009 for the bigger picture issue

**Comment by arash009** [comment]
Closing this for now as starting with no options gives a meaningful error and no longer an NPE.
