### ISSUE TITLE
NullPointerException: interface tech.pegasys.teku.util.time.channels.TimeTickChannel.onTick

### ISSUE THREAD

**Issue by torfbolt** [Consensys-Incorporated/teku#1732]
### Description
```
07:51:08.011 FATAL - PLEASE FIX OR REPORT | Unexpected exception thrown for java.lang.NullPointerException: event 'interface tech.pegasys.teku.util.time.channels.TimeTickChannel.onTick' in handler 'tech.pegasys.teku.services.beaconchain.BeaconChainController'
java.lang.NullPointerException: null
	at tech.pegasys.teku.statetransition.forkchoice.ForkChoice.processHead(ForkChoice.java:53) ~[teku-ethereum-statetransition-0.11.0-SNAPSHOT.jar:0.11.0-dev-f7daad76]
	at tech.pegasys.teku.services.beaconchain.BeaconChainController.processSlot(BeaconChainController.java:493) ~[teku-services-beaconchain-0.11.0-SNAPSHOT.jar:0.11.0-dev-f7daad76]
	at tech.pegasys.teku.services.beaconchain.BeaconChainController.onTick(BeaconChainController.java:468) ~[teku-services-beaconchain-0.11.0-SNAPSHOT.jar:0.11.0-dev-f7daad76]
	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at tech.pegasys.teku.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:67) ~[teku-events-0.11.0-SNAPSHOT.jar:0.11.0-dev-f7daad76]
	at tech.pegasys.teku.events.DirectEventDeliverer.deliverTo(DirectEventDeliverer.java:54) ~[teku-events-0.11.0-SNAPSHOT.jar:0.11.0-dev-f7daad76]
	at tech.pegasys.teku.events.AsyncEventDeliverer.lambda$deliverTo$0(AsyncEventDeliverer.java:60) ~[teku-events-0.11.0-SNAPSHOT.jar:0.11.0-dev-f7daad76]
	at tech.pegasys.teku.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:111) [teku-events-0.11.0-SNAPSHOT.jar:0.11.0-dev-f7daad76]
	at tech.pegasys.teku.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:103) [teku-events-0.11.0-SNAPSHOT.jar:0.11.0-dev-f7daad76]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

### Steps to Reproduce (Bug)
1. Sync up to Schlesi head according to the instructions in schlesi repo
2. Stop client
3. Restart client

**Expected behavior:** Teku continues syncing back to head

**Actual behavior:** Repeated output of the above error message every 4s

**Frequency:** 100% repeatable across client restarts

### Versions (Add all that apply)
* Software version: teku/v0.11.0-dev-f7daad76/linux-x86_64/-debian-openjdk64bitservervm-java-11
* Java version: openjdk 11.0.7-ea 2020-04-14
OpenJDK Runtime Environment (build 11.0.7-ea+9-post-Debian-1)
OpenJDK 64-Bit Server VM (build 11.0.7-ea+9-post-Debian-1, mixed mode, sharing)
* OS Name & Version: Debian GNU/Linux bullseye/sid
* Kernel Version: Linux torfbook 5.5.0-2-amd64 #1 SMP Debian 5.5.17-1 (2020-04-15) x86_64 GNU/Linux

**Comment by ajsutton** [comment]
Thanks for reporting this. I believe that https://github.com/PegaSysEng/teku/pull/1721 should fix this which was merged in a few hours ago.  Could you please update to the latest version from master (or the latest `develop` docker image or the latest `-SNAPSHOT` release if you're download binaries) and try again please?

**Comment by torfbolt** [comment]
Yep, that seems to have done it. Working again with `teku/v0.11.0-dev-ef496fe8/linux-x86_64/-debian-openjdk64bitservervm-java-11`.
