### ISSUE TITLE
Error on default startup

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#1776]
### Description
Running `./bin/teku` results in a `NullPointerException`:

```
Teku failed to start.
java.lang.NullPointerException
	at tech.pegasys.teku.services.powchain.PowchainService.<init>(PowchainService.java:54)
	at tech.pegasys.teku.services.ServiceController.<init>(ServiceController.java:37)
	at tech.pegasys.teku.BeaconNode.<init>(BeaconNode.java:77)
	at tech.pegasys.teku.Teku.start(Teku.java:37)
	at tech.pegasys.teku.cli.BeaconNodeCommand.call(BeaconNodeCommand.java:241)
	at tech.pegasys.teku.cli.BeaconNodeCommand.call(BeaconNodeCommand.java:61)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
	at picocli.CommandLine.execute(CommandLine.java:1904)
	at tech.pegasys.teku.cli.BeaconNodeCommand.parse(BeaconNodeCommand.java:194)
	at tech.pegasys.teku.Teku.main(Teku.java:30)
```

The deposit contract address isn't specified and eth1 is enabled.  We should provide a clear error message when eth1 is enabled but the deposit contract is not set explicitly or via the network definition.

**Comment by ajsutton** [comment]
Dupe of #1717.
