### ISSUE TITLE
Eth1RequestException: Eth1 call has failed:missing trie node

### ISSUE THREAD

**Issue by q9f** [Consensys-Incorporated/teku#1813]
### Description
Trying to bootstrap a new testnet. Teku does not do anything. Maybe because it's prior to genesis time?

### Steps to Reproduce (Bug)
https://github.com/goerli/schlesi/tree/master/teku

* connect a teku node to a geth node
* teku eth1_follow_distance is 1024
* geth tries_in_memory value is 128

**Expected behavior:** [What you expect to happen]

It should launch the beacon node and validators.

**Actual behavior:** [What actually happens]

It doesn't do anything for more than 40 minutes:

```
~/.opt/PegaSysEng/teku master 15m 16s
❯ 
teku \
--config-file="/home/user/.opt/goerli/witti/teku/config.yaml" \
--network="/home/user/.opt/goerli/witti/teku/chain.yaml"


^C^C^C^C^C^C^C^C^C^C^C^C^C^C
^C

~/.opt/PegaSysEng/teku master 43m 55s
❯ 
teku \
--config-file="/home/user/.opt/goerli/witti/teku/config.yaml" \
--network="/home/user/.opt/goerli/witti/teku/chain.yaml"

```

**Frequency:** 1

### Versions (Add all that apply)
* Software version: `teku/v0.11.2-dev-982608ec/linux-x86_64/oracle_openjdk-java-11`
* Java version: `openjdk version "11.0.6" 2020-01-14`
* OS Name & Version: `NAME="Arch Linux"`
* Kernel Version: `Linux ceres 5.6.10-arch1-1 #1 SMP PREEMPT Sat, 02 May 2020 19:11:54 +0000 x86_64 GNU/Linux`

**Comment by ajsutton** [comment]
I'm surprised it's completely silent. If it started running it should at least print something like:
```
2020-05-20 06:41:17,131 main INFO Configuring logging for destination: console and file
2020-05-20 06:41:17,134 main INFO Logging file location: /Users/aj/Library/teku/logs/teku.log
2020-05-20 06:41:17,134 main INFO Logging includes events: true
2020-05-20 06:41:17,134 main INFO Logging includes color: true
06:41:17.188 INFO  - Using data path: /Users/aj/Library/teku/data
06:41:17.202 INFO  - Initializing storage
```

I note that in the config file at https://raw.githubusercontent.com/goerli/schlesi/master/teku/config.yaml it has `Xinterop-enabled: true` which will cause Teku to generate a genesis with deterministically generated validator keys but since `Xinterop-owned-validator-count` isn't set, it won't be running any of the validators and the genesis time is still a fair way in the future.

With interop mode disabled it's connecting to the ETH1 chain and finding 66% of the required validators for genesis.

There is likely a log file in `~/.local/teku/logs/teku.log` which may provide more detail as well.

**Comment by ajsutton** [comment]
Make sure you delete any existing database as well - otherwise if the db contains an interop genesis it will start from that again and still be waiting for the genesis time.

**Comment by q9f** [comment]
I deleted the database and removed the interop options from the config file, it still does not do anything.

**Comment by q9f** [comment]
I read this in the log file, still strange that this is not printed to stdout:

```
2020-05-20 10:59:59.473+02:00 | main | INFO  | teku-status-log | Using data path: /home/user/.local/share/teku/data
2020-05-20 10:59:59.487+02:00 | main | INFO  | QuartzScheduler | Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2020-05-20 10:59:59.502+02:00 | main | INFO  | teku-status-log | Initializing storage
2020-05-20 10:59:59.537+02:00 | main | INFO  | VersionedDatabaseFactory | Data directory set to: /home/user/.local/share/teku/data
2020-05-20 11:00:00.055+02:00 | pool-10-thread-4 | ERROR | SafeFuture | Unhandled exception
java.util.concurrent.CompletionException: tech.pegasys.teku.pow.exception.Eth1RequestException: Eth1 call has failed:missing trie node ff117036f780631bde201e7e63ea29e602ec3fa76279bb8af2fae17786276cf1 (path )
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
	at tech.pegasys.teku.util.async.SafeFuture.lambda$propagateResult$2(SafeFuture.java:99) ~[teku-util-0.11.2-SNAPSHOT.jar:0.11.2-dev-2675292d]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
	at tech.pegasys.teku.util.async.SafeFuture.lambda$propagateResult$2(SafeFuture.java:99) ~[teku-util-0.11.2-SNAPSHOT.jar:0.11.2-dev-2675292d]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
	at org.web3j.utils.Async.lambda$run$1(Async.java:38) ~[core-4.5.6.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
	Suppressed: java.util.concurrent.CompletionException: tech.pegasys.teku.pow.exception.Eth1RequestException: Eth1 call has failed:missing trie node ff117036f780631bde201e7e63ea29e602ec3fa76279bb8af2fae17786276cf1 (path )
		at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
		at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
		at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645) ~[?:?]
		at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
		at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
		at tech.pegasys.teku.util.async.SafeFuture.lambda$propagateResult$2(SafeFuture.java:99) ~[teku-util-0.11.2-SNAPSHOT.jar:0.11.2-dev-2675292d]
		at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
		at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
		at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
		at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
		at tech.pegasys.teku.util.async.SafeFuture.lambda$propagateResult$2(SafeFuture.java:99) ~[teku-util-0.11.2-SNAPSHOT.jar:0.11.2-dev-2675292d]
		at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
		at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
		at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
		at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
		at org.web3j.utils.Async.lambda$run$1(Async.java:38) ~[core-4.5.6.jar:?]
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) [?:?]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
		at java.lang.Thread.run(Thread.java:834) [?:?]
	Caused by: tech.pegasys.teku.pow.exception.Eth1RequestException: Eth1 call has failed:missing trie node ff117036f780631bde201e7e63ea29e602ec3fa76279bb8af2fae17786276cf1 (path )
		at tech.pegasys.teku.pow.DepositContractAccessor.lambda$callFunctionAtBlockNumber$2(DepositContractAccessor.java:90) ~[teku-pow-0.11.2-SNAPSHOT.jar:0.11.2-dev-2675292d]
		at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642) ~[?:?]
		... 17 more
Caused by: tech.pegasys.teku.pow.exception.Eth1RequestException: Eth1 call has failed:missing trie node ff117036f780631bde201e7e63ea29e602ec3fa76279bb8af2fae17786276cf1 (path )
	at tech.pegasys.teku.pow.DepositContractAccessor.lambda$callFunctionAtBlockNumber$2(DepositContractAccessor.java:90) ~[teku-pow-0.11.2-SNAPSHOT.jar:0.11.2-dev-2675292d]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642) ~[?:?]
	... 17 more
2020-05-20 11:00:00.037+02:00 | pool-10-thread-5 | ERROR | Eth1DataManager | Unable to populate Eth1 cache for block 2726859
java.util.concurrent.CompletionException: tech.pegasys.teku.pow.exception.Eth1RequestException: Eth1 call has failed:missing trie node 39a2baf1fc31ef54a1e96b46844e01eb9fffd7d8f5f4d92e472abed780094714 (path )
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
	at tech.pegasys.teku.util.async.SafeFuture.lambda$propagateResult$2(SafeFuture.java:99) ~[teku-util-0.11.2-SNAPSHOT.jar:0.11.2-dev-2675292d]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
	at tech.pegasys.teku.util.async.SafeFuture.lambda$propagateResult$2(SafeFuture.java:99) ~[teku-util-0.11.2-SNAPSHOT.jar:0.11.2-dev-2675292d]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
	at org.web3j.utils.Async.lambda$run$1(Async.java:38) ~[core-4.5.6.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
	Suppressed: java.util.concurrent.CompletionException: tech.pegasys.teku.pow.exception.Eth1RequestException: Eth1 call has failed:missing trie node 39a2baf1fc31ef54a1e96b46844e01eb9fffd7d8f5f4d92e472abed780094714 (path )
		at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
		at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
		at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645) ~[?:?]
		at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
		at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
		at tech.pegasys.teku.util.async.SafeFuture.lambda$propagateResult$2(SafeFuture.java:99) ~[teku-util-0.11.2-SNAPSHOT.jar:0.11.2-dev-2675292d]
		at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
		at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
		at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
		at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
		at tech.pegasys.teku.util.async.SafeFuture.lambda$propagateResult$2(SafeFuture.java:99) ~[teku-util-0.11.2-SNAPSHOT.jar:0.11.2-dev-2675292d]
		at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
		at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
		at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
		at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
		at org.web3j.utils.Async.lambda$run$1(Async.java:38) ~[core-4.5.6.jar:?]
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) [?:?]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
		at java.lang.Thread.run(Thread.java:834) [?:?]
	Caused by: tech.pegasys.teku.pow.exception.Eth1RequestException: Eth1 call has failed:missing trie node 39a2baf1fc31ef54a1e96b46844e01eb9fffd7d8f5f4d92e472abed780094714 (path )
		at tech.pegasys.teku.pow.DepositContractAccessor.lambda$callFunctionAtBlockNumber$2(DepositContractAccessor.java:90) ~[teku-pow-0.11.2-SNAPSHOT.jar:0.11.2-dev-2675292d]
		at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642) ~[?:?]
		... 17 more
Caused by: tech.pegasys.teku.pow.exception.Eth1RequestException: Eth1 call has failed:missing trie node 39a2baf1fc31ef54a1e96b46844e01eb9fffd7d8f5f4d92e472abed780094714 (path )
	at tech.pegasys.teku.pow.DepositContractAccessor.lambda$callFunctionAtBlockNumber$2(DepositContractAccessor.java:90) ~[teku-pow-0.11.2-SNAPSHOT.jar:0.11.2-dev-2675292d]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642) ~[?:?]
	... 17 more
2020-05-20 11:00:00.099+02:00 | pool-10-thread-3 | ERROR | SafeFuture | Unhandled exception
java.util.concurrent.CompletionException: tech.pegasys.teku.pow.exception.Eth1RequestException: Eth1 call has failed:missing trie node 39a2baf1fc31ef54a1e96b46844e01eb9fffd7d8f5f4d92e472abed780094714 (path )
```

**Comment by ajsutton** [comment]
Those exceptions indicate that the cache of `Eth1Data` information is failing to read from the historical world state - likely the ETH1 node is pruning and with the long follow distance the blocks ETH2 is looking at no longer have world state available.  We've got some work happening currently in our ETH1 integration which will avoid this but it's probably at least a week away yet.  That might affect validators producing blocks, but it shouldn't stop us reaching genesis.

Could you give me the full output and log so I can see exactly what teku is doing?  For me, Teku is generating genesis for Witti and starts processing (empty) slots.

**Comment by q9f** [comment]
I'm nowhere near these logs before Monday.

Meanwhile, I'm seeing this in Geth:

```
INFO [05-22|14:00:32.443] Imported new chain segment               blocks=1    txs=5    mgas=0.837   elapsed=28.714ms    mgasps=29.165   number=2741071 hash="cbbdd0…5e50f7" dirty=80.92MiB
WARN [05-22|14:00:40.354] Served eth_call                          conn=127.0.0.1:54418 reqid=6933 t="268.513µs" err="missing trie node c96cd0abdc8a2c504f89396f2a1c84c35b2004368a8b5842cb6857b22027703f (path )"
WARN [05-22|14:00:40.354] Served eth_call                          conn=127.0.0.1:54420 reqid=6934 t="238.902µs" err="missing trie node c96cd0abdc8a2c504f89396f2a1c84c35b2004368a8b5842cb6857b22027703f (path )"
INFO [05-22|14:00:47.056] Imported new chain segment               blocks=1    txs=1    mgas=3.716   elapsed=24.553ms    mgasps=151.354  number=2741072 hash="ada9b8…59e6f0" dirty=80.87MiB
WARN [05-22|14:00:54.354] Served eth_call                          conn=127.0.0.1:54418 reqid=6943 t="396.26µs"  err="missing trie node 64af56bac2459409fd3ff2f86eb9780f48784e60c346740b5547b07f5b0504eb (path )"
WARN [05-22|14:00:54.354] Served eth_call                          conn=127.0.0.1:54420 reqid=6944 t="256.252µs" err="missing trie node 64af56bac2459409fd3ff2f86eb9780f48784e60c346740b5547b07f5b0504eb (path )"
INFO [05-22|14:01:02.681] Imported new chain segment               blocks=1    txs=4    mgas=0.889   elapsed=12.153ms    mgasps=73.162   number=2741073 hash="202ad6…7d54d8" dirty=80.91MiB
INFO [05-22|14:01:05.044] Deep froze chain segment                 blocks=4    elapsed=23.877ms    number=2651072 hash="2768ee…35b0f1"
WARN [05-22|14:01:08.352] Served eth_call                          conn=127.0.0.1:54418 reqid=6947 t="218.306µs" err="missing trie node 64af56bac2459409fd3ff2f86eb9780f48784e60c346740b5547b07f5b0504eb (path )"
WARN [05-22|14:01:08.353] Served eth_call                          conn=127.0.0.1:54420 reqid=6948 t="179.857µs" err="missing trie node 64af56bac2459409fd3ff2f86eb9780f48784e60c346740b5547b07f5b0504eb (path )"
INFO [05-22|14:01:17.105] Imported new chain segment               blocks=1    txs=1    mgas=0.021   elapsed=1.946ms     mgasps=10.790   number=2741074 hash="adc859…1ef5fc" dirty=80.91MiB
WARN [05-22|14:01:22.354] Served eth_call                          conn=127.0.0.1:54418 reqid=6957 t="414.883µs" err="missing trie node 30471e149d1990f52e9c5e3b44da0927afeb05045b9a6112c76ab60671045ba1 (path )"
WARN [05-22|14:01:22.354] Served eth_call                          conn=127.0.0.1:54420 reqid=6958 t="245.724µs" err="missing trie node 30471e149d1990f52e9c5e3b44da0927afeb05045b9a6112c76ab60671045ba1 (path )"
```

How can I fix this? I'm running with `--syncmode full` and `--gcmode full`.

**Comment by q9f** [comment]
ref https://github.com/ethereum/eth2.0-specs/issues/1839

would it be possible to rely on deposit logs instead of the entire state?

![Screenshot at 2020-05-22 14-50-05](https://user-images.githubusercontent.com/58883403/82669434-b6acc180-9c3b-11ea-8935-58ec22df0ab5.png)

**Comment by cemozerr** [comment]
Yes, totally. We are aware of this issue and the solution. @ajsutton has just picked it up due to its urgency.

**Comment by q9f** [comment]
Manually hacking Geth to retain 1024 states fixed that for me.
