### ISSUE TITLE
Debug initialization of gossip network

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1855]
When writing acceptance tests for block gossiping, I had to add a call to Thread.sleep() in order for the gossiping to work.  Otherwise, attempts to gossip would fail because the gossip layer didn't have any peers available for gossiping.  We should investigate why this is required and see if there's a way to remove the extra wait: https://github.com/PegaSysEng/artemis/pull/986/files#diff-66d1036b3a68c67245aaaaa19fb588efR74

Output when the wait is removed:

```
2019-11-06 17:28:03.721-05:00 | P2PService-event-thread-0 | TRACE  | GossipTopicHandler | Failed to gossip message on Topic(topic=/eth2/beacon_block/ssz)
java.util.concurrent.CompletionException: io.libp2p.etc.types.NothingToCompleteException
	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1074) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705) [?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: io.libp2p.etc.types.NothingToCompleteException
	at io.libp2p.etc.types.AsyncExtKt.anyComplete(AsyncExt.kt:62) ~[jvm-libp2p-minimal-0.1.0-RELEASE.jar:?]
	at io.libp2p.etc.types.AsyncExtKt.anyComplete(AsyncExt.kt:59) ~[jvm-libp2p-minimal-0.1.0-RELEASE.jar:?]
	at io.libp2p.pubsub.gossip.GossipRouter.broadcastOutbound(GossipRouter.kt:123) ~[jvm-libp2p-minimal-0.1.0-RELEASE.jar:?]
	at io.libp2p.pubsub.AbstractRouter$publish$1.invoke(AbstractRouter.kt:48) ~[jvm-libp2p-minimal-0.1.0-RELEASE.jar:?]
	at io.libp2p.pubsub.AbstractRouter$publish$1.invoke(AbstractRouter.kt:24) ~[jvm-libp2p-minimal-0.1.0-RELEASE.jar:?]
	at io.libp2p.etc.types.AsyncExtKt$submitAsync$1.get(AsyncExt.kt:51) ~[jvm-libp2p-minimal-0.1.0-RELEASE.jar:?]
	at io.libp2p.etc.types.AsyncExtKt$submitAsync$1.get(AsyncExt.kt) ~[jvm-libp2p-minimal-0.1.0-RELEASE.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
	... 6 more
```

**Comment by ajsutton** [comment]
This is required because jvm-libp2p performs a number of operations asynchronously, including sending messages to subscribe.  The jvm-libp2p API doesn't currently provide a way to track when the operation is actually complete.

Given the amount of work involved in making such tracking possible, and the limited number of tests that have been affected by this, closing this as won't fix.
