### ISSUE TITLE
Too much log noise during shutdown

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1891]
Teku logs a bunch of exceptions and other scary looking junk during shutdown.  We should spend some time killing it and working through the exceptions we find to ensure that: 

- we shut everything down cleanly
- we shut things down in the right order so dependencies 
- any cancellation exceptions or other stuff that gets thrown as a part of normal shutdown should be reduced to debug or trace level

**Comment by macfarla** [comment]
ctrl-C is not a normal way to shut down running processes.
what are the success criteria for this ticket? Can you be more specific @arash009

**Comment by ajsutton** [comment]
ctrl-C is the expected way to terminate an application like Teku.  It sends a SIGINT which is the same as systemd would send.

**Comment by rolfyone** [comment]
should really only report 'teku is shutting down' on CTRL+C

**Comment by rolfyone** [comment]
this appears to be no longer an issue. i've tried a number of things including syncing to Witti, and I'm not getting extra output when shutting down under any circumstances i've found.

**Comment by ajsutton** [comment]
I got:
```
onTick: java.lang.InterruptedException: sleep interrupted
java.lang.InterruptedException: sleep interrupted
	at java.base/java.lang.Thread.sleep(Native Method)
	at tech.pegasys.teku.services.beaconchain.BeaconChainController.processSlot(BeaconChainController.java:509)
	at tech.pegasys.teku.services.beaconchain.BeaconChainController.onTick(BeaconChainController.java:474)
	at jdk.internal.reflect.GeneratedMethodAccessor31.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at tech.pegasys.teku.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:70)
	at tech.pegasys.teku.events.DirectEventDeliverer.deliverTo(DirectEventDeliverer.java:53)
	at tech.pegasys.teku.events.AsyncEventDeliverer.lambda$deliverTo$0(AsyncEventDeliverer.java:60)
	at tech.pegasys.teku.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:111)
	at tech.pegasys.teku.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:103)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
a few hours ago when shutting down.  Often get various rejected execution exceptions as well.

**Comment by ajsutton** [comment]
Another example from today:
```
Scheduling next check of ETH1 chain head failed
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$AsyncRun@27b8f306 rejected from java.util.concurrent.ThreadPoolExecutor@297f0981[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 18324]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
	at java.base/java.util.concurrent.CompletableFuture.asyncRunStage(CompletableFuture.java:1750)
	at java.base/java.util.concurrent.CompletableFuture.runAsync(CompletableFuture.java:1959)
	at org.web3j.utils.Async.run(Async.java:33)
	at org.web3j.protocol.Service.sendAsync(Service.java:54)
	at org.web3j.protocol.core.Request.sendAsync(Request.java:85)
	at tech.pegasys.teku.pow.Web3jEth1Provider.getEth1Block(Web3jEth1Provider.java:83)
	at tech.pegasys.teku.pow.Web3jEth1Provider.getLatestEth1Block(Web3jEth1Provider.java:90)
	at tech.pegasys.teku.pow.ThrottlingEth1Provider.lambda$queueRequest$5(ThrottlingEth1Provider.java:70)
	at tech.pegasys.teku.pow.ThrottlingEth1Provider.processQueuedRequests(ThrottlingEth1Provider.java:86)
	at tech.pegasys.teku.pow.ThrottlingEth1Provider.queueRequest(ThrottlingEth1Provider.java:74)
	at tech.pegasys.teku.pow.ThrottlingEth1Provider.getLatestEth1Block(ThrottlingEth1Provider.java:57)
	at tech.pegasys.teku.pow.Eth1HeadTracker.pollLatestHead(Eth1HeadTracker.java:55)
	at tech.pegasys.teku.util.async.SafeFuture.fromRunnable(SafeFuture.java:104)
	at tech.pegasys.teku.util.async.AsyncRunner.lambda$runAfterDelay$1(AsyncRunner.java:34)
	at tech.pegasys.teku.util.async.DelayedExecutorAsyncRunner.lambda$runAsync$1(DelayedExecutorAsyncRunner.java:57)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
