### ISSUE TITLE
Block production fails in interop mode

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1911]
Suspect we’re including invalid attestations in generated blocks - and potentially holding old attestations in the pool too long.

```
2020-05-12 11:35:03.288+10:00 | ValidatorApiChannel-0 | ERROR | ScheduledDuties | Block production for slot 30 by 0x94f0c8535601596eb2165adb28ebe495891a3e4ea77ef501e7790cccb281827d377a5a8d4c200e3595d3f38f8633b480 failed
java.util.concurrent.CompletionException: tech.pegasys.teku.core.StateTransitionException: tech.pegasys.teku.core.exceptions.BlockProcessingException: java.lang.IllegalArgumentException: process_attestations: Attestation source error 1
	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1108) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235) ~[?:?]
	at tech.pegasys.teku.util.async.SafeFuture.thenCompose(SafeFuture.java:314) ~[classes/:?]
	at tech.pegasys.teku.util.async.SafeFuture.thenApplyChecked(SafeFuture.java:274) ~[classes/:?]
	at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.createFromBlockAndState(ValidatorApiHandler.java:164) ~[classes/:?]
	at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.createUnsignedBlock(ValidatorApiHandler.java:142) ~[classes/:?]
	at jdk.internal.reflect.GeneratedMethodAccessor28.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at tech.pegasys.teku.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:67) ~[classes/:?]
	at tech.pegasys.teku.events.DirectEventDeliverer.deliverToWithResponse(DirectEventDeliverer.java:60) ~[classes/:?]
	at tech.pegasys.teku.events.AsyncEventDeliverer.lambda$deliverToWithResponse$1(AsyncEventDeliverer.java:70) ~[classes/:?]
	at tech.pegasys.teku.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:111) [classes/:?]
	at tech.pegasys.teku.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:103) [classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: tech.pegasys.teku.core.StateTransitionException: tech.pegasys.teku.core.exceptions.BlockProcessingException: java.lang.IllegalArgumentException: process_attestations: Attestation source error 1
	at tech.pegasys.teku.core.StateTransition.initiate(StateTransition.java:112) ~[classes/:?]
	at tech.pegasys.teku.core.BlockProposalUtil.createNewUnsignedBlock(BlockProposalUtil.java:69) ~[classes/:?]
	at tech.pegasys.teku.validator.coordinator.BlockFactory.createUnsignedBlock(BlockFactory.java:78) ~[classes/:?]
	at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.lambda$createUnsignedBlock$3(ValidatorApiHandler.java:145) ~[classes/:?]
	at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.lambda$createFromBlockAndState$4(ValidatorApiHandler.java:169) ~[classes/:?]
	at tech.pegasys.teku.util.async.SafeFuture.lambda$thenApplyChecked$15(SafeFuture.java:277) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106) ~[?:?]
	... 16 more
Caused by: tech.pegasys.teku.core.exceptions.BlockProcessingException: java.lang.IllegalArgumentException: process_attestations: Attestation source error 1
	at tech.pegasys.teku.core.BlockProcessorUtil.process_attestations_no_validation(BlockProcessorUtil.java:453) ~[classes/:?]
	at tech.pegasys.teku.core.BlockProcessorUtil.process_operations_no_validation(BlockProcessorUtil.java:223) ~[classes/:?]
	at tech.pegasys.teku.core.StateTransition.lambda$process_block$0(StateTransition.java:130) ~[classes/:?]
	at tech.pegasys.teku.datastructures.state.BeaconStateImpl.updated(BeaconStateImpl.java:273) ~[classes/:?]
	at tech.pegasys.teku.core.StateTransition.process_block(StateTransition.java:125) ~[classes/:?]
	at tech.pegasys.teku.core.StateTransition.initiate(StateTransition.java:97) ~[classes/:?]
	at tech.pegasys.teku.core.BlockProposalUtil.createNewUnsignedBlock(BlockProposalUtil.java:69) ~[classes/:?]
	at tech.pegasys.teku.validator.coordinator.BlockFactory.createUnsignedBlock(BlockFactory.java:78) ~[classes/:?]
	at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.lambda$createUnsignedBlock$3(ValidatorApiHandler.java:145) ~[classes/:?]
	at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.lambda$createFromBlockAndState$4(ValidatorApiHandler.java:169) ~[classes/:?]
	at tech.pegasys.teku.util.async.SafeFuture.lambda$thenApplyChecked$15(SafeFuture.java:277) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106) ~[?:?]
	... 16 more
Caused by: java.lang.IllegalArgumentException: process_attestations: Attestation source error 1
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142) ~[guava-28.1-jre.jar:?]
	at tech.pegasys.teku.core.BlockProcessorUtil.process_attestations_no_validation(BlockProcessorUtil.java:440) ~[classes/:?]
	at tech.pegasys.teku.core.BlockProcessorUtil.process_operations_no_validation(BlockProcessorUtil.java:223) ~[classes/:?]
	at tech.pegasys.teku.core.StateTransition.lambda$process_block$0(StateTransition.java:130) ~[classes/:?]
	at tech.pegasys.teku.datastructures.state.BeaconStateImpl.updated(BeaconStateImpl.java:273) ~[classes/:?]
	at tech.pegasys.teku.core.StateTransition.process_block(StateTransition.java:125) ~[classes/:?]
	at tech.pegasys.teku.core.StateTransition.initiate(StateTransition.java:97) ~[classes/:?]
	at tech.pegasys.teku.core.BlockProposalUtil.createNewUnsignedBlock(BlockProposalUtil.java:69) ~[classes/:?]
	at tech.pegasys.teku.validator.coordinator.BlockFactory.createUnsignedBlock(BlockFactory.java:78) ~[classes/:?]
	at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.lambda$createUnsignedBlock$3(ValidatorApiHandler.java:145) ~[classes/:?]
	at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.lambda$createFromBlockAndState$4(ValidatorApiHandler.java:169) ~[classes/:?]
	at tech.pegasys.teku.util.async.SafeFuture.lambda$thenApplyChecked$15(SafeFuture.java:277) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106) ~[?:?]
	... 16 more


```

**Comment by ajsutton** [comment]
Fixed.
