### ISSUE TITLE
ETH1 connection doesn’t recover when eth1 node connection interrupted

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1913]
I was connected to the ETH1 node via an SSH tunnel.  The SSH connection droped and I had to recreate it.  Teku restored the connection to the eth1 node but didn’t recreate the filter it was using to track head blocks:

```
2020-05-09 22:48:48.841+00:00 | pool-11-thread-3 | ERROR | Filter | Error sending request
org.web3j.protocol.exceptions.ClientConnectionException: Invalid response received: 400; {
  "jsonrpc" : "2.0",
  "id" : 4797,
  "error" : {
    "code" : -32000,
    "message" : "Filter not found"
  }
}
        at org.web3j.protocol.http.HttpService.performIO(HttpService.java:173) ~[core-4.5.6.jar:?]
        at org.web3j.protocol.Service.send(Service.java:42) ~[core-4.5.6.jar:?]
        at org.web3j.protocol.core.Request.send(Request.java:81) ~[core-4.5.6.jar:?]
        at org.web3j.protocol.core.filters.Filter.pollFilter(Filter.java:128) ~[core-4.5.6.jar:?]
        at org.web3j.protocol.core.filters.Filter.lambda$run$0(Filter.java:92) ~[core-4.5.6.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

```

**Comment by ajsutton** [comment]
No longer using filters.
