### ISSUE TITLE
Netty error: ReadTimeoutExcpetion

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#2031]
### Description
Error often logged:

```
An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.timeout.ReadTimeoutException
```

Unfortunately no stack trace is available (netty reuses a single instance of this exception which disables capture of stack traces).

**Comment by ajsutton** [comment]
```
io.netty.handler.timeout.ReadTimeoutException: null
	at io.netty.handler.timeout.ReadTimeoutException.<clinit>(ReadTimeoutException.java:29) ~[netty-all-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.handler.timeout.ReadTimeoutHandler.readTimedOut(ReadTimeoutHandler.java:98) [netty-all-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelIdle(ReadTimeoutHandler.java:90) [netty-all-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.handler.timeout.IdleStateHandler$ReaderIdleTimeoutTask.run(IdleStateHandler.java:505) [netty-all-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.handler.timeout.IdleStateHandler$AbstractIdleTask.run(IdleStateHandler.java:477) [netty-all-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) [netty-all-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:139) [netty-all-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-all-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510) [netty-all-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518) [netty-all-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044) [netty-all-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.42.Final.jar:4.1.42.Final]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```
is the full stack trace (had to hack netty to stop it disabling stack trace capture).  Not something we can catch directly but may be able to add something into the netty pipeline...

**Comment by Nashatyrev** [comment]
The only place we are using `ReadTimeoutHandler` is the multistream `Negotiator` handler 
https://github.com/libp2p/jvm-libp2p/blob/02380696b12670d7269b06615b12e3a1bb21090e/src/main/kotlin/io/libp2p/multistream/Negotiator.kt#L75

It indeed has no `exceptionCaught` implemented. But it was intended that the next handler `ProtocolSelect` should deal with any outcomes of negotiation: like success/unsuccess of protocol selection and exceptions. But it turned out that the `ProtocolSelect` handler occurred at the very beginning of pipeline (see commit https://github.com/libp2p/jvm-libp2p/pull/112/commits/02380696b12670d7269b06615b12e3a1bb21090e which fixes that)

So the libp2p `0.5.1` should resolve this issue: https://github.com/libp2p/jvm-libp2p/pull/112

The other question is that why timeout occurs so often. Is it remote party defects? Would be good to see wire logs.
