### ISSUE TITLE
Unable to create block because ETH1 deposits are not available

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#2047]
I believe my local Besu is up to date and functioning and should be viewable by the beacon node.

```
2020-06-03 15:26:48.074+00:00 | ValidatorApiChannel-0 | ERROR | teku-validator-log | ^[[31mValidator   *** Failed to produce block  Slot: 55034^[[0m
tech.pegasys.teku.validator.coordinator.MissingDepositsException: Unable to create block because ETH1 deposits are not available. Missing deposits 806 to 806
        at tech.pegasys.teku.validator.coordinator.DepositProvider.getDeposits(DepositProvider.java:110) ~[teku-validator-coordinator-0.11.4-SNAPSHOT.jar:0.11.4-dev-4cd32f63]
        at tech.pegasys.teku.validator.coordinator.BlockFactory.createUnsignedBlock(BlockFactory.java:92) ~[teku-validator-coordinator-0.11.4-SNAPSHOT.jar:0.11.4-dev-4cd32f63]
        at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.lambda$createUnsignedBlock$3(ValidatorApiHandler.java:149) ~[teku-validator-coordinator-0.11.4-SNAPSHOT.jar:0.11.4-dev-4cd32f63]
        at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.lambda$createFromBlockAndState$4(ValidatorApiHandler.java:164) ~[teku-validator-coordinator-0.11.4-SNAPSHOT.jar:0.11.4-dev-4cd32f63]
        at tech.pegasys.teku.util.async.SafeFuture.lambda$thenApplyChecked$15(SafeFuture.java:275) ~[teku-util-0.11.4-SNAPSHOT.jar:0.11.4-dev-4cd32f63]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1183) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2306) ~[?:?]
        at tech.pegasys.teku.util.async.SafeFuture.thenCompose(SafeFuture.java:312) ~[teku-util-0.11.4-SNAPSHOT.jar:0.11.4-dev-4cd32f63]
        at tech.pegasys.teku.util.async.SafeFuture.thenApplyChecked(SafeFuture.java:272) ~[teku-util-0.11.4-SNAPSHOT.jar:0.11.4-dev-4cd32f63]
        at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.createFromBlockAndState(ValidatorApiHandler.java:159) ~[teku-validator-coordinator-0.11.4-SNAPSHOT.jar:0.11.4-dev-4cd32f63]
        at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.createUnsignedBlock(ValidatorApiHandler.java:146) ~[teku-validator-coordinator-0.11.4-SNAPSHOT.jar:0.11.4-dev-4cd32f63]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at tech.pegasys.teku.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:70) ~[teku-events-0.11.4-SNAPSHOT.jar:0.11.4-dev-4cd32f63]
        at tech.pegasys.teku.events.DirectEventDeliverer.deliverToWithResponse(DirectEventDeliverer.java:63) ~[teku-events-0.11.4-SNAPSHOT.jar:0.11.4-dev-4cd32f63]
        at tech.pegasys.teku.events.AsyncEventDeliverer.lambda$deliverToWithResponse$1(AsyncEventDeliverer.java:70) ~[teku-events-0.11.4-SNAPSHOT.jar:0.11.4-dev-4cd32f63]
        at tech.pegasys.teku.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:111) [teku-events-0.11.4-SNAPSHOT.jar:0.11.4-dev-4cd32f63]
        at tech.pegasys.teku.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:103) [teku-events-0.11.4-SNAPSHOT.jar:0.11.4-dev-4cd32f63]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]
```

**Comment by cemozerr** [comment]
Thanks, Ben. I think we might have an off by one error in our Deposit Provider: https://github.com/PegaSysEng/teku/commit/5f0b0fae5cf5363fa7b751cdb53378ae1b3d1883#r39647046
@ajsutton any thoughts?

**Comment by ajsutton** [comment]
Definitely an error in the check Teku is doing. This is the slot Ben's node missed: https://witti.beaconcha.in/block/55034
and the next block is valid but doesn't contain any deposits: https://witti.beaconcha.in/block/55035
