### ISSUE TITLE
discovery-tasks-1 | ERROR | DefaultSchedulers | Unhandled exception (2)

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#2059]
Saw this once yesterday:

```
2020-06-04 17:22:04.379+00:00 | TimeTickChannel-0 | INFO  | teku-event-log | ^[[37mSlot Event  *** Slot: 62810, Block: a56b45..bdae, Epoch: 1962, Finalized checkpoint: 1960, Finalized root: a94975..7622, Peers: 20^[[0m
2020-06-04 17:22:07.556+00:00 | discovery-tasks-1 | ERROR | DefaultSchedulers | Unhandled exception:
java.lang.NullPointerException: null
        at org.ethereum.beacon.discovery.scheduler.ExpirationScheduler.cancel(ExpirationScheduler.java:55) ~[discovery-0.3.6.jar:0.3.6]
        at org.ethereum.beacon.discovery.scheduler.ExpirationScheduler.put(ExpirationScheduler.java:39) ~[discovery-0.3.6.jar:0.3.6]
        at org.ethereum.beacon.discovery.task.RecursiveLookupTasks.addTimeout(RecursiveLookupTasks.java:66) ~[discovery-0.3.6.jar:0.3.6]
        at org.ethereum.beacon.discovery.task.RecursiveLookupTasks.lambda$add$1(RecursiveLookupTasks.java:51) ~[discovery-0.3.6.jar:0.3.6]
        at org.ethereum.beacon.discovery.scheduler.ErrorHandlingScheduler.runAndHandleError(ErrorHandlingScheduler.java:70) ~[discovery-0.3.6.jar:0.3.6]
        at org.ethereum.beacon.discovery.scheduler.ErrorHandlingScheduler.lambda$execute$1(ErrorHandlingScheduler.java:46) ~[discovery-0.3.6.jar:0.3.6]
        at org.ethereum.beacon.discovery.scheduler.Scheduler.lambda$execute$0(Scheduler.java:35) ~[discovery-0.3.6.jar:0.3.6]
        at org.ethereum.beacon.discovery.scheduler.ExecutorScheduler.lambda$execute$0(ExecutorScheduler.java:32) ~[discovery-0.3.6.jar:0.3.6]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]
2020-06-04 17:22:16.380+00:00 | TimeTickChannel-0 | INFO  | teku-event-log | ^[[37mSlot Event  *** Slot: 62811, Block: 33db02..6e7a, Epoch: 1962, Finalized checkpoint: 1960, Finalized root: a94975..7622, Peers: 20^[[0m
```

**Comment by ajsutton** [comment]
Added to discovery as https://github.com/PegaSysEng/discovery/issues/53
