### ISSUE TITLE
Unhandled exception in discovery

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#2176]
This is the sole error in my logs today:

```
2020-06-19 01:21:40.236+00:00 | TimeTickChannel-0 | INFO  | teku-event-log | ^[[37mSlot Event  *** Slot: 166008, Block: ec6969..537f, Epoch: 5187, Finalized checkpoint: 5185, Finalized root: 322661..f559, Peers: 27^[[0m
2020-06-19 01:21:41.637+00:00 | discovery-tasks-1 | ERROR | DefaultSchedulers | Unhandled exception:
java.lang.NullPointerException: null
        at org.ethereum.beacon.discovery.scheduler.ExpirationScheduler.cancel(ExpirationScheduler.java:55) ~[discovery-0.3.6.jar:0.3.6]
        at org.ethereum.beacon.discovery.scheduler.ExpirationScheduler.put(ExpirationScheduler.java:39) ~[discovery-0.3.6.jar:0.3.6]
        at org.ethereum.beacon.discovery.task.RecursiveLookupTasks.addTimeout(RecursiveLookupTasks.java:66) ~[discovery-0.3.6.jar:0.3.6]
        at org.ethereum.beacon.discovery.task.RecursiveLookupTasks.lambda$add$1(RecursiveLookupTasks.java:51) ~[discovery-0.3.6.jar:0.3.6]
        at org.ethereum.beacon.discovery.scheduler.ErrorHandlingScheduler.runAndHandleError(ErrorHandlingScheduler.java:70) ~[discovery-0.3.6.jar:0.3.6]
        at org.ethereum.beacon.discovery.scheduler.ErrorHandlingScheduler.lambda$execute$1(ErrorHandlingScheduler.java:46) ~[discovery-0.3.6.jar:0.3.6]
        at org.ethereum.beacon.discovery.scheduler.Scheduler.lambda$execute$0(Scheduler.java:35) ~[discovery-0.3.6.jar:0.3.6]
        at org.ethereum.beacon.discovery.scheduler.ExecutorScheduler.lambda$execute$0(ExecutorScheduler.java:32) ~[discovery-0.3.6.jar:0.3.6]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]
2020-06-19 01:21:52.241+00:00 | TimeTickChannel-0 | INFO  | teku-event-log | ^[[37mSlot Event  *** Slot: 166009, Block: b8f441..7a7e, Epoch: 5187, Finalized checkpoint: 5185, Finalized root: 322661..f559, Peers: 27^[[0m
```

**Comment by benjaminion** [comment]
Saw this again today on the Altona network (the earlier one was on Witti).

**Comment by ajsutton** [comment]
This one is fixed in discovery but we haven't yet pulled in the new version. Will do so once I've reviewed #2269 to see if we can fix it in the same update.
