### ISSUE TITLE
Unexpected exception thrown for StorageUpdateChannel-0

### ISSUE THREAD

**Issue by ethers** [Consensys-Incorporated/teku#2207]
2020-06-24 03:43:07.826-04:00 | TimeTickChannel-0 | INFO  | teku-event-log | ESC[37mSync Event  *** Current slot: 72728, Head slot: 15359, Connected peers: 1
4ESC[0m
2020-06-24 03:43:12.821-04:00 | StorageUpdateChannel-0 | ERROR | teku-status-log | PLEASE FIX OR REPORT | Unexpected exception thrown for StorageUpdateChanne
l-0
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: ProtoArray: Invalid delta length
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
        at tech.pegasys.teku.util.async.SafeFuture.lambda$propagateResult$2(SafeFuture.java:97) ~[teku-util-0.12.0-SNAPSHOT.jar:0.12.0-dev-1bcf7d0d]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
        at tech.pegasys.teku.util.async.SafeFuture.lambda$propagateResult$2(SafeFuture.java:97) ~[teku-util-0.12.0-SNAPSHOT.jar:0.12.0-dev-1bcf7d0d]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883) ~[?:?]
        at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251) ~[?:?]
        at tech.pegasys.teku.util.async.SafeFuture.whenComplete(SafeFuture.java:328) ~[teku-util-0.12.0-SNAPSHOT.jar:0.12.0-dev-1bcf7d0d]
        at tech.pegasys.teku.util.async.SafeFuture.whenComplete(SafeFuture.java:26) ~[teku-util-0.12.0-SNAPSHOT.jar:0.12.0-dev-1bcf7d0d]
        at tech.pegasys.teku.util.async.SafeFuture.propagateResult(SafeFuture.java:92) ~[teku-util-0.12.0-SNAPSHOT.jar:0.12.0-dev-1bcf7d0d]
        at tech.pegasys.teku.util.async.SafeFuture.propagateTo(SafeFuture.java:181) ~[teku-util-0.12.0-SNAPSHOT.jar:0.12.0-dev-1bcf7d0d]
        at tech.pegasys.teku.events.AsyncEventDeliverer.lambda$deliverToWithResponse$1(AsyncEventDeliverer.java:70) ~[teku-events-0.12.0-SNAPSHOT.jar:0.12.0-dev-1bcf7d0d]
        at tech.pegasys.teku.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:111) [teku-events-0.12.0-SNAPSHOT.jar:0.12.0-dev-1bcf7d0d]
        at tech.pegasys.teku.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:103) [teku-events-0.12.0-SNAPSHOT.jar:0.12.0-dev-1bcf7d0d]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalArgumentException: ProtoArray: Invalid delta length
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142) ~[guava-28.1-jre.jar:?]
        at tech.pegasys.teku.protoarray.ProtoArray.applyScoreChanges(ProtoArray.java:155) ~[teku-protoarray-0.12.0-SNAPSHOT.jar:0.12.0-dev-1bcf7d0d]
        at tech.pegasys.teku.protoarray.ProtoArrayForkChoiceStrategyUpdater.updateForkChoiceWeights(ProtoArrayForkChoiceStrategyUpdater.java:175) ~[teku-protoarray-0.12.0-SNAPSHOT.jar:0.12.0-dev-1bcf7d0d]
        at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
        at tech.pegasys.teku.protoarray.ProtoArrayForkChoiceStrategyUpdater.commit(ProtoArrayForkChoiceStrategyUpdater.java:88) ~[teku-protoarray-0.12.0-SNAPSHOT.jar:0.12.0-dev-1bcf7d0d]
        at tech.pegasys.teku.storage.store.StoreTransactionUpdates.applyToStore(StoreTransactionUpdates.java:270) ~[teku-storage-0.12.0-SNAPSHOT.jar:0.12.0-dev-1bcf7d0d]
        at tech.pegasys.teku.storage.store.Store$Transaction.lambda$commit$0(Store.java:543) ~[teku-storage-0.12.0-SNAPSHOT.jar:0.12.0-dev-1bcf7d0d]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
        ... 21 more
2020-06-24 03:43:13.720-04:00 | TimeTickChannel-0 | INFO  | teku-event-log | ESC[37mSync Event  *** Current slot: 72729, Head slot: 15361, Connected peers: 14ESC[0m
2020-06-24 03:43:24.033-04:00 | TimeTickChannel-0 | INFO  | teku-event-log | ESC[37mSync Event  *** Current slot: 72730, Head slot: 15385, Connected peers: 14ESC[0m

**Comment by cemozerr** [comment]
Closing this as it's the same error with https://github.com/PegaSysEng/teku/issues/2208 bubbled up in a different place.
