### ISSUE TITLE
Unexpected exception thrown for TimeTickChannel-0

### ISSUE THREAD

**Issue by ethers** [Consensys-Incorporated/teku#2208]
2020-06-24 02:36:36.012-04:00 | TimeTickChannel-0 | INFO  | teku-event-log | ESC[37mSync Event  *** Current slot: 72396, Head slot: 8219, Connected peers: 11ESC[0m
2020-06-24 02:36:48.058-04:00 | TimeTickChannel-0 | ERROR | teku-status-log | PLEASE FIX OR REPORT | Unexpected exception thrown for TimeTickChannel-0
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: ProtoArray: Invalid delta length
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108) ~[?:?]
        at tech.pegasys.teku.util.async.SafeFuture.thenAccept(SafeFuture.java:299) ~[teku-util-0.12.0-SNAPSHOT.jar:0.12.0-dev-1bcf7d0d]
        at tech.pegasys.teku.storage.store.Store$Transaction.commit(Store.java:537) ~[teku-storage-0.12.0-SNAPSHOT.jar:0.12.0-dev-1bcf7d0d]
        at tech.pegasys.teku.services.beaconchain.SlotProcessor.processSlotWhileSyncing(SlotProcessor.java:126) ~[teku-services-beaconchain-0.12.0-SNAPSHOT.jar:0.12.0-dev-1bcf7d0d]
        at tech.pegasys.teku.services.beaconchain.SlotProcessor.onTick(SlotProcessor.java:96) ~[teku-services-beaconchain-0.12.0-SNAPSHOT.jar:0.12.0-dev-1bcf7d0d]
        at tech.pegasys.teku.services.beaconchain.BeaconChainController.onTick(BeaconChainController.java:507) ~[teku-services-beaconchain-0.12.0-SNAPSHOT.jar:0.12.0-dev-1bcf7d0d]
        at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at tech.pegasys.teku.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:70) ~[teku-events-0.12.0-SNAPSHOT.jar:0.12.0-dev-1bcf7d0d]
        at tech.pegasys.teku.events.DirectEventDeliverer.deliverTo(DirectEventDeliverer.java:53) ~[teku-events-0.12.0-SNAPSHOT.jar:0.12.0-dev-1bcf7d0d]
        at tech.pegasys.teku.events.AsyncEventDeliverer.lambda$deliverTo$0(AsyncEventDeliverer.java:60) ~[teku-events-0.12.0-SNAPSHOT.jar:0.12.0-dev-1bcf7d0d]
        at tech.pegasys.teku.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:111) [teku-events-0.12.0-SNAPSHOT.jar:0.12.0-dev-1bcf7d0d]
        at tech.pegasys.teku.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:103) [teku-events-0.12.0-SNAPSHOT.jar:0.12.0-dev-1bcf7d0d]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalArgumentException: ProtoArray: Invalid delta length
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142) ~[guava-28.1-jre.jar:?]
        at tech.pegasys.teku.protoarray.ProtoArray.applyScoreChanges(ProtoArray.java:155) ~[teku-protoarray-0.12.0-SNAPSHOT.jar:0.12.0-dev-1bcf7d0d]
        at tech.pegasys.teku.protoarray.ProtoArrayForkChoiceStrategyUpdater.updateForkChoiceWeights(ProtoArrayForkChoiceStrategyUpdater.java:175) ~[teku-protoarray-0.12.0-SNAPSHOT.jar:0.12.0-dev-1bcf7d0d]
        at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
        at tech.pegasys.teku.protoarray.ProtoArrayForkChoiceStrategyUpdater.commit(ProtoArrayForkChoiceStrategyUpdater.java:88) ~[teku-protoarray-0.12.0-SNAPSHOT.jar:0.12.0-dev-1bcf7d0d]
        at tech.pegasys.teku.storage.store.StoreTransactionUpdates.applyToStore(StoreTransactionUpdates.java:270) ~[teku-storage-0.12.0-SNAPSHOT.jar:0.12.0-dev-1bcf7d0d]
        at tech.pegasys.teku.storage.store.Store$Transaction.lambda$commit$0(Store.java:543) ~[teku-storage-0.12.0-SNAPSHOT.jar:0.12.0-dev-1bcf7d0d]
        at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753) ~[?:?]
        ... 18 more
2020-06-24 02:36:49.343-04:00 | TimeTickChannel-0 | INFO  | teku-event-log | ESC[37mSync Event  *** Current slot: 72397, Head slot: 8219, Connected peers: 12ESC[0m

**Comment by cemozerr** [comment]
Thanks for making an issue about this. I've recently started seeing this error in my logs as well. I'll be looking into it right away.

**Comment by cemozerr** [comment]
We've reverted the PRs that caused this issue so we shouldn't see this issue again.
