### ISSUE TITLE
ConcurrentModificationException in fork choice

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#2238]
### Description
https://app.circleci.com/pipelines/github/PegaSysEng/teku/5013/workflows/71d2a509-6659-4a21-b9d7-fb55f10d15ce/jobs/31152
AT failure due to:

```
22:29:05.044 ERROR - PLEASE FIX OR REPORT | Unexpected exception thrown for event 'interface tech.pegasys.teku.util.time.channels.SlotEventsChannel.onSlot' in handler 'tech.pegasys.teku.statetransition.attestation.AttestationManager'

java.util.ConcurrentModificationException: null

	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1493) ~[?:?]

	at java.util.HashMap$EntryIterator.next(HashMap.java:1526) ~[?:?]

	at java.util.HashMap$EntryIterator.next(HashMap.java:1524) ~[?:?]

	at java.util.HashMap.putMapEntries(HashMap.java:507) ~[?:?]

	at java.util.HashMap.<init>(HashMap.java:485) ~[?:?]

	at tech.pegasys.teku.protoarray.ProtoArrayForkChoiceStrategyUpdater$VoteUpdater.<init>(ProtoArrayForkChoiceStrategyUpdater.java:318) ~[teku-protoarray-0.12.0-SNAPSHOT.jar:0.12.0-dev-820ad5e5]

	at tech.pegasys.teku.protoarray.ProtoArrayForkChoiceStrategyUpdater.<init>(ProtoArrayForkChoiceStrategyUpdater.java:58) ~[teku-protoarray-0.12.0-SNAPSHOT.jar:0.12.0-dev-820ad5e5]

	at tech.pegasys.teku.protoarray.ProtoArrayForkChoiceStrategy.updater(ProtoArrayForkChoiceStrategy.java:142) ~[teku-protoarray-0.12.0-SNAPSHOT.jar:0.12.0-dev-820ad5e5]

	at tech.pegasys.teku.storage.store.Store$Transaction.<init>(Store.java:601) ~[teku-storage-0.12.0-SNAPSHOT.jar:0.12.0-dev-820ad5e5]

	at tech.pegasys.teku.storage.store.Store.startTransaction(Store.java:242) ~[teku-storage-0.12.0-SNAPSHOT.jar:0.12.0-dev-820ad5e5]

	at tech.pegasys.teku.storage.client.RecentChainData.startStoreTransaction(RecentChainData.java:156) ~[teku-storage-0.12.0-SNAPSHOT.jar:0.12.0-dev-820ad5e5]

	at tech.pegasys.teku.statetransition.attestation.ForkChoiceAttestationProcessor.applyIndexedAttestationToForkChoice(ForkChoiceAttestationProcessor.java:44) ~[teku-ethereum-statetransition-0.12.0-SNAPSHOT.jar:0.12.0-dev-820ad5e5]

	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]

	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]

	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654) ~[?:?]

	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]

	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]

	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]

	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]

	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]

	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]

	at tech.pegasys.teku.statetransition.attestation.AttestationManager.onSlot(AttestationManager.java:86) ~[teku-ethereum-statetransition-0.12.0-SNAPSHOT.jar:0.12.0-dev-820ad5e5]

	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source) ~[?:?]

	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]

	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]

	at tech.pegasys.teku.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:70) ~[teku-events-0.12.0-SNAPSHOT.jar:0.12.0-dev-820ad5e5]

	at tech.pegasys.teku.events.DirectEventDeliverer.deliverTo(DirectEventDeliverer.java:53) ~[teku-events-0.12.0-SNAPSHOT.jar:0.12.0-dev-820ad5e5]

	at tech.pegasys.teku.events.AsyncEventDeliverer.lambda$deliverTo$0(AsyncEventDeliverer.java:60) ~[teku-events-0.12.0-SNAPSHOT.jar:0.12.0-dev-820ad5e5]

	at tech.pegasys.teku.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:111) [teku-events-0.12.0-SNAPSHOT.jar:0.12.0-dev-820ad5e5]

	at tech.pegasys.teku.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:103) [teku-events-0.12.0-SNAPSHOT.jar:0.12.0-dev-820ad5e5]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]

	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by cemozerr** [comment]
My guess is that this issue has ceased to exist since we reverted a few PRs that caused issues in Fork Choice, yet I will monitor our Altona nodes to see if we have this again. Otherwise, I'll close this issue soon.

**Comment by cemozerr** [comment]
Haven't seen this issue in a day, thus closing.
