### ISSUE TITLE
Invalid Merkle tree proof in generated block

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#2264]
### Description
Got this error in Altona:
```
{"timestamp":"2020-06-29T19:24:05,144","level":"ERROR","thread":"ValidatorApiChannel-0","class":"teku-validator-log","message":"Validator   *** Failed to produce block  Slot: 2070","throwable":" tech.pegasys.teku.core.StateTransitionException: tech.pegasys.teku.core.exceptions.BlockProcessingException: java.lang.IllegalArgumentException: process_deposit: Verify the Merkle branch
at tech.pegasys.teku.core.StateTransition.initiate(StateTransition.java:97)
at tech.pegasys.teku.core.BlockProposalUtil.createNewUnsignedBlock(BlockProposalUtil.java:78)
at tech.pegasys.teku.validator.coordinator.BlockFactory.createUnsignedBlock(BlockFactory.java:109)
at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.lambda$createUnsignedBlock$3(ValidatorApiHandler.java:152)
at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.lambda$createFromBlockAndState$4(ValidatorApiHandler.java:167)
at tech.pegasys.teku.util.async.SafeFuture.lambda$thenApplyChecked$15(SafeFuture.java:275)
at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
at tech.pegasys.teku.util.async.SafeFuture.thenCompose(SafeFuture.java:312)
at tech.pegasys.teku.util.async.SafeFuture.thenApplyChecked(SafeFuture.java:272)
at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.createFromBlockAndState(ValidatorApiHandler.java:162)
at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.createUnsignedBlock(ValidatorApiHandler.java:149)
at jdk.internal.reflect.GeneratedMethodAccessor84.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at tech.pegasys.teku.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:70)
at tech.pegasys.teku.events.DirectEventDeliverer.deliverToWithResponse(DirectEventDeliverer.java:63)
at tech.pegasys.teku.events.AsyncEventDeliverer.lambda$deliverToWithResponse$1(AsyncEventDeliverer.java:70)
at tech.pegasys.teku.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:111)
at tech.pegasys.teku.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:103)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
\nCaused by: tech.pegasys.teku.core.exceptions.BlockProcessingException: java.lang.IllegalArgumentException: process_deposit: Verify the Merkle branch
at tech.pegasys.teku.core.BlockProcessorUtil.process_deposits(BlockProcessorUtil.java:420)
at tech.pegasys.teku.core.BlockProcessorUtil.process_operations_no_validation(BlockProcessorUtil.java:222)
at tech.pegasys.teku.core.StateTransition.lambda$process_block$0(StateTransition.java:115)
at tech.pegasys.teku.datastructures.state.BeaconStateImpl.updated(BeaconStateImpl.java:246)
at tech.pegasys.teku.core.StateTransition.process_block(StateTransition.java:110)
at tech.pegasys.teku.core.StateTransition.initiate(StateTransition.java:82)\n\t... 22 more\nCaused by: java.lang.IllegalArgumentException: process_deposit: Verify the Merkle branch
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
at tech.pegasys.teku.datastructures.util.BeaconStateUtil.process_deposit(BeaconStateUtil.java:112)
at tech.pegasys.teku.core.BlockProcessorUtil.process_deposits(BlockProcessorUtil.java:416)\n\t... 27 more\n"}
```

**Comment by ajsutton** [comment]
I'm at a loss as to how this happened.  At slot 2070 our Eth1Data vote would not have been sufficient to switch to the new Eth1Data.  So eth1DepositIndex was 1526 and deposit count 1657 meaning there were more deposits than could be included (the block that wound up being included at 2071 included those 16 deposits): https://altona.beaconcha.in/block/2071

If I comment out a couple of things so we don't prune deposit events and allow creating new blocks in historic slots, I'm able to successfully create the block we should have made at slot 2070.

All additions to `depositMerkleTree` and the call to create the proof are correctly within `synchronized` blocks - there are a couple of calls which populate the Eth1Data cache which are unsynchronised by they're read only so they might make us vote for the wrong Eth1Data but shouldn't be able to cause an invalid proof.   The deposits included in the body of the block I generated are exactly identical to the ones included in the real block at 2071 (which included the deposits we should have).  So we're able to create the proof correctly but something happened in real-time which made the proofs incorrect.

**Comment by ajsutton** [comment]
Looks like the synchronization issues were the cause and it's now fixed.
