### ISSUE TITLE
State Transition error - Invalid attestation: Signature is invalid

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#2334]
Seen this a handful of times in the logs, most recently today. If it's due to receiving an invalid block from a peer, then there's not much an operator can do about this, so it is probably better to move it to DEBUG level. But it might also be due to something internal that needs to be fixed.

```
2020-07-09 00:26:41.512+00:00 | ValidatorApiChannel-0 | INFO  | teku-validator-log | ^[[34mValidator   *** Published block        Count: 1, Slot: 68383, Root: 6017b1..5c80^[[0m
2020-07-09 00:26:41.614+00:00 | events-420 | WARN  | StateTransition | State Transition error
tech.pegasys.teku.core.exceptions.BlockProcessingException: tech.pegasys.teku.core.exceptions.BlockProcessingException: Invalid attestation: Signature is invalid
        at tech.pegasys.teku.core.StateTransition.initiate(StateTransition.java:88) [teku-ethereum-core-0.12.1-SNAPSHOT.jar:0.12.1-dev-3e9bc8a3]
        at tech.pegasys.teku.core.ForkChoiceUtil.on_block(ForkChoiceUtil.java:223) [teku-ethereum-core-0.12.1-SNAPSHOT.jar:0.12.1-dev-3e9bc8a3]
        at tech.pegasys.teku.statetransition.forkchoice.ForkChoice.onBlock(ForkChoice.java:77) [teku-ethereum-statetransition-0.12.1-SNAPSHOT.jar:0.12.1-dev-3e9bc8a3]
        at tech.pegasys.teku.statetransition.blockimport.BlockImporter.importBlock(BlockImporter.java:70) [teku-ethereum-statetransition-0.12.1-SNAPSHOT.jar:0.12.1-dev-3e9bc8a3]
        at tech.pegasys.teku.statetransition.blockimport.BlockImporter.onBlockProposed(BlockImporter.java:100) [teku-ethereum-statetransition-0.12.1-SNAPSHOT.jar:0.12.1-dev-3e9bc8a3]
        at jdk.internal.reflect.GeneratedMethodAccessor75.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87) [guava-28.1-jre.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144) [guava-28.1-jre.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72) [guava-28.1-jre.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: tech.pegasys.teku.core.exceptions.BlockProcessingException: Invalid attestation: Signature is invalid
        at tech.pegasys.teku.core.BlockProcessorUtil.verify_attestations(BlockProcessorUtil.java:399) ~[teku-ethereum-core-0.12.1-SNAPSHOT.jar:0.12.1-dev-3e9bc8a3]
        at tech.pegasys.teku.core.blockvalidator.SimpleBlockValidator.validatePreState(SimpleBlockValidator.java:78) ~[teku-ethereum-core-0.12.1-SNAPSHOT.jar:0.12.1-dev-3e9bc8a3]
        at tech.pegasys.teku.core.blockvalidator.BatchBlockValidator.validatePreState(BatchBlockValidator.java:43) ~[teku-ethereum-core-0.12.1-SNAPSHOT.jar:0.12.1-dev-3e9bc8a3]
        at tech.pegasys.teku.core.blockvalidator.BlockValidator.validate(BlockValidator.java:88) ~[teku-ethereum-core-0.12.1-SNAPSHOT.jar:0.12.1-dev-3e9bc8a3]
        at tech.pegasys.teku.core.StateTransition.initiate(StateTransition.java:85) ~[teku-ethereum-core-0.12.1-SNAPSHOT.jar:0.12.1-dev-3e9bc8a3]
        ... 13 more
2020-07-09 00:26:41.619+00:00 | events-420 | ERROR | BlockImporter | Failed to import proposed block for reason + FAILED_STATE_TRANSITION: tech.pegasys.teku.statetransition.events.block.ProposedBlockEvent@4037b97d
tech.pegasys.teku.core.StateTransitionException: tech.pegasys.teku.core.exceptions.BlockProcessingException: tech.pegasys.teku.core.exceptions.BlockProcessingException: Invalid attestation: Signature is invalid
        at tech.pegasys.teku.core.StateTransition.initiate(StateTransition.java:97) ~[teku-ethereum-core-0.12.1-SNAPSHOT.jar:0.12.1-dev-3e9bc8a3]
        at tech.pegasys.teku.core.ForkChoiceUtil.on_block(ForkChoiceUtil.java:223) ~[teku-ethereum-core-0.12.1-SNAPSHOT.jar:0.12.1-dev-3e9bc8a3]
        at tech.pegasys.teku.statetransition.forkchoice.ForkChoice.onBlock(ForkChoice.java:77) ~[teku-ethereum-statetransition-0.12.1-SNAPSHOT.jar:0.12.1-dev-3e9bc8a3]
        at tech.pegasys.teku.statetransition.blockimport.BlockImporter.importBlock(BlockImporter.java:70) ~[teku-ethereum-statetransition-0.12.1-SNAPSHOT.jar:0.12.1-dev-3e9bc8a3]
        at tech.pegasys.teku.statetransition.blockimport.BlockImporter.onBlockProposed(BlockImporter.java:100) [teku-ethereum-statetransition-0.12.1-SNAPSHOT.jar:0.12.1-dev-3e9bc8a3]
        at jdk.internal.reflect.GeneratedMethodAccessor75.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87) [guava-28.1-jre.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144) [guava-28.1-jre.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72) [guava-28.1-jre.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: tech.pegasys.teku.core.exceptions.BlockProcessingException: tech.pegasys.teku.core.exceptions.BlockProcessingException: Invalid attestation: Signature is invalid
        at tech.pegasys.teku.core.StateTransition.initiate(StateTransition.java:88) ~[teku-ethereum-core-0.12.1-SNAPSHOT.jar:0.12.1-dev-3e9bc8a3]
        ... 13 more
Caused by: tech.pegasys.teku.core.exceptions.BlockProcessingException: Invalid attestation: Signature is invalid
        at tech.pegasys.teku.core.BlockProcessorUtil.verify_attestations(BlockProcessorUtil.java:399) ~[teku-ethereum-core-0.12.1-SNAPSHOT.jar:0.12.1-dev-3e9bc8a3]
        at tech.pegasys.teku.core.blockvalidator.SimpleBlockValidator.validatePreState(SimpleBlockValidator.java:78) ~[teku-ethereum-core-0.12.1-SNAPSHOT.jar:0.12.1-dev-3e9bc8a3]
        at tech.pegasys.teku.core.blockvalidator.BatchBlockValidator.validatePreState(BatchBlockValidator.java:43) ~[teku-ethereum-core-0.12.1-SNAPSHOT.jar:0.12.1-dev-3e9bc8a3]
        at tech.pegasys.teku.core.blockvalidator.BlockValidator.validate(BlockValidator.java:88) ~[teku-ethereum-core-0.12.1-SNAPSHOT.jar:0.12.1-dev-3e9bc8a3]
        at tech.pegasys.teku.core.StateTransition.initiate(StateTransition.java:85) ~[teku-ethereum-core-0.12.1-SNAPSHOT.jar:0.12.1-dev-3e9bc8a3]
        ... 13 more
```

```
teku/v0.12.1-dev-3e9bc8a3/linux-x86_64/-privatebuild-openjdk64bitservervm-java-13
```

**Comment by cemozerr** [comment]
Seems like we see this issue in the blocks we propose, and so we either don't verify some attestations we get over the wire correctly or create an invalid attestation as we did in the past. This actually looks eerily similar to: https://github.com/PegaSysEng/teku/issues/2179

**Comment by cemozerr** [comment]
Keeping this active for a little longer but haven't seen this issue in a while so it might have been fixed.

**Comment by cemozerr** [comment]
Closing this due to inactivity.

**Comment by benjaminion** [comment]
Reopening - sorry!

@protolambda is seeing this or something very like it today. [Logs](https://gist.github.com/protolambda/fac25701d257769fe9eb8449e4d0bc0e)

This is on the **Teku attacknet**, running develop docker image, `teku-ethereum-core-0.12.2-SNAPSHOT.jar:0.12.2-dev-836fbd4f`

Note that this network was actively under attack during this period by @jrhea. I believe he will be writing up the attack which may help with further investigation.

**Comment by mbaxter** [comment]
#2501 had to be reverted - reopening
