### ISSUE TITLE
Teku deadlock

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#2347]
### Description
After running on Altona for a number of days without any issues, Teku silently stopped importing blocks (failed to recognise the chain head had moved forward at all).

Thread dump is attached which shows a lot of event bus threads all waiting on a lock which suggests something has deadlocked or gotten stuck.

[stack.txt](https://github.com/PegaSysEng/teku/files/4915374/stack.txt)

**Comment by ajsutton** [comment]
The key thread looks to be this one:
```
"ValidatorApiChannel-0" #58 daemon prio=5 os_prio=0 cpu=1425595.74ms elapsed=254802.83s tid=0x00007f58205d6000 nid=0x17a6 waiting on condition  [0x00007f57f51e4000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.2/Native Method)
	- parking to wait for  <0x00000000c485af90> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.2/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@11.0.2/AbstractQueuedSynchronizer.java:2081)
	at java.util.concurrent.ArrayBlockingQueue.put(java.base@11.0.2/ArrayBlockingQueue.java:367)
	at tech.pegasys.teku.events.AsyncEventDeliverer.enqueueDelivery(AsyncEventDeliverer.java:78)
	at tech.pegasys.teku.events.AsyncEventDeliverer.deliverTo(AsyncEventDeliverer.java:60)
	at tech.pegasys.teku.events.EventDeliverer.lambda$invoke$0(EventDeliverer.java:54)
	at tech.pegasys.teku.events.EventDeliverer$$Lambda$922/0x000000010074e040.accept(Unknown Source)
	at tech.pegasys.teku.util.events.Subscribers.lambda$forEach$0(Subscribers.java:98)
	at tech.pegasys.teku.util.events.Subscribers$$Lambda$295/0x00000001004f9840.accept(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(java.base@11.0.2/ConcurrentHashMap.java:4772)
	at tech.pegasys.teku.util.events.Subscribers.forEach(Subscribers.java:95)
	at tech.pegasys.teku.events.EventDeliverer.invoke(EventDeliverer.java:54)
	at tech.pegasys.teku.events.AsyncEventDeliverer.invoke(AsyncEventDeliverer.java:31)
	at com.sun.proxy.$Proxy38.subscribeToBeaconCommitteeForAggregation(Unknown Source)
	at tech.pegasys.teku.validator.client.metrics.MetricRecordingValidatorApiChannel.subscribeToBeaconCommitteeForAggregation(MetricRecordingValidatorApiChannel.java:160)
	at tech.pegasys.teku.validator.client.duties.AggregationDuty.lambda$addValidator$0(AggregationDuty.java:78)
	at tech.pegasys.teku.validator.client.duties.AggregationDuty$$Lambda$1266/0x0000000100881440.apply(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(java.base@11.0.2/ConcurrentHashMap.java:1705)
	- locked <0x00000000f33a8f48> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
	at tech.pegasys.teku.validator.client.duties.AggregationDuty.addValidator(AggregationDuty.java:75)
	at tech.pegasys.teku.validator.client.duties.ScheduledDuties.scheduleAggregationDuties(ScheduledDuties.java:66)
	- locked <0x00000000f30f7e08> (a tech.pegasys.teku.validator.client.duties.ScheduledDuties)
	at tech.pegasys.teku.validator.client.ValidatorApiDutyLoader.lambda$scheduleAggregation$9(ValidatorApiDutyLoader.java:165)
	at tech.pegasys.teku.validator.client.ValidatorApiDutyLoader$$Lambda$1260/0x000000010087f040.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniAcceptNow(java.base@11.0.2/CompletableFuture.java:753)
	at java.util.concurrent.CompletableFuture.uniAcceptStage(java.base@11.0.2/CompletableFuture.java:731)
	at java.util.concurrent.CompletableFuture.thenAccept(java.base@11.0.2/CompletableFuture.java:2108)
	at tech.pegasys.teku.util.async.SafeFuture.thenAccept(SafeFuture.java:299)
	at tech.pegasys.teku.validator.client.ValidatorApiDutyLoader.scheduleAggregation(ValidatorApiDutyLoader.java:162)
	at tech.pegasys.teku.validator.client.ValidatorApiDutyLoader.scheduleAttestationDuties(ValidatorApiDutyLoader.java:130)
	at tech.pegasys.teku.validator.client.ValidatorApiDutyLoader.lambda$scheduleDuties$7(ValidatorApiDutyLoader.java:96)
	at tech.pegasys.teku.validator.client.ValidatorApiDutyLoader$$Lambda$1251/0x000000010087c840.apply(Unknown Source)
	at java.util.Optional.map(java.base@11.0.2/Optional.java:265)
	at tech.pegasys.teku.validator.client.ValidatorApiDutyLoader.scheduleDuties(ValidatorApiDutyLoader.java:91)
	at tech.pegasys.teku.validator.client.ValidatorApiDutyLoader.lambda$scheduleAllDuties$4(ValidatorApiDutyLoader.java:81)
	at tech.pegasys.teku.validator.client.ValidatorApiDutyLoader$$Lambda$1249/0x000000010087c040.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(java.base@11.0.2/ReferencePipeline.java:195)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(java.base@11.0.2/ArrayList.java:1654)
	at java.util.stream.AbstractPipeline.copyInto(java.base@11.0.2/AbstractPipeline.java:484)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(java.base@11.0.2/AbstractPipeline.java:474)
	at java.util.stream.AbstractPipeline.evaluate(java.base@11.0.2/AbstractPipeline.java:550)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(java.base@11.0.2/AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(java.base@11.0.2/ReferencePipeline.java:517)
	at tech.pegasys.teku.validator.client.ValidatorApiDutyLoader.scheduleAllDuties(ValidatorApiDutyLoader.java:82)
	at tech.pegasys.teku.validator.client.ValidatorApiDutyLoader.lambda$requestAndScheduleDutiesForEpoch$2(ValidatorApiDutyLoader.java:73)
	at tech.pegasys.teku.validator.client.ValidatorApiDutyLoader$$Lambda$991/0x0000000100778440.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(java.base@11.0.2/CompletableFuture.java:1072)
	at java.util.concurrent.CompletableFuture.postComplete(java.base@11.0.2/CompletableFuture.java:506)
	at java.util.concurrent.CompletableFuture.complete(java.base@11.0.2/CompletableFuture.java:2073)
	at tech.pegasys.teku.util.async.SafeFuture.lambda$propagateResult$2(SafeFuture.java:97)
	at tech.pegasys.teku.util.async.SafeFuture$$Lambda$297/0x00000001004fa040.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(java.base@11.0.2/CompletableFuture.java:859)
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(java.base@11.0.2/CompletableFuture.java:883)
	at java.util.concurrent.CompletableFuture.whenComplete(java.base@11.0.2/CompletableFuture.java:2251)
	at tech.pegasys.teku.util.async.SafeFuture.whenComplete(SafeFuture.java:328)
	at tech.pegasys.teku.util.async.SafeFuture.whenComplete(SafeFuture.java:26)
	at tech.pegasys.teku.util.async.SafeFuture.propagateResult(SafeFuture.java:92)
	at tech.pegasys.teku.util.async.SafeFuture.lambda$exceptionallyCompose$13(SafeFuture.java:233)
	at tech.pegasys.teku.util.async.SafeFuture$$Lambda$299/0x00000001004fa840.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(java.base@11.0.2/CompletableFuture.java:859)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(java.base@11.0.2/CompletableFuture.java:837)
	at java.util.concurrent.CompletableFuture.postComplete(java.base@11.0.2/CompletableFuture.java:506)
	at java.util.concurrent.CompletableFuture.complete(java.base@11.0.2/CompletableFuture.java:2073)
	at tech.pegasys.teku.util.async.SafeFuture.lambda$propagateResult$2(SafeFuture.java:97)
	at tech.pegasys.teku.util.async.SafeFuture$$Lambda$297/0x00000001004fa040.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(java.base@11.0.2/CompletableFuture.java:859)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(java.base@11.0.2/CompletableFuture.java:837)
	at java.util.concurrent.CompletableFuture.postComplete(java.base@11.0.2/CompletableFuture.java:506)
	at java.util.concurrent.CompletableFuture.complete(java.base@11.0.2/CompletableFuture.java:2073)
	at tech.pegasys.teku.util.async.SafeFuture.lambda$propagateResult$2(SafeFuture.java:97)
	at tech.pegasys.teku.util.async.SafeFuture$$Lambda$297/0x00000001004fa040.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(java.base@11.0.2/CompletableFuture.java:859)
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(java.base@11.0.2/CompletableFuture.java:883)
	at java.util.concurrent.CompletableFuture.whenComplete(java.base@11.0.2/CompletableFuture.java:2251)
	at tech.pegasys.teku.util.async.SafeFuture.whenComplete(SafeFuture.java:328)
	at tech.pegasys.teku.util.async.SafeFuture.whenComplete(SafeFuture.java:26)
	at tech.pegasys.teku.util.async.SafeFuture.propagateResult(SafeFuture.java:92)
	at tech.pegasys.teku.util.async.SafeFuture.propagateTo(SafeFuture.java:181)
	at tech.pegasys.teku.events.AsyncEventDeliverer.lambda$deliverToWithResponse$1(AsyncEventDeliverer.java:70)
	at tech.pegasys.teku.events.AsyncEventDeliverer$$Lambda$296/0x00000001004f9c40.run(Unknown Source)
	at tech.pegasys.teku.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:111)
	at tech.pegasys.teku.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.2/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.2/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.2/Thread.java:834)
```


The thread I followed is:
- `SlotEventsChannel-0` is the first event channel thread I spotted. It is blocked in `BeaconChainEventAdapter.onSlot(BeaconChainEventAdapter.java:55)` trying to publish to `ValidatorTimingChannel`.
- `ValidatorTimingChannel-0` is blocked in `MetricRecordingValidatorApiChannel.subscribeToPersistentSubnets(MetricRecordingValidatorApiChannel.java:166)` trying to publish to `ValidatorApiChannel`
- `ValidatorApiChannel-0` is the thread above.  It's processing an event which has resulted in completing a future - that future in turn has sent another event to `ValidatorApiChannel` which creates a loop.  Normally that's fine because the event gets added to the queue and processed later, but when the queue is full the publish blocks until `ValidatorApiChannel-0` finishes processing some events to free up space, but it *is* what has gotten block so everything is now deadlocked.  Eventually that has a knock on effect and other queues back up but it's this loop that likely causes the initial problem.

I suspect we should change `AsyncEventDeliverer` to complete the future return value on a separate thread to the one that processes events. to avoid this kind of issue.

**Comment by ajsutton** [comment]
I suspect we should also have multiple threads servicing events for `ValidatorApiChannel`.

**Comment by ajsutton** [comment]
![image](https://user-images.githubusercontent.com/72675/87623581-0bb31280-c769-11ea-943a-eccb2fe5b273.png)

This shows the event channel queue sizes during the problematic time.  The one that goes up first is the `ValidatorApiChannel` which confirms that it was the source of the problem and everything else was a knock-on effect.
