### ISSUE TITLE
Libp2p InternalException

### ISSUE THREAD

**Issue by Nashatyrev** [Consensys-Incorporated/teku#2359]
### Description
Seen that exception once when running Altona node:
```
2020-07-15 08:20:03.568+03:00 | P2PService-event-thread-0 | WARN  | AbstractRouter | AbstractRouter internal error on message null from peer null
io.libp2p.core.InternalErrorException: [peerHandler] not initialized yet
        at io.libp2p.etc.util.P2PService$StreamHandler.getPeerHandler(P2PService.kt:82) ~[jvm-libp2p-minimal-0.5.3-RELEASE.jar:?]
        at io.libp2p.etc.util.P2PServiceSemiDuplex.streamActive(P2PServiceSemiDuplex.kt:55) ~[jvm-libp2p-minimal-0.5.3-RELEASE.jar:?]
        at io.libp2p.etc.util.P2PService$StreamHandler$channelActive$1.invoke(P2PService.kt:61) ~[jvm-libp2p-minimal-0.5.3-RELEASE.jar:?]
        at io.libp2p.etc.util.P2PService$StreamHandler$channelActive$1.invoke(P2PService.kt:36) ~[jvm-libp2p-minimal-0.5.3-RELEASE.jar:?]
        at io.libp2p.etc.util.P2PService$runOnEventThread$1.run(P2PService.kt:231) [jvm-libp2p-minimal-0.5.3-RELEASE.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
```

This is highly likely the Libp2p problem. It might happen before but could be invisible since internal exceptions were swallowed before. 

Don't think this can be easily reproduced. 
One way to handle this is to create high-load Libp2p tests. 
Another way is add excessive logs to gather additional info.

### Acceptance Criteria
No exceptions 

### Steps to Reproduce (Bug)
Run node for long time and check logs for exceptions

**Frequency:** once in a day or so

### Versions (Add all that apply)
Libp2p 0.5.3

**Comment by benjaminion** [comment]
I've seen this 15 times since restarting my node 11 hours ago with a fresh build. So it's occurring quite a lot more frequently on my platform. Happy to add instrumentation/increase the log level.
