### ISSUE TITLE
Abstract Router Internal Error Message

### ISSUE THREAD

**Issue by cemozerr** [Consensys-Incorporated/teku#2430]
### Description
Seeing this on my `0.12.2-SNAPSHOT` Altona mode, yet it doesn't seem to affect the node at all:

```
WARN - AbstractRouter internal error on message null from peer null

io.libp2p.core.InternalErrorException: [peerHandler] not initialized yet
	at io.libp2p.etc.util.P2PService$StreamHandler.getPeerHandler(P2PService.kt:82)
	at io.libp2p.etc.util.P2PServiceSemiDuplex.streamActive(P2PServiceSemiDuplex.kt:55)
	at io.libp2p.etc.util.P2PService$StreamHandler$channelActive$1.invoke(P2PService.kt:61)
	at io.libp2p.etc.util.P2PService$StreamHandler$channelActive$1.invoke(P2PService.kt:36)
	at io.libp2p.etc.util.P2PService$runOnEventThread$1.run(P2PService.kt:231)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by cemozerr** [comment]
Closing this as duplicate.

**Comment by rolfyone** [comment]
duplicate of #2359
