### ISSUE TITLE
Skipped producing attestation while node is syncing (while not syncing)

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#2438]
This seems to be new:

```
2020-07-24 01:40:33.377+00:00 | TimeTickChannel-0 | INFO  | teku-event-log | ^[[37mSlot Event  *** Slot: 176752, Block: 57e63b..991a, Epoch: 5523, Finalized checkpoint: 5521, Finalized root: 23fb5c..8e39, Peers: 78^[[0m
2020-07-24 01:40:45.377+00:00 | TimeTickChannel-0 | INFO  | teku-event-log | ^[[37mSlot Event  *** Slot: 176753, Block: b56950..bfb9, Epoch: 5523, Finalized checkpoint: 5521, Finalized root: 23fb5c..8e39, Peers: 78^[[0m
2020-07-24 01:40:45.408+00:00 | validator-async-7720 | INFO  | teku-validator-log | ^[[34mValidator   *** Published attestation  Count: 1, Slot: 176753, Root: b56950..bfb9^[[0m
2020-07-24 01:40:57.377+00:00 | TimeTickChannel-0 | INFO  | teku-event-log | ^[[37mSlot Event  *** Slot: 176754, Block: 5048fc..ac90, Epoch: 5523, Finalized checkpoint: 5521, Finalized root: 23fb5c..8e39, Peers: 78^[[0m
2020-07-24 01:40:57.383+00:00 | validator-async-7721 | WARN  | teku-validator-log | ^[[33mValidator   *** Skipped producing attestation while node is syncing  Count: 1, Slot: 176754^[[0m
2020-07-24 01:41:09.374+00:00 | TimeTickChannel-0 | INFO  | teku-event-log | ^[[37mSlot Event  *** Slot: 176755, Block: 744b4d..f977, Epoch: 5523, Finalized checkpoint: 5521, Finalized root: 23fb5c..8e39, Peers: 78^[[0m
2020-07-24 01:41:09.380+00:00 | validator-async-7722 | INFO  | teku-validator-log | ^[[34mValidator   *** Published attestation  Count: 1, Slot: 176755, Root: 744b4d..f977^[[0m
2020-07-24 01:41:21.376+00:00 | TimeTickChannel-0 | INFO  | teku-event-log | ^[[37mSlot Event  *** Slot: 176756, Block:    ... empty, Epoch: 5523, Finalized checkpoint: 5521, Finalized root: 23fb5c..8e39, Peers: 78^[[0m
2020-07-24 01:41:33.376+00:00 | TimeTickChannel-0 | INFO  | teku-event-log | ^[[37mSlot Event  *** Slot: 176757, Block: a90a17..e97d, Epoch: 5523, Finalized checkpoint: 5521, Finalized root: 23fb5c..8e39, Peers: 78^[[0m
```

Version `teku/v0.12.2-dev-43e04799/linux-x86_64/-privatebuild-openjdk64bitservervm-java-13`.

It might be related to the micro-syncs I note in https://github.com/PegaSysEng/teku/issues/2423#issuecomment-663238479.

**Comment by ajsutton** [comment]
Running in interop mode with a single node a number of times just after launching with a fresh db I've gotten:

```
2020-08-05 10:14:59.201 | TimeTickChannel-0         | INFO  | teku-event-log                 | Epoch Event *** Epoch: 0, Justified checkpoint: 0, Finalized checkpoint: 0, Finalized root: a7a6f3..09a5
2020-08-05 10:15:01.202 | TimeTickChannel-0         | INFO  | teku-event-log                 | Slot Event  *** Slot: 0, Block: a7a6f3..09a5, Epoch: 0, Finalized checkpoint: 0, Finalized root: a7a6f3..09a5, Peers: 0
2020-08-05 10:15:01.227 | validator-async-3         | INFO  | teku-validator-log             | Validator   *** Published attestation  Count: 8, Slot: 0, Root: a7a6f3..09a5
2020-08-05 10:15:03.206 | validator-async-7         | INFO  | teku-validator-log             | Validator   *** Published aggregate    Count: 2, Slot: 0, Root: a7a6f3..09a5
2020-08-05 10:15:05.235 | validator-async-8         | INFO  | teku-validator-log             | Validator   *** Published block        Count: 1, Slot: 1, Root: fcde05..935b
2020-08-05 10:15:05.288 | validator-async-6         | INFO  | teku-validator-log             | Validator   *** Published attestation  Count: 8, Slot: 1, Root: a7a6f3..09a5
2020-08-05 10:15:07.203 | TimeTickChannel-0         | INFO  | teku-event-log                 | Slot Event  *** Slot: 1, Block: fcde05..935b, Epoch: 0, Finalized checkpoint: 0, Finalized root: a7a6f3..09a5, Peers: 0
2020-08-05 10:15:09.201 | validator-async-9         | INFO  | teku-validator-log             | Validator   *** Published aggregate    Count: 2, Slot: 1, Root: a7a6f3..09a5
2020-08-05 10:15:11.209 | validator-async-10        | INFO  | teku-validator-log             | Validator   *** Published block        Count: 1, Slot: 2, Root: 546107..f423
2020-08-05 10:15:11.229 | validator-async-1         | INFO  | teku-validator-log             | Validator   *** Published attestation  Count: 8, Slot: 2, Root: fcde05..935b
2020-08-05 10:15:13.200 | TimeTickChannel-0         | INFO  | teku-event-log                 | Slot Event  *** Slot: 2, Block: 546107..f423, Epoch: 0, Finalized checkpoint: 0, Finalized root: a7a6f3..09a5, Peers: 0
2020-08-05 10:15:15.200 | validator-async-3         | INFO  | teku-validator-log             | Validator   *** Published aggregate    Count: 2, Slot: 2, Root: fcde05..935b
2020-08-05 10:15:17.201 | validator-async-11        | WARN  | teku-validator-log             | Validator   *** Skipped producing block while node is syncing  Count: 1, Slot: 3
2020-08-05 10:15:19.203 | TimeTickChannel-0         | INFO  | teku-event-log                 | Slot Event  *** Slot: 3, Block:    ... empty, Epoch: 0, Finalized checkpoint: 0, Finalized root: a7a6f3..09a5, Peers: 0
2020-08-05 10:15:19.205 | validator-async-8         | WARN  | teku-validator-log             | Validator   *** Skipped producing attestation while node is syncing  Count: 2, Slot: 3
2020-08-05 10:15:21.199 | ValidatorTimingChannel-0  | WARN  | teku-validator-log             | Validator   *** Skipped producing aggregate while node is syncing  Count: 2, Slot: 3
2020-08-05 10:15:23.199 | validator-async-5         | WARN  | teku-validator-log             | Validator   *** Skipped producing block while node is syncing  Count: 1, Slot: 4
2020-08-05 10:15:25.196 | TimeTickChannel-0         | INFO  | teku-event-log                 | Slot Event  *** Slot: 4, Block:    ... empty, Epoch: 0, Finalized checkpoint: 0, Finalized root: a7a6f3..09a5, Peers: 0
2020-08-05 10:15:25.196 | validator-async-4         | WARN  | teku-validator-log             | Validator   *** Skipped producing attestation while node is syncing  Count: 2, Slot: 4
2020-08-05 10:15:27.198 | ValidatorTimingChannel-0  | WARN  | teku-validator-log             | Validator   *** Skipped producing aggregate while node is syncing  Count: 2, Slot: 4
2020-08-05 10:15:29.207 | validator-async-9         | INFO  | teku-validator-log             | Validator   *** Published block        Count: 1, Slot: 5, Root: 9b8a62..7c69
2020-08-05 10:15:29.236 | validator-async-0         | INFO  | teku-validator-log             | Validator   *** Published attestation  Count: 8, Slot: 5, Root: 546107..f423
2020-08-05 10:15:31.201 | TimeTickChannel-0         | INFO  | teku-event-log                 | Slot Event  *** Slot: 5, Block: 9b8a62..7c69, Epoch: 0, Finalized checkpoint: 0, Finalized root: a7a6f3..09a5, Peers: 0
```

Not sure why the node decided it was syncing in there...

**Comment by benjaminion** [comment]
I'm going to reopen this as I still see it occasionally (~2-3 times per day, with 64 validators).

Here are yesterday's. On two occasions immediately following this message there was a `PeerSync | Failed to import block from peer` message:

```
2020-08-07 10:07:12.478+00:00 | TimeTickChannel-0 | INFO  | teku-event-log | ^[[37mSlot Event  *** Slot: 20735, Block: 6fd245..e292, Epoch: 647, Finalized checkpoint: 644, Finalized root: 4fa3e3..bbdc, Peers: 80^[[0m
2020-08-07 10:07:20.443+00:00 | TimeTickChannel-0 | INFO  | teku-event-log | ^[[32mEpoch Event *** Epoch: 648, Justified checkpoint: 646, Finalized checkpoint: 644, Finalized root: 4fa3e3..bbdc^[[0m
2020-08-07 10:07:24.933+00:00 | validator-async-115 | WARN  | teku-validator-log | ^[[33mValidator   *** Skipped producing attestation while node is syncing  Count: 3, Slot: 20736^[[0m
2020-08-07 10:07:24.956+00:00 | TimeTickChannel-0 | INFO  | teku-event-log | ^[[37mSync Event  *** Current slot: 20736, Head slot: 20736, Connected peers: 80^[[0m
2020-08-07 10:07:25.165+00:00 | p2p-async-9 | WARN  | PeerSync | Failed to import block from peer (err: UNKNOWN_PARENT) SignedBeaconBlock{message=BeaconBlock{root=0x16f2b2c4c3f9a20d6d18c99ca3b8f88fd42e50195aa5d71deae89239f52ec512, slot=20676, proposer_index=9437, parent_root=0x272671d817b4e128021a0f506b3ec2db85e5670e4e1f5b92a400b90a79257a16, state_root=0x949ea44505963891cb06f87b7418ce47559e0d780975fa9fa7d6f62c5efe471e, body=0x4d29134e64518cb8eb77a1d599546f9e27b4544085a12009b3375aa46cce40f9}, signature=0xacb18ffcba1bffba77ea9a92da636d067619d0919e9cd10de2d19fd805ef13d4332dfa718b714d7b661d51f6dbd0135d13e13fc339216ed02a38a26ca10bb8f49097bff3133649173432fa4c21e8776f9566c11bc25c08e8c1bb4d9f6f4e8920}: Eth2Peer{id=16Uiu2HAmPNRRV61S68KkpfKmndt9w5JbXSVX5TkKFivf1TTtkgs8, remoteStatus=Optional[PeerStatus{forkDigest=0xe7a75d5a, finalizedRoot=0x54fdf6dd7b09401b63ca6d37d9acbef914394e1a02ac277dbab351456d115780, finalizedEpoch=646, headRoot=0x639ebff5fce94530da621ccb698a0da535e42cb04688461db7f47eb84ba4a604, headSlot=20736}]}
2020-08-07 10:07:36.463+00:00 | TimeTickChannel-0 | INFO  | teku-event-log | ^[[37mSlot Event  *** Slot: 20737, Block:    ... empty, Epoch: 648, Finalized checkpoint: 646, Finalized root: 54fdf6..5780, Peers: 78^[[0m
2020-08-07 10:07:36.485+00:00 | validator-async-121 | INFO  | teku-validator-log | ^[[34mValidator   *** Published attestation  Count: 5, Slot: 20737, Root: 639ebf..a604^[[0m
```

```
2020-08-07 17:29:00.466+00:00 | TimeTickChannel-0 | INFO  | teku-event-log | ^[[37mSlot Event  *** Slot: 22944, Block:    ... empty, Epoch: 717, Finalized checkpoint: 714, Finalized root: c4a43e..39d8, Peers: 80^[[0m
2020-08-07 17:29:00.490+00:00 | validator-async-360 | INFO  | teku-validator-log | ^[[34mValidator   *** Published attestation  Count: 4, Slot: 22944, Root: 66e9e5..af95^[[0m
2020-08-07 17:29:12.771+00:00 | validator-async-361 | WARN  | teku-validator-log | ^[[33mValidator   *** Skipped producing attestation while node is syncing  Count: 1, Slot: 22945^[[0m
2020-08-07 17:29:12.832+00:00 | TimeTickChannel-0 | INFO  | teku-event-log | ^[[37mSync Event  *** Current slot: 22945, Head slot: 22945, Connected peers: 80^[[0m
2020-08-07 17:29:21.218+00:00 | validator-async-362 | INFO  | teku-validator-log | ^[[34mValidator   *** Published attestation  Count: 1, Slot: 22946, Root: 2192f3..889e^[[0m
2020-08-07 17:29:24.459+00:00 | TimeTickChannel-0 | INFO  | teku-event-log | ^[[37mSlot Event  *** Slot: 22946, Block: 642c1e..4d78, Epoch: 717, Finalized checkpoint: 715, Finalized root: df5625..22bc, Peers: 80^[[0m
```

```
2020-08-07 22:29:36.509+00:00 | TimeTickChannel-0 | INFO  | teku-event-log | ^[[37mSlot Event  *** Slot: 24447, Block: ce371c..85bc, Epoch: 763, Finalized checkpoint: 761, Finalized root: cbe22b..d3ed, Peers: 80^[[0m
2020-08-07 22:29:44.444+00:00 | TimeTickChannel-0 | INFO  | teku-event-log | ^[[32mEpoch Event *** Epoch: 764, Justified checkpoint: 762, Finalized checkpoint: 761, Finalized root: cbe22b..d3ed^[[0m
2020-08-07 22:29:49.530+00:00 | validator-async-499 | WARN  | teku-validator-log | ^[[33mValidator   *** Skipped producing attestation while node is syncing  Count: 2, Slot: 24448^[[0m
2020-08-07 22:29:49.559+00:00 | TimeTickChannel-0 | INFO  | teku-event-log | ^[[37mSync Event  *** Current slot: 24448, Head slot: 24448, Connected peers: 80^[[0m
2020-08-07 22:29:50.345+00:00 | p2p-async-0 | WARN  | PeerSync | Failed to import block from peer (err: UNKNOWN_PARENT) SignedBeaconBlock{message=BeaconBlock{root=0x8b5d5fbd58ca085dd47cc7a7deb0b679d930bc667cad08344055e39a8d0353a0, slot=24353, proposer_index=5822, parent_root=0xcbe22b753447c83366c5f53e1c82185591766aed671eb9f9f85dce894313d3ed, state_root=0xe1c0419153270238b6880fc24a639dcb9fe0be62894d79a3a2505fa7e3ee3951, body=0xec58fe1443127310937c89c07d657a4af47217da30e48491977da2def2ad2043}, signature=0x940667bc1057b117c11485966c170078520099dc4871144616e19b4670435940d13be013f3d561a38e24b77ef93c0d4a0a2319cbbebafefba66728ca36adb59b2f90a66fc9e80835416cfb660c49edb61b36dda87b0e60ae9b09f138424c2e65}: Eth2Peer{id=16Uiu2HAmEfRpvY5uvg4veJZNf1WByYbfEcGmhYvR1kcbDtEhfNwR, remoteStatus=Optional[PeerStatus{forkDigest=0xe7a75d5a, finalizedRoot=0xc44797fb79e095a9755a61603c8f627ec6957e8e00f642e02965099a100e94c9, finalizedEpoch=762, headRoot=0xe33bf3a28bfc56c8dec7ea6caa48c26b6d6ad38ac53e2af036c6f51c8936620d, headSlot=24448}]}
2020-08-07 22:29:50.356+00:00 | nioEventLoopGroup-3-3 | ERROR | Eth2OutgoingRequestHandler | Encountered error while processing response
java.lang.IllegalStateException: New response submitted after closing AsyncResponseProcessor for new responses: SignedBeaconBlock{message=BeaconBlock{root=0x0adc715f0284d545491bb6e263d95ef4997614bd2259d74b398acd5f5a59c51d, slot=24354, proposer_index=13955, parent_root=0x8b5d5fbd58ca085dd47cc7a7deb0b679d930bc667cad08344055e39a8d0353a0, state_root=0xb8058f64d6c500a8bbdd59c6035c72382341790da9579fdd4294318c439f907d, body=0x9401e1d0169cf4ef5b98859b80fa55336752b0149986f299ea5ab6ddc65a0c51}, signature=0x95a8cf292efa2af5d1bbdcca821ff75b51c8b35bbaba8022d5b574a87b70efb07538a2d1b4d83f8f9ae5768ef8e0881f106aa7f2aaf662ffd2e09f8fd78c664e5b01ddef922387b4632f8c86f6c907b0cf002eaf1336d990865570ad2991ba77}
        at tech.pegasys.teku.networking.eth2.rpc.core.AsyncResponseProcessor.processResponse(AsyncResponseProcessor.java:53) ~[teku-networking-eth2-0.12.3-SNAPSHOT.jar:0.12.3-dev-79ef540b]
        at java.util.ArrayList.forEach(ArrayList.java:1507) ~[?:?]
        at tech.pegasys.teku.networking.eth2.rpc.core.Eth2OutgoingRequestHandler.processData(Eth2OutgoingRequestHandler.java:96) [teku-networking-eth2-0.12.3-SNAPSHOT.jar:0.12.3-dev-79ef540b]
        at tech.pegasys.teku.networking.p2p.libp2p.rpc.RpcHandler$Controller.channelRead0(RpcHandler.java:143) [teku-networking-p2p-0.12.3-SNAPSHOT.jar:0.12.3-dev-79ef540b]
        at tech.pegasys.teku.networking.p2p.libp2p.rpc.RpcHandler$Controller.channelRead0(RpcHandler.java:118) [teku-networking-p2p-0.12.3-SNAPSHOT.jar:0.12.3-dev-79ef540b]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.libp2p.etc.util.netty.mux.AbstractMuxHandler.childRead(AbstractMuxHandler.kt:55) [jvm-libp2p-minimal-0.5.4-RELEASE.jar:?]
        at io.libp2p.mux.MuxHandler.channelRead(MuxHandler.kt:39) [jvm-libp2p-minimal-0.5.4-RELEASE.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:425) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at java.lang.Thread.run(Thread.java:830) [?:?]
```

teku/v0.12.3-dev-79ef540b/linux-x86_64/-privatebuild-openjdk64bitservervm-java-13

As far as I can tell, I have had no network interruptions that might lead to needing to sync. Not seeing any significant GC going on that might have interrupted things.
