### ISSUE TITLE
Blocked vertx thread and node drops out of sync

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#2444]
### Description
Exceptions like the one below repeatedly printing and node was out of sync.  Restarting fixed it.

``` 
Jul 26, 2020 8:15:47 PM io.vertx.core.impl.BlockedThreadChecker                                                                                                                   │
│ WARNING: Thread Thread[vert.x-worker-thread-18,5,main]=Thread[vert.x-worker-thread-18,5,main] has been blocked for 56574355 ms, time limit is 60000 ms                            │
│ io.vertx.core.VertxException: Thread blocked                                                                                                                                      │
│     at java.base@14.0.2/jdk.internal.misc.Unsafe.park(Native Method)                                                                                                              │
│     at java.base@14.0.2/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)                                                                                         │
│     at java.base@14.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:714)                                                        │
│     at java.base@14.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(AbstractQueuedSynchronizer.java:1026)                                                 │
│     at java.base@14.0.2/java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(ReentrantReadWriteLock.java:738)                                                          │
│     at app//tech.pegasys.teku.storage.store.Store.countCheckpointStates(Store.java:623)                                                                                           │
│     at app//tech.pegasys.teku.storage.store.Store$$Lambda$511/0x0000000800f63c40.getAsInt(Unknown Source)                                                                         │
│     at app//org.hyperledger.besu.plugin.services.MetricsSystem.lambda$createIntegerGauge$0(MetricsSystem.java:103)                                                                │
│     at app//org.hyperledger.besu.plugin.services.MetricsSystem$$Lambda$196/0x0000000800d5c040.getAsDouble(Unknown Source)                                                         │
│     at app//org.hyperledger.besu.metrics.prometheus.CurrentValueCollector.collect(CurrentValueCollector.java:42)                                                                  │
│     at app//io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:190)                                                     │
│     at app//io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:223)                                                         │
│     at app//io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:144)                                                         │
│     at app//io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:22)                                                                                          │
│     at app//org.hyperledger.besu.metrics.prometheus.MetricsHttpService.lambda$metricsRequest$4(MetricsHttpService.java:205)                                                       │
│     at app//org.hyperledger.besu.metrics.prometheus.MetricsHttpService$$Lambda$1329/0x00000008012a5c40.handle(Unknown Source)                                                     │
│     at app//io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)                                                                                         │
│     at app//io.vertx.core.impl.ContextImpl$$Lambda$1331/0x00000008012a5440.run(Unknown Source)                                                                                    │
│     at java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)                                                                           │
│     at java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)                                                                           │
│     at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)                                                                                 │
│     at java.base@14.0.2/java.lang.Thread.run(Thread.java:832) 
```

Reported via internal slack https://consensys.slack.com/archives/C014L7NGS2G/p1595794604181300

**Comment by rolfyone** [comment]
moved the metrics to a settableGauge which will at least stop that issue.
Will close this.
