### ISSUE TITLE
Dropped out of sync on Altona

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#2446]
### Description
My local node has dropped out of sync on Altona.  AWS nodes we run have continued tracking head so this is not a straight consensus split - more likely our sync code getting stuck somewhere.

I have a lot of

```
ku_1           | 2020-07-26 23:54:06.041 | p2p-async-4               | WARN  | PeerSync                       | Failed to import block from peer (err: FAILED_STATE_TRANSITION) SignedBeaconBlock{message=BeaconBlock{root=0x6f3dd4fdc0b4a30e911d607c8810f4a6e67253be2925fb3ea51efdcefa4aedc3, slot=190953, proposer_index=4766, parent_root=0x961416590b72bee69ac3de2b5f368be08e7e3561ea1b5ca8319bb8ba20639080, state_root=0xd8671292df6bc47bddab7aceb1c90adeebae72778bbf1523f87edc3e7b8c473a, body=0x773fd31666f17bfc8368599b6affaf3dd28e205c3e096390b82bec62c9271da0}, signature=0x8bac93e329cdfe5c48b630df82baf168682038a1bb424e763f6f884b5a80574a1e201e38daa0259771a4310e4564c4f00eee23bd2d0ac6a2be98d1147d20a3002923260337149e24d405ba1c9610c4c1b610fd55f778d1a2ec69eae7d6254527}: Eth2Peer{id=16Uiu2HAmGuSCvqbtGYJtUUwwrcC697HoDmGEwTXBGNbi4DpEYCip, remoteStatus=Optional[PeerStatus{forkDigest=0xfdca39b0, finalizedRoot=0x028460d5ed683b82f43b7f353a6131a1bd66d2231af79b2c96ef4eec3ca741e3, finalizedEpoch=6170, headRoot=0x3130976da9ce87d3117fff850215218ffd1d96e99e580b728717a4487a89737a, headSlot=197818}]}
teku_1           | 2020-07-26 23:54:17.210 | TimeTickChannel-0         | INFO  | teku-event-log                 | Sync Event  *** Current slot: 197821, Head slot: 190950, Connected peers: 5
teku_1           | 2020-07-26 23:54:29.210 | TimeTickChannel-0         | INFO  | teku-event-log                 | Sync Event  *** Current slot: 197822, Head slot: 190950, Connected peers: 7
teku_1           | 2020-07-26 23:54:35.574 | p2p-async-2               | WARN  | StateTransition                | State Transition error
teku_1           | tech.pegasys.teku.core.exceptions.BlockProcessingException: tech.pegasys.teku.core.exceptions.BlockProcessingException: Invalid attestation: Signature is invalid
teku_1           | 	at tech.pegasys.teku.core.StateTransition.initiate(StateTransition.java:109) ~[teku-ethereum-core-0.12.2-SNAPSHOT.jar:0.12.2-dev-95530612]
teku_1           | 	at tech.pegasys.teku.core.ForkChoiceUtil.on_block(ForkChoiceUtil.java:229) ~[teku-ethereum-core-0.12.2-SNAPSHOT.jar:0.12.2-dev-95530612]
teku_1           | 	at tech.pegasys.teku.statetransition.forkchoice.ForkChoice.onBlock(ForkChoice.java:79) ~[teku-ethereum-statetransition-0.12.2-SNAPSHOT.jar:0.12.2-dev-95530612]
teku_1           | 	at tech.pegasys.teku.statetransition.blockimport.BlockImporter.lambda$importBlock$0(BlockImporter.java:73) ~[teku-ethereum-statetransition-0.12.2-SNAPSHOT.jar:0.12.2-dev-95530612]
teku_1           | 	at java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680) ~[?:?]
teku_1           | 	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658) ~[?:?]
teku_1           | 	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2158) ~[?:?]
teku_1           | 	at tech.pegasys.teku.infrastructure.async.SafeFuture.thenApply(SafeFuture.java:309) ~[teku-infrastructure-async-0.12.2-SNAPSHOT.jar:0.12.2-dev-95530612]
teku_1           | 	at tech.pegasys.teku.statetransition.blockimport.BlockImporter.importBlock(BlockImporter.java:71) ~[teku-ethereum-statetransition-0.12.2-SNAPSHOT.jar:0.12.2-dev-95530612]
teku_1           | 	at tech.pegasys.teku.sync.PeerSync.blockResponseListener(PeerSync.java:216) ~[teku-sync-0.12.2-SNAPSHOT.jar:0.12.2-dev-95530612]
teku_1           | 	at tech.pegasys.teku.sync.PeerSyncBlockRequest.onResponse(PeerSyncBlockRequest.java:41) ~[teku-sync-0.12.2-SNAPSHOT.jar:0.12.2-dev-95530612]
teku_1           | 	at tech.pegasys.teku.sync.PeerSyncBlockRequest.onResponse(PeerSyncBlockRequest.java:22) ~[teku-sync-0.12.2-SNAPSHOT.jar:0.12.2-dev-95530612]
teku_1           | 	at tech.pegasys.teku.networking.eth2.rpc.core.ResponseStreamImpl.respond(ResponseStreamImpl.java:67) ~[teku-networking-eth2-0.12.2-SNAPSHOT.jar:0.12.2-dev-95530612]
teku_1           | 	at tech.pegasys.teku.networking.eth2.rpc.core.AsyncResponseProcessor.lambda$processNextResponse$0(AsyncResponseProcessor.java:108) ~[teku-networking-eth2-0.12.2-SNAPSHOT.jar:0.12.2-dev-95530612]
teku_1           | 	at tech.pegasys.teku.infrastructure.async.SafeFuture.ofComposed(SafeFuture.java:85) ~[teku-infrastructure-async-0.12.2-SNAPSHOT.jar:0.12.2-dev-95530612]
teku_1           | 	at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:119) ~[teku-infrastructure-async-0.12.2-SNAPSHOT.jar:0.12.2-dev-95530612]
teku_1           | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
teku_1           | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
teku_1           | 	at java.lang.Thread.run(Thread.java:832) [?:?]
teku_1           | Caused by: tech.pegasys.teku.core.exceptions.BlockProcessingException: Invalid attestation: Signature is invalid
teku_1           | 	at tech.pegasys.teku.core.BlockProcessorUtil.verify_attestations(BlockProcessorUtil.java:380) ~[teku-ethereum-core-0.12.2-SNAPSHOT.jar:0.12.2-dev-95530612]
teku_1           | 	at tech.pegasys.teku.core.blockvalidator.SimpleBlockValidator.validatePreState(SimpleBlockValidator.java:78) ~[teku-ethereum-core-0.12.2-SNAPSHOT.jar:0.12.2-dev-95530612]
teku_1           | 	at tech.pegasys.teku.core.blockvalidator.BatchBlockValidator.validatePreState(BatchBlockValidator.java:43) ~[teku-ethereum-core-0.12.2-SNAPSHOT.jar:0.12.2-dev-95530612]
teku_1           | 	at tech.pegasys.teku.core.blockvalidator.BlockValidator.validate(BlockValidator.java:88) ~[teku-ethereum-core-0.12.2-SNAPSHOT.jar:0.12.2-dev-95530612]
teku_1           | 	at tech.pegasys.teku.core.StateTransition.initiate(StateTransition.java:106) ~[teku-ethereum-core-0.12.2-SNAPSHOT.jar:0.12.2-dev-95530612]
teku_1           | 	... 18 more
```

Complete logs since last restart:
[tekuLogs.txt](https://github.com/PegaSysEng/teku/files/4978996/tekuLogs.txt)

**Comment by Nashatyrev** [comment]
Additional info from @mbaxter :
> Basically, we’re trying to sync altona and the node is getting stuck processing the block at `190953` (root `0x6f3dd4fdc0b4a30e911d607c8810f4a6e67253be2925fb3ea51efdcefa4aedc3`).  It keeps requesting the block from different peers, reporting that some attestation signature in the block is invalid during block import, and then disconnecting the peer for sending us a bad block.  Other teku nodes are syncing fine, so its not a straight bug in the consensus logic.  On restart, the node started syncing normally.  The only thing I can think that makes sense would be if we’re somehow reading the wrong data from the preState due to threading / visibility issues, or bad caching or something.

**Comment by Nashatyrev** [comment]
Yes, this smells like some `BeaconState` cache (either `TransitionCaches` or backing view caches) concurrency issue.

**Comment by Nashatyrev** [comment]
The node was hanging (or may be machine was suspended) for 51 minutes: 
```
2020-07-26 00:08:57.216 | TimeTickChannel-0         | INFO  | teku-event-log                 | [37mSlot Event  *** Slot: 190694, Block:    ... empty, Epoch: 5959, Finalized checkpoint: 5947, Finalized root: b057cc..cb70, Peers: 72[0m
2020-07-26 00:08:57.232 | validator-async-1444      | INFO  | teku-validator-log             | [34mValidator   *** Published attestation  Count: 1, Slot: 190694, Root: 4b43c7..c622[0m
2020-07-26 01:00:00.284 | TimeTickChannel-0         | INFO  | teku-event-log                 | [37mMiss slots  *** Current slot: 190949, previous slot: 190695[0m
````

**Comment by Nashatyrev** [comment]
Just another observation: before `190953` we had successfully imported some blocks with attestations within the same epoch `5967`.

Unfortunately there is not too much info we can extract from the present data. 

I'd suggest two vectors to resolve this: 
- add more file logs: 
  - I think it would be good to log every transition (slot, block, epoch) with pre and post state roots
  - When the block is failed to import (supposing it's a rare and most likely fatal event) I would probably dump the whole pre-state 
  - would be good to see more detailed info in transition exceptions. I.e. in this concrete case would be good to see the attestation, validator index and validator pubkey
- add high-load concurrency state transition tests to discover potential threading issues with the `BeaconState`

**Comment by ajsutton** [comment]
The node is running on my laptop so it does go to sleep sometimes which is likely why it missed those slots. At other times I'm just torturing the machine doing other things and using all the CPU.

**Comment by mbaxter** [comment]
#2501 had to be reverted - reopening
