### ISSUE TITLE
internal error on message publish: IndexOutOfBoundsException

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#2476]
Got 20 similar to this in about an 80 minute period:

```
2020-07-29 07:01:33.218+00:00 | P2PService-event-thread-0 | WARN  | AbstractRouter | AbstractRouter internal error on message publish {
  from: "\000\001\000"
  data: "\366\001\034\344\000\000\000UE\003\000.\001\000\210\003\206K~Wc\022\321\020Z\376\342\304+\033\365\031\210\201\235\323\020\0026k`\320\301\"{\263\320)\032\000\005/\200\377\253\177\257\211+r\232\352\305\324B\264\363_rY-\331L=\254\003B\020<,\202\277\373m3*\r(\360\221\307\377\323\341\202cFM\262\254\317\3039\306\244\243\304\274D\256\301o3\002\211\233\235\263\0018\247\322\253\027\244\336\226\r]\321\272\340\256\226B\032T\004&B*d\325\a$\271p\370t\370\227\235\"\374\211\327\024Tnz\210\272\256z\016Y\033\333=\237\031J\364\265I?\a\003;\251U\\\221t\323?\272\361-\241\224\300\270\f_R*\242\210\314\212\rOb\377g\355\376\031M\2167\241\376\206x\3330\000\000\000\000\000\000\200\000\000\000\000\000\000\000\000\000\000\200"
  topicIDs: "/eth2/fdca39b0/beacon_attestation_21/ssz_snappy"
}
 from peer PeerHandler(peerId=16Uiu2HAm7EvdK8Z7SbnJF3phqxbzmbHUtCiSDTaWJVpBsRqLcyGo, stream=P2PChannelOverNetty(nettyChannel=[id: 0x3a6823f2/16/true, L:Mux[/192.168.1.203:9000-3a6823f2/16/true] - R:Mux[/178.27.90.170:13000-3a6823f2/16/true]], isInitiator=true))
java.lang.IndexOutOfBoundsException: toIndex (8) is greater than size (0).
        at kotlin.collections.ArraysKt__ArraysJVMKt.copyOfRangeToIndexCheck(ArraysJVM.kt:49) ~[kotlin-stdlib-1.3.72.jar:1.3.72-release-468 (1.3.72)]
        at kotlin.collections.ArraysKt___ArraysJvmKt.copyOfRange(_ArraysJvm.kt:1319) ~[kotlin-stdlib-1.3.72.jar:1.3.72-release-468 (1.3.72)]
        at io.libp2p.pubsub.PubsubApiImpl.rpc2Msg(PubsubApiImpl.kt:83) ~[jvm-libp2p-minimal-0.5.3-RELEASE.jar:?]
        at io.libp2p.pubsub.PubsubApiImpl.onNewMessage(PubsubApiImpl.kt:71) ~[jvm-libp2p-minimal-0.5.3-RELEASE.jar:?]
        at io.libp2p.pubsub.PubsubApiImpl.access$onNewMessage(PubsubApiImpl.kt:23) ~[jvm-libp2p-minimal-0.5.3-RELEASE.jar:?]
        at io.libp2p.pubsub.PubsubApiImpl$1.invoke(PubsubApiImpl.kt:55) ~[jvm-libp2p-minimal-0.5.3-RELEASE.jar:?]
        at io.libp2p.pubsub.PubsubApiImpl$1.invoke(PubsubApiImpl.kt:23) ~[jvm-libp2p-minimal-0.5.3-RELEASE.jar:?]
        at io.libp2p.pubsub.AbstractRouter.onInbound(AbstractRouter.kt:203) [jvm-libp2p-minimal-0.5.3-RELEASE.jar:?]
        at io.libp2p.etc.util.P2PService.streamInbound(P2PService.kt:171) ~[jvm-libp2p-minimal-0.5.3-RELEASE.jar:?]
        at io.libp2p.etc.util.P2PService$StreamHandler$channelRead$1.invoke(P2PService.kt:51) ~[jvm-libp2p-minimal-0.5.3-RELEASE.jar:?]
        at io.libp2p.etc.util.P2PService$StreamHandler$channelRead$1.invoke(P2PService.kt:36) ~[jvm-libp2p-minimal-0.5.3-RELEASE.jar:?]
        at io.libp2p.etc.util.P2PService$runOnEventThread$1.run(P2PService.kt:231) [jvm-libp2p-minimal-0.5.3-RELEASE.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]
```

This differs from #2452, being `IndexOutOfBoundsException` whereas #2452 is a `KotlinNullPointerException`.

Teku version: teku/v0.12.2-dev-fb9e13c7/linux-x86_64/-privatebuild-openjdk64bitservervm-java-13

**Comment by Nashatyrev** [comment]
No `seqno` in the inbound message

**Comment by Nashatyrev** [comment]
Would need to relax Libp2p on all optional fields from this spec issue: https://github.com/ethereum/eth2.0-specs/issues/1981
