### ISSUE TITLE
attestations not getting generated sometimes because state is too far behind

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#2570]
connected to 64 peers, and not able to produce attestations was reported. logs show the following. There seems to be a large number of empty blocks in the log.

from teku discord: https://gist.github.com/J2R5M3/5d6fcbee36c0a806feb3a30d706eaf9c

```
2020-08-12 18:20:24.073-06:00 | TimeTickChannel-0 | INFO  | teku-event-log | [37mSlot Event  *** Slot: 61001, Block:    ... empty, Epoch: 1906, Finalized checkpoint: 1903, Finalized root: c9927d..0d6f, Peers: 30[0m
2020-08-12 18:20:36.089-06:00 | TimeTickChannel-0 | INFO  | teku-event-log | [37mSlot Event  *** Slot: 61002, Block:    ... empty, Epoch: 1906, Finalized checkpoint: 1903, Finalized root: c9927d..0d6f, Peers: 30[0m
2020-08-12 18:20:36.368-06:00 | P2PService-event-thread-0 | WARN  | Eth2TopicHandler | Encountered exception while processing message for topic /eth2/e7a75d5a/beacon_aggregate_and_proof/ssz_snappy
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Committee information must be derived from a state no older than the previous epoch. State at slot 60925 is older than cutoff slot 60960
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:683) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094) [?:?]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.thenApply(SafeFuture.java:320) ~[teku-infrastructure-async-0.12.4-SNAPSHOT.jar:0.12.4-dev-c6548285]
	at tech.pegasys.teku.networking.eth2.gossip.topics.validation.AttestationValidator.singleOrAggregateAttestationChecks(AttestationValidator.java:125) ~[teku-networking-eth2-0.12.4-SNAPSHOT.jar:0.12.4-dev-c6548285]
	at tech.pegasys.teku.networking.eth2.gossip.topics.validation.SignedAggregateAndProofValidator.validate(SignedAggregateAndProofValidator.java:95) ~[teku-networking-eth2-0.12.4-SNAPSHOT.jar:0.12.4-dev-c6548285]
	at tech.pegasys.teku.networking.eth2.gossip.topics.AggregateAttestationTopicHandler.validateData(AggregateAttestationTopicHandler.java:99) ~[teku-networking-eth2-0.12.4-SNAPSHOT.jar:0.12.4-dev-c6548285]
	at tech.pegasys.teku.networking.eth2.gossip.topics.AggregateAttestationTopicHandler.validateData(AggregateAttestationTopicHandler.java:27) ~[teku-networking-eth2-0.12.4-SNAPSHOT.jar:0.12.4-dev-c6548285]
	at tech.pegasys.teku.networking.eth2.gossip.topics.Eth2TopicHandler.lambda$handleMessage$2(Eth2TopicHandler.java:39) ~[teku-networking-eth2-0.12.4-SNAPSHOT.jar:0.12.4-dev-c6548285]
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106) [?:?]
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235) [?:?]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.thenCompose(SafeFuture.java:364) [teku-infrastructure-async-0.12.4-SNAPSHOT.jar:0.12.4-dev-c6548285]
	at tech.pegasys.teku.networking.eth2.gossip.topics.Eth2TopicHandler.handleMessage(Eth2TopicHandler.java:37) [teku-networking-eth2-0.12.4-SNAPSHOT.jar:0.12.4-dev-c6548285]
	at tech.pegasys.teku.networking.p2p.libp2p.gossip.GossipHandler.apply(GossipHandler.java:77) [teku-networking-p2p-0.12.4-SNAPSHOT.jar:0.12.4-dev-c6548285]
	at tech.pegasys.teku.networking.p2p.libp2p.gossip.GossipHandler.apply(GossipHandler.java:34) [teku-networking-p2p-0.12.4-SNAPSHOT.jar:0.12.4-dev-c6548285]
	at io.libp2p.pubsub.PubsubApiImpl.onNewMessage(PubsubApiImpl.kt:79) [jvm-libp2p-minimal-0.5.5-RELEASE.jar:?]
	at io.libp2p.pubsub.PubsubApiImpl.access$onNewMessage(PubsubApiImpl.kt:22) [jvm-libp2p-minimal-0.5.5-RELEASE.jar:?]
	at io.libp2p.pubsub.PubsubApiImpl$1.invoke(PubsubApiImpl.kt:63) [jvm-libp2p-minimal-0.5.5-RELEASE.jar:?]
	at io.libp2p.pubsub.PubsubApiImpl$1.invoke(PubsubApiImpl.kt:22) [jvm-libp2p-minimal-0.5.5-RELEASE.jar:?]
	at io.libp2p.pubsub.AbstractRouter.onInbound(AbstractRouter.kt:212) [jvm-libp2p-minimal-0.5.5-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService.streamInbound(P2PService.kt:171) [jvm-libp2p-minimal-0.5.5-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$StreamHandler$channelRead$1.invoke(P2PService.kt:51) [jvm-libp2p-minimal-0.5.5-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$StreamHandler$channelRead$1.invoke(P2PService.kt:36) [jvm-libp2p-minimal-0.5.5-RELEASE.jar:?]
	at io.libp2p.etc.util.P2PService$runOnEventThread$1.run(P2PService.kt:231) [jvm-libp2p-minimal-0.5.5-RELEASE.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalArgumentException: Committee information must be derived from a state no older than the previous epoch. State at slot 60925 is older than cutoff slot 60960
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:441) ~[guava-29.0-jre.jar:?]
	at tech.pegasys.teku.datastructures.util.CommitteeUtil.validateStateForCommitteeQuery(CommitteeUtil.java:252) ~[teku-ethereum-datastructures-0.12.4-SNAPSHOT.jar:0.12.4-dev-c6548285]
	at tech.pegasys.teku.datastructures.util.CommitteeUtil.get_beacon_committee(CommitteeUtil.java:229) ~[teku-ethereum-datastructures-0.12.4-SNAPSHOT.jar:0.12.4-dev-c6548285]
	at tech.pegasys.teku.networking.eth2.gossip.topics.validation.AttestationValidator.lambda$singleOrAggregateAttestationChecks$1(AttestationValidator.java:142) ~[teku-networking-eth2-0.12.4-SNAPSHOT.jar:0.12.4-dev-c6548285]
	at java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680) ~[?:?]
	... 29 more
```

**Comment by ajsutton** [comment]
This was fixed with https://github.com/PegaSysEng/teku/pull/2575
