### ISSUE TITLE
UnsatisfiedLinkError on fresh install/build

### ISSUE THREAD

**Issue by jnew00** [Consensys-Incorporated/teku#2640]
Getting this error when trying to run teku for the first time 

```
Teku failed to start.
java.util.concurrent.CompletionException: java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni8697586722914603821.so: /tmp/librocksdbjni8697586722914603821.so: failed to map segment from shared object
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1099)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
        at tech.pegasys.teku.infrastructure.async.SafeFuture.thenCompose(SafeFuture.java:373)
        at tech.pegasys.teku.services.ServiceController.doStart(ServiceController.java:54)
        at tech.pegasys.teku.service.serviceutils.Service.start(Service.java:33)
        at tech.pegasys.teku.BeaconNode.start(BeaconNode.java:98)
        at tech.pegasys.teku.Teku.start(Teku.java:39)
        at tech.pegasys.teku.cli.BeaconNodeCommand.call(BeaconNodeCommand.java:261)
        at tech.pegasys.teku.cli.BeaconNodeCommand.call(BeaconNodeCommand.java:65)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1100(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at tech.pegasys.teku.cli.BeaconNodeCommand.parse(BeaconNodeCommand.java:210)
        at tech.pegasys.teku.Teku.main(Teku.java:31)
Caused by: java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni8697586722914603821.so: /tmp/librocksdbjni8697586722914603821.so: failed to map segment from shared object
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
        at java.base/java.lang.Runtime.load0(Runtime.java:768)
        at java.base/java.lang.System.load(System.java:1837)
        at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:79)
        at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:57)
        at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:67)
        at org.rocksdb.RocksDB.<clinit>(RocksDB.java:38)
        at tech.pegasys.teku.storage.server.rocksdb.core.RocksDbUtil.loadNativeLibrary(RocksDbUtil.java:27)
        at tech.pegasys.teku.storage.server.rocksdb.core.RocksDbInstanceFactory.<clinit>(RocksDbInstanceFactory.java:44)
        at tech.pegasys.teku.storage.server.rocksdb.RocksDbDatabase.createV4(RocksDbDatabase.java:96)
        at tech.pegasys.teku.storage.server.VersionedDatabaseFactory.createV5Database(VersionedDatabaseFactory.java:170)
        at tech.pegasys.teku.storage.server.VersionedDatabaseFactory.createDatabase(VersionedDatabaseFactory.java:119)
        at tech.pegasys.teku.services.chainstorage.StorageService.lambda$doStart$0(StorageService.java:54)
        at tech.pegasys.teku.infrastructure.async.SafeFuture.fromRunnable(SafeFuture.java:138)
        at tech.pegasys.teku.services.chainstorage.StorageService.doStart(StorageService.java:44)
        at tech.pegasys.teku.service.serviceutils.Service.start(Service.java:33)
        at tech.pegasys.teku.services.ServiceController.doStart(ServiceController.java:51)
        ... 14 more
Teku failed to start
```

### Versions (Add all that apply)
* Software version: [`teku/v0.12.4-dev-1dc98016/linux-x86_64/-ubuntu-openjdk64bitservervm-java-11`]
* Java version: 
[`openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)`]

* OS Name & Version: [`Ubuntu 20.04.1 LTS`]
* Kernel Version:  [`Linux earth 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`]

**Comment by rolfyone** [comment]
It looks like rocksdb is using the temp dir to extract a shared object, and the /tmp is marked as noexec...

There's a couple of options:

 - could remove noexec on the /tmp mount so things are executable
   - can be done permanently in the fstab, or temporarily as `sudo mount /tmp -o remount,exec`
 
- could change tmpdir so that executables can be run from the tmpdir for the application...

```
mkdir tmp
export TMPDIR=`pwd`/tmp
```
in the shell before executing teku would create a new temp folder under the current working folder, then set that as the tempdir to use for the applications within that shell...

**Comment by jnew00** [comment]
This worked. Thank you.

**Comment by benjaminion** [comment]
TODO: Check if we can write to /tmp, if not check if we can write instead to $HOME or the data directory.

**Comment by ajsutton** [comment]
I haven't had another report of this since 2020 and we managed to solve the immediate issue so going to close this one.
