### ISSUE TITLE
SlashableConditionException

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#2669]
### Description
Since updating validators to 0.12.4, have been periodically seeing slashing protection kick in:

```
tech.pegasys.teku.core.signatures.SlashableConditionException: Refusing to sign attestation at slot 162110 with source epoch 5064 and target epoch 5065 because it may violate a slashing condition
	at tech.pegasys.teku.core.signatures.SlashingProtectedSigner.lambda$verifySigningAllowed$4(SlashingProtectedSigner.java:93)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
	at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2172)
```
In normal operation of the beacon node, the validator should never attempt to sign anything that would be slashable - the slashing protection should just be a fallback. These errors indicate something unusual is happening with either the beacon chain or the validator client.

**Comment by ajsutton** [comment]
Haven't seen an instance of this since updating to 0.12.5. Will monitor for another day or two and close if no further instances occur.

**Comment by ajsutton** [comment]
When a reorg event occurs the scheduled duties map was cleared, however the duties objects weren't cancelled. So any events that were already pending but waiting for the duties scheduling to load would still be processed once the request for duties came back. This potentially creates a slashable offence as the recalculated duties would also be scheduled.

#2682 will fix it.

**Comment by ajsutton** [comment]
#2682 has been merged which fixes this.
