### ISSUE TITLE
ERROR - Unexpected error in Noise channel

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#2784]
Just seen this the one time. Seems harmless, but noisy (heh).

```
10:39:40.813 ERROR - Unexpected error in Noise channel
io.netty.handler.codec.DecoderException: javax.crypto.AEADBadTagException
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:425) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: javax.crypto.AEADBadTagException
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:166) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:404) ~[?:?]
        at java.lang.Class.newInstance(Class.java:591) ~[?:?]
        at com.southernstorm.noise.protocol.Noise.throwBadTagException(Noise.java:229) ~[jvm-libp2p-minimal-0.5.6-RELEASE.jar:?]
        at com.southernstorm.noise.protocol.ChaChaPolyCipherState.decryptWithAd(ChaChaPolyCipherState.java:273) ~[jvm-libp2p-minimal-0.5.6-RELEASE.jar:?]
        at io.libp2p.security.noise.NoiseXXCodec.decode(NoiseXXCodec.kt:28) ~[jvm-libp2p-minimal-0.5.6-RELEASE.jar:?]
        at io.libp2p.security.noise.NoiseXXCodec.decode(NoiseXXCodec.kt:16) ~[jvm-libp2p-minimal-0.5.6-RELEASE.jar:?]
        at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[netty-all-4.1.51.Final.jar:4.1.51.Final]
        ... 26 more
```

Version: `teku/v0.12.6-dev-616f13a3/linux-x86_64/-privatebuild-openjdk64bitservervm-java-13`

**Comment by stefa2k** [comment]
Got this too, unfortunately the docker container didn't restart, here's the log:
```
ESC[36mteku_node_1        |ESC[0m 14:03:45.096 ERROR - Unexpected error in Noise channel
ESC[36mteku_node_1        |ESC[0m io.netty.handler.codec.DecoderException: javax.crypto.AEADBadTagException
ESC[36mteku_node_1        |ESC[0m       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[netty-all-4.1.51.Final.jar:4.1.51.Final]
ESC[36mteku_node_1        |ESC[0m       at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[netty-all-4.1.51.Final.jar:4.1.51.Final]
ESC[36mteku_node_1        |ESC[0m       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.51.Final.jar:4.1.51.Final]
ESC[36mteku_node_1        |ESC[0m       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.51.Final.jar:4.1.51.Final]
ESC[36mteku_node_1        |ESC[0m       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.51.Final.jar:4.1.51.Final]
ESC[36mteku_node_1        |ESC[0m       at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [netty-all-4.1.51.Final.jar:4.1.51.Final]
ESC[36mteku_node_1        |ESC[0m       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.51.Final.jar:4.1.51.Final]
ESC[36mteku_node_1        |ESC[0m       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) [netty-all-4.1.51.Final.jar:4.1.51.Final]
ESC[36mteku_node_1        |ESC[0m       at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:425) [netty-all-4.1.51.Final.jar:4.1.51.Final]
ESC[36mteku_node_1        |ESC[0m       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-all-4.1.51.Final.jar:4.1.51.Final]
ESC[36mteku_node_1        |ESC[0m       at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [netty-all-4.1.51.Final.jar:4.1.51.Final]
ESC[36mteku_node_1        |ESC[0m       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.51.Final.jar:4.1.51.Final]
ESC[36mteku_node_1        |ESC[0m       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.51.Final.jar:4.1.51.Final]
ESC[36mteku_node_1        |ESC[0m       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.51.Final.jar:4.1.51.Final]
ESC[36mteku_node_1        |ESC[0m       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.51.Final.jar:4.1.51.Final]
ESC[36mteku_node_1        |ESC[0m       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.51.Final.jar:4.1.51.Final]
ESC[36mteku_node_1        |ESC[0m       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.51.Final.jar:4.1.51.Final]
ESC[36mteku_node_1        |ESC[0m       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.51.Final.jar:4.1.51.Final]
ESC[36mteku_node_1        |ESC[0m       at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-all-4.1.51.Final.jar:4.1.51.Final]
ESC[36mteku_node_1        |ESC[0m       at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-all-4.1.51.Final.jar:4.1.51.Final]
ESC[36mteku_node_1        |ESC[0m       at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-all-4.1.51.Final.jar:4.1.51.Final]
ESC[36mteku_node_1        |ESC[0m       at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-all-4.1.51.Final.jar:4.1.51.Final]
ESC[36mteku_node_1        |ESC[0m       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-all-4.1.51.Final.jar:4.1.51.Final]
ESC[36mteku_node_1        |ESC[0m       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-all-4.1.51.Final.jar:4.1.51.Final]
ESC[36mteku_node_1        |ESC[0m       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.51.Final.jar:4.1.51.Final]
ESC[36mteku_node_1        |ESC[0m       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.51.Final.jar:4.1.51.Final]
ESC[36mteku_node_1        |ESC[0m       at java.lang.Thread.run(Thread.java:832) [?:?]
ESC[36mteku_node_1        |ESC[0m Caused by: javax.crypto.AEADBadTagException
ESC[36mteku_node_1        |ESC[0m       at jdk.internal.reflect.GeneratedConstructorAccessor151.newInstance(Unknown Source) ~[?:?]
ESC[36mteku_node_1        |ESC[0m       at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
ESC[36mteku_node_1        |ESC[0m       at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
ESC[36mteku_node_1        |ESC[0m       at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:124) ~[?:?]
ESC[36mteku_node_1        |ESC[0m       at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:346) ~[?:?]
ESC[36mteku_node_1        |ESC[0m       at java.lang.Class.newInstance(Class.java:604) ~[?:?]
ESC[36mteku_node_1        |ESC[0m       at com.southernstorm.noise.protocol.Noise.throwBadTagException(Noise.java:229) ~[jvm-libp2p-minimal-0.5.7-RELEASE.jar:?]
ESC[36mteku_node_1        |ESC[0m       at com.southernstorm.noise.protocol.ChaChaPolyCipherState.decryptWithAd(ChaChaPolyCipherState.java:273) ~[jvm-libp2p-minimal-0.5.7-RELEASE.jar:?]
ESC[36mteku_node_1        |ESC[0m       at io.libp2p.security.noise.NoiseXXCodec.decode(NoiseXXCodec.kt:28) ~[jvm-libp2p-minimal-0.5.7-RELEASE.jar:?]
ESC[36mteku_node_1        |ESC[0m       at io.libp2p.security.noise.NoiseXXCodec.decode(NoiseXXCodec.kt:16) ~[jvm-libp2p-minimal-0.5.7-RELEASE.jar:?]
ESC[36mteku_node_1        |ESC[0m       at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[netty-all-4.1.51.Final.jar:4.1.51.Final]
ESC[36mteku_node_1        |ESC[0m       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[netty-all-4.1.51.Final.jar:4.1.51.Final]
ESC[36mteku_node_1        |ESC[0m       ... 26 more
ESC[36mteku_node_1        |ESC[0m 14:06:16.812 ERROR - Unhandled exception:
ESC[36mteku_node_1        |ESC[0m java.lang.OutOfMemoryError: Java heap space
ESC[36mteku_node_1        |ESC[0m Deserialization error with class: BeaconStateImpl
ESC[36mteku_node_1        |ESC[0m  Error: java.lang.reflect.InvocationTargetException
ESC[36mteku_node_1        |ESC[0m Deserialization error with class: BeaconStateImpl
ESC[36mteku_node_1        |ESC[0m  Error: java.lang.reflect.InvocationTargetException
ESC[36mteku_node_1        |ESC[0m 14:09:26.906 WARN  - Unexpected exception
ESC[36mteku_node_1        |ESC[0m java.lang.OutOfMemoryError: Java heap space
```

Running with `JAVA_OPTS=-Xmx2g` and docker tag `0.12.9`

**Comment by Nashatyrev** [comment]
Relates to #3031
