### ISSUE TITLE
ERROR - Failed to process gossiped attestation (DatabaseStorageException: Failed to commit transaction)

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#2830]
Version: `teku/v0.12.6-dev-616f13a3/linux-x86_64/-privatebuild-openjdk64bitservervm-java-13`

Teku had been up and running for ~14 days without trouble. The following error occurred 12 hours ago, after which Teku made no further progress. Peer counts remained high, but blocks were not longer processed and the chain head did not advance. CPU use was high. This error gets repeated hundreds of times (~900 in 12 hours).

There's plenty of room available on the database drive, so it's not running out of space.
```
ben@metalalbert:/data$ df .
Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/nvme0n1p1 983455132 36673272 896755364   4% /data
```

After an update to the latest version and a restart, Teku happily synced up the last 12 hours everything seems to be back on track.

```
21:22:13.521 ERROR - Failed to process gossiped attestation.
java.util.concurrent.CompletionException: tech.pegasys.teku.storage.server.DatabaseStorageException: Failed to commit transaction
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:704) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2159) ~[?:?]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$2(SafeFuture.java:129) ~[teku-infrastructure-async-0.12.6-SNAPSHOT.jar:0.12.6-dev-616f13a3]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2159) ~[?:?]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateToAsync$11(SafeFuture.java:222) ~[teku-infrastructure-async-0.12.6-SNAPSHOT.jar:0.12.6-dev-616f13a3]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:76) ~[teku-infrastructure-async-0.12.6-SNAPSHOT.jar:0.12.6-dev-616f13a3]
        at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$1(AsyncRunner.java:35) ~[teku-infrastructure-async-0.12.6-SNAPSHOT.jar:0.12.6-dev-616f13a3]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.ofComposed(SafeFuture.java:85) ~[teku-infrastructure-async-0.12.6-SNAPSHOT.jar:0.12.6-dev-616f13a3]
        at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:119) ~[teku-infrastructure-async>
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: tech.pegasys.teku.storage.server.DatabaseStorageException: Failed to commit transaction
        at tech.pegasys.teku.storage.server.rocksdb.core.RocksDbInstance$Transaction.lambda$commit$4(RocksDbInstance.java:264) ~[teku-storage-0.12.6-SNAPSHOT.jar:0.12.6-dev-616f1>
        at tech.pegasys.teku.storage.server.rocksdb.core.RocksDbInstance$Transaction.applyUpdate(RocksDbInstance.java:289) ~[teku-storage-0.12.6-SNAPSHOT.jar:0.12.6-dev-616f13a3]
        at tech.pegasys.teku.storage.server.rocksdb.core.RocksDbInstance$Transaction.commit(RocksDbInstance.java:259) ~[teku-storage-0.12.6-SNAPSHOT.jar:0.12.6-dev-616f13a3]
        at tech.pegasys.teku.storage.server.rocksdb.dataaccess.V4HotRocksDbDao$V4HotUpdater.commit(V4HotRocksDbDao.java:246) ~[teku-storage-0.12.6-SNAPSHOT.jar:0.12.6-dev-616f13a>
        at tech.pegasys.teku.storage.server.rocksdb.RocksDbDatabase.doUpdate(RocksDbDatabase.java:399) ~[teku-storage-0.12.6-SNAPSHOT.jar:0.12.6-dev-616f13a3]
        at tech.pegasys.teku.storage.server.rocksdb.RocksDbDatabase.update(RocksDbDatabase.java:173) ~[teku-storage-0.12.6-SNAPSHOT.jar:0.12.6-dev-616f13a3]
        at tech.pegasys.teku.storage.server.ChainStorage.lambda$onStorageUpdate$0(ChainStorage.java:93) ~[teku-storage-0.12.6-SNAPSHOT.jar:0.12.6-dev-616f13a3]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.fromRunnable(SafeFuture.java:138) ~[teku-infrastructure-async-0.12.6-SNAPSHOT.jar:0.12.6-dev-616f13a3]
        at tech.pegasys.teku.storage.server.ChainStorage.onStorageUpdate(ChainStorage.java:91) ~[teku-storage-0.12.6-SNAPSHOT.jar:0.12.6-dev-616f13a3]
        at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:74) ~[teku-infrastructure-events-0.12.6-SNAPSHOT.jar:0.12.6-dev-61>
        at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.deliverToWithResponse(DirectEventDeliverer.java:67) ~[teku-infrastructure-events-0.12.6-SNAPSHOT.jar:0.12.>
        at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer.lambda$deliverToWithResponse$1(AsyncEventDeliverer.java:75) ~[teku-infrastructure-events-0.12.6-SNAPSHOT.ja>
        at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:117) ~[teku-infrastructure-events-0.12.6-SNAPSHOT.jar>
        at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:109) ~[teku-infrastructure-events-0.12.6-SNAPSHOT.jar:0.12.6-dev-6>
        ... 3 more
Caused by: org.rocksdb.RocksDBException: block checksum mismatch: expected 1283599863, got 3619522171  in /data/teku_medalla/data/db/046983.sst offset 1804870 size 4070
        at org.rocksdb.Transaction.commit(Native Method) ~[rocksdbjni-6.11.4.jar:?]
        at org.rocksdb.Transaction.commit(Transaction.java:206) ~[rocksdbjni-6.11.4.jar:?]
        at tech.pegasys.teku.storage.server.rocksdb.core.RocksDbInstance$Transaction.lambda$commit$4(RocksDbInstance.java:262) ~[teku-storage-0.12.6-SNAPSHOT.jar:0.12.6-dev-616f1>
        at tech.pegasys.teku.storage.server.rocksdb.core.RocksDbInstance$Transaction.applyUpdate(RocksDbInstance.java:289) ~[teku-storage-0.12.6-SNAPSHOT.jar:0.12.6-dev-616f13a3]
        at tech.pegasys.teku.storage.server.rocksdb.core.RocksDbInstance$Transaction.commit(RocksDbInstance.java:259) ~[teku-storage-0.12.6-SNAPSHOT.jar:0.12.6-dev-616f13a3]
        at tech.pegasys.teku.storage.server.rocksdb.dataaccess.V4HotRocksDbDao$V4HotUpdater.commit(V4HotRocksDbDao.java:246) ~[teku-storage-0.12.6-SNAPSHOT.jar:0.12.6-dev-616f13a>
        at tech.pegasys.teku.storage.server.rocksdb.RocksDbDatabase.doUpdate(RocksDbDatabase.java:399) ~[teku-storage-0.12.6-SNAPSHOT.jar:0.12.6-dev-616f13a3]
        at tech.pegasys.teku.storage.server.rocksdb.RocksDbDatabase.update(RocksDbDatabase.java:173) ~[teku-storage-0.12.6-SNAPSHOT.jar:0.12.6-dev-616f13a3]
        at tech.pegasys.teku.storage.server.ChainStorage.lambda$onStorageUpdate$0(ChainStorage.java:93) ~[teku-storage-0.12.6-SNAPSHOT.jar:0.12.6-dev-616f13a3]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.fromRunnable(SafeFuture.java:138) ~[teku-infrastructure-async-0.12.6-SNAPSHOT.jar:0.12.6-dev-616f13a3]
        at tech.pegasys.teku.storage.server.ChainStorage.onStorageUpdate(ChainStorage.java:91) ~[teku-storage-0.12.6-SNAPSHOT.jar:0.12.6-dev-616f13a3]
        at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source) ~[?:?]
        at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:74) ~[teku-infrastructure-events-0.12.6-SNAPSHOT.jar:0.12.6-dev-61>
        at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.deliverToWithResponse(DirectEventDeliverer.java:67) ~[teku-infrastructure-events-0.12.6-SNAPSHOT.jar:0.12.>
        at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer.lambda$deliverToWithResponse$1(AsyncEventDeliverer.java:75) ~[teku-infrastructure-events-0.12.6-SNAPSHOT.ja>
        at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:117) ~[teku-infrastructure-events-0.12.6-SNAPSHOT.jar>
        at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:109) ~[teku-infrastructure-events-0.12.6-SNAPSHOT.jar:0.12.6-dev-6>
        ... 3 more
21:22:13.535 ERROR - Failed to process gossiped attestation.
java.util.concurrent.CompletionException: tech.pegasys.teku.storage.server.DatabaseStorageException: Failed to commit transaction

<repeated many times>
```

The following error that appears to be related also started being reported shortly afterwards:

```
21:22:24.738 ERROR - PLEASE FIX OR REPORT | Unexpected exception thrown for event 'interface tech.pegasys.teku.util.time.channels.TimeTickChannel.onTick' in handler 'tech.pegasys.teku.serv>
java.util.concurrent.CompletionException: tech.pegasys.teku.storage.server.DatabaseStorageException: Failed to commit transaction
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]

<remainder is the same as above>
```

**Comment by rolfyone** [comment]
closed during planning - hasn't been seen again.
