### ISSUE TITLE
Teku does not catch up to head again

### ISSUE THREAD

**Issue by dankrad** [Consensys-Incorporated/teku#2861]
Woke up today to see that teku has stopped signing attestations. At some point it seems to have failed syncing to the chain, reason is unknown (network seems to be good, nothing in the logs). After that, it simply was stuck there and never caught up to the head again, until the client was restarted. Peer count was constantly >70.

### Description
Whatever the root cause of falling behind was (it may be a short network outage of some minutes, happens quite regularly here), I would expect that the client manages to detect this condition and catch up again.

### Steps to Reproduce (Bug)
Unfortunately I do not know what caused it in the first place, there is nothing in the logs about the trigger.

### Versions (Add all that apply)
* Software version: teku/v0.12.4-dev-93d6ef0a/linux-x86_64/-ubuntu-openjdk64bitservervm-java-11
* Java version: openjdk version "11.0.8" 2020-07-14
* OS Name & Version: Ubuntu 20.04.1 LTS
* Kernel Version: Linux pascal 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Virtual Machine software & version: -
* Docker Version: -
* Cloud VM, type, size: -
[teku.log.zip](https://github.com/PegaSysEng/teku/files/5291479/teku.log.zip)

**Comment by dankrad** [comment]
Oh it appears that the exception is in the detailed logs:

```
[tekulog2.zip](https://github.com/PegaSysEng/teku/files/5291500/tekulog2.zip)

2020-09-28 07:20:58.443+01:00 | forkchoice-0 | WARN  | BlockProcessorUtil | process_block_header: Verify that proposer index is the correct index
2020-09-28 07:20:58.443+01:00 | forkchoice-0 | WARN  | StateTransition | State Transition error
tech.pegasys.teku.core.exceptions.BlockProcessingException: java.lang.IllegalArgumentException: process_block_header: Verify that proposer index is the correct index
	at tech.pegasys.teku.core.BlockProcessorUtil.process_block_header(BlockProcessorUtil.java:117) ~[teku-ethereum-core-0.12.4-SNAPSHOT.jar:0.12.4-dev-93d6ef0a]
	at tech.pegasys.teku.core.StateTransition.lambda$process_block$2(StateTransition.java:142) ~[teku-ethereum-core-0.12.4-SNAPSHOT.jar:0.12.4-dev-93d6ef0a]
	at tech.pegasys.teku.datastructures.state.BeaconStateImpl.updated(BeaconStateImpl.java:247) ~[teku-ethereum-datastructures-0.12.4-SNAPSHOT.jar:0.12.4-dev-93d6ef0a]
	at tech.pegasys.teku.core.StateTransition.process_block(StateTransition.java:140) ~[teku-ethereum-core-0.12.4-SNAPSHOT.jar:0.12.4-dev-93d6ef0a]
	at tech.pegasys.teku.core.StateTransition.initiate(StateTransition.java:110) ~[teku-ethereum-core-0.12.4-SNAPSHOT.jar:0.12.4-dev-93d6ef0a]
	at tech.pegasys.teku.core.ForkChoiceUtil.on_block(ForkChoiceUtil.java:234) ~[teku-ethereum-core-0.12.4-SNAPSHOT.jar:0.12.4-dev-93d6ef0a]
	at tech.pegasys.teku.statetransition.forkchoice.ForkChoice.lambda$onBlock$7(ForkChoice.java:122) ~[teku-ethereum-statetransition-0.12.4-SNAPSHOT.jar:0.12.4-dev-93d6ef0a]
	at tech.pegasys.teku.statetransition.forkchoice.SingleThreadedForkChoiceExecutor.lambda$syncPerformTask$1(SingleThreadedForkChoiceExecutor.java:77) ~[teku-ethereum-statetransition-0.12.4-SNAPSHOT.jar:0.12.4-dev-93d6ef0a]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:76) ~[teku-infrastructure-async-0.12.4-SNAPSHOT.jar:0.12.4-dev-93d6ef0a]
	at tech.pegasys.teku.statetransition.forkchoice.SingleThreadedForkChoiceExecutor.syncPerformTask(SingleThreadedForkChoiceExecutor.java:77) ~[teku-ethereum-statetransition-0.12.4-SNAPSHOT.jar:0.12.4-dev-93d6ef0a]
	at tech.pegasys.teku.statetransition.forkchoice.SingleThreadedForkChoiceExecutor.lambda$performTask$0(SingleThreadedForkChoiceExecutor.java:58) ~[teku-ethereum-statetransition-0.12.4-SNAPSHOT.jar:0.12.4-dev-93d6ef0a]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalArgumentException: process_block_header: Verify that proposer index is the correct index
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142) ~[guava-29.0-jre.jar:?]
	at tech.pegasys.teku.core.BlockProcessorUtil.process_block_header(BlockProcessorUtil.java:91) ~[teku-ethereum-core-0.12.4-SNAPSHOT.jar:0.12.4-dev-93d6ef0a]
	... 13 more
```

**Comment by benjaminion** [comment]
> Software version: teku/v0.12.4-dev-93d6ef0a/linux-x86_64/-ubuntu-openjdk64bitservervm-java-11

This version is over a month old and it is likely that this issue has been addressed in the meanwhile. Could you please try updating to the latest and seeing how it goes?

**Comment by ajsutton** [comment]
Thanks for reporting. I'm going to close this as it was with a very old version.  Please do reopen if you the issue reoccurs on a more recent version.
