### ISSUE TITLE
Teku fails to start: IllegalArgumentException: State must belong to the given block

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#2862]
I am currently unable to start Teku. Medalla network/64 validators.

Version: `teku/v0.12.7-dev-10c2471c/linux-x86_64/-privatebuild-openjdk64bitservervm-java-13` (this is almost up to date, but also running the validator performance patch from Cem. The restart issue also occurs with the latest master, `teku/v0.12.9-dev-e2fa70d3/linux-x86_64/-privatebuild-openjdk64bitservervm-java-13`).

```
11:22:40.216 INFO  - Initializing storage
11:22:43.646 FATAL - Failed to initialize storage. Check the existing database matches the current network configuration. Set log level to debug for more information.
Teku failed to start.
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Latest finalized state does not match latest finalized block
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1137)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2159)
        at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$2(SafeFuture.java:130)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
        at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2322)
        at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:466)
        at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:28)
        at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:127)
        at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$exceptionallyCompose$23(SafeFuture.java:319)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2159)
        at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$2(SafeFuture.java:130)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2159)
        at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateToAsync$11(SafeFuture.java:223)
        at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:77)
        at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$1(AsyncRunner.java:35)
        at tech.pegasys.teku.infrastructure.async.SafeFuture.ofComposed(SafeFuture.java:86)
        at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:119)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.IllegalStateException: Latest finalized state does not match latest finalized block
        at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
        at tech.pegasys.teku.storage.server.rocksdb.RocksDbDatabase.createMemoryStore(RocksDbDatabase.java:217)
        at tech.pegasys.teku.storage.server.ChainStorage.getStore(ChainStorage.java:70)
        at tech.pegasys.teku.storage.server.ChainStorage.onStoreRequest(ChainStorage.java:86)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:74)
        at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.deliverToWithResponse(DirectEventDeliverer.java:67)
        at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer.lambda$deliverToWithResponse$1(AsyncEventDeliverer.java:75)
        at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:117)
        at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:109)
        ... 3 more
Teku failed to start
```

This is after a simple stop and restart of Teku; there was no config change.

I tried to restart Teku because it had stopped making progress. The following error had occurred multiple times:

```
11:04:49.066 INFO  - Slot Event  *** Slot: 395423, Block: 233fa1..3d45, Epoch: 12356, Finalized checkpoint: 12354, Finalized root: 8887bf..f6de, Peers: 80
11:04:56.407 INFO  - Epoch Event *** Epoch: 12357, Justified checkpoint: 12355, Finalized checkpoint: 12354, Finalized root: 8887bf..f6de
11:04:56.485 INFO  - Attestation performance: produced 64, included 49 (77%), distance 1 / 2.53 / 31, correct target 56 (88%), correct head 55 (86%)
11:05:01.123 INFO  - Slot Event  *** Slot: 395424, Block:    ... empty, Epoch: 12357, Finalized checkpoint: 12354, Finalized root: 8887bf..f6de, Peers: 80
11:05:07.225 ERROR - Internal error while importing block: b58e92..63f2 (395424)
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: State must belong to the given block
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:704) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2159) ~[?:?]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$2(SafeFuture.java:130) ~[teku-infrastructure-async-0.12.7-SNAPSHOT.jar:0.12.7-dev-10c2471c]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2159) ~[?:?]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateToAsync$11(SafeFuture.java:223) ~[teku-infrastructure-async-0.12.7-SNAPSHOT.jar:0.12.7-dev-10c2471c]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:77) ~[teku-infrastructure-async-0.12.7-SNAPSHOT.jar:0.12.7-dev-10c2471c]
        at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$1(AsyncRunner.java:35) ~[teku-infrastructure-async-0.12.7-SNAPSHOT.jar:0.12.7-dev-10c2471c]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.ofComposed(SafeFuture.java:86) ~[teku-infrastructure-async-0.12.7-SNAPSHOT.jar:0.12.7-dev-10c2471c]
        at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:119) ~[teku-infrastructure-async-0.12.7-SNAPSHOT.jar:0.12.7-dev-10c2471c]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: java.lang.IllegalArgumentException: State must belong to the given block
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142) ~[guava-29.0-jre.jar:?]
        at tech.pegasys.teku.datastructures.blocks.SignedBlockAndState.<init>(SignedBlockAndState.java:32) ~[teku-ethereum-datastructures-0.12.7-SNAPSHOT.jar:0.12.7-dev-10c2471c]
        at tech.pegasys.teku.storage.server.rocksdb.RocksDbDatabase.getFinalizedBlockAndState(RocksDbDatabase.java:480) ~[teku-storage-0.12.7-SNAPSHOT.jar:0.12.7-dev-10c2471c]
        at tech.pegasys.teku.storage.server.rocksdb.RocksDbDatabase.updateFinalizedData(RocksDbDatabase.java:436) ~[teku-storage-0.12.7-SNAPSHOT.jar:0.12.7-dev-10c2471c]
        at tech.pegasys.teku.storage.server.rocksdb.RocksDbDatabase.doUpdate(RocksDbDatabase.java:382) ~[teku-storage-0.12.7-SNAPSHOT.jar:0.12.7-dev-10c2471c]
        at tech.pegasys.teku.storage.server.rocksdb.RocksDbDatabase.update(RocksDbDatabase.java:174) ~[teku-storage-0.12.7-SNAPSHOT.jar:0.12.7-dev-10c2471c]
        at tech.pegasys.teku.storage.server.ChainStorage.lambda$onStorageUpdate$0(ChainStorage.java:93) ~[teku-storage-0.12.7-SNAPSHOT.jar:0.12.7-dev-10c2471c]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.fromRunnable(SafeFuture.java:139) ~[teku-infrastructure-async-0.12.7-SNAPSHOT.jar:0.12.7-dev-10c2471c]
        at tech.pegasys.teku.storage.server.ChainStorage.onStorageUpdate(ChainStorage.java:91) ~[teku-storage-0.12.7-SNAPSHOT.jar:0.12.7-dev-10c2471c]
        at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:74) ~[teku-infrastructure-events-0.12.7-SNAPSHOT.jar:0.12.7-dev-10c2471c]
        at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.deliverToWithResponse(DirectEventDeliverer.java:67) ~[teku-infrastructure-events-0.12.7-SNAPSHOT.jar:0.12.7-dev-10c2471c]
        at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer.lambda$deliverToWithResponse$1(AsyncEventDeliverer.java:75) ~[teku-infrastructure-events-0.12.7-SNAPSHOT.jar:0.12.7-dev-10c2471c]
        at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:117) ~[teku-infrastructure-events-0.12.7-SNAPSHOT.jar:0.12.7-dev-10c2471c]
        at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:109) ~[teku-infrastructure-events-0.12.7-SNAPSHOT.jar:0.12.7-dev-10c2471c]
        ... 3 more
```

After an epoch of seeing only empty slots, Teku went into sync mode after this, but remained stuck at slot 395423, and frequently producing the above error, always for block 395424. Now I am unable to restart.

**Comment by mbaxter** [comment]
Link to [RocksDbDatabase.java:436](https://github.com/PegaSysEng/teku/blob/10c2471cf03bc5cd0937086fb6ce6b7d3e1f1bc7/storage/src/main/java/tech/pegasys/teku/storage/server/rocksdb/RocksDbDatabase.java#L436)

**Comment by benjaminion** [comment]
Closing for now as likely due to a hardware fault (memory errors) and not a bug in Teku.
