### ISSUE TITLE
Failed to load validator indexes

### ISSUE THREAD

**Issue by tzapu** [Consensys-Incorporated/teku#3014]
### Description
I am getting errors like these:
```
:15:32.357 INFO  - Completed regeneration of block 0x569e64641a87ae18d69b1f2dafb5fa2d586abf82447f0f31a1f7e59035534f7d at slot 547233 by replaying 1 blocks. Took 197ms
13:15:32.523 INFO  - Chain reorg from 2a22fb..8d03 (547275) to bbacf2..4255 (547275). Common ancestor at slot 547244
13:15:32.529 WARN  - The latest finalized checkpoint at epoch 15614 (74606 active validators) fell outside of the weak subjectivity period after epoch 16802, which is prior to the current epoch 17102.
13:15:32.529 WARN  - The latest finalized checkpoint at epoch 15614 is outside of the weak subjectivity period.  Please supply a recent weak subjectivity checkpoint using --ws-checkpoint=<BLOCK_ROOT>:<EPOCH>.
13:15:37.990 INFO  - Slot Event  *** Slot: 547276, Block:    ... empty, Epoch: 17102, Finalized checkpoint: 15614, Finalized root: b38064..b440, Peers: 36
13:15:40.761 INFO  - Chain reorg from bbacf2..4255 (547276) to ef4cc4..4b23 (547276). Common ancestor at slot 547249
13:15:49.705 INFO  - Regenerate state for block 0x7047760bbb1b8d38d0990ef8afec1c47dde4d193cb003e923ce8942a29260b38 by replaying 4 blocks
13:15:50.001 ERROR - Failed to load validator indexes.
java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:870) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) [?:?]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2152) [?:?]
        at java.util.concurrent.CompletableFuture$Timeout.run(CompletableFuture.java:2864) [?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.util.concurrent.TimeoutException
        ... 7 more
```

**Frequency:** [What percentage of the time does it occur?]
medium

### Versions (Add all that apply)
Teku version: teku/v0.12.11-dev-35d5b8a4/linux-x86_64/oracle_openjdk-java-14 in Docker

**Comment by mbaxter** [comment]
@tzapu - thanks for reporting.  Can you attach the full log file related to these errors?

**Comment by tzapu** [comment]
[logs.txt](https://github.com/PegaSysEng/teku/files/5404229/logs.txt)
hi, here are the full logs, they should apply to https://github.com/PegaSysEng/teku/issues/3013#issuecomment-712241657 as well

**Comment by mbaxter** [comment]
awesome - thanks!
