### ISSUE TITLE
OutOfMemoryError when starting with -Xmx2g

### ISSUE THREAD

**Issue by plamarque** [Consensys-Incorporated/teku#3103]
### Description
As a Mac user with 16GB RAM, I want to start Teku with -Xmx2g so that I save some memory for other apps. 

### Acceptance Criteria
* Following the [Memory Management guidelines ](https://docs.teku.consensys.net/en/latest/HowTo/Get-Started/Manage-Memory/) in the docs should work : 

### Steps to Reproduce (Bug)
1. git fetch 
2. git checkout 0.12.12
3. sudo ./gradlew distInstall
4. cd build/bin
5. JAVA_OPTS=-Xmx2g ./teku -c /Users/patrice/eth2/teku/teku.yaml

**Expected behavior:** [What you expect to happen]

Teku should start, sync and keep attesting.

**Actual behavior:** [What actually happens]

An OutOfMemoryError happens

```
JAVA_OPTS=-Xmx2g ./teku -c /Users/patrice/eth2/teku/teku.yaml
2020-10-28 08:23:56,006 main INFO Configuring logging for destination: console
2020-10-28 08:23:56,008 main INFO Logging includes events: true
2020-10-28 08:23:56,009 main INFO Logging includes validator duties: true
2020-10-28 08:23:56,009 main INFO Logging includes color: true
08:23:56.015 INFO  - Teku version: teku/v0.12.12/osx-x86_64/oracle-java-11
08:23:56.098 INFO  - Loading 1 validator keys...
08:23:58.414 INFO  - BLS: loaded BLST library
08:23:58.421 INFO  - Loaded 1 Validators: b6f52d7
08:23:58.464 INFO  - Using default implementation for ThreadExecutor
08:23:58.466 INFO  - Job execution threads will use class loader of thread: main
08:23:58.475 INFO  - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
08:23:58.475 INFO  - Quartz Scheduler v.2.3.2 created.
08:23:58.476 INFO  - RAMJobStore initialized.
08:23:58.476 INFO  - Scheduler meta-data: Quartz Scheduler (v2.3.2) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

08:23:58.476 INFO  - Quartz scheduler 'DefaultQuartzScheduler' initialized from default resource file in Quartz package: 'quartz.properties'
08:23:58.476 INFO  - Quartz scheduler version: 2.3.2
08:23:58.605 INFO  - Storing beacon chain data in: /Users/patrice/eth2/teku/data/beacon
08:23:58.605 INFO  - Starting metrics http service on 127.0.0.1:8008
08:23:58.773 INFO  - Metrics service started and listening on 8008:8008
08:23:58.776 INFO  - Beacon data directory set to: /Users/patrice/eth2/teku/data/beacon
08:24:08.411 INFO  - Created V5 Hot database (5) at /Users/patrice/eth2/teku/data/beacon/db
08:24:08.411 INFO  - Created V5 Finalized database (5) at /Users/patrice/eth2/teku/data/beacon/archive
08:24:08.484 INFO  - Initializing storage
08:27:24.126 INFO  - Regenerate state for block 0x755631b47ca8626bba564785df90782c3d8be1d88291cd3dbf71d5d3f1868b7b by replaying 22 blocks
08:27:27.604 INFO  - Completed regeneration of block 0x755631b47ca8626bba564785df90782c3d8be1d88291cd3dbf71d5d3f1868b7b at slot 610274 by replaying 22 blocks. Took 3478ms
08:27:48.438 INFO  - Regenerate state for block 0x148802706def6fe98d128667c348b78b1bcf5438822c8c96b704a11d92f267a7 by replaying 23 blocks
08:27:51.134 INFO  - Completed regeneration of block 0x148802706def6fe98d128667c348b78b1bcf5438822c8c96b704a11d92f267a7 at slot 610272 by replaying 23 blocks. Took 2696ms
08:27:51.301 INFO  - Regenerate state for block 0x4dcd267634cbe4758543c3e6b41762d24ea9ee60475f380e9ebbef399369bf91 by replaying 1 blocks
08:27:51.372 INFO  - Completed regeneration of block 0x4dcd267634cbe4758543c3e6b41762d24ea9ee60475f380e9ebbef399369bf91 at slot 610283 by replaying 1 blocks. Took 71ms
08:27:51.600 INFO  - Regenerate state for block 0x5d723d48fb1234d06c5cfd86eae69318081e8800d29958f4428a99db70581784 by replaying 1 blocks
08:27:51.705 INFO  - Completed regeneration of block 0x5d723d48fb1234d06c5cfd86eae69318081e8800d29958f4428a99db70581784 at slot 610278 by replaying 1 blocks. Took 104ms
08:27:52.276 INFO  - Regenerate state for block 0x4eecf8a967257f6a31d27cc060a20ee17ed509c5d577f4de6d8ca3479921f856 by replaying 1 blocks
08:27:52.294 INFO  - Completed regeneration of block 0x4eecf8a967257f6a31d27cc060a20ee17ed509c5d577f4de6d8ca3479921f856 at slot 610279 by replaying 1 blocks. Took 18ms
08:27:52.462 INFO  - Regenerate state for block 0xda20633e6e8574e7d556836ef8af9e9a638317782e95860504de24771ceb11c4 by replaying 1 blocks
08:27:52.475 INFO  - Completed regeneration of block 0xda20633e6e8574e7d556836ef8af9e9a638317782e95860504de24771ceb11c4 at slot 610282 by replaying 1 blocks. Took 13ms
08:27:52.648 INFO  - Regenerate state for block 0x0b6514e949c7e7911e5533b1fe6460bd47babe57ffaf0dce0d43189693faadd6 by replaying 1 blocks
08:27:52.724 INFO  - Completed regeneration of block 0x0b6514e949c7e7911e5533b1fe6460bd47babe57ffaf0dce0d43189693faadd6 at slot 610285 by replaying 1 blocks. Took 75ms
08:27:53.283 INFO  - Regenerate state for block 0x658d9a1d82ca79b97775583b8d053bc25f5527fc644682612ebc54c0c87c9906 by replaying 1 blocks
08:27:53.296 INFO  - Completed regeneration of block 0x658d9a1d82ca79b97775583b8d053bc25f5527fc644682612ebc54c0c87c9906 at slot 610286 by replaying 1 blocks. Took 13ms
08:27:53.473 INFO  - Regenerate state for block 0x3c4416fc70545e9fe036fa6b35dc1ac551f465501f72a669f2a0cc4a730b73e1 by replaying 1 blocks
08:27:53.492 INFO  - Completed regeneration of block 0x3c4416fc70545e9fe036fa6b35dc1ac551f465501f72a669f2a0cc4a730b73e1 at slot 610290 by replaying 1 blocks. Took 19ms
08:27:53.669 INFO  - Regenerate state for block 0xff45c6deb31f27cd571f9bf1c46609f27fca5995a25112c16536d4978ea1784a by replaying 1 blocks
08:27:54.146 INFO  - Completed regeneration of block 0xff45c6deb31f27cd571f9bf1c46609f27fca5995a25112c16536d4978ea1784a at slot 610291 by replaying 1 blocks. Took 477ms
08:27:54.333 INFO  - Regenerate state for block 0x4aac542817f436f4e77d50e9470dd7bbb5303f560cba109c41aa58e664bee8df by replaying 1 blocks
08:27:54.353 INFO  - Completed regeneration of block 0x4aac542817f436f4e77d50e9470dd7bbb5303f560cba109c41aa58e664bee8df at slot 610293 by replaying 1 blocks. Took 19ms
08:27:54.553 INFO  - Regenerate state for block 0x97d21769dc81ceec05db42d37fb96b570a47e35d6f2aa1444d9c4dbbe16bbed8 by replaying 1 blocks
08:27:54.565 INFO  - Completed regeneration of block 0x97d21769dc81ceec05db42d37fb96b570a47e35d6f2aa1444d9c4dbbe16bbed8 at slot 610294 by replaying 1 blocks. Took 11ms
08:27:54.565 INFO  - Storage initialization complete
08:28:14.816 INFO  - Regenerate state for block 0x62591f06e5131c9f0f930eaaaef80e63044924f687a0372f46c81a9e2d34e26f by replaying 0 blocks
08:28:14.819 INFO  - Completed regeneration of block 0x62591f06e5131c9f0f930eaaaef80e63044924f687a0372f46c81a9e2d34e26f at slot 610112 by replaying 0 blocks. Took 3ms
08:28:18.516 INFO  - Loading generated p2p private key from: generated-node-key
java.lang.OutOfMemoryError: Java heap space
Dumping heap to java_pid15729.hprof ...
Unable to create java_pid15729.hprof: Permission denied
Deserialization error with class: BeaconStateImpl
 Error: java.lang.reflect.InvocationTargetException
08:28:56.042 ERROR - PLEASE FIX OR REPORT | Unexpected exception thrown for beaconchain-async-2
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Unread data detected.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1063) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$2(SafeFuture.java:130) ~[teku-infrastructure-async-0.12.12.jar:0.12.12]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateToAsync$11(SafeFuture.java:223) ~[teku-infrastructure-async-0.12.12.jar:0.12.12]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:77) ~[teku-infrastructure-async-0.12.12.jar:0.12.12]
	at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$1(AsyncRunner.java:35) ~[teku-infrastructure-async-0.12.12.jar:0.12.12]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.ofComposed(SafeFuture.java:86) ~[teku-infrastructure-async-0.12.12.jar:0.12.12]
	at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:119) ~[teku-infrastructure-async-0.12.12.jar:0.12.12]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalStateException: Unread data detected.
	at tech.pegasys.teku.datastructures.util.SimpleOffsetSerializer.assertAllDataRead(SimpleOffsetSerializer.java:232) ~[teku-ethereum-datastructures-0.12.12.jar:0.12.12]
	at tech.pegasys.teku.datastructures.util.SimpleOffsetSerializer.lambda$deserialize$1(SimpleOffsetSerializer.java:212) ~[teku-ethereum-datastructures-0.12.12.jar:0.12.12]
	at org.apache.tuweni.ssz.SSZ.decode(SSZ.java:1255) ~[tuweni-ssz-1.0.0.jar:1.0.0]
	at tech.pegasys.teku.datastructures.util.SimpleOffsetSerializer.deserialize(SimpleOffsetSerializer.java:207) ~[teku-ethereum-datastructures-0.12.12.jar:0.12.12]
	at tech.pegasys.teku.storage.server.rocksdb.serialization.SszSerializer.deserialize(SszSerializer.java:30) ~[teku-storage-0.12.12.jar:0.12.12]
	at tech.pegasys.teku.storage.server.rocksdb.serialization.SszSerializer.deserialize(SszSerializer.java:20) ~[teku-storage-0.12.12.jar:0.12.12]
	at tech.pegasys.teku.storage.server.rocksdb.core.RocksDbInstance.lambda$get$1(RocksDbInstance.java:79) ~[teku-storage-0.12.12.jar:0.12.12]
	at java.util.Optional.map(Optional.java:265) ~[?:?]
	at tech.pegasys.teku.storage.server.rocksdb.core.RocksDbInstance.get(RocksDbInstance.java:79) ~[teku-storage-0.12.12.jar:0.12.12]
	at tech.pegasys.teku.storage.server.rocksdb.dataaccess.V4HotRocksDbDao.getHotState(V4HotRocksDbDao.java:79) ~[teku-storage-0.12.12.jar:0.12.12]
	at tech.pegasys.teku.storage.server.rocksdb.RocksDbDatabase.getHotState(RocksDbDatabase.java:338) ~[teku-storage-0.12.12.jar:0.12.12]
	at tech.pegasys.teku.storage.server.ChainStorage.lambda$getHotBlockAndStateByBlockRoot$7(ChainStorage.java:139) ~[teku-storage-0.12.12.jar:0.12.12]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:77) ~[teku-infrastructure-async-0.12.12.jar:0.12.12]
	at tech.pegasys.teku.storage.server.ChainStorage.getHotBlockAndStateByBlockRoot(ChainStorage.java:136) ~[teku-storage-0.12.12.jar:0.12.12]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:74) ~[teku-infrastructure-events-0.12.12.jar:0.12.12]
	at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.deliverToWithResponse(DirectEventDeliverer.java:67) ~[teku-infrastructure-events-0.12.12.jar:0.12.12]
	at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer.lambda$deliverToWithResponse$1(AsyncEventDeliverer.java:75) ~[teku-infrastructure-events-0.12.12.jar:0.12.12]
	at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:117) ~[teku-infrastructure-events-0.12.12.jar:0.12.12]
	at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:109) ~[teku-infrastructure-events-0.12.12.jar:0.12.12]
	... 3 more
08:28:56.328 INFO  - PreGenesis Local ENR: enr:-KG4QNqagWZQc5rFH34ftRLfSWxKqus07Y8nhMGB-JeOorx2epyd9h_OfNjkfXIxrH3Hq2F3N08KU_0oMh52oa1lJc83hGV0aDKQGK5MywAAAAH__________4JpZIJ2NIJpcIR_AAABiXNlY3AyNTZrMaEDdEdZzAX98GUWv3uoukXbkZHOlNxI5pPRfLCb2gFWbWaDdGNwgiMpg3VkcIIjKQ
08:28:56.424 INFO  - Logging initialized @301893ms to org.eclipse.jetty.util.log.Slf4jLog
08:28:56.539 INFO  - Starting Javalin ...
08:28:56.646 INFO  - Listening on http://localhost:5051/
08:28:56.646 INFO  - Javalin started in 108ms \o/
08:28:56.662 INFO  - Waiting for genesis data to be known
08:28:56.671 INFO  - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
08:28:57.573 INFO  - Eth1 tracker successfully caught up to chain head
08:28:57.859 INFO  - The latest finalized checkpoint at epoch 15614 (74606 active validators) fell outside of the weak subjectivity period after epoch 16802, which is prior to the current epoch 19073.
08:28:57.859 INFO  - The latest finalized checkpoint at epoch 15614 is outside of the weak subjectivity period.  Please supply a recent weak subjectivity checkpoint using --ws-checkpoint=<BLOCK_ROOT>:<EPOCH>.
08:29:06.733 INFO  - Waiting for genesis data to be known
08:29:15.204 INFO  - Regenerate state for block 0x62591f06e5131c9f0f930eaaaef80e63044924f687a0372f46c81a9e2d34e26f by replaying 0 blocks
08:29:15.208 INFO  - Completed regeneration of block 0x62591f06e5131c9f0f930eaaaef80e63044924f687a0372f46c81a9e2d34e26f at slot 610112 by replaying 0 blocks. Took 4ms
08:29:16.943 INFO  - Waiting for genesis data to be known
08:29:27.295 INFO  - Waiting for genesis data to be known
08:29:37.689 INFO  - Waiting for genesis data to be known
08:29:48.635 INFO  - Waiting for genesis data to be known
^CTeku is shutting down
08:30:17.578 INFO  - Stopping Javalin ...
08:30:17.578 INFO  - Javalin has stopped
08:30:17.578 INFO  - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED shutting down.
08:30:18.040 INFO  - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED paused.
08:30:18.040 INFO  - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED shutdown complete.
```

**Frequency:** [What percentage of the time does it occur?]

Only tried once. 
Increased to 3g after initial failure to work around.

### Versions (Add all that apply)
* Software version: teku/v0.12.12/osx-x86_64/oracle-java-11
* Java version: "11.0.1" 2018-10-16 LTS
* OS Name & Version: macOs Catalina 10.15.7

### Additional Information

```
cat  /Users/patrice/eth2/teku/teku.yaml
data-path: "/Users/patrice/eth2/teku/data"
network: "medalla"
eth1-endpoint: "https://goerli.infura.io/v3/XXXXXXXXXOBFUSCATEDXXXXXXXXXXXXX"
validators-key-files: [
  "/Users/patrice/eth2/validator_keys/keystore-m_12381_3600_0_0_0-1596085936.json"
]
validators-key-password-files: [
  "/Users/patrice/eth2/teku/validators-password.txt"
]
validators-graffiti: "poapAAenXZ/Teo00FGXlDtfAh06xYHYB"
p2p-port: 9001
log-destination: CONSOLE
metrics-enabled: true
metrics-port: 8008
rest-api-enabled: true
rest-api-docs-enabled: true
```

**Comment by ajsutton** [comment]
Thanks for raising this. We are seeing higher than intended memory usage on Medalla because of the very long time its gone without finalisation and are currently tracking that via #2832.  I'm going to close this one in favour of that existing ticket.

A change did land today which dramatically reduces CPU usage and will likely reduce memory requirements as well because queues won't build up (they have a limited size but being full does still use more memory).  There is likely further work required but it will likely help in at least some situations.

**Comment by Nashatyrev** [comment]
Relates to #3031
