### ISSUE TITLE
reduce log level for rpc request timed out after 5 sec: Timed out waiting for initial response

### ISSUE THREAD

**Issue by plamarque** [Consensys-Incorporated/teku#3115]
### Description
As a beacon node operator, I want the logs to be error-free when a peer RPC times out  so that my log is not polluted with noise of false errors that do not require my attention. 

### Acceptance Criteria
* logs (using default log level) are no longer polluted with a stacktrace
* log level is not ERROR

### Steps to Reproduce (Bug)
1. stop teku until it's fully synced
2. stop teku for a while (30 minutes or so)
3. restart 
4. watch the logs

**Expected behavior:** [What you expect to happen]

- a lower log level (DEBUG ?)
- no stacktrace 

**Actual behavior:** [What actually happens]

this appears in the  logs :
```
09:27:15.857 ERROR - Error during sync to peer Eth2Peer{id=16Uiu2HAmTZVPipLyb2yEfk7jSF1k4sW241ph9qNaavuQF9yPtw7a, remoteStatus=Optional[PeerStatus{forkDigest=0xe7a75d5a, finalizedRoot=0xb3806428b52a802fb9c4355b6e93a6afde02ecbd27a9f4723eb427c27cadb440, finalizedEpoch=15614, headRoot=0xfe0aeba9ade17ada72190afccfe2c6f90084ef13626ad9401d5f142868233a31, headSlot=632234}]}
java.util.concurrent.CompletionException: tech.pegasys.teku.networking.eth2.rpc.core.RpcTimeouts$RpcTimeoutException: Rpc request timed out after 5 sec: Timed out waiting for initial response
	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1019) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
	at tech.pegasys.teku.networking.eth2.rpc.core.ResponseStreamImpl.completeWithError(ResponseStreamImpl.java:75) ~[teku-networking-eth2-0.12.13-SNAPSHOT.jar:0.12.13-dev-eb9ee281]
	at tech.pegasys.teku.networking.eth2.rpc.core.Eth2OutgoingRequestHandler.lambda$abortRequest$2(Eth2OutgoingRequestHandler.java:228) ~[teku-networking-eth2-0.12.13-SNAPSHOT.jar:0.12.13-dev-eb9ee281]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$always$15(SafeFuture.java:244) ~[teku-infrastructure-async-0.12.13-SNAPSHOT.jar:0.12.13-dev-eb9ee281]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$finish$19(SafeFuture.java:262) ~[teku-infrastructure-async-0.12.13-SNAPSHOT.jar:0.12.13-dev-eb9ee281]
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:946) ~[?:?]
	at java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2266) ~[?:?]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.handle(SafeFuture.java:439) ~[teku-infrastructure-async-0.12.13-SNAPSHOT.jar:0.12.13-dev-eb9ee281]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.finish(SafeFuture.java:257) ~[teku-infrastructure-async-0.12.13-SNAPSHOT.jar:0.12.13-dev-eb9ee281]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.always(SafeFuture.java:244) ~[teku-infrastructure-async-0.12.13-SNAPSHOT.jar:0.12.13-dev-eb9ee281]
	at tech.pegasys.teku.networking.eth2.rpc.core.Eth2OutgoingRequestHandler.abortRequest(Eth2OutgoingRequestHandler.java:228) ~[teku-networking-eth2-0.12.13-SNAPSHOT.jar:0.12.13-dev-eb9ee281]
	at tech.pegasys.teku.networking.eth2.rpc.core.Eth2OutgoingRequestHandler.abortRequest(Eth2OutgoingRequestHandler.java:212) ~[teku-networking-eth2-0.12.13-SNAPSHOT.jar:0.12.13-dev-eb9ee281]
	at tech.pegasys.teku.networking.eth2.rpc.core.Eth2OutgoingRequestHandler.lambda$ensureFirstBytesArriveWithinTimeLimit$3(Eth2OutgoingRequestHandler.java:239) ~[teku-networking-eth2-0.12.13-SNAPSHOT.jar:0.12.13-dev-eb9ee281]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$2(SafeFuture.java:132) ~[teku-infrastructure-async-0.12.13-SNAPSHOT.jar:0.12.13-dev-eb9ee281]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883) ~[?:?]
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251) ~[?:?]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:479) ~[teku-infrastructure-async-0.12.13-SNAPSHOT.jar:0.12.13-dev-eb9ee281]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:28) ~[teku-infrastructure-async-0.12.13-SNAPSHOT.jar:0.12.13-dev-eb9ee281]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:127) ~[teku-infrastructure-async-0.12.13-SNAPSHOT.jar:0.12.13-dev-eb9ee281]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateTo(SafeFuture.java:220) ~[teku-infrastructure-async-0.12.13-SNAPSHOT.jar:0.12.13-dev-eb9ee281]
	at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:119) ~[teku-infrastructure-async-0.12.13-SNAPSHOT.jar:0.12.13-dev-eb9ee281]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: tech.pegasys.teku.networking.eth2.rpc.core.RpcTimeouts$RpcTimeoutException: Rpc request timed out after 5 sec: Timed out waiting for initial response
	... 16 more
```

**Frequency:** [What percentage of the time does it occur?]

irregular, frequently after the beacon node has been offline for a while.

### Versions (Add all that apply)
* Software version: [`teku/v0.12.13-dev-eb9ee281/osx-x86_64/oracle-java-11`]
* Java version: [`java version "11.0.1" 2018-10-16 LTS`]
* OS Name & Version: [`macOS Catalina 10.15.7`]
* Kernel Version: [`Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64`]

**Comment by rolfyone** [comment]
Thanks for the bug report. We agree with the sentiment, and are putting this on the list of things to action soon.
