### ISSUE TITLE
Lock file on keys not properly erroring

### ISSUE THREAD

**Issue by PatrickAlphaC** [Consensys-Incorporated/teku#3438]
### Description
When a lock file is left on a validator key (maybe the box crashes before teku has a chance to remove the lock files), the node will not properly identify this, but instead hang around and be confused. 

### Acceptance Criteria
* When a validator key has a lock file on it, set an error message saying so and exit. 

### Steps to Reproduce (Bug)
1. Add lockfiles to validator keys 
ie: keystore-m_2425245-3453453.json.lock
2. Start teku node
3. Hang. If you set the logging to `--logging debug` you'll see the error. 

**Expected behavior:** [What you expect to happen]
Teku prints an error mentioning the locks and exits

**Actual behavior:** [What actually happens]
```
2021-01-07 00:43:01.813-05:00 | validator-async-0 | ERROR | ValidatorClientService | Unable to initialize validators
tech.pegasys.teku.util.config.InvalidConfigurationException: Keystore file /var/lib/teku/validator_keys/keystore-m_1111_1111_1_0_0-11111111.json.lock already in use.
        at tech.pegasys.teku.validator.client.loader.KeystoreLocker.keystoreInUseException(KeystoreLocker.java:84) ~[teku-validator-client-20.12.1.jar:20.12.1]
        at tech.pegasys.teku.validator.client.loader.KeystoreLocker.attemptReplaceStaleLockFile(KeystoreLocker.java:67) ~[teku-validator-client-20.12.1.jar:20.12.1]
        at tech.pegasys.teku.validator.client.loader.KeystoreLocker.lockKeystore(KeystoreLocker.java:42) ~[teku-validator-client-20.12.1.jar:20.12.1]
        at tech.pegasys.teku.validator.client.loader.KeystoresValidatorKeyProvider.loadBLSPrivateKey(KeystoresValidatorKeyProvider.java:110) ~[teku-validator-client-20.12.1.jar:20.12.1]
        at tech.pegasys.teku.validator.client.loader.KeystoresValidatorKeyProvider.lambda$loadValidatorKeys$0(KeystoresValidatorKeyProvider.java:78) ~[teku-validator-client-20.12.1.jar:20.12.1]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2021-01-07 00:43:01.821-05:00 | main | INFO  | SimpleThreadPool | Job execution threads will use class loader of thread: main
```
And proceeds to hang around and be confused. 

**Frequency:** [What percentage of the time does it occur?]
100%

### Versions (Add all that apply)
* Software version: [`teku --version`]
teku/v20.12.1/linux-x86_64/-ubuntu-openjdk64bitservervm-java-11
* Java version: [`java -version`]
openjdk 11.0.9.1 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
* OS Name & Version: [`cat /etc/*release`]
Ubuntu 20.04.1 LTS
* Kernel Version: [`uname -a`]
Linux mainnet-eth-2-box 5.4.0-59-generic #65-Ubuntu SMP Thu Dec 10 12:01:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Additional Information

Temporary work around is to manually delete the lockfiles in the validators key folder and restart your node. Works fine after that.

**Comment by PatrickAlphaC** [comment]
Thanks to @ajsutton for helping me out with this issue!

**Comment by ajsutton** [comment]
I suspect this was broken when we moved to loading validator keys asynchronously.  That's been a very beneficial change so would be good to keep it but need to work out how to get Teku to exit and print the error message right at the end of output if it fails.  If the error is further up the output its really easy to miss it.
