### ISSUE TITLE
Treat failure to commit to database as a fatal error

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#3489]
### Description
When the database is unable to commit transactions, treat it as a fatal error and exit teku.  This allows monitoring to restart the service or node to recover from the issue.

This includes cases where the underlying disk fails, out of space errors and database corruption.

Example exception:
```
10:11:19.094 ERROR - PLEASE FIX OR REPORT | Unexpected exception thrown for event 'interface tech.pegasys.teku.util.time.channels.TimeTickChannel.onTick' in handler 'tech.pegasys.teku.services.beaconchain.BeaconChainController'
java.util.concurrent.CompletionException: tech.pegasys.teku.storage.server.DatabaseStorageException: Failed to commit transaction
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:704) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2152) ~[?:?]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:141) ~[teku-infrastructure-async-20.12.1.jar:20.12.1]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2152) ~[?:?]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateToAsync$13(SafeFuture.java:242) ~[teku-infrastructure-async-20.12.1.jar:20.12.1]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:77) ~[teku-infrastructure-async-20.12.1.jar:20.12.1]
        at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$1(AsyncRunner.java:35) ~[teku-infrastructure-async-20.12.1.jar:20.12.1]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:69) ~[teku-infrastructure-async-20.12.1.jar:20.12.1]
        at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:120) ~[teku-infrastructure-async-20.12.1.jar:20.12.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: tech.pegasys.teku.storage.server.DatabaseStorageException: Failed to commit transaction
        at tech.pegasys.teku.storage.server.rocksdb.core.RocksDbInstance$Transaction.lambda$commit$5(RocksDbInstance.java:297) ~[teku-storage-20.12.1.jar:20.12.1]
        at tech.pegasys.teku.storage.server.rocksdb.core.RocksDbInstance$Transaction.applyUpdate(RocksDbInstance.java:322) ~[teku-storage-20.12.1.jar:20.12.1]
        at tech.pegasys.teku.storage.server.rocksdb.core.RocksDbInstance$Transaction.commit(RocksDbInstance.java:292) ~[teku-storage-20.12.1.jar:20.12.1]
        at tech.pegasys.teku.storage.server.rocksdb.dataaccess.V4HotRocksDbDao$V4HotUpdater.commit(V4HotRocksDbDao.java:285) ~[teku-storage-20.12.1.jar:20.12.1]
        at tech.pegasys.teku.storage.server.rocksdb.RocksDbDatabase.doUpdate(RocksDbDatabase.java:564) ~[teku-storage-20.12.1.jar:20.12.1]
        at tech.pegasys.teku.storage.server.rocksdb.RocksDbDatabase.update(RocksDbDatabase.java:240) ~[teku-storage-20.12.1.jar:20.12.1]
        at tech.pegasys.teku.storage.server.ChainStorage.lambda$onStorageUpdate$0(ChainStorage.java:104) ~[teku-storage-20.12.1.jar:20.12.1]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.fromRunnable(SafeFuture.java:150) ~[teku-infrastructure-async-20.12.1.jar:20.12.1]
        at tech.pegasys.teku.storage.server.ChainStorage.onStorageUpdate(ChainStorage.java:102) ~[teku-storage-20.12.1.jar:20.12.1]
        at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
        at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:74) ~[teku-infrastructure-events-20.12.1.jar:20.12.1]
        at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.deliverToWithResponse(DirectEventDeliverer.java:67) ~[teku-infrastructure-events-20.12.1.jar:20.12.1]
        at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer.lambda$deliverToWithResponse$1(AsyncEventDeliverer.java:75) ~[teku-infrastructure-events-20.12.1.jar:20.12.1]
        at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:117) [teku-infrastructure-events-20.12.1.jar:20.12.1]
        at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:109) [teku-infrastructure-events-20.12.1.jar:20.12.1]
        ... 3 more
Caused by: org.rocksdb.RocksDBException: While sync_file_range returned -1: /data/beacon/db/035932.log: Resource temporarily unavailable
        at org.rocksdb.Transaction.commit(Native Method) ~[rocksdbjni-6.11.4.jar:?]
        at org.rocksdb.Transaction.commit(Transaction.java:206) ~[rocksdbjni-6.11.4.jar:?]
        at tech.pegasys.teku.storage.server.rocksdb.core.RocksDbInstance$Transaction.lambda$commit$5(RocksDbInstance.java:295) ~[teku-storage-20.12.1.jar:20.12.1]
        at tech.pegasys.teku.storage.server.rocksdb.core.RocksDbInstance$Transaction.applyUpdate(RocksDbInstance.java:322) ~[teku-storage-20.12.1.jar:20.12.1]
        at tech.pegasys.teku.storage.server.rocksdb.core.RocksDbInstance$Transaction.commit(RocksDbInstance.java:292) ~[teku-storage-20.12.1.jar:20.12.1]
        at tech.pegasys.teku.storage.server.rocksdb.dataaccess.V4HotRocksDbDao$V4HotUpdater.commit(V4HotRocksDbDao.java:285) ~[teku-storage-20.12.1.jar:20.12.1]
        at tech.pegasys.teku.storage.server.rocksdb.RocksDbDatabase.doUpdate(RocksDbDatabase.java:564) ~[teku-storage-20.12.1.jar:20.12.1]
        at tech.pegasys.teku.storage.server.rocksdb.RocksDbDatabase.update(RocksDbDatabase.java:240) ~[teku-storage-20.12.1.jar:20.12.1]
        at tech.pegasys.teku.storage.server.ChainStorage.lambda$onStorageUpdate$0(ChainStorage.java:104) ~[teku-storage-20.12.1.jar:20.12.1]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.fromRunnable(SafeFuture.java:150) ~[teku-infrastructure-async-20.12.1.jar:20.12.1]
        at tech.pegasys.teku.storage.server.ChainStorage.onStorageUpdate(ChainStorage.java:102) ~[teku-storage-20.12.1.jar:20.12.1]
        at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
        at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:74) ~[teku-infrastructure-events-20.12.1.jar:20.12.1]
        at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.deliverToWithResponse(DirectEventDeliverer.java:67) ~[teku-infrastructure-events-20.12.1.jar:20.12.1]
        at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer.lambda$deliverToWithResponse$1(AsyncEventDeliverer.java:75) ~[teku-infrastructure-events-20.12.1.jar:20.12.1]
        at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:117) ~[teku-infrastructure-events-20.12.1.jar:20.12.1]
        at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:109) ~[teku-infrastructure-events-20.12.1.jar:20.12.1]
        ... 3 more
```

**Comment by rolfyone** [comment]
- maybe a tolerance, like N failures (5-10?)

**Comment by tzapu** [comment]
i've got no idea how much a retry would complicate things or if there are any cases where it would help, in the example above or in case of disk full which apparently would trigger something like this, it doesn't seem like it would help. the above log went on for hours, a restart of teku sorted it

**Comment by ajsutton** [comment]
I think all the `DatabaseException` cases I've seen have been pretty fatal, but it's a pretty generic type of exception so won't always be.  There's actually a status field in `RocksDbException` which can be set to things like `tryAgain` which probably shouldn't be considered fatal. This example would come up as an `IoError` which would be fatal.

Given there's such a clear status in the underlying exception I think we can just add a simple flag to say if it's fatal or not and go from there.
