### ISSUE TITLE
ProtoNode RuntimeException

### ISSUE THREAD

**Issue by mbaxter** [Consensys-Incorporated/teku#3533]
### Description
We have a user report of the following `ProtoNode` exception triggering repeatedly (every 500ms) on an instance of teku (running `20.12.1`):
```
10:34:16.842 ERROR - PLEASE FIX OR REPORT | Unexpected exception thrown for event 'interface tech.pegasys.teku.util.time.channels.TimeTickChannel.onTick' in handler 'tech.pegasys.teku.services.beaconchain.BeaconChainController'
java.util.concurrent.CompletionException: java.lang.RuntimeException: ProtoNode: Delta to be subtracted is greater than node weight for block 0xa99cb183832311be35d7b6f46ee722dee84d52626aa3085d8ccb2781c38ef1ca (543848). Attempting to subtract 32426968918 from 461006704
	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1093) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2152) ~[?:?]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:141) ~[teku-infrastructure-async-20.12.1.jar:20.12.1]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883) ~[?:?]
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2315) ~[?:?]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:494) ~[teku-infrastructure-async-20.12.1.jar:20.12.1]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:28) ~[teku-infrastructure-async-20.12.1.jar:20.12.1]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:138) ~[teku-infrastructure-async-20.12.1.jar:20.12.1]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateTo(SafeFuture.java:235) ~[teku-infrastructure-async-20.12.1.jar:20.12.1]
	at tech.pegasys.teku.statetransition.forkchoice.SingleThreadedForkChoiceExecutor.lambda$performTask$0(SingleThreadedForkChoiceExecutor.java:58) ~[teku-ethereum-statetransition-20.12.1.jar:20.12.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.RuntimeException: ProtoNode: Delta to be subtracted is greater than node weight for block 0xa99cb183832311be35d7b6f46ee722dee84d52626aa3085d8ccb2781c38ef1ca (543848). Attempting to subtract 32426968918 from 461006704
	at tech.pegasys.teku.protoarray.ProtoNode.adjustWeight(ProtoNode.java:66) ~[teku-protoarray-20.12.1.jar:20.12.1]
	at tech.pegasys.teku.protoarray.ProtoArray.applyDelta(ProtoArray.java:434) ~[teku-protoarray-20.12.1.jar:20.12.1]
	at tech.pegasys.teku.protoarray.ProtoArray.lambda$applyDeltas$6(ProtoArray.java:423) ~[teku-protoarray-20.12.1.jar:20.12.1]
	at tech.pegasys.teku.protoarray.ProtoArray.applyToNodes(ProtoArray.java:450) ~[teku-protoarray-20.12.1.jar:20.12.1]
	at tech.pegasys.teku.protoarray.ProtoArray.applyDeltas(ProtoArray.java:423) ~[teku-protoarray-20.12.1.jar:20.12.1]
	at tech.pegasys.teku.protoarray.ProtoArray.applyScoreChanges(ProtoArray.java:184) ~[teku-protoarray-20.12.1.jar:20.12.1]
	at tech.pegasys.teku.protoarray.ProtoArrayForkChoiceStrategy.findHead(ProtoArrayForkChoiceStrategy.java:207) ~[teku-protoarray-20.12.1.jar:20.12.1]
	at tech.pegasys.teku.protoarray.ProtoArrayForkChoiceStrategy.findHead(ProtoArrayForkChoiceStrategy.java:99) ~[teku-protoarray-20.12.1.jar:20.12.1]
	at tech.pegasys.teku.storage.store.StoreTransaction.applyForkChoiceScoreChanges(StoreTransaction.java:154) ~[teku-storage-20.12.1.jar:20.12.1]
	at tech.pegasys.teku.statetransition.forkchoice.ForkChoice.lambda$processHead$1(ForkChoice.java:106) ~[teku-ethereum-statetransition-20.12.1.jar:20.12.1]
	at tech.pegasys.teku.statetransition.forkchoice.SingleThreadedForkChoiceExecutor.lambda$syncPerformTask$1(SingleThreadedForkChoiceExecutor.java:77) ~[teku-ethereum-statetransition-20.12.1.jar:20.12.1]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:77) ~[teku-infrastructure-async-20.12.1.jar:20.12.1]
	at tech.pegasys.teku.statetransition.forkchoice.SingleThreadedForkChoiceExecutor.syncPerformTask(SingleThreadedForkChoiceExecutor.java:77) ~[teku-ethereum-statetransition-20.12.1.jar:20.12.1]
	... 4 more
```

**Comment by rolfyone** [comment]
block `a99cb183832311be35d7b6f46ee722dee84d52626aa3085d8ccb2781c38ef1ca` appears to be a pyrmont block hash, and it's an orphaned block.

**Comment by ajsutton** [comment]
This happens when the `ProtoArray` and the record of votes wind up out of sync.  In previous cases we've seen this was caused by multiple threads updating the votes simultaneously but it was rearchitected to make that exceptionally unlikely.  Code review strongly suggests that wasn't what caused it this time.

The other possibly risk is that the `ProtoArray` was updated but then the storage of votes failed and that transaction was rolled back. The changes in the `ProtoArray` don't use transactions and so wouldn't have been rolled back, leaving the two out of sync.

We may need to make vote updates not use transactions either - the weightings in the `ProtoArray` aren't stored on disk so we only need the in-memory `ProtoArray` and votes to be in sync.  It's ok if the votes on disk are out of sync because of a missed update - that will be correctly when the next attestation from the relevant validators is received.

**Comment by ajsutton** [comment]
Switched votes to always update in memory even if the disk update fails.  Can't be certain that this was the original cause of the issue but it seems the most likely, so closing for now.  If it pops up again we may need to add asserts to ensure votes and protoarray weightings are only ever changed on the fork choice thread.
