### ISSUE TITLE
Exception when client requests 'attestation' events

### ISSUE THREAD

**Issue by mcdee** [Consensys-Incorporated/teku#3579]
Attempting to fetch attestation events from Teku stops after a while (usually 20-30 seconds).  The connection closes and an error is reported in the teku logs:

```
09:27:34.517 ERROR - Failed to process event queue for client 1759904277
java.util.concurrent.CompletionException: java.lang.IllegalStateException: AsyncContext completed and/or Request lifecycle recycled
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2152) ~[?:?]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:141) ~[teku-infrastructure-async-21.1.1.jar:21.1.1]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883) ~[?:?]
        at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2315) ~[?:?]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:494) ~[teku-infrastructure-async-21.1.1.jar:21.1.1]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:28) ~[teku-infrastructure-async-21.1.1.jar:21.1.1]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:138) ~[teku-infrastructure-async-21.1.1.jar:21.1.1]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$exceptionallyCompose$25(SafeFuture.java:338) ~[teku-infrastructure-async-21.1.1.jar:21.1.1]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2152) ~[?:?]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:141) ~[teku-infrastructure-async-21.1.1.jar:21.1.1]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883) ~[?:?]
        at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2315) ~[?:?]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:494) ~[teku-infrastructure-async-21.1.1.jar:21.1.1]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:28) ~[teku-infrastructure-async-21.1.1.jar:21.1.1]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:138) ~[teku-infrastructure-async-21.1.1.jar:21.1.1]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateTo(SafeFuture.java:235) ~[teku-infrastructure-async-21.1.1.jar:21.1.1]
        at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:120) ~[teku-infrastructure-async-21.1.1.jar:21.1.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.IllegalStateException: AsyncContext completed and/or Request lifecycle recycled
        at org.eclipse.jetty.server.AsyncContextState.state(AsyncContextState.java:52) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
        at org.eclipse.jetty.server.AsyncContextState.getResponse(AsyncContextState.java:118) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
        at io.javalin.http.sse.Emitter.emit(Emitter.kt:34) ~[javalin-3.12.0.jar:?]
        at io.javalin.http.sse.SseClient.sendEvent(SseClient.java:29) ~[javalin-3.12.0.jar:?]
        at io.javalin.http.sse.SseClient.sendEvent(SseClient.java:25) ~[javalin-3.12.0.jar:?]
        at tech.pegasys.teku.beaconrestapi.handlers.v1.events.EventSubscriber.lambda$processEventQueue$0(EventSubscriber.java:82) ~[teku-data-beaconrestapi-21.1.1.jar:21.1.1]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.fromRunnable(SafeFuture.java:150) ~[teku-infrastructure-async-21.1.1.jar:21.1.1]
        at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$0(AsyncRunner.java:24) ~[teku-infrastructure-async-21.1.1.jar:21.1.1]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:69) ~[teku-infrastructure-async-21.1.1.jar:21.1.1]
        ... 4 more
```

### Steps to Reproduce (Bug)
1. run `curl -H "Accept:text/event-stream" 'http://localhost:5051/eth/v1/events?topics=attestation'`
2. wait a bit

**Expected behavior:** [What you expect to happen]
Stream continues until stopped.

**Actual behavior:** [What actually happens]
Stream is closed by Teku.

**Frequency:** [What percentage of the time does it occur?]

100%

### Versions (Add all that apply)

* Software version: [`teku --version`]

`teku/v21.1.1/linux-x86_64/-privatebuild-openjdk64bitservervm-java-14`

* Java version: [`java -version`]
```
openjdk 14.0.2 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-Ubuntu-120.04)OpenJDK 64-Bit Server VM (build 14.0.2+12-Ubuntu-120.04, mixed mode, sharing)
```
* OS Name & Version: [`cat /etc/*release`]
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
* Kernel Version: [`uname -a`]
```
Linux jack-d01 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ajsutton** [comment]
It seems to be working for me on MainNet.  My quick theory is that at some point attestations are received faster than they can be sent out to the event stream. Normally that's because the client reading from the stream is lagging behind and TCP back pressure builds up but could be thread contention on the server I guess.  Whatever causes is, Teku limits the number of pending events it will hold for a connection and if the limit is reached, the connection is closed.  Teku only logs a message at trace level when it does that.  Since a separate thread is publishing attestation events as fast as it can, the event above is triggered when it tries to publish the next one because the context is closed.

If that's right (which is definitely not a given), then the first log saying the queue is full should probably be more visible and the error because the context is closed should be bumped down to debug since it's entirely expected.  It also means this will be more likely to happen on Pyrmont with greater numbers of validators.

**Comment by ajsutton** [comment]
Reproduced this pretty easily with Pyrmont.   The maximum number of pending events is set to just 10 which is far too small for attestations.  Going to increase the default to about 250 which works with a local connection and make it a hidden config option in case there are use cases that needs to handle larger bursts.
