### ISSUE TITLE
Repeated crash and corruption on Windows

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#3858]
### Description
Reported by `EyeBrain360` on Teku discord:

>Our teku validator crashed again. When this happens we can't restart it and need to delete the Archive and db folder to start a rebuild. Here's what it looks like in the shell when this happens. 
![image](https://user-images.githubusercontent.com/72675/114657415-5f23b280-9d33-11eb-8c60-7b4398207fb5.png)

> Trying to restart after this crash looks like this:

![image](https://user-images.githubusercontent.com/72675/114657430-65b22a00-9d33-11eb-9f26-3e486973cc9c.png)

```
2021-04-07 23:02:47.174-04:00 | TimeTickChannel-0 | INFO  | teku-event-log | [32mEpoch Event *** Epoch: 28716, Justified checkpoint: 28714, Finalized checkpoint: 28713, Finalized root: 2e9da2..ce7f[0m
2021-04-07 23:02:47.174-04:00 | SlotEventsChannel-4 | INFO  | teku-status-log | Attestation performance: expected 1, produced 1, included 1 (100%), distance 1 / 1.00 / 1, correct target 1 (100%), correct head 1 (100%)
2021-04-07 23:02:51.306-04:00 | TimeTickChannel-0 | INFO  | teku-event-log | [37mSlot Event  *** Slot: 918912, Block: f4a175..b337, Epoch: 28716, Finalized checkpoint: 28714, Finalized root: 915e29..53c7, Peers: 47[0m
2021-04-07 23:03:03.204-04:00 | TimeTickChannel-0 | INFO  | teku-event-log | [37mSlot Event  *** Slot: 918913, Block: 397f63..83ff, Epoch: 28716, Finalized checkpoint: 28714, Finalized root: 915e29..53c7, Peers: 48[0m
2021-04-07 23:03:15.197-04:00 | TimeTickChannel-0 | INFO  | teku-event-log | [37mSlot Event  *** Slot: 918914, Block:    ... empty, Epoch: 28716, Finalized checkpoint: 28714, Finalized root: 915e29..53c7, Peers: 48[0m
2021-04-07 23:03:27.199-04:00 | TimeTickChannel-0 | INFO  | teku-event-log | [37mSlot Event  *** Slot: 918915, Block: 71d08b..e91e, Epoch: 28716, Finalized checkpoint: 28714, Finalized root: 915e29..53c7, Peers: 50[0m
2021-04-07 23:03:39.203-04:00 | TimeTickChannel-0 | INFO  | teku-event-log | [37mSlot Event  *** Slot: 918916, Block:    ... empty, Epoch: 28716, Finalized checkpoint: 28714, Finalized root: 915e29..53c7, Peers: 50[0m
2021-04-07 23:03:40.737-04:00 | forkchoice-async-0 | INFO  | CoalescingChainHeadChannel | Chain reorg at slot 918916 from 71d08b..e91e to 16bf4c..bf7c. Common ancestor at slot 918915
2021-04-07 23:03:49.756-04:00 | forkchoice-async-0 | INFO  | CoalescingChainHeadChannel | Chain reorg at slot 918917 from 16bf4c..bf7c to 8d6378..f721. Common ancestor at slot 918915
2021-04-07 23:03:51.194-04:00 | forkchoice-async-0 | INFO  | CoalescingChainHeadChannel | Chain reorg at slot 918917 from 8d6378..f721 to 16bf4c..bf7c. Common ancestor at slot 918915
2021-04-07 23:03:51.194-04:00 | TimeTickChannel-0 | INFO  | teku-event-log | [37mSlot Event  *** Slot: 918917, Block:    ... empty, Epoch: 28716, Finalized checkpoint: 28714, Finalized root: 915e29..53c7, Peers: 50[0m
2021-04-07 23:04:03.203-04:00 | TimeTickChannel-0 | INFO  | teku-event-log | [37mSlot Event  *** Slot: 918918, Block: 831164..49f7, Epoch: 28716, Finalized checkpoint: 28714, Finalized root: 915e29..53c7, Peers: 48[0m
2021-04-07 23:04:15.200-04:00 | TimeTickChannel-0 | INFO  | teku-event-log | [37mSlot Event  *** Slot: 918919, Block: 9fdd3e..59d9, Epoch: 28716, Finalized checkpoint: 28714, Finalized root: 915e29..53c7, Peers: 45[0m
2021-04-07 23:04:27.201-04:00 | TimeTickChannel-0 | INFO  | teku-event-log | [37mSlot Event  *** Slot: 918920, Block: a5bc79..43bb, Epoch: 28716, Finalized checkpoint: 28714, Finalized root: 915e29..53c7, Peers: 46[0m
2021-04-07 23:04:39.205-04:00 | TimeTickChannel-0 | INFO  | teku-event-log | [37mSlot Event  *** Slot: 918921, Block: 9a3a6e..3ccd, Epoch: 28716, Finalized checkpoint: 28714, Finalized root: 915e29..53c7, Peers: 46[0m
2021-04-07 23:04:39.236-04:00 | VoteUpdateChannel-0 | FATAL | teku-status-log | Exiting due to fatal error in event 'interface tech.pegasys.teku.storage.api.VoteUpdateChannel.onVotesUpdated' in handler 'tech.pegasys.teku.storage.server.ChainStorage'
tech.pegasys.teku.storage.server.DatabaseStorageException: Failed to commit transaction
	at tech.pegasys.teku.storage.server.DatabaseStorageException.unrecoverable(DatabaseStorageException.java:31) ~[teku-storage-21.3.0.jar:21.3.0]
	at tech.pegasys.teku.storage.server.rocksdb.RocksDbExceptionUtil.wrapException(RocksDbExceptionUtil.java:23) ~[teku-storage-21.3.0.jar:21.3.0]
	at tech.pegasys.teku.storage.server.rocksdb.core.RocksDbInstance$Transaction.lambda$commit$5(RocksDbInstance.java:288) ~[teku-storage-21.3.0.jar:21.3.0]
	at tech.pegasys.teku.storage.server.rocksdb.core.RocksDbInstance$Transaction.applyUpdate(RocksDbInstance.java:313) ~[teku-storage-21.3.0.jar:21.3.0]
	at tech.pegasys.teku.storage.server.rocksdb.core.RocksDbInstance$Transaction.commit(RocksDbInstance.java:283) ~[teku-storage-21.3.0.jar:21.3.0]
	at tech.pegasys.teku.storage.server.rocksdb.dataaccess.V4HotRocksDbDao$V4HotUpdater.commit(V4HotRocksDbDao.java:285) ~[teku-storage-21.3.0.jar:21.3.0]
	at tech.pegasys.teku.storage.server.rocksdb.RocksDbDatabase.storeVotes(RocksDbDatabase.java:657) ~[teku-storage-21.3.0.jar:21.3.0]
	at tech.pegasys.teku.storage.server.ChainStorage.onVotesUpdated(ChainStorage.java:220) ~[teku-storage-21.3.0.jar:21.3.0]
	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:74) ~[teku-infrastructure-events-21.3.0.jar:21.3.0]
	at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.deliverTo(DirectEventDeliverer.java:54) ~[teku-infrastructure-events-21.3.0.jar:21.3.0]
	at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer.lambda$deliverTo$0(AsyncEventDeliverer.java:61) ~[teku-infrastructure-events-21.3.0.jar:21.3.0]
	at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:117) [teku-infrastructure-events-21.3.0.jar:21.3.0]
	at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:109) [teku-infrastructure-events-21.3.0.jar:21.3.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.rocksdb.RocksDBException: block checksum mismatch: expected 4024324689, got 2735320014  in C:\Users\Eyebrain360ETH\AppData\Local\teku\beacon\db/030750.sst offset 1829308 size 4070
	at org.rocksdb.Transaction.commit(Native Method) ~[rocksdbjni-6.11.4.jar:?]
	at org.rocksdb.Transaction.commit(Transaction.java:206) ~[rocksdbjni-6.11.4.jar:?]
	at tech.pegasys.teku.storage.server.rocksdb.core.RocksDbInstance$Transaction.lambda$commit$5(RocksDbInstance.java:286) ~[teku-storage-21.3.0.jar:21.3.0]
	... 16 more
2021-04-07 23:04:39.361-04:00 | Thread-5 | INFO  | QuartzScheduler | Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED shutting down.
2021-04-07 23:04:39.361-04:00 | Thread-5 | INFO  | QuartzScheduler | Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED paused.
2021-04-07 23:04:39.361-04:00 | Thread-5 | INFO  | QuartzScheduler | Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED shutdown complete.
2021-04-07 23:04:40.161-04:00 | nioEventLoopGroup-3-8 | INFO  | NettyDiscoveryServerImpl | Stopping discovery server
2021-04-07 23:04:40.161-04:00 | nioEventLoopGroup-4-1 | INFO  | NettyDiscoveryServerImpl | Shutting down discovery server
```

Follow up database corruption may be solved by the switch from RocksDB to LevelDB but would be good to get a better understanding of why it's crashing.

**Comment by ajsutton** [comment]
Request full version info and the hs_err file.

**Comment by ajsutton** [comment]
Version: teku/v21.3.0/windows-x86_64/adoptopenjdk-java-11

Windows 10 Pro
[hs_err_pid7076.log](https://github.com/ConsenSys/teku/files/6314629/hs_err_pid7076.log)

**Comment by ajsutton** [comment]
User reports that a memory fault was found in one of the DIMMs which will be the cause of the initial crashes.  RocksDB corruption issues will be fixed by moving to LevelDB.
