### ISSUE TITLE
Fatal exception when Eth1 block not returned

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#3924]
### Description
`MinimumGenesisTimeBlockFinder.binarySearchLoop` expects that `getEth1BlockWithRetry` will always return the block and has no exception handling for when it doesn't.

Specifically this code:
```
eth1Provider.getEth1BlockWithRetry(searchContext.low).thenApply(Optional::get)
```

If the block isn't returned we get the exception below which is treated as a fatal exception and Teku exits.  We should at minimum provide a much more clear error message indicating that we couldn't find the min genesis time block and hopefully find better way to handle this.

Note the exception below doesn't even include a reference to `MinimumGenesisTimeBlockFinder` because of the use of a method reference for `Optional::get`.  All the other places that use `Optional::get` in the pow module also have an exception handler so wouldn't cause this `FatalServiceFailureException`.

```
java.util.concurrent.CompletionException: tech.pegasys.teku.service.serviceutils.FatalServiceFailureException: java.util.concurrent.CompletionException: java.util.NoSuchElementException: No value present
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147) ~[teku-infrastructure-async-21.4.1.jar:21.4.1]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147) ~[teku-infrastructure-async-21.4.1.jar:21.4.1]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.whenComplete(Unknown Source) ~[?:?]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:524) ~[teku-infrastructure-async-21.4.1.jar:21.4.1]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:32) ~[teku-infrastructure-async-21.4.1.jar:21.4.1]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:142) ~[teku-infrastructure-async-21.4.1.jar:21.4.1]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$exceptionallyCompose$26(SafeFuture.java:362) ~[teku-infrastructure-async-21.4.1.jar:21.4.1]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147) ~[teku-infrastructure-async-21.4.1.jar:21.4.1]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.whenComplete(Unknown Source) ~[?:?]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:524) ~[teku-infrastructure-async-21.4.1.jar:21.4.1]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:32) ~[teku-infrastructure-async-21.4.1.jar:21.4.1]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:142) ~[teku-infrastructure-async-21.4.1.jar:21.4.1]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$exceptionallyCompose$26(SafeFuture.java:362) ~[teku-infrastructure-async-21.4.1.jar:21.4.1]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147) ~[teku-infrastructure-async-21.4.1.jar:21.4.1]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.whenComplete(Unknown Source) ~[?:?]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:524) ~[teku-infrastructure-async-21.4.1.jar:21.4.1]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:32) ~[teku-infrastructure-async-21.4.1.jar:21.4.1]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:142) ~[teku-infrastructure-async-21.4.1.jar:21.4.1]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$exceptionallyCompose$26(SafeFuture.java:362) ~[teku-infrastructure-async-21.4.1.jar:21.4.1]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147) ~[teku-infrastructure-async-21.4.1.jar:21.4.1]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
	at org.web3j.utils.Async.lambda$run$1(Async.java:38) ~[core-4.6.2.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: tech.pegasys.teku.service.serviceutils.FatalServiceFailureException: java.util.concurrent.CompletionException: java.util.NoSuchElementException: No value present
	at tech.pegasys.teku.pow.Eth1DepositManager.lambda$start$4(Eth1DepositManager.java:80) ~[teku-pow-21.4.1.jar:21.4.1]
	... 55 more
Caused by: java.util.concurrent.CompletionException: java.util.NoSuchElementException: No value present
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?]
	... 53 more
Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?]
	... 53 more
```

**Comment by remyroy** [comment]
This was with `Geth/v1.10.2-stable-97d11b01/windows-amd64/go1.16`
