### ISSUE TITLE
Altair: Invalid signatures for blocks and attestations after fork activates

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#3946]
### Description
We appear to generate invalid signatures once Altair activates for both blocks and attestations. Tested with minimal config and fork block  set to 8.

Blocks don't give as clear an error but one of the signatures is invalid:
```
2021-05-07 10:24:37.101 | forkchoice-async-0        | WARN  | AbstractBlockProcessor         | State Transition error
tech.pegasys.teku.spec.logic.common.statetransition.exceptions.BlockProcessingException: null
	at tech.pegasys.teku.spec.logic.common.block.AbstractBlockProcessor.processAndValidateBlock(AbstractBlockProcessor.java:138) ~[classes/:?]
	at tech.pegasys.teku.spec.logic.common.util.ForkChoiceUtil.onBlock(ForkChoiceUtil.java:325) ~[classes/:?]
	at tech.pegasys.teku.spec.Spec.onBlock(Spec.java:365) ~[classes/:?]
	at tech.pegasys.teku.statetransition.forkchoice.ForkChoice.lambda$onBlock$4(ForkChoice.java:190) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.async.eventthread.AsyncRunnerEventThread.recordEventThreadIdAndExecute(AsyncRunnerEventThread.java:109) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.async.eventthread.AsyncRunnerEventThread.lambda$doExecute$1(AsyncRunnerEventThread.java:92) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:81) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$2(AsyncRunner.java:38) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:73) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:119) ~[classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

Attestations report:
```
2021-05-07 10:24:39.097 | ValidatorApiChannel-0     | ERROR | teku-validator-log             | Validator   *** Produced invalid attestation for slot 8. Invalid reason: Signature is invalid
2021-05-07 10:24:39.098 | validator-async-2         | INFO  | teku-validator-log             | Validator   *** Published attestation        Count: 8, Slot: 8, Root: d54604..744a
2021-05-07 10:24:39.100 | ValidatorApiChannel-0     | ERROR | teku-validator-log             | Validator   *** Produced invalid attestation for slot 8. Invalid reason: Signature is invalid
2021-05-07 10:24:39.102 | ValidatorApiChannel-0     | ERROR | teku-validator-log             | Validator   *** Produced invalid attestation for slot 8. Invalid reason: Signature is invalid
2021-05-07 10:24:39.105 | ValidatorApiChannel-0     | ERROR | teku-validator-log             | Validator   *** Produced invalid attestation for slot 8. Invalid reason: Signature is invalid
2021-05-07 10:24:39.107 | ValidatorApiChannel-0     | ERROR | teku-validator-log             | Validator   *** Produced invalid attestation for slot 8. Invalid reason: Signature is invalid
2021-05-07 10:24:39.110 | ValidatorApiChannel-0     | ERROR | teku-validator-log             | Validator   *** Produced invalid attestation for slot 8. Invalid reason: Signature is invalid
2021-05-07 10:24:39.112 | ValidatorApiChannel-0     | ERROR | teku-validator-log             | Validator   *** Produced invalid attestation for slot 8. Invalid reason: Signature is invalid
2021-05-07 10:24:39.115 | ValidatorApiChannel-0     | ERROR | teku-validator-log             | Validator   *** Produced invalid attestation for slot 8. Invalid reason: Signature is invalid
```

The problem continues beyond the fork activation slot.

**Comment by ajsutton** [comment]
This will almost certainly be that `ForkProvider` isn't getting the new fork.  It's getting the fork from the best state but really wants to get the next fork to activate if any (that includes the previous fork which is the currently active one).
