### ISSUE TITLE
invalid signature during block production on altair minimal network

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#3950]
scenario: started a minimal network of altair to do some testing for APIs, and noticed this a couple of times in my logs:
```
2021-05-07 13:30:51.025+10:00 | validator-async-8 | ERROR | teku-validator-log | ^[[31mValidator   *** Failed to produce block  Slot: 832 Validator: ae00fc3^[[0m
tech.pegasys.teku.spec.logic.common.statetransition.exceptions.StateTransitionException: tech.pegasys.teku.spec.logic.common.statetransition.exceptions.BlockProcessingException: Invalid sync committee signature in SyncAggregate{sync_committee_bits=SszBitvector{size=32, 11111111111111111111111111111111}, sync_committee_signature=SszByteVector{0x8a68f4032257182582d02afe12569a461296d06dc85115d504ac2929e6b277405f3bbac0e730274eadca97747d7ef899030f7f9033efb746dae154c51c1a9a4f088438db8ab15fcf03620d301fc5d21c0ca2af08e8a7d9fafe9864ec8640b318}}
        at tech.pegasys.teku.spec.logic.common.util.BlockProposalUtil.createNewUnsignedBlock(BlockProposalUtil.java:80) ~[classes/:?]
        at tech.pegasys.teku.spec.Spec.createNewUnsignedBlock(Spec.java:414) ~[classes/:?]
        at tech.pegasys.teku.validator.coordinator.BlockFactory.createUnsignedBlock(BlockFactory.java:122) ~[classes/:?]
        at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.createBlock(ValidatorApiHandler.java:309) ~[classes/:?]
        at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.lambda$createUnsignedBlock$12(ValidatorApiHandler.java:292) ~[classes/:?]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$thenApplyChecked$29(SafeFuture.java:415) ~[classes/:?]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235) ~[?:?]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.thenCompose(SafeFuture.java:463) ~[classes/:?]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.thenApplyChecked(SafeFuture.java:412) ~[classes/:?]
        at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.lambda$createUnsignedBlock$13(ValidatorApiHandler.java:290) ~[classes/:?]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
        at tech.pegasys.teku.dataproviders.generators.CachingTaskQueue.lambda$completePendingTask$9(CachingTaskQueue.java:204) ~[classes/:?]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.fromRunnable(SafeFuture.java:154) ~[classes/:?]
        at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$0(AsyncRunner.java:23) ~[classes/:?]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:73) ~[classes/:?]
        at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:119) ~[classes/:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: tech.pegasys.teku.spec.logic.common.statetransition.exceptions.BlockProcessingException: Invalid sync committee signature in SyncAggregate{sync_committee_bits=SszBitvector{size=32, 11111111111111111111111111111111}, sync_committee_signature=SszByteVector{0x8a68f4032257182582d02afe12569a461296d06dc85115d504ac2929e6b277405f3bbac0e730274eadca97747d7ef899030f7f9033efb746dae154c51c1a9a4f088438db8ab15fcf03620d301fc5d21c0ca2af08e8a7d9fafe9864ec8640b318}}
        at tech.pegasys.teku.spec.logic.versions.altair.block.BlockProcessorAltair.processSyncCommittee(BlockProcessorAltair.java:223) ~[classes/:?]
        at tech.pegasys.teku.spec.logic.versions.altair.block.BlockProcessorAltair.processBlock(BlockProcessorAltair.java:99) ~[classes/:?]
        at tech.pegasys.teku.spec.logic.common.block.BlockProcessor.lambda$processBlock$0(BlockProcessor.java:78) ~[classes/:?]
        at tech.pegasys.teku.spec.datastructures.state.beaconstate.common.AbstractBeaconState.updated(AbstractBeaconState.java:59) ~[classes/:?]
        at tech.pegasys.teku.spec.logic.common.block.BlockProcessor.processBlock(BlockProcessor.java:78) ~[classes/:?]
        at tech.pegasys.teku.spec.logic.common.block.BlockProcessor.processBlock(BlockProcessor.java:72) ~[classes/:?]
        at tech.pegasys.teku.spec.logic.common.util.BlockProposalUtil.createNewUnsignedBlock(BlockProposalUtil.java:73) ~[classes/:?]
        ... 21 more
```

on master at `872557e8d1cc77014263604d3839fcb483bdc40e`

**Comment by rolfyone** [comment]
interestingly, epoch transition of 104,112, 120, 128 have all had this (first block of new epochs)

**Comment by ajsutton** [comment]
I may be missing something but this looks like a bug in the spec.  Each block includes a `SyncAggregate` created from the `SyncCommitteeContribution` from the previous slot.  It can't include the ones from the same slot as the block because the block is published first, followed by the signatures and then the contributions, same attestations come after blocks.

In the block processing from the spec (https://github.com/ethereum/eth2.0-specs/blob/dev/specs/altair/beacon-chain.md#sync-committee-processing) it gets the public keys to verify the sync committee from `state.current_sync_committee`.  Since the state has already had empty slots processed, for the first slot in a new sync committee period the `SyncAggregate` will actually be from the previous sync committee and so this method will select the wrong public keys to use.  There isn't a way to get the previous sync committee to correctly verify the `SyncAggregate`.

**Comment by ajsutton** [comment]
I can't see what I'm missing so have logged https://github.com/ethereum/eth2.0-specs/issues/2397 so someone smarter can point it out to me. :)
