### ISSUE TITLE
Handle SyncCommitteeContribution gossip with no attestation bits set

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#4168]
```
{"timestamp":"2021-07-17T01:20:08,580","level":"WARN","thread":"p2p-async-7","class":"Eth2TopicHandler","message":"Encountered exception while processing message for topic /eth2/0112ad5a/sync_committee_contribution_and_proof/ssz_snappy","throwable":" java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: No public keys supplied for verify
at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:683)
at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2164)
at tech.pegasys.teku.infrastructure.async.SafeFuture.thenApply(SafeFuture.java:408)
at tech.pegasys.teku.statetransition.synccommittee.SignedContributionAndProofValidator.validate(SignedContributionAndProofValidator.java:107)
at tech.pegasys.teku.statetransition.synccommittee.SyncCommitteeContributionPool.add(SyncCommitteeContributionPool.java:60)
at tech.pegasys.teku.networking.eth2.gossip.topics.topichandlers.Eth2TopicHandler.lambda$handleMessage$2(Eth2TopicHandler.java:95)
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:73)
at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:119)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)\nCaused by: java.lang.IllegalArgumentException: No public keys supplied for verify
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
at tech.pegasys.teku.spec.logic.common.statetransition.blockvalidator.BatchSignatureVerifier.verify(BatchSignatureVerifier.java:63)
at tech.pegasys.teku.statetransition.synccommittee.SignedContributionAndProofValidator.validateWithState(SignedContributionAndProofValidator.java:231)
at tech.pegasys.teku.statetransition.synccommittee.SignedContributionAndProofValidator.lambda$validate$0(SignedContributionAndProofValidator.java:113)
at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)\n\t... 11 more\n"}
```

**Comment by ajsutton** [comment]
Logged https://github.com/ethereum/eth2.0-specs/issues/2527 to get clarification on what the expected behaviour is here.  In the mean time will update Teku to cleanly reject rather than throwing an exception.

**Comment by ajsutton** [comment]
https://github.com/ethereum/eth2.0-specs/pull/2528#event-5052761982 clarifies that rejecting these messages is correct which is what Teku does cleanly now.
