### ISSUE TITLE
validator client threw illegal Argument exception handling sync committee aggregation

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#4382]
on pyrmont nodes, we had a sync committee aggregate fail, it's possible that there was just nothing to aggregate and it needs to be handled silently rather than raising an exception, but we should investigate this stack trace further

```
java.lang.IllegalArgumentException: Invalid params response from Beacon Node API (url = http://127.0.0.1:5051/eth/v1/validator/sync_committee_contribution?beacon_block_root=0x396bec36c852e3bfdaeb768d895ed4d1db70b7fb6e78b096384afac5233a32e3&slot=2176379&subcommittee_index=3, response = {"status":400,"message":"Not found"})
	at tech.pegasys.teku.validator.remote.apiclient.ResponseHandler.defaultBadRequestHandler(ResponseHandler.java:93)
	at tech.pegasys.teku.validator.remote.apiclient.ResponseHandler.handleResponse(ResponseHandler.java:64)
	at tech.pegasys.teku.validator.remote.apiclient.OkHttpValidatorRestApiClient.executeCall(OkHttpValidatorRestApiClient.java:393)
	at tech.pegasys.teku.validator.remote.apiclient.OkHttpValidatorRestApiClient.get(OkHttpValidatorRestApiClient.java:342)
	at tech.pegasys.teku.validator.remote.apiclient.OkHttpValidatorRestApiClient.createSyncCommitteeContribution(OkHttpValidatorRestApiClient.java:308)
	at tech.pegasys.teku.validator.remote.RemoteValidatorApiHandler.lambda$createSyncCommitteeContribution$23(RemoteValidatorApiHandler.java:355)
	at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:81)
	at tech.pegasys.teku.validator.remote.RemoteValidatorApiHandler.sendRequest(RemoteValidatorApiHandler.java:431)
	at tech.pegasys.teku.validator.remote.RemoteValidatorApiHandler.lambda$sendRequest$34(RemoteValidatorApiHandler.java:426)
	at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:73)
	at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:119)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by rolfyone** [comment]
Bad request will basically happen if params fail to parse, or if we're not in altair yet. all of these I'd be happy with the exception, so will close ticket.
