### ISSUE TITLE
Failed to export slashing protection data.

### ISSUE THREAD

**Issue by chrishobcroft** [Consensys-Incorporated/teku#4383]
### Description

When I try to export slashing-protection, the process fails, reporting:

```
java.nio.file.FileSystemException: /home/ubuntu/slashing-interchange-format-minimal.json.tmp -> /home/ubuntu/slashing-interchange-format-minimal.json: Is a directory
```

### Acceptance Criteria

When running the following command, the process successfully exports slashing protection data:
```
/usr/local/bin/teku/bin/teku slashing-protection export --data-base-path=/var/lib/teku --to=/home/ubuntu/slashing-interchange-format-minimal.json
```

### Steps to Reproduce (Bug)
1. Have at least 1 active Validator running on teku
2. Run this command:
```
/usr/local/bin/teku/bin/teku slashing-protection export --data-base-path=/var/lib/teku --to=/home/ubuntu/slashing-interchange-format-minimal.json
```
3. Observe this:
```
Reading slashing protection data from: /var/lib/teku/validator/slashprotection
Exporting 92c163e03d2d325f71d1374a3499bdf4b99b06139f3b538109e5aad2313cfddfcaaae10c72238db16af57784d4cafea3
Writing slashing protection data to: /home/ubuntu/slashing-interchange-format-minimal.json
Failed to export slashing protection data.
java.nio.file.FileSystemException: /home/ubuntu/slashing-interchange-format-minimal.json.tmp -> /home/ubuntu/slashing-interchange-format-minimal.json: Is a directory
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:417)
	at java.base/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:267)
	at java.base/java.nio.file.Files.move(Files.java:1422)
	at tech.pegasys.teku.infrastructure.io.SyncDataAccessor.atomicSyncedWrite(SyncDataAccessor.java:122)
	at tech.pegasys.teku.infrastructure.io.SyncDataAccessor.syncedWrite(SyncDataAccessor.java:96)
	at tech.pegasys.teku.data.SlashingProtectionExporter.saveToFile(SlashingProtectionExporter.java:94)
	at tech.pegasys.teku.cli.slashingprotection.ExportCommand.run(ExportCommand.java:68)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at tech.pegasys.teku.cli.BeaconNodeCommand.parse(BeaconNodeCommand.java:233)
	at tech.pegasys.teku.Teku.main(Teku.java:32)
```

### Expected behavior:

I expect the file to write correctly.

### Actual behavior

The file does not write correctly.

### Frequency

100% of the time

### Versions

* Software version: `teku/v21.9.1/linux-x86_64/-ubuntu-openjdk64bitservervm-java-11`
* Java version:
```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)
```
* OS Name & Version:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by chrishobcroft** [comment]
Attempted the same with previous versions:

`21.8.2` - success
`21.9.0` - fail
