### ISSUE TITLE
Syncing issue with LevelDB tree archive (Windows)

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#4529]
Teku version: 21.10.1
OS: Windows 10

While syncing mainnet with the experimental `Xdata-storage-create-db-version: "leveldb-tree"` setting, everything looked great until slot 505,000-ish

After that, the console began to look like this:

```
16:01:59.578 INFO  - Syncing     *** Target slot: 2369708, Head slot: 504929, Remaining slots: 1864779, Connected peers: 28
16:02:12.761 INFO  - Syncing     *** Target slot: 2369709, Head slot: 505185, Remaining slots: 1864524, Connected peers: 28
16:02:23.360 INFO  - Syncing     *** Target slot: 2369710, Head slot: 505503, Remaining slots: 1864207, Connected peers: 30
16:02:35.360 INFO  - Syncing     *** Target slot: 2369711, Head slot: 505791, Remaining slots: 1863920, Connected peers: 29
16:02:47.316 INFO  - Syncing     *** Target slot: 2369712, Head slot: 505791, Remaining slots: 1863921, Connected peers: 27
16:02:59.316 INFO  - Syncing     *** Target slot: 2369713, Head slot: 505791, Remaining slots: 1863922, Connected peers: 24
16:03:11.316 INFO  - Syncing     *** Target slot: 2369714, Head slot: 505791, Remaining slots: 1863923, Connected peers: 30
16:03:23.316 INFO  - Syncing     *** Target slot: 2369715, Head slot: 505791, Remaining slots: 1863924, Connected peers: 28
16:03:35.317 INFO  - Syncing     *** Target slot: 2369716, Head slot: 505791, Remaining slots: 1863925, Connected peers: 22
16:03:47.316 INFO  - Syncing     *** Target slot: 2369717, Head slot: 505791, Remaining slots: 1863926, Connected peers: 16
16:03:59.317 INFO  - Syncing     *** Target slot: 2369718, Head slot: 505791, Remaining slots: 1863927, Connected peers: 16
16:04:11.317 INFO  - Syncing     *** Target slot: 2369719, Head slot: 505791, Remaining slots: 1863928, Connected peers: 6
16:04:23.317 INFO  - Syncing     *** Target slot: 2369720, Head slot: 505791, Remaining slots: 1863929, Connected peers: 3
16:04:35.316 INFO  - Syncing     *** Target slot: 2369721, Head slot: 505791, Remaining slots: 1863930, Connected peers: 9
16:04:47.316 INFO  - Syncing     *** Target slot: 2369722, Head slot: 505791, Remaining slots: 1863931, Connected peers: 5
16:04:59.317 INFO  - Syncing     *** Target slot: 2369723, Head slot: 505791, Remaining slots: 1863932, Connected peers: 9
16:05:11.317 INFO  - Syncing     *** Target slot: 2369724, Head slot: 505791, Remaining slots: 1863933, Connected peers: 2
16:05:14.047 INFO  - Syncing completed
16:05:17.770 INFO  - Syncing started
16:05:23.317 INFO  - Syncing     *** Target slot: 2369725, Head slot: 505791, Remaining slots: 1863934, Connected peers: 3
16:05:33.961 INFO  - Syncing completed
16:05:39.316 INFO  - Slot Event  *** Slot: 2369726, Block:    ... empty, Epoch: 74053, Finalized checkpoint: 15803, Finalized root: 33f18b..973d, Peers: 1
16:05:47.972 INFO  - Syncing started
16:05:48.316 INFO  - Syncing     *** Target slot: 2369727, Head slot: 505791, Remaining slots: 1863936, Connected peers: 4
16:05:57.155 INFO  - Syncing completed
16:05:59.316 INFO  - Epoch Event *** Epoch: 74054, Justified checkpoint: 15804, Finalized checkpoint: 15803, Finalized root: 33f18b..973d
16:06:03.316 INFO  - Slot Event  *** Slot: 2369728, Block:    ... empty, Epoch: 74054, Finalized checkpoint: 15803, Finalized root: 33f18b..973d, Peers: 1
16:06:15.316 INFO  - Slot Event  *** Slot: 2369729, Block:    ... empty, Epoch: 74054, Finalized checkpoint: 15803, Finalized root: 33f18b..973d, Peers: 1
16:06:18.011 INFO  - Syncing started
16:06:23.316 INFO  - Syncing     *** Target slot: 2369730, Head slot: 505791, Remaining slots: 1863939, Connected peers: 3
16:06:32.717 INFO  - Syncing completed
16:06:38.656 INFO  - Syncing started
16:06:38.816 INFO  - Syncing     *** Target slot: 2369731, Head slot: 505791, Remaining slots: 1863940, Connected peers: 5
16:06:47.317 INFO  - Syncing     *** Target slot: 2369732, Head slot: 505791, Remaining slots: 1863941, Connected peers: 4
16:06:50.543 INFO  - Syncing completed
16:07:03.317 INFO  - Slot Event  *** Slot: 2369733, Block:    ... empty, Epoch: 74054, Finalized checkpoint: 15803, Finalized root: 33f18b..973d, Peers: 0
16:07:15.317 INFO  - Slot Event  *** Slot: 2369734, Block:    ... empty, Epoch: 74054, Finalized checkpoint: 15803, Finalized root: 33f18b..973d, Peers: 0
16:07:27.316 INFO  - Slot Event  *** Slot: 2369735, Block:    ... empty, Epoch: 74054, Finalized checkpoint: 15803, Finalized root: 33f18b..973d, Peers: 0
```

And the logs began to look like this:

```
2021-10-26 16:01:59.578+01:00 | TimeTickChannel-0 | INFO  | teku-event-log | Syncing     *** Target slot: 2369708, Head slot: 504929, Remaining slots: 1864779, Connected peers: 28
2021-10-26 16:02:12.761+01:00 | TimeTickChannel-0 | INFO  | teku-event-log | Syncing     *** Target slot: 2369709, Head slot: 505185, Remaining slots: 1864524, Connected peers: 28
2021-10-26 16:02:23.258+01:00 | forkchoice-async-0 | ERROR | BlockImporter | Internal error while importing block: 1f15d1..18bf (505505)
java.util.concurrent.CompletionException: java.lang.RuntimeException: org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: E:\teku\data\beacon\db\264850.sst: Could not create random access file.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:704) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:145) ~[teku-infrastructure-async-21.10.1.jar:21.10.1]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateToAsync$15(SafeFuture.java:271) ~[teku-infrastructure-async-21.10.1.jar:21.10.1]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:81) ~[teku-infrastructure-async-21.10.1.jar:21.10.1]
	at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$2(AsyncRunner.java:38) ~[teku-infrastructure-async-21.10.1.jar:21.10.1]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:73) ~[teku-infrastructure-async-21.10.1.jar:21.10.1]
	at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:119) ~[teku-infrastructure-async-21.10.1.jar:21.10.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.RuntimeException: org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: E:\teku\data\beacon\db\264850.sst: Could not create random access file.
	at org.fusesource.leveldbjni.internal.JniDBIterator.seek(JniDBIterator.java:68) ~[leveldbjni-all-1.8.jar:1.8]
	at tech.pegasys.teku.storage.server.leveldb.LevelDbInstance.streamRaw(LevelDbInstance.java:253) ~[teku-storage-21.10.1.jar:21.10.1]
	at tech.pegasys.teku.storage.server.leveldb.LevelDbInstance.stream(LevelDbInstance.java:240) ~[teku-storage-21.10.1.jar:21.10.1]
	at tech.pegasys.teku.storage.server.leveldb.LevelDbInstance.stream(LevelDbInstance.java:218) ~[teku-storage-21.10.1.jar:21.10.1]
	at tech.pegasys.teku.storage.server.kvstore.dataaccess.V4HotKvStoreDao.getStateRootsBeforeSlot(V4HotKvStoreDao.java:113) ~[teku-storage-21.10.1.jar:21.10.1]
	at tech.pegasys.teku.storage.server.kvstore.KvStoreDatabase.lambda$doUpdate$8(KvStoreDatabase.java:587) ~[teku-storage-21.10.1.jar:21.10.1]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at tech.pegasys.teku.storage.server.kvstore.KvStoreDatabase.doUpdate(KvStoreDatabase.java:582) ~[teku-storage-21.10.1.jar:21.10.1]
	at tech.pegasys.teku.storage.server.kvstore.KvStoreDatabase.update(KvStoreDatabase.java:259) ~[teku-storage-21.10.1.jar:21.10.1]
	at tech.pegasys.teku.storage.server.ChainStorage.lambda$onStorageUpdate$0(ChainStorage.java:91) ~[teku-storage-21.10.1.jar:21.10.1]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.fromRunnable(SafeFuture.java:154) ~[teku-infrastructure-async-21.10.1.jar:21.10.1]
	at tech.pegasys.teku.storage.server.ChainStorage.onStorageUpdate(ChainStorage.java:89) ~[teku-storage-21.10.1.jar:21.10.1]
	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:74) ~[teku-infrastructure-events-21.10.1.jar:21.10.1]
	at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.deliverToWithResponse(DirectEventDeliverer.java:67) ~[teku-infrastructure-events-21.10.1.jar:21.10.1]
	at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer.lambda$deliverToWithResponse$1(AsyncEventDeliverer.java:75) ~[teku-infrastructure-events-21.10.1.jar:21.10.1]
	at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:117) ~[teku-infrastructure-events-21.10.1.jar:21.10.1]
	at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:109) ~[teku-infrastructure-events-21.10.1.jar:21.10.1]
	... 3 more
Caused by: org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: E:\teku\data\beacon\db\264850.sst: Could not create random access file.
	at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200) ~[leveldbjni-all-1.8.jar:1.8]
	at org.fusesource.leveldbjni.internal.NativeIterator.checkStatus(NativeIterator.java:121) ~[leveldbjni-all-1.8.jar:1.8]
	at org.fusesource.leveldbjni.internal.NativeIterator.seek(NativeIterator.java:151) ~[leveldbjni-all-1.8.jar:1.8]
	at org.fusesource.leveldbjni.internal.NativeIterator.seek(NativeIterator.java:145) ~[leveldbjni-all-1.8.jar:1.8]
	at org.fusesource.leveldbjni.internal.NativeIterator.seek(NativeIterator.java:138) ~[leveldbjni-all-1.8.jar:1.8]
	at org.fusesource.leveldbjni.internal.JniDBIterator.seek(JniDBIterator.java:63) ~[leveldbjni-all-1.8.jar:1.8]
	at tech.pegasys.teku.storage.server.leveldb.LevelDbInstance.streamRaw(LevelDbInstance.java:253) ~[teku-storage-21.10.1.jar:21.10.1]
	at tech.pegasys.teku.storage.server.leveldb.LevelDbInstance.stream(LevelDbInstance.java:240) ~[teku-storage-21.10.1.jar:21.10.1]
	at tech.pegasys.teku.storage.server.leveldb.LevelDbInstance.stream(LevelDbInstance.java:218) ~[teku-storage-21.10.1.jar:21.10.1]
	at tech.pegasys.teku.storage.server.kvstore.dataaccess.V4HotKvStoreDao.getStateRootsBeforeSlot(V4HotKvStoreDao.java:113) ~[teku-storage-21.10.1.jar:21.10.1]
	at tech.pegasys.teku.storage.server.kvstore.KvStoreDatabase.lambda$doUpdate$8(KvStoreDatabase.java:587) ~[teku-storage-21.10.1.jar:21.10.1]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at tech.pegasys.teku.storage.server.kvstore.KvStoreDatabase.doUpdate(KvStoreDatabase.java:582) ~[teku-storage-21.10.1.jar:21.10.1]
	at tech.pegasys.teku.storage.server.kvstore.KvStoreDatabase.update(KvStoreDatabase.java:259) ~[teku-storage-21.10.1.jar:21.10.1]
	at tech.pegasys.teku.storage.server.ChainStorage.lambda$onStorageUpdate$0(ChainStorage.java:91) ~[teku-storage-21.10.1.jar:21.10.1]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.fromRunnable(SafeFuture.java:154) ~[teku-infrastructure-async-21.10.1.jar:21.10.1]
	at tech.pegasys.teku.storage.server.ChainStorage.onStorageUpdate(ChainStorage.java:89) ~[teku-storage-21.10.1.jar:21.10.1]
	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:74) ~[teku-infrastructure-events-21.10.1.jar:21.10.1]
	at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.deliverToWithResponse(DirectEventDeliverer.java:67) ~[teku-infrastructure-events-21.10.1.jar:21.10.1]
	at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer.lambda$deliverToWithResponse$1(AsyncEventDeliverer.java:75) ~[teku-infrastructure-events-21.10.1.jar:21.10.1]
	at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:117) ~[teku-infrastructure-events-21.10.1.jar:21.10.1]
	at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:109) ~[teku-infrastructure-events-21.10.1.jar:21.10.1]
	... 3 more
2021-10-26 16:02:23.360+01:00 | TimeTickChannel-0 | INFO  | teku-event-log | Syncing     *** Target slot: 2369710, Head slot: 505503, Remaining slots: 1864207, Connected peers: 30
2021-10-26 16:02:34.864+01:00 | forkchoice-async-0 | ERROR | BlockImporter | Internal error while importing block: 786972..3454 (505792)
java.util.concurrent.CompletionException: java.lang.RuntimeException: org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: E:\teku\data\beacon\db\181959.sst: Could not create random access file.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
```

And so on for another 5MB until I noticed 90 mins later.

There's plenty of space on the `E:` drive (679GB free), so that's not the issue. Conceivably there is a disk error. I've now started again with a fresh DB (also on the `E:` drive) and will see how it goes.

**Comment by benjaminion** [comment]
Update: second sync also failed (but later), with the same error. Restarting Teku seems to allow progress to be made again.

The root cause is likely the very old version of LevelDB we are using. This is an [old issue](https://gitter.im/ethereum/ethereumj?at=56c1a50b37437b67560957ab)!

Work on building a newer LevelDB version for Windows is being tracked [here](https://github.com/ConsenSys/leveldbjni-native/issues/3).

**Comment by benjaminion** [comment]
Closing - running a tree archive on Windows seems to be a minority sport, and the root cause looks to be covered by the other issue in any case.
