### ISSUE TITLE
Failed to open database when downgrading beacon from 21.11.1 to 21.10.0

### ISSUE THREAD

**Issue by jmcruz1983** [Consensys-Incorporated/teku#4699]
```
2021-11-24 10:53:15,150 main INFO Configuring logging for destination: console
2021-11-24 10:53:15,153 main INFO Logging includes events: true
2021-11-24 10:53:15,153 main INFO Logging includes validator duties: true
2021-11-24 10:53:15,154 main INFO Logging includes color: true
2021-11-24 10:53:15,162 main INFO Include P2P warnings set to: false
10:53:15.164 INFO  - Teku version: teku/v21.10.0/linux-x86_64/-eclipsefoundation-openjdk64bitservervm-java-16
10:53:15.168 INFO  - This software is licensed under the Apache License, Version 2.0 (the "License"); you may not use this software except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
10:53:15.478 INFO  - Loading 0 validator keys...
10:53:15.482 INFO  - Loaded 0 Validators: 
10:53:15.510 INFO  - Using default implementation for ThreadExecutor
10:53:15.512 INFO  - Job execution threads will use class loader of thread: main
10:53:15.538 INFO  - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
10:53:15.538 INFO  - Quartz Scheduler v.2.3.2 created.
10:53:15.539 INFO  - RAMJobStore initialized.
10:53:15.540 INFO  - Scheduler meta-data: Quartz Scheduler (v2.3.2) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.
10:53:15.540 INFO  - Quartz scheduler 'DefaultQuartzScheduler' initialized from default resource file in Quartz package: 'quartz.properties'
10:53:15.540 INFO  - Quartz scheduler version: 2.3.2
10:53:15.586 INFO  - Storing beacon chain data in: /data/beacon
10:53:15.594 INFO  - Starting metrics http service on 0.0.0.0:8008
10:53:15.737 INFO  - Metrics service started and listening on 8008:8008
10:53:15.739 INFO  - Beacon data directory set to: /data/beacon
10:53:15.825 FATAL - Failed to open database
tech.pegasys.teku.storage.server.DatabaseStorageException: Failed to open database
    at tech.pegasys.teku.storage.server.DatabaseStorageException.unrecoverable(DatabaseStorageException.java:31) ~[teku-storage-21.10.0.jar:21.10.0[]
    at tech.pegasys.teku.storage.server.leveldb.LevelDbInstanceFactory.create(LevelDbInstanceFactory.java:47) ~[teku-storage-21.10.0.jar:21.10.0[]
    at tech.pegasys.teku.storage.server.leveldb.LevelDbDatabaseFactory.createLevelDbV2(LevelDbDatabaseFactory.java:76) ~[teku-storage-21.10.0.jar:21.10.0[]
    at tech.pegasys.teku.storage.server.VersionedDatabaseFactory.createLevelDbV2Database(VersionedDatabaseFactory.java:266) ~[teku-storage-21.10.0.jar:21.10.0[]
    at tech.pegasys.teku.storage.server.VersionedDatabaseFactory.createDatabase(VersionedDatabaseFactory.java:159) ~[teku-storage-21.10.0.jar:21.10.0[]
    at tech.pegasys.teku.services.chainstorage.StorageService.lambda$doStart$0(StorageService.java:61) ~[teku-services-chainstorage-21.10.0.jar:21.10.0[]
    at tech.pegasys.teku.infrastructure.async.SafeFuture.fromRunnable(SafeFuture.java:154) ~[teku-infrastructure-async-21.10.0.jar:21.10.0[]
    at tech.pegasys.teku.services.chainstorage.StorageService.doStart(StorageService.java:48) ~[teku-services-chainstorage-21.10.0.jar:21.10.0[]
    at tech.pegasys.teku.service.serviceutils.Service.start(Service.java:35) ~[teku-services-serviceutils-21.10.0.jar:21.10.0[]
    at tech.pegasys.teku.services.ServiceController.doStart(ServiceController.java:29) ~[teku-21.10.0.jar:21.10.0[]
    at tech.pegasys.teku.service.serviceutils.Service.start(Service.java:35) ~[teku-services-serviceutils-21.10.0.jar:21.10.0[]
    at tech.pegasys.teku.AbstractNode.start(AbstractNode.java:96) ~[teku-21.10.0.jar:21.10.0[]
    at tech.pegasys.teku.Teku.start(Teku.java:50) ~[teku-21.10.0.jar:21.10.0[]
    at tech.pegasys.teku.cli.BeaconNodeCommand.call(BeaconNodeCommand.java:284) [teku-21.10.0.jar:21.10.0[]
    at tech.pegasys.teku.cli.BeaconNodeCommand.call(BeaconNodeCommand.java:72) [teku-21.10.0.jar:21.10.0[]
    at picocli.CommandLine.executeUserObject(CommandLine.java:1933) [picocli-4.4.0.jar:4.4.0[]
    at picocli.CommandLine.access$1100(CommandLine.java:145) [picocli-4.4.0.jar:4.4.0[]
    at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332) [picocli-4.4.0.jar:4.4.0[]
    at picocli.CommandLine$RunLast.handle(CommandLine.java:2326) [picocli-4.4.0.jar:4.4.0[]
    at picocli.CommandLine$RunLast.handle(CommandLine.java:2291) [picocli-4.4.0.jar:4.4.0[]
    at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159) [picocli-4.4.0.jar:4.4.0[]
    at picocli.CommandLine.execute(CommandLine.java:2058) [picocli-4.4.0.jar:4.4.0[]
    at tech.pegasys.teku.cli.BeaconNodeCommand.parse(BeaconNodeCommand.java:233) [teku-21.10.0.jar:21.10.0[]
    at tech.pegasys.teku.Teku.main(Teku.java:32) [teku-21.10.0.jar:21.10.0[]
Caused by: org.fusesource.leveldbjni.internal.NativeDB$DBException: Corruption: 21 missing files; e.g.: /data/beacon/db/1948020.sst
    at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200) ~[leveldbjni-all-1.8.jar:1.8[]
    at org.fusesource.leveldbjni.internal.NativeDB.open(NativeDB.java:218) ~[leveldbjni-all-1.8.jar:1.8[]
    at org.fusesource.leveldbjni.JniDBFactory.open(JniDBFactory.java:168) ~[leveldbjni-all-1.8.jar:1.8[]
    at tech.pegasys.teku.storage.server.leveldb.LevelDbInstanceFactory.create(LevelDbInstanceFactory.java:44) ~[teku-storage-21.10.0.jar:21.10.0[]
    ... 22 more
Failed to open database
To display full help:
teku [COMMAND[] --help
```

**Comment by benjaminion** [comment]
Apologies - this is due to an upgrade of LevelDB that is not backward compatible. We were aware of this but failed to announce it in the release notes. We'll take care to note any future incompatibilities in the release notes.
