### ISSUE TITLE
[Merge] Parse PayloadId as QUANTITY

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#4700]
### Description
Need to check against the JSON-RPC spec but I believe QUANTITY values, which includes the returned payloadId are serialised with no leading zeros.  So payloadId of 1 would be 0x1 which causes teku to throw:

```
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Invalid remote response: Invalid odd-length hex binary representation (through reference chain: tech.pegasys.teku.ethereum.executionlayer.client.Web3JExecutionE
ngineClient$ForkChoiceUpdatedWeb3jResponse["result"]->tech.pegasys.teku.ethereum.executionlayer.client.schema.ForkChoiceUpdatedResult["payloadId"])
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2137) ~[?:?]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147) ~[teku-infrastructure-async-develop.jar:21.11.0+64-gdf02342]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2152) ~[?:?]
        at org.web3j.utils.Async.lambda$run$1(Async.java:40) ~[core-4.8.7.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.IllegalArgumentException: Invalid remote response: Invalid odd-length hex binary representation (through reference chain: tech.pegasys.teku.ethereum.executionlayer.client.Web3JExecutionEngineClient$ForkChoiceUpdatedWe
b3jResponse["result"]->tech.pegasys.teku.ethereum.executionlayer.client.schema.ForkChoiceUpdatedResult["payloadId"])
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:219) ~[guava-30.1.1-jre.jar:?]
        at tech.pegasys.teku.ethereum.executionlayer.ExecutionEngineChannelImpl.unwrapResponseOrThrow(ExecutionEngineChannelImpl.java:59) ~[teku-ethereum-executionlayer-develop.jar:21.11.0+64-gdf02342]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642) ~[?:?]
        ... 12 more
```

**Comment by ajsutton** [comment]
Actually PayloadID is DATA type so must always have the full 8 bytes.  I think this one's a besu bug. Confirming before closing this.

**Comment by tbenr** [comment]
I currently cant find the source anymore but I remember is should be the most(less) significative 8bytes of a sha256 of the attributes. I'll put a link once i find the reference.

**Comment by ajsutton** [comment]
I believe that changed - EL clients are allowed to create the payloadId anyway they want to now (hence it being returned instead of independently calculated both sides).  Using the hash approach to create it is still an option for them, just not required.

It is clearly a `DATA` value in https://github.com/ethereum/execution-apis/blob/main/src/engine/specification.md#response-1 though.

**Comment by ajsutton** [comment]
Going to close this one based on that.
