### ISSUE TITLE
when attestation publishing fails, need to be careful about handling

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#5272]
test setup:
 BN (minimal, no keys)
 VC (minimal, N keys)

All duties from the VC go via BN clearly, but the BN has no peers to talk to...

in the VC output we get:
```
13:35:29.286 INFO  - Validator   *** Published attestation        Count: 4, Slot: 106, Root: 348bad601b71bb14d0bad12cb84534ace42033f45c8b026004c4a6edbe1ad1ff
13:35:29.287 ERROR - Validator   *** Failed to produce attestation  Slot: 106 Validator: ab0bdda, a5869ba, a8d4c7c, b8cd1ce java.lang.IllegalArgumentException: Invalid params response from Beacon Node API (url = http://127.0.0.1:5051/eth/v1/validator/attestation_data?slot=106&committee_index=0) (See log file for full stack trace)
13:35:33.008 INFO  - Validator   *** Published aggregate          Count: 1, Slot: 106, Root: 348bad601b71bb14d0bad12cb84534ace42033f45c8b026004c4a6edbe1ad1ff
13:35:33.009 ERROR - Validator   *** Failed to produce aggregate  Slot: 106 Validator: ab0bdda java.lang.IllegalArgumentException: Invalid params response from Beacon Node API (url = http://127.0.0.1:5051/eth/v1/validator/attestation_data?slot=106&committee_index=0) (See log file for full stack trace)
```

and in the BN log we get:
```
2022-04-01 13:35:41.283+10:00 | P2PService-event-thread-0 | ERROR | AttestationGossipManager | Failed to publish attestation for slot 108
java.util.concurrent.CompletionException: io.libp2p.pubsub.NoPeersForOutboundMessageException: No peers for message topics [/eth2/5267d9c6/beacon_attestation_9/ssz_snappy] found
at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:368) ~[?:?]
at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:377) ~[?:?]
at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1152) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) ~[?:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: io.libp2p.pubsub.NoPeersForOutboundMessageException: No peers for message topics [/eth2/5267d9c6/beacon_attestation_9/ssz_snappy] found
at io.libp2p.pubsub.gossip.GossipRouter.broadcastOutbound(GossipRouter.kt:370) ~[jvm-libp2p-minimal-0.8.9-RELEASE.jar:?]
at io.libp2p.pubsub.AbstractRouter$publish$1.invoke(AbstractRouter.kt:73) ~[jvm-libp2p-minimal-0.8.9-RELEASE.jar:?]
at io.libp2p.pubsub.AbstractRouter$publish$1.invoke(AbstractRouter.kt:40) ~[jvm-libp2p-minimal-0.8.9-RELEASE.jar:?]
at io.libp2p.etc.types.AsyncExtKt$submitAsync$1.get(AsyncExt.kt:51) ~[jvm-libp2p-minimal-0.8.9-RELEASE.jar:?]
at io.libp2p.etc.types.AsyncExtKt$submitAsync$1.get(AsyncExt.kt) ~[jvm-libp2p-minimal-0.8.9-RELEASE.jar:?]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
... 6 more
```

A couple of observations.
 - our setup is weird, having no peers kind of does defeat the point
 - the attestation published, it's just that there's no peers to gossip it to.

Desired behaviour:
 - when attestations/aggregates/ other duties are performed, and there's no peer connections on a subscription to notify, we currently raise an error with stacktrace, but it'd be better to be a warning with no stack trace. We still want to know that it occurred if its a real network, but the logs are very noisy currently because of the stack trace
- If you have no peers and because of that can't publish to the network, it's not really 'correct' to notify the rest api client that you couldn't publish - you published to all of your 0 peers. In this case we'd prefer a 200, although an invalid attestation etc. should continue to raise a 400.
 - locally, the produced attestations or other duties should still be considered candidates for blocks etc.

**Comment by ajsutton** [comment]
The errors logged are now much improved and I think we've found a decent balance of functionality here.
