### ISSUE TITLE
BellatrixMergeTransitionAT failures

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#5284]
### Description
Getting quite a few failures from `BellatrixMergeTransitionAcceptanceTest`. e.g:

https://app.circleci.com/pipelines/github/ConsenSys/teku/17338/workflows/6c74ad15-a7af-42ea-932c-1ffd41c3675d/jobs/117774

It looks like it managed to create invalid payloads which shouldn't be possible. There's also a bunch of cases where it failed to get a payloadId.

```
2022-04-03 21:36:02.014 ERROR - Validator   *** Failed to produce block  Slot: 23 Validator: b96ef61
tech.pegasys.teku.spec.logic.common.statetransition.exceptions.StateTransitionException: tech.pegasys.teku.spec.logic.common.statetransition.exceptions.BlockProcessingException: Execution payload parent hash does not match previous execution payload header
at tech.pegasys.teku.spec.logic.common.util.BlockProposalUtil.createNewUnsignedBlock(BlockProposalUtil.java:98) ~[teku-ethereum-spec-develop.jar:22.3.2+48-g163c5da]
at tech.pegasys.teku.spec.Spec.createNewUnsignedBlock(Spec.java:502) ~[teku-ethereum-spec-develop.jar:22.3.2+48-g163c5da]
at tech.pegasys.teku.validator.coordinator.BlockFactory.createUnsignedBlock(BlockFactory.java:54) ~[teku-beacon-validator-develop.jar:22.3.2+48-g163c5da]
at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.createBlock(ValidatorApiHandler.java:312) ~[teku-beacon-validator-develop.jar:22.3.2+48-g163c5da]
at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.lambda$createUnsignedBlock$11(ValidatorApiHandler.java:289) ~[teku-beacon-validator-develop.jar:22.3.2+48-g163c5da]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$thenApplyChecked$29(SafeFuture.java:422) ~[teku-infrastructure-async-develop.jar:22.3.2+48-g163c5da]
at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
at tech.pegasys.teku.dataproviders.generators.CachingTaskQueue.lambda$completePendingTask$9(CachingTaskQueue.java:199) ~[teku-ethereum-dataproviders-develop.jar:22.3.2+48-g163c5da]
at tech.pegasys.teku.infrastructure.async.SafeFuture.fromRunnable(SafeFuture.java:154) ~[teku-infrastructure-async-develop.jar:22.3.2+48-g163c5da]
at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$0(AsyncRunner.java:23) ~[teku-infrastructure-async-develop.jar:22.3.2+48-g163c5da]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:73) ~[teku-infrastructure-async-develop.jar:22.3.2+48-g163c5da]
at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:119) ~[teku-infrastructure-async-develop.jar:22.3.2+48-g163c5da]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: tech.pegasys.teku.spec.logic.common.statetransition.exceptions.BlockProcessingException: Execution payload parent hash does not match previous execution payload header
at tech.pegasys.teku.spec.logic.versions.bellatrix.block.BlockProcessorBellatrix.processExecutionPayload(BlockProcessorBellatrix.java:102) ~[teku-ethereum-spec-develop.jar:22.3.2+48-g163c5da]
at tech.pegasys.teku.spec.logic.versions.bellatrix.block.BlockProcessorBellatrix.processBlock(BlockProcessorBellatrix.java:85) ~[teku-ethereum-spec-develop.jar:22.3.2+48-g163c5da]
at tech.pegasys.teku.spec.logic.common.block.AbstractBlockProcessor.lambda$processUnsignedBlock$7(AbstractBlockProcessor.java:299) ~[teku-ethereum-spec-develop.jar:22.3.2+48-g163c5da]
at tech.pegasys.teku.spec.datastructures.state.beaconstate.common.AbstractBeaconState.updated(AbstractBeaconState.java:64) ~[teku-ethereum-spec-develop.jar:22.3.2+48-g163c5da]
at tech.pegasys.teku.spec.logic.common.block.AbstractBlockProcessor.processUnsignedBlock(AbstractBlockProcessor.java:297) ~[teku-ethereum-spec-develop.jar:22.3.2+48-g163c5da]
at tech.pegasys.teku.spec.logic.common.util.BlockProposalUtil.createNewUnsignedBlock(BlockProposalUtil.java:86) ~[teku-ethereum-spec-develop.jar:22.3.2+48-g163c5da]
... 16 more
```

**Comment by ajsutton** [comment]
Seems to be caused by https://github.com/hyperledger/besu/issues/3677

Not entirely sure why it's intermittent, though it could just be around the timing of when the merge block is created.
