### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid params response from Beacon Node API

### ISSUE THREAD

**Issue by briansun** [Consensys-Incorporated/teku#5384]
### Description
I'm using Infura Eth2 API as a Beacon Node with `--beacon-node-api-endpoint`

### Error Message
2022-04-25 22:46:47.406+00:00 | validator-async-4 | ERROR | RetryingDutyLoader | Failed to request validator duties for epoch 114852. Retrying after delay.
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Invalid params response from Beacon Node API (url = https://eth2-beacon-mainnet.infura.io/eth/v1/validator/duties/attester/114852)
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:145) ~[teku-infrastructure-async-22.4.0.jar:22.4.0]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883) ~[?:?]
at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:536) ~[teku-infrastructure-async-22.4.0.jar:22.4.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:32) ~[teku-infrastructure-async-22.4.0.jar:22.4.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:142) ~[teku-infrastructure-async-22.4.0.jar:22.4.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$exceptionallyCompose$27(SafeFuture.java:367) ~[teku-infrastructure-async-22.4.0.jar:22.4.0]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:145) ~[teku-infrastructure-async-22.4.0.jar:22.4.0]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883) ~[?:?]
at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:536) ~[teku-infrastructure-async-22.4.0.jar:22.4.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:32) ~[teku-infrastructure-async-22.4.0.jar:22.4.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:142) ~[teku-infrastructure-async-22.4.0.jar:22.4.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateTo(SafeFuture.java:264) ~[teku-infrastructure-async-22.4.0.jar:22.4.0]
at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:119) ~[teku-infrastructure-async-22.4.0.jar:22.4.0]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Invalid params response from Beacon Node API (url = https://eth2-beacon-mainnet.infura.io/eth/v1/validator/duties/attester/114852)
at tech.pegasys.teku.validator.remote.apiclient.ResponseHandler.defaultBadRequestHandler(ResponseHandler.java:113) ~[teku-validator-remote-22.4.0.jar:22.4.0]
at tech.pegasys.teku.validator.remote.apiclient.ResponseHandler.handleResponse(ResponseHandler.java:72) ~[teku-validator-remote-22.4.0.jar:22.4.0]
at tech.pegasys.teku.validator.remote.apiclient.OkHttpValidatorRestApiClient.executeCall(OkHttpValidatorRestApiClient.java:404) ~[teku-validator-remote-22.4.0.jar:22.4.0]
at tech.pegasys.teku.validator.remote.apiclient.OkHttpValidatorRestApiClient.post(OkHttpValidatorRestApiClient.java:375) ~[teku-validator-remote-22.4.0.jar:22.4.0]
at tech.pegasys.teku.validator.remote.apiclient.OkHttpValidatorRestApiClient.getAttestationDuties(OkHttpValidatorRestApiClient.java:142) ~[teku-validator-remote-22.4.0.jar:22.4.0]
at tech.pegasys.teku.validator.remote.RemoteValidatorApiHandler.lambda$getAttestationDuties$7(RemoteValidatorApiHandler.java:164) ~[teku-validator-remote-22.4.0.jar:22.4.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:81) ~[teku-infrastructure-async-22.4.0.jar:22.4.0]
at tech.pegasys.teku.validator.remote.RemoteValidatorApiHandler.sendRequest(RemoteValidatorApiHandler.java:453) ~[teku-validator-remote-22.4.0.jar:22.4.0]
at tech.pegasys.teku.validator.remote.RemoteValidatorApiHandler.lambda$sendRequest$38(RemoteValidatorApiHandler.java:448) ~[teku-validator-remote-22.4.0.jar:22.4.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:73) ~[teku-infrastructure-async-22.4.0.jar:22.4.0]
... 4 more

**Frequency:** About 50% of attestations are missed or failed.

### Versions (Add all that apply)
* Software version: teku/v22.4.0/linux-x86_64/-ubuntu-openjdk64bitservervm-java-11
* Java version: openjdk 11.0.14.1 2022-02-08
* OS Name & Version: Ubuntu 20.04.4 LTS
* Docker Version: -no-
* Cloud VM, type, size: AWS 2GB ram, 1 vCPU, 60GB SSD

**Comment by ajsutton** [comment]
hmm, this could happen for quite a range of reasons.  The first thing to check though is that your validator client clock is in sync.

In general I would recommend against using Infura as a beacon node - the performance of a remote beacon node is always less than a local one because of the latency involved. In the future it will become even worse or even impossible to use Infura as a beacon node, particularly once proof of execution semantics are added to the protocol.

In the mean time though to diagnose this further we probably need to get some debug logs to get more detail on why the request is being rejected.  Can you try running with `--logging debug` please? It will generate quite a lot of log output so you may want to remove the option again once you've captured a few requests that are rejected like this.

**Comment by ajsutton** [comment]
I'm going to close this one as we don't have sufficient information to facilitate investigation.  If you're able to check the validator clock and grab the debug logs mentioned above please feel free to reopen.

**Comment by briansun** [comment]
I agree with you that It's not a good idea to use Infura as beacon node
same as your reason.

After I submitted this issue, I switched to Lighthouse. Firstly, it was
still unstable. Keep missing some attestations. Some, not all. Then I
run beacon node locally, starting with `checkpoint-sync` with Infura's
beacon node service. Then everything works together.

Still thank you for your reply.


On May 4, 2022, GitHub ***@***.***> wrote:
> Closed #5384 <https://github.com/ConsenSys/teku/issues/5384>.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/ConsenSys/teku/issues/5384#event-6545283977>, or
unsubscribe <https://github.com/notifications/unsubscribe-
auth/AAAJUMUNXAGTZOE72WBHCLDVIHCAHANCNFSM5UKH2ZJQ>.
You are receiving this because you authored the thread.Message ID:
***@***.***>
