### ISSUE TITLE
Error while calculating TTD ETA

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#5412]
### Description
Division by 0 error while estimating the time until TTD:

```
{"timestamp":"2022-05-03T03:24:05,812","level":"ERROR","thread":"beaconchain-async-4","class":"TerminalPowBlockMonitor","message":"Unexpected error while checking TTD","throwable":" java.util.concurrent.CompletionException: java.lang.ArithmeticException: divide by zero
at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159)
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147)
at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateToAsync$13(SafeFuture.java:269)
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:81)
at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$2(AsyncRunner.java:38)
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:73)
at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:119)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)\nCaused by: java.lang.ArithmeticException: divide by zero
at org.apache.tuweni.units.bigints.UInt256.divide(UInt256.java:425)
at tech.pegasys.teku.statetransition.forkchoice.TerminalPowBlockMonitor.checkTtdEta(TerminalPowBlockMonitor.java:300)
at tech.pegasys.teku.statetransition.forkchoice.TerminalPowBlockMonitor.lambda$checkTerminalBlockByTTD$6(TerminalPowBlockMonitor.java:237)
at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)\n\t... 15 more\n"}

```

**Comment by ajsutton** [comment]
Happening while besu is syncing.
