### ISSUE TITLE
Improve reporting of "Error while attempting to publish metrics to remote service"

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#5416]
Every few hours I see the below in my console. I am pushing metrics to the remote beaconchai.in service with `metrics-publish-endpoint: "https://beaconcha.in/api/v1/client/metrics?apikey=XXX"`. Presumably it's due to the remote service sometimes being down.

1. Suggest this be demoted to "WARNING" level since it's definitely not critical for the operation of Teku.
2. It would be nice not to have the full stack trace in my console output. (I have `log-destination: "CONSOLE"`). Suggest trapping common cases like "timeout" and including them in a nice warning message, and doing the stack trace only for other untrapped cases.

```
May 03 09:34:50 metalalbert teku[2458]: 2022-05-03 09:34:50.546 ERROR - Error while attempting to publish metrics to remote service
May 03 09:34:50 metalalbert teku[2458]: java.net.SocketTimeoutException: timeout
May 03 09:34:50 metalalbert teku[2458]: at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:677) ~[okhttp-4.9.2.jar:?]
May 03 09:34:50 metalalbert teku[2458]: at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:686) ~[okhttp-4.9.2.jar:?]
May 03 09:34:50 metalalbert teku[2458]: at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:143) ~[okhttp-4.9.2.jar:?]
May 03 09:34:50 metalalbert teku[2458]: at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:96) ~[okhttp-4.9.2.jar:?]
May 03 09:34:50 metalalbert teku[2458]: at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106) ~[okhttp-4.9.2.jar:?]
May 03 09:34:50 metalalbert teku[2458]: at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79) ~[okhttp-4.9.2.jar:?]
May 03 09:34:50 metalalbert teku[2458]: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.9.2.jar:?]
May 03 09:34:50 metalalbert teku[2458]: at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34) ~[okhttp-4.9.2.jar:?]
May 03 09:34:50 metalalbert teku[2458]: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.9.2.jar:?]
May 03 09:34:50 metalalbert teku[2458]: at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) ~[okhttp-4.9.2.jar:?]
May 03 09:34:50 metalalbert teku[2458]: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.9.2.jar:?]
May 03 09:34:50 metalalbert teku[2458]: at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.9.2.jar:?]
May 03 09:34:50 metalalbert teku[2458]: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.9.2.jar:?]
May 03 09:34:50 metalalbert teku[2458]: at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.9.2.jar:?]
May 03 09:34:50 metalalbert teku[2458]: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.9.2.jar:?]
May 03 09:34:50 metalalbert teku[2458]: at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) ~[okhttp-4.9.2.jar:?]
May 03 09:34:50 metalalbert teku[2458]: at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154) ~[okhttp-4.9.2.jar:?]
May 03 09:34:50 metalalbert teku[2458]: at tech.pegasys.teku.data.publisher.MetricsPublisher.publishMetrics(MetricsPublisher.java:43) ~[teku-data-publisher-22.3.2.jar:22.3.2]
May 03 09:34:50 metalalbert teku[2458]: at tech.pegasys.teku.data.publisher.MetricsPublisherManager.publishMetrics(MetricsPublisherManager.java:87) ~[teku-data-publisher-22.3.2.jar:22.3.2]
May 03 09:34:50 metalalbert teku[2458]: at tech.pegasys.teku.infrastructure.async.FutureUtil.lambda$runWithFixedDelay$0(FutureUtil.java:39) ~[teku-infrastructure-async-22.3.2.jar:22.3.2]
May 03 09:34:50 metalalbert teku[2458]: at tech.pegasys.teku.infrastructure.async.SafeFuture.fromRunnable(SafeFuture.java:154) ~[teku-infrastructure-async-22.3.2.jar:22.3.2]
May 03 09:34:50 metalalbert teku[2458]: at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAfterDelay$1(AsyncRunner.java:32) ~[teku-infrastructure-async-22.3.2.jar:22.3.2]
May 03 09:34:50 metalalbert teku[2458]: at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:73) ~[teku-infrastructure-async-22.3.2.jar:22.3.2]
May 03 09:34:50 metalalbert teku[2458]: at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:119) ~[teku-infrastructure-async-22.3.2.jar:22.3.2]
May 03 09:34:50 metalalbert teku[2458]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
May 03 09:34:50 metalalbert teku[2458]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
May 03 09:34:50 metalalbert teku[2458]: at java.lang.Thread.run(Thread.java:830) ~[?:?]
```

**Comment by benjaminion** [comment]
Seems like for 502 responses we already do the second one. Just need to do similar for "timeout".

```
May 03 08:55:15 metalalbert teku[2458]: 2022-05-03 08:55:15.553 INFO  - Slot Event  *** Slot: 3728674, Block: da341e841c2dd910ca20d0b3f80a895685dfa3fb5a7c611916f1296315d40e11, Justified: 116520, Finalized: 116519, Peers: 100
May 03 08:55:26 metalalbert teku[2458]: 2022-05-03 08:55:26.283 ERROR - Failed to publish metrics to external metrics service. Response code 502
May 03 08:55:27 metalalbert teku[2458]: 2022-05-03 08:55:27.563 INFO  - Slot Event  *** Slot: 3728675, Block: 184660d036d8311bdec0dac95c5a5c50f656f466e89087f20d6b8166248aa866, Justified: 116520, Finalized: 116519, Peers: 100
```
