### ISSUE TITLE
Two Instances of Artemis Error

### ISSUE THREAD

**Issue by araskachoi** [Consensys-Incorporated/teku#544]
### Steps to reproduce:
1. create the docker image
2. run the artemis client in background (detatched)
`docker exec -d <container name> artemis`
3. go into docker container
`docker exec -it <container name> /bin/bash`
4. run the artemis client again (in the correct directory)
`artemis --logging ALL`

### Expected Behavior
- should throw a better error, right now it gives :
`SEVERE: Unhandled exception
java.lang.RuntimeException: java.net.BindException: Address already in use`
- maybe give the port that is being occupied : 
`Fatal: Error starting protocol stack: listen tcp :9000: bind: address already in use`
- hiding the stack trace and giving a concise error message might provide a better user experience
- should stop the application when this error is given

### Actual Results
- gives a very verbose stack trace of the error
- the client still runs and proceeds to run the application

### Stack Trace:
```
root@whiteblock-node0:/artemis# artemis --logging ALL
Setting logging level to ALL
[INFO ] - ******* Eth2Genesis Event detected ******* : 0x00000000000000000000000000000000000000000000000000000000726F6F74
[INFO ] - Node slot: 4294967296
[INFO ] - Node time: 25769803776
[DEBUG] - -Dio.netty.allocator.numHeapArenas: 32
[DEBUG] - -Dio.netty.allocator.numDirectArenas: 32
[DEBUG] - -Dio.netty.allocator.pageSize: 8192
[DEBUG] - -Dio.netty.allocator.maxOrder: 11
[DEBUG] - -Dio.netty.allocator.chunkSize: 16777216
[DEBUG] - -Dio.netty.allocator.tinyCacheSize: 512
[DEBUG] - -Dio.netty.allocator.smallCacheSize: 256
[DEBUG] - -Dio.netty.allocator.normalCacheSize: 64
[DEBUG] - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
[DEBUG] - -Dio.netty.allocator.cacheTrimInterval: 8192
[DEBUG] - -Dio.netty.allocator.useCacheForAllThreads: true
[DEBUG] - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
[DEBUG] - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
[DEBUG] - -Dio.netty.processId: 1180 (auto-detected)
[DEBUG] - -Dio.netty.machineId: 02:42:0a:ff:fe:01:00:02 (auto-detected)
[DEBUG] - -Dio.netty.allocator.type: pooled
[DEBUG] - -Dio.netty.threadLocalDirectBufferSize: 0
[DEBUG] - -Dio.netty.maxThreadLocalCharBufferSize: 16384
Apr 01, 2019 10:19:28 PM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.RuntimeException: java.net.BindException: Address already in use
        at tech.pegasys.artemis.networking.p2p.HobbitsP2PNetwork.lambda$run$0(HobbitsP2PNetwork.java:105)
        at io.vertx.core.net.impl.NetServerImpl.lambda$listen$4(NetServerImpl.java:324)
        at io.vertx.core.net.impl.NetServerImpl.lambda$null$2(NetServerImpl.java:285)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:130)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:558)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1358)
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501)
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486)
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:1019)
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:254)
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:366)
        ... 6 more

[INFO ] - Initial state root is 0xB1676C0B58B0A274A55CFB1D616B8B1B5901710CF3771EBEB8637F0B01FC1A43

[INFO ] - ******* Slot Event *******
[INFO ] - Node time:                            25769803782 |  6
[INFO ] - New BeaconBlock detected.
[INFO ] - Node slot:                             4294967297 |  1
```

**Comment by jrhea** [comment]
This issue has been resolved
