### ISSUE TITLE
Some attestations being re-validated with SIMPLE BLS verifier

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#5478]
### Description
Normally the gossip validation performs the `isValidIndexedAttestationCheck` which is cached in `ValidatableAttestation` so we don't have to recheck it when processing the attestation.  If we do wind up rechecking it, currently we use the simple BLS signature verifier which does not do any batching.

There seem to be some attestations slipping through which aren't yet marked as valid indexed attestations and wind up actually doing signature verification with this simple approach.  I'm not yet sure what flow leads to these.

I added a check in `AttestationUtil.isValidIndexedAttestationAsync` to print a stack trace if simple verification was used and got:
```
java.lang.Exception: Using simple BLS verification
	at tech.pegasys.teku.spec.logic.common.util.AttestationUtil.isValidIndexedAttestationAsync(AttestationUtil.java:169)
	at tech.pegasys.teku.spec.logic.common.util.AttestationUtil.isValidIndexedAttestation(AttestationUtil.java:139)
	at tech.pegasys.teku.spec.logic.common.util.ForkChoiceUtil.lambda$validate$1(ForkChoiceUtil.java:232)
	at tech.pegasys.teku.spec.datastructures.util.AttestationProcessingResult.ifSuccessful(AttestationProcessingResult.java:47)
	at tech.pegasys.teku.spec.logic.common.util.ForkChoiceUtil.validate(ForkChoiceUtil.java:227)
	at tech.pegasys.teku.spec.Spec.validateAttestation(Spec.java:477)
	at tech.pegasys.teku.statetransition.forkchoice.ForkChoice.lambda$onAttestation$18(ForkChoice.java:507)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
	at tech.pegasys.teku.infrastructure.async.SafeFuture.thenCompose(SafeFuture.java:470)
	at tech.pegasys.teku.statetransition.forkchoice.ForkChoice.onAttestation(ForkChoice.java:503)
	at tech.pegasys.teku.statetransition.attestation.AttestationManager.onAttestation(AttestationManager.java:196)
	at tech.pegasys.teku.statetransition.attestation.AttestationManager.lambda$processInternallyValidatedAttestation$5(AttestationManager.java:142)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735)
	at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2182)
	at tech.pegasys.teku.infrastructure.async.SafeFuture.thenAccept(SafeFuture.java:451)
	at tech.pegasys.teku.statetransition.attestation.AttestationManager.processInternallyValidatedAttestation(AttestationManager.java:138)
	at tech.pegasys.teku.statetransition.attestation.AttestationManager.addAttestation(AttestationManager.java:124)
	at tech.pegasys.teku.networking.eth2.gossip.topics.topichandlers.SingleAttestationTopicHandler.lambda$createHandler$0(SingleAttestationTopicHandler.java:40)
	at tech.pegasys.teku.networking.eth2.gossip.topics.topichandlers.Eth2TopicHandler.lambda$handleMessage$2(Eth2TopicHandler.java:101)
	at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:73)
	at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:119)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

This is quite rare so not a significant contributor to CPU usage (and the resulting behaviour is correct and entirely safe - just potentially less efficient than it could be).  We need to investigate why this occurs and work out if we can safely use the batching signature verification for these as well.

**Comment by ajsutton** [comment]
One theory is that these attestations are being recovered from re-orged blocks.  So they are initially included in a canonical block (and thus removed from our pool) then that block is re-orged back out and the attestation isn't included in the other fork so we add it back to our pool.  Sincee we're getting these attestations from a block we know that the signature is valid even though we won't have a cached IndexedAttestation for them so we should find a way to skip rechecking the signature.
