### ISSUE TITLE
Unrecoverable LevelDB corruption on MacOS

### ISSUE THREAD

**Issue by Nashatyrev** [Consensys-Incorporated/teku#5519]
### Description

Just hit the LevelDB corruption issue on my MacBook Pro. Teku don't start:
```
12:24:35.553 INFO  - Initializing storage
12:24:36.963 DEBUG - Failed to intiailize storage java.lang.RuntimeException: org.fusesource.leveldbjni.internal.NativeDB$DBException: Corruption: corrupted compressed block contents (See log file for full stack trace)
12:24:36.971 FATAL - Failed to initialize storage. Check the existing database matches the current network configuration. Set log level to debug for more information.
java.util.concurrent.CompletionException: java.lang.RuntimeException: org.fusesource.leveldbjni.internal.NativeDB$DBException: Corruption: corrupted compressed block contents
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:636)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:145)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325)
	at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:536)
	at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:32)
	at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:142)
	at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$exceptionallyCompose$27(SafeFuture.java:367)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:145)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateToAsync$15(SafeFuture.java:271)
	at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:81)
	at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$2(AsyncRunner.java:38)
	at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:73)
	at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:119)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: org.fusesource.leveldbjni.internal.NativeDB$DBException: Corruption: corrupted compressed block contents
	at org.fusesource.leveldbjni.internal.JniDBIterator.next(JniDBIterator.java:102)
	at org.fusesource.leveldbjni.internal.JniDBIterator.next(JniDBIterator.java:45)
	at tech.pegasys.teku.storage.server.leveldb.LevelDbInstance.lambda$getAll$1(LevelDbInstance.java:120)
	at tech.pegasys.teku.storage.server.leveldb.LevelDbInstance.withIterator(LevelDbInstance.java:292)
	at tech.pegasys.teku.storage.server.leveldb.LevelDbInstance.getAll(LevelDbInstance.java:115)
	at tech.pegasys.teku.storage.server.kvstore.dataaccess.V4HotKvStoreDao.getVotes(V4HotKvStoreDao.java:127)
	at tech.pegasys.teku.storage.server.kvstore.KvStoreDatabase.createMemoryStore(KvStoreDatabase.java:311)
	at tech.pegasys.teku.storage.server.kvstore.KvStoreDatabase.createMemoryStore(KvStoreDatabase.java:294)
	at tech.pegasys.teku.storage.server.ChainStorage.getStore(ChainStorage.java:66)
	at tech.pegasys.teku.storage.server.ChainStorage.onStoreRequest(ChainStorage.java:82)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:74)
	at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.deliverToWithResponse(DirectEventDeliverer.java:67)
	at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer.lambda$deliverToWithResponse$1(AsyncEventDeliverer.java:75)
	at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:117)
	at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:109)
	... 3 more
Caused by: org.fusesource.leveldbjni.internal.NativeDB$DBException: Corruption: corrupted compressed block contents
	at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200)
	at org.fusesource.leveldbjni.internal.NativeIterator.checkStatus(NativeIterator.java:121)
	at org.fusesource.leveldbjni.internal.NativeIterator.next(NativeIterator.java:157)
	at org.fusesource.leveldbjni.internal.JniDBIterator.next(JniDBIterator.java:100)
	... 21 more
```
### Steps to Reproduce (Bug)

Unfortunately no specific steps to reproduce. 
Found in logs that the corruption originally happened on Saturday early morning, which means the computer was 100% unattended 
```
2022-05-14 07:01:30.063+04:00 | forkchoice-async-0 | ERROR | BlockImporter | Internal error while importing block: 391b8101d07996e09d074a6bda6c0ab6be83eb2bfdbfd8a4d2c3c7c63d72ea6d (3806080)
java.util.concurrent.CompletionException: org.iq80.leveldb.DBException: Corruption: corrupted compressed block contents
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[?:?]
at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347) ~[?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire$$$capture(CompletableFuture.java:708) ~[?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:145) ~[classes/:?]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateToAsync$15(SafeFuture.java:271) ~[classes/:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:81) ~[classes/:?]
at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$2(AsyncRunner.java:38) ~[classes/:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:73) ~[classes/:?]
at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:119) ~[classes/:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.iq80.leveldb.DBException: Corruption: corrupted compressed block contents
at org.fusesource.leveldbjni.internal.JniDB.write(JniDB.java:153) ~[leveldbjni-1.8.jar:1.8]
at org.fusesource.leveldbjni.internal.JniDB.write(JniDB.java:114) ~[leveldbjni-1.8.jar:1.8]
at tech.pegasys.teku.storage.server.leveldb.LevelDbTransaction.lambda$commit$6(LevelDbTransaction.java:95) ~[classes/:?]
at tech.pegasys.teku.storage.server.leveldb.LevelDbTransaction.applyUpdate(LevelDbTransaction.java:130) ~[classes/:?]
at tech.pegasys.teku.storage.server.leveldb.LevelDbTransaction.commit(LevelDbTransaction.java:92) ~[classes/:?]
at tech.pegasys.teku.storage.server.kvstore.dataaccess.V4FinalizedKvStoreDao$V4FinalizedUpdater.commit(V4FinalizedKvStoreDao.java:284) ~[classes/:?]
at tech.pegasys.teku.storage.server.kvstore.KvStoreDatabase.updateFinalizedDataPruneMode(KvStoreDatabase.java:743) ~[classes/:?]
at tech.pegasys.teku.storage.server.kvstore.KvStoreDatabase.updateFinalizedData(KvStoreDatabase.java:603) ~[classes/:?]
at tech.pegasys.teku.storage.server.kvstore.KvStoreDatabase.doUpdate(KvStoreDatabase.java:539) ~[classes/:?]
at tech.pegasys.teku.storage.server.kvstore.KvStoreDatabase.update(KvStoreDatabase.java:241) ~[classes/:?]
at tech.pegasys.teku.storage.server.ChainStorage.lambda$onStorageUpdate$0(ChainStorage.java:94) ~[classes/:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:81) ~[classes/:?]
at tech.pegasys.teku.storage.server.ChainStorage.onStorageUpdate(ChainStorage.java:92) ~[classes/:?]
at jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:74) ~[classes/:?]
at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.deliverToWithResponse(DirectEventDeliverer.java:67) ~[classes/:?]
at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer.lambda$deliverToWithResponse$1(AsyncEventDeliverer.java:75) ~[classes/:?]
at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:117) ~[classes/:?]
at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:109) ~[classes/:?]
... 3 more
Caused by: org.fusesource.leveldbjni.internal.NativeDB$DBException: Corruption: corrupted compressed block contents
at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200) ~[leveldbjni-1.8.jar:1.8]
at org.fusesource.leveldbjni.internal.NativeDB.write(NativeDB.java:285) ~[leveldbjni-1.8.jar:1.8]
at org.fusesource.leveldbjni.internal.JniDB.write(JniDB.java:150) ~[leveldbjni-1.8.jar:1.8]
at org.fusesource.leveldbjni.internal.JniDB.write(JniDB.java:114) ~[leveldbjni-1.8.jar:1.8]
at tech.pegasys.teku.storage.server.leveldb.LevelDbTransaction.lambda$commit$6(LevelDbTransaction.java:95) ~[classes/:?]
at tech.pegasys.teku.storage.server.leveldb.LevelDbTransaction.applyUpdate(LevelDbTransaction.java:130) ~[classes/:?]
at tech.pegasys.teku.storage.server.leveldb.LevelDbTransaction.commit(LevelDbTransaction.java:92) ~[classes/:?]
at tech.pegasys.teku.storage.server.kvstore.dataaccess.V4FinalizedKvStoreDao$V4FinalizedUpdater.commit(V4FinalizedKvStoreDao.java:284) ~[classes/:?]
at tech.pegasys.teku.storage.server.kvstore.KvStoreDatabase.updateFinalizedDataPruneMode(KvStoreDatabase.java:743) ~[classes/:?]
at tech.pegasys.teku.storage.server.kvstore.KvStoreDatabase.updateFinalizedData(KvStoreDatabase.java:603) ~[classes/:?]
at tech.pegasys.teku.storage.server.kvstore.KvStoreDatabase.doUpdate(KvStoreDatabase.java:539) ~[classes/:?]
at tech.pegasys.teku.storage.server.kvstore.KvStoreDatabase.update(KvStoreDatabase.java:241) ~[classes/:?]
at tech.pegasys.teku.storage.server.ChainStorage.lambda$onStorageUpdate$0(ChainStorage.java:94) ~[classes/:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:81) ~[classes/:?]
at tech.pegasys.teku.storage.server.ChainStorage.onStorageUpdate(ChainStorage.java:92) ~[classes/:?]
at jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:74) ~[classes/:?]
at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.deliverToWithResponse(DirectEventDeliverer.java:67) ~[classes/:?]
at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer.lambda$deliverToWithResponse$1(AsyncEventDeliverer.java:75) ~[classes/:?]
at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:117) ~[classes/:?]
at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:109) ~[classes/:?]
... 3 more
```

**Frequency:** occurred for the first time 

### Versions (Add all that apply)
* Software version: custom Teku fork of 0206b510 (no much changes to the core Teku code, totally no DB tweaks)
* Java version: 
```
  java 17.0.3.1 2022-04-22 LTS
  Java(TM) SE Runtime Environment (build 17.0.3.1+2-LTS-6)
  Java HotSpot(TM) 64-Bit Server VM (build 17.0.3.1+2-LTS-6, mixed mode, sharing)
```
* OS Name & Version: 
```
MacBookPro16,1
6‑core Intel Core i7
2,6 GHz
RAM: 16 ГБ
Version:	1731.100.130.0.0 (iBridge: 19.16.14243.0.0,0)
```

**Comment by Nashatyrev** [comment]
[teku-node_2022-05-14.zip](https://github.com/ConsenSys/teku/files/8707780/teku-node_2022-05-14.zip)
Attaching the log for the day when the issue occurred for the first time. However nothing notable was detected there preceding the failure

**Comment by Nashatyrev** [comment]
Oh, there is a enough space was available on disk:
```
nashatyrev@MacBook-Pro-3 ~ % df -h
Filesystem       Size   Used  Avail Capacity iused      ifree %iused  Mounted on
/dev/disk1s1s1  466Gi   14Gi  135Gi    10%  500637 1419298320    0%   /
devfs           193Ki  193Ki    0Bi   100%     666          0  100%   /dev
/dev/disk1s5    466Gi  2.0Gi  135Gi     2%       2 1419298320    0%   /System/Volumes/VM
/dev/disk1s3    466Gi  260Mi  135Gi     1%     838 1419298320    0%   /System/Volumes/Preboot
/dev/disk1s6    466Gi  636Ki  135Gi     1%      19 1419298320    0%   /System/Volumes/Update
/dev/disk1s2    466Gi  313Gi  135Gi    70%  986540 1419298320    0%   /System/Volumes/Data
map auto_home     0Bi    0Bi    0Bi   100%       0          0  100%   /System/Volumes/Data/home
```

**Comment by benjaminion** [comment]
I recommend running a memory test as a first step - on the three occasions I've experienced DB corruption like this (1 x Teku, 1 x Besu, 1 x Parity some years ago) they all turned out to be due to faulty RAM.

**Comment by Nashatyrev** [comment]
@benjaminion thanks, this is a very good hint!
Since beside of this issue I started getting intermittent JVM crashes at some point (tried 2 different JVM versions) 
Faulty RAM could explain all of this. 

However I tried running `Rember` Mac tool for about 5 hours but all results was 'OK'. But it allocated just 50% of all available RAM (because running within functioning OS) and CPU wasn't overheated (like it does usually during Teku sync)
Embedded Mac recovery and testing tool (on startup) seems to be doing very light testing (just 2 mins for all) 

Does anybody have ideas what could be the most appropriate tool to test Mac RAM?

**Comment by rolfyone** [comment]
have we tried memtestx86?

**Comment by Nashatyrev** [comment]
I've finally gave up trying to create a bootable memtest86 flash drive. Tried 2 distinct drives and all options found on forums and my macbook still doesn't see it as a bootable device (secure boot was turned off). 

Closing this issue as it is very likely I still have issues with my mac.
