### ISSUE TITLE
Teku Errors when syncing

### ISSUE THREAD

**Issue by DockBoss** [Consensys-Incorporated/teku#5617]
### Description
I was attempting to sync to Kiln with Nethermind and Teku and I keep getting this error. 
```
2022-05-29 20:43:02.691-05:00 | FinalizedCheckpointChannel-0 | ERROR | teku-status-log | PLEASE FIX OR REPORT | Unexpected exception thrown for event 'interface tech.pegasys.teku.storage.api.FinalizedCheckpointChannel.onNewFinalizedCheckpoint' in handler 'tech.pegasys.teku.validator.coordinator.DepositProvider'
java.lang.UnsupportedOperationException: Cannot finalized an empty tree
at tech.pegasys.teku.ethereum.pow.merkletree.ZeroMerkleTree.finalize(ZeroMerkleTree.java:57) ~[teku-ethereum-pow-merkletree-develop.jar:22.5.1+55-g25039d6]
at tech.pegasys.teku.ethereum.pow.merkletree.DepositTree.finalize(DepositTree.java:70) ~[teku-ethereum-pow-merkletree-develop.jar:22.5.1+55-g25039d6]
at tech.pegasys.teku.validator.coordinator.DepositProvider.onNewFinalizedCheckpoint(DepositProvider.java:123) ~[teku-beacon-validator-develop.jar:22.5.1+55-g25039d6]
at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:74) ~[teku-infrastructure-events-develop.jar:22.5.1+55-g25039d6]
at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.deliverTo(DirectEventDeliverer.java:54) ~[teku-infrastructure-events-develop.jar:22.5.1+55-g25039d6]
at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer.lambda$deliverTo$0(AsyncEventDeliverer.java:61) ~[teku-infrastructure-events-develop.jar:22.5.1+55-g25039d6]
at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:117) ~[teku-infrastructure-events-develop.jar:22.5.1+55-g25039d6]
at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:109) ~[teku-infrastructure-events-develop.jar:22.5.1+55-g25039d6]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

```
### Steps to Reproduce (Bug)
Attempt to sync to Kiln with Nethermind.
**Frequency:**
Every time I start the node.
### Versions (Add all that apply)
* Software version: `master:25039d6`
* Java version: `java 18`
* OS Name & Version: `Wndows 11`

**Comment by ajsutton** [comment]
Thanks for reporting this. To help us investigate could you provide some additional info please?

What is actually happening with the node beyond logging this error? 
Is the sync progressing? 

Having some additional logs around the exception would also be very useful for additional context.

**Comment by DockBoss** [comment]
[teku.zip](https://github.com/ConsenSys/teku/files/8794888/teku.zip)
Here are my logs. I am not sure if it progresses, I shut it down after I saw the error. I can restart it and let it run to see if it gets anywhere.
