### ISSUE TITLE
Suppress EofException caused by client terminating REST API request stream early

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#5659]
### Description
Don't log `EofException` when the client disconnects while streaming REST API responses.

Previously this went into Javalin but now that we're streaming we seem to be able to handle it in the default exception handler.

```
2022-06-01 12:57:39.490 | qtp154415291-99           | ERROR | BeaconRestApi                  | Failed to process request to URL http://localhost:19501/teku/v1/beacon/pool/deposits
java.io.UncheckedIOException: org.eclipse.jetty.io.EofException
	at tech.pegasys.teku.infrastructure.json.JsonUtil.serializeToBytes(JsonUtil.java:71) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.json.JsonUtil.serializeToBytes(JsonUtil.java:60) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.restapi.openapi.response.JsonResponseContentTypeDefinition.serialize(JsonResponseContentTypeDefinition.java:42) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.restapi.endpoints.EndpointMetadata.serialize(EndpointMetadata.java:254) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.restapi.endpoints.JavalinRestApiRequest.respondImpl(JavalinRestApiRequest.java:127) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.restapi.endpoints.JavalinRestApiRequest.respond(JavalinRestApiRequest.java:117) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.restapi.endpoints.JavalinRestApiRequest.respondOk(JavalinRestApiRequest.java:61) ~[classes/:?]
	at tech.pegasys.teku.beaconrestapi.handlers.tekuv1.beacon.GetDeposits.handleRequest(GetDeposits.java:93) ~[classes/:?]
	at tech.pegasys.teku.beaconrestapi.MigratingEndpointAdapter.adapt(MigratingEndpointAdapter.java:37) ~[classes/:?]
	at tech.pegasys.teku.beaconrestapi.handlers.tekuv1.beacon.GetDeposits.handle(GetDeposits.java:88) ~[classes/:?]
	at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:20) ~[javalin-4.4.0.jar:4.4.0]
	at io.javalin.http.JavalinServlet.addHandler$lambda-5(JavalinServlet.kt:115) ~[javalin-4.4.0.jar:4.4.0]
	at io.javalin.http.JavalinServlet$service$tryBeforeAndEndpointHandlers$1.invoke(JavalinServlet.kt:44) ~[javalin-4.4.0.jar:4.4.0]
	at io.javalin.http.JavalinServlet$service$tryBeforeAndEndpointHandlers$1.invoke(JavalinServlet.kt:39) ~[javalin-4.4.0.jar:4.4.0]
	at io.javalin.http.JavalinServlet.service$tryWithExceptionMapper(JavalinServlet.kt:131) ~[javalin-4.4.0.jar:4.4.0]
	at io.javalin.http.JavalinServlet.service$tryBeforeAndEndpointHandlers(JavalinServlet.kt:39) ~[javalin-4.4.0.jar:4.4.0]
	at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:87) ~[javalin-4.4.0.jar:4.4.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet-api-3.1.0.jar:3.1.0]
	at io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:58) ~[javalin-4.4.0.jar:4.4.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet-api-3.1.0.jar:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) ~[jetty-servlet-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550) ~[jetty-servlet-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
	at io.javalin.jetty.JettyServer$start$wsAndHttpHandler$1.doHandle(JettyServer.kt:52) ~[javalin-4.4.0.jar:4.4.0]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501) ~[jetty-servlet-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) ~[jetty-io-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) ~[jetty-io-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) ~[jetty-io-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:279) ~[jetty-io-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:422) ~[jetty-io-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:277) ~[jetty-io-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:381) ~[jetty-io-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:831) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:223) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:555) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:1014) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:1086) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:285) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:269) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:873) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator._flushBuffer(UTF8JsonGenerator.java:2171) ~[jackson-core-2.13.3.jar:2.13.3]
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeString(UTF8JsonGenerator.java:515) ~[jackson-core-2.13.3.jar:2.13.3]
	at tech.pegasys.teku.infrastructure.json.types.StringBasedPrimitiveTypeDefinition.serialize(StringBasedPrimitiveTypeDefinition.java:85) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.json.types.RequiredSerializableFieldDefinition.writeField(RequiredSerializableFieldDefinition.java:39) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.json.types.SerializableObjectTypeDefinition.serialize(SerializableObjectTypeDefinition.java:56) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.json.types.RequiredSerializableFieldDefinition.writeField(RequiredSerializableFieldDefinition.java:39) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.json.types.SerializableObjectTypeDefinition.serialize(SerializableObjectTypeDefinition.java:56) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.json.types.SerializableArrayTypeDefinition.serialize(SerializableArrayTypeDefinition.java:41) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.json.types.SerializableArrayTypeDefinition.serialize(SerializableArrayTypeDefinition.java:21) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.json.types.RequiredSerializableFieldDefinition.writeField(RequiredSerializableFieldDefinition.java:39) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.json.types.SerializableObjectTypeDefinition.serialize(SerializableObjectTypeDefinition.java:56) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.json.JsonUtil.lambda$serializeToBytes$1(JsonUtil.java:60) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.json.JsonUtil.serializeToBytes(JsonUtil.java:67) ~[classes/:?]
	... 48 more
	Suppressed: org.eclipse.jetty.io.EofException: Closed
		at org.eclipse.jetty.server.HttpOutput.checkWritable(HttpOutput.java:771) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
		at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:795) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
		at com.fasterxml.jackson.core.json.UTF8JsonGenerator._flushBuffer(UTF8JsonGenerator.java:2171) ~[jackson-core-2.13.3.jar:2.13.3]
		at com.fasterxml.jackson.core.json.UTF8JsonGenerator.close(UTF8JsonGenerator.java:1214) ~[jackson-core-2.13.3.jar:2.13.3]
		at tech.pegasys.teku.infrastructure.json.JsonUtil.serializeToBytes(JsonUtil.java:66) ~[classes/:?]
		at tech.pegasys.teku.infrastructure.json.JsonUtil.serializeToBytes(JsonUtil.java:60) ~[classes/:?]
		at tech.pegasys.teku.infrastructure.restapi.openapi.response.JsonResponseContentTypeDefinition.serialize(JsonResponseContentTypeDefinition.java:42) ~[classes/:?]
		at tech.pegasys.teku.infrastructure.restapi.endpoints.EndpointMetadata.serialize(EndpointMetadata.java:254) ~[classes/:?]
		at tech.pegasys.teku.infrastructure.restapi.endpoints.JavalinRestApiRequest.respondImpl(JavalinRestApiRequest.java:127) ~[classes/:?]
		at tech.pegasys.teku.infrastructure.restapi.endpoints.JavalinRestApiRequest.respond(JavalinRestApiRequest.java:117) ~[classes/:?]
		at tech.pegasys.teku.infrastructure.restapi.endpoints.JavalinRestApiRequest.respondOk(JavalinRestApiRequest.java:61) ~[classes/:?]
		at tech.pegasys.teku.beaconrestapi.handlers.tekuv1.beacon.GetDeposits.handleRequest(GetDeposits.java:93) ~[classes/:?]
		at tech.pegasys.teku.beaconrestapi.MigratingEndpointAdapter.adapt(MigratingEndpointAdapter.java:37) ~[classes/:?]
		at tech.pegasys.teku.beaconrestapi.handlers.tekuv1.beacon.GetDeposits.handle(GetDeposits.java:88) ~[classes/:?]
		at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:20) ~[javalin-4.4.0.jar:4.4.0]
		at io.javalin.http.JavalinServlet.addHandler$lambda-5(JavalinServlet.kt:115) ~[javalin-4.4.0.jar:4.4.0]
		at io.javalin.http.JavalinServlet$service$tryBeforeAndEndpointHandlers$1.invoke(JavalinServlet.kt:44) ~[javalin-4.4.0.jar:4.4.0]
		at io.javalin.http.JavalinServlet$service$tryBeforeAndEndpointHandlers$1.invoke(JavalinServlet.kt:39) ~[javalin-4.4.0.jar:4.4.0]
		at io.javalin.http.JavalinServlet.service$tryWithExceptionMapper(JavalinServlet.kt:131) ~[javalin-4.4.0.jar:4.4.0]
		at io.javalin.http.JavalinServlet.service$tryBeforeAndEndpointHandlers(JavalinServlet.kt:39) ~[javalin-4.4.0.jar:4.4.0]
		at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:87) ~[javalin-4.4.0.jar:4.4.0]
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet-api-3.1.0.jar:3.1.0]
		at io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:58) ~[javalin-4.4.0.jar:4.4.0]
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet-api-3.1.0.jar:3.1.0]
		at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) ~[jetty-servlet-9.4.45.v20220203.jar:9.4.45.v20220203]
		at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550) ~[jetty-servlet-9.4.45.v20220203.jar:9.4.45.v20220203]
		at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
		at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
		at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
		at io.javalin.jetty.JettyServer$start$wsAndHttpHandler$1.doHandle(JettyServer.kt:52) ~[javalin-4.4.0.jar:4.4.0]
		at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
		at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501) ~[jetty-servlet-9.4.45.v20220203.jar:9.4.45.v20220203]
		at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
		at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
		at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
		at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
		at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
		at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
		at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
		at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
		at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
		at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
		at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) ~[jetty-io-9.4.45.v20220203.jar:9.4.45.v20220203]
		at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) ~[jetty-io-9.4.45.v20220203.jar:9.4.45.v20220203]
		at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) ~[jetty-io-9.4.45.v20220203.jar:9.4.45.v20220203]
		at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
		at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
		at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
		at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
		at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
		at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
		at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
		at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method) ~[?:?]
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:66) ~[?:?]
	at sun.nio.ch.IOUtil.write(IOUtil.java:217) ~[?:?]
	at sun.nio.ch.IOUtil.write(IOUtil.java:153) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:563) ~[?:?]
	at java.nio.channels.SocketChannel.write(SocketChannel.java:642) ~[?:?]
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:273) ~[jetty-io-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:422) ~[jetty-io-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:277) ~[jetty-io-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:381) ~[jetty-io-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:831) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:223) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:555) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:1014) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:1086) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:285) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:269) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:873) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator._flushBuffer(UTF8JsonGenerator.java:2171) ~[jackson-core-2.13.3.jar:2.13.3]
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeString(UTF8JsonGenerator.java:515) ~[jackson-core-2.13.3.jar:2.13.3]
	at tech.pegasys.teku.infrastructure.json.types.StringBasedPrimitiveTypeDefinition.serialize(StringBasedPrimitiveTypeDefinition.java:85) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.json.types.RequiredSerializableFieldDefinition.writeField(RequiredSerializableFieldDefinition.java:39) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.json.types.SerializableObjectTypeDefinition.serialize(SerializableObjectTypeDefinition.java:56) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.json.types.RequiredSerializableFieldDefinition.writeField(RequiredSerializableFieldDefinition.java:39) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.json.types.SerializableObjectTypeDefinition.serialize(SerializableObjectTypeDefinition.java:56) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.json.types.SerializableArrayTypeDefinition.serialize(SerializableArrayTypeDefinition.java:41) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.json.types.SerializableArrayTypeDefinition.serialize(SerializableArrayTypeDefinition.java:21) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.json.types.RequiredSerializableFieldDefinition.writeField(RequiredSerializableFieldDefinition.java:39) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.json.types.SerializableObjectTypeDefinition.serialize(SerializableObjectTypeDefinition.java:56) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.json.JsonUtil.lambda$serializeToBytes$1(JsonUtil.java:60) ~[classes/:?]
	at tech.pegasys.teku.infrastructure.json.JsonUtil.serializeToBytes(JsonUtil.java:67) ~[classes/:?]
	... 48 more
```

**Comment by rolfyone** [comment]
fixed by #5670
