### ISSUE TITLE
500 on POST /eth/v1/validator/{pubkey}/feerecipient

### ISSUE THREAD

**Issue by ThomasDalla** [Consensys-Incorporated/teku#5700]
### Description
I have enabled the validator API and can list the keystores. I have both read-only (imported manually in the folder) and read-write keystores (imported via the API).
When I try to set the recipient fee (`POST /eth/v1/validator/{pubkey}/feerecipient for a read-only validator` with `--data '{"ethaddress":"0xMyEth1Address"}'`, I receive a 500.

### Steps to Reproduce (Bug)

```
curl -X POST --insecure -H "Authorization: Bearer XYZ" -H "Accept: application/json" -H "Content-Type: application/json" --data '{"ethaddress":"0xMyEth1Address"}' https://127.0.0.1:5052/eth/v1/validator/{pubkey}/feerecipient
```

Reponse:
```json
{
    "code": 500,
    "message": "An unexpected error occurred"
}
```

**Expected behavior:** Either it works and returns a success, or it fails and returns a useful error message telling us why it failed.

**Actual behavior:** Return an error 500 with a generic `"An unexpected error occurred"` message.

**Frequency:** Every time I query it.

### Logs

```
2022-06-04 12:17:42.797+01:00 | qtp353489239-34 | ERROR | RestApiBuilder | Failed to process request to URL https://alderlake.tail:5062/eth/v1/validator/{{PUBKEY-REDACTED}}/feerecipient
java.util.NoSuchElementException: No value present
at java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
at tech.pegasys.teku.validator.client.restapi.apis.SetFeeRecipient.handleRequest(SetFeeRecipient.java:82) ~[teku-validator-client-22.5.2.jar:22.5.2]
at tech.pegasys.teku.infrastructure.restapi.endpoints.JavalinEndpointAdapter.handle(JavalinEndpointAdapter.java:36) ~[teku-infrastructure-restapi-22.5.2.jar:22.5.2]
at tech.pegasys.teku.infrastructure.restapi.AuthorizationManager.manage(AuthorizationManager.java:89) ~[teku-infrastructure-restapi-22.5.2.jar:22.5.2]
at io.javalin.http.JavalinServlet.addHandler$lambda-5(JavalinServlet.kt:115) ~[javalin-4.4.0.jar:4.4.0]
at io.javalin.http.JavalinServlet$service$tryBeforeAndEndpointHandlers$1.invoke(JavalinServlet.kt:44) ~[javalin-4.4.0.jar:4.4.0]
at io.javalin.http.JavalinServlet$service$tryBeforeAndEndpointHandlers$1.invoke(JavalinServlet.kt:39) ~[javalin-4.4.0.jar:4.4.0]
at io.javalin.http.JavalinServlet.service$tryWithExceptionMapper(JavalinServlet.kt:131) ~[javalin-4.4.0.jar:4.4.0]
at io.javalin.http.JavalinServlet.service$tryBeforeAndEndpointHandlers(JavalinServlet.kt:39) ~[javalin-4.4.0.jar:4.4.0]
at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:87) ~[javalin-4.4.0.jar:4.4.0]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet-api-3.1.0.jar:3.1.0]
at io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:58) ~[javalin-4.4.0.jar:4.4.0]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet-api-3.1.0.jar:3.1.0]
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) ~[jetty-servlet-9.4.45.v20220203.jar:9.4.45.v20220203]
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550) ~[jetty-servlet-9.4.45.v20220203.jar:9.4.45.v20220203]
at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
at io.javalin.jetty.JettyServer$start$wsAndHttpHandler$1.doHandle(JettyServer.kt:52) ~[javalin-4.4.0.jar:4.4.0]
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501) ~[jetty-servlet-9.4.45.v20220203.jar:9.4.45.v20220203]
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) ~[jetty-io-9.4.45.v20220203.jar:9.4.45.v20220203]
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) ~[jetty-io-9.4.45.v20220203.jar:9.4.45.v20220203]
at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:555) ~[jetty-io-9.4.45.v20220203.jar:9.4.45.v20220203]
at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:410) ~[jetty-io-9.4.45.v20220203.jar:9.4.45.v20220203]
at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164) ~[jetty-io-9.4.45.v20220203.jar:9.4.45.v20220203]
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) ~[jetty-io-9.4.45.v20220203.jar:9.4.45.v20220203]
at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) ~[jetty-io-9.4.45.v20220203.jar:9.4.45.v20220203]
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
at java.lang.Thread.run(Unknown Source) ~[?:?]
```

### Versions
* Software version: `teku/v22.5.2/linux-x86_64/-eclipseadoptium-openjdk64bitservervm-java-17`
* Java version: `OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode)`
* OS Name & Version: `Ubuntu 20.04.4 LTS`
* Docker Version: `Community 20.10.16`
* Cloud VM, type, size: `My own bare metal`

**Comment by rolfyone** [comment]
Thanks for raising.

What network are you on at the moment? Basically that's being thrown because the the network doesn't think it needs to do anything with Bellatrix...

When I tested it, bellatrix was enabled so i didnt see the 500, but I'll add a better message for that...

I had a quick look and I think that should only be only in the case where the Bellatrix milestone isn't enabled, but if you can share what network you were on it'll help me get a better understanding of why...

**Comment by ThomasDalla** [comment]
That's right, I was testing these commands on Prater/Goerli where Bellatrix isn't enabled.
An error message telling us so would be great, thanks.

**Comment by rolfyone** [comment]
ok that's great, just making sure there wasn't another scenario - thanks for clarifying.
