### ISSUE TITLE
ERROR - Unexpected error while checking TTD during Ropsten Merge

### ISSUE THREAD

**Issue by nalepae** [Consensys-Incorporated/teku#5736]
### Description
During Ropsten Merge, this error with Stack Trace appeared:
```
2022-06-08 16:08:28.220 INFO  - Slot Event  *** Slot: 65142, Block: 416bc2cf9ed9adce9c8d48763edbefbcd367f3fdd23768effa6723d9633f9b6f, Justified: 2034, Finalized: 2033, Peers: 100
2022-06-08 16:08:39.118 ERROR - Unexpected error while checking TTD
java.util.concurrent.CompletionException: java.lang.ArithmeticException: Value does not fit a 8 byte long
at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147) ~[teku-infrastructure-async-22.5.2.jar:22.5.2]
at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateToAsync$13(SafeFuture.java:269) ~[teku-infrastructure-async-22.5.2.jar:22.5.2]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:81) ~[teku-infrastructure-async-22.5.2.jar:22.5.2]
at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$2(AsyncRunner.java:38) ~[teku-infrastructure-async-22.5.2.jar:22.5.2]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:73) ~[teku-infrastructure-async-22.5.2.jar:22.5.2]
at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:119) ~[teku-infrastructure-async-22.5.2.jar:22.5.2]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ArithmeticException: Value does not fit a 8 byte long
at org.apache.tuweni.units.bigints.UInt256.toLong(UInt256.java:830) ~[tuweni-units-2.2.0.jar:2.2.0]
at tech.pegasys.teku.statetransition.forkchoice.TerminalPowBlockMonitor.checkTtdEta(TerminalPowBlockMonitor.java:327) ~[teku-ethereum-statetransition-22.5.2.jar:22.5.2]
at tech.pegasys.teku.statetransition.forkchoice.TerminalPowBlockMonitor.lambda$checkTerminalBlockByTTD$6(TerminalPowBlockMonitor.java:242) ~[teku-ethereum-statetransition-22.5.2.jar:22.5.2]
... 16 more
2022-06-08 16:08:40.220 INFO  - Slot Event  *** Slot: 65143, Block: cc5b88f79cb3e5a507c11bf1c8ea942d8f02c8f61eae30e5b74579a29c70dfdd, Justified: 2034, Finalized: 2033, Peers: 100
```

**Expected behavior:** No error appears

**Actual behavior:** Error appears

**Frequency:** 1 - during merge

### Versions (Add all that apply)
* Software version: `teku/v22.5.2/linux-aarch_64/-eclipseadoptium-openjdk64bitservervm-java-17`
* Java version: 
```
openjdk 17.0.3 2022-04-19
OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)
OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode)
```
* OS Name & Version: 
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
* Docker Version:
```
Client:
 Cloud integration: v1.0.24
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 24 01:49:20 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.8.2 (79419)
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 01:45:44 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.5.11
  GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by benjaminion** [comment]
Thanks for reporting! Also saw this elsewhere.

**Comment by tbenr** [comment]
This is a TTD estimation problem at merge. Will look into it.
