### ISSUE TITLE
Ropsten Merge - loss of websockets connection

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#5738]
A user reports the following.

`teku v22.5.2 + geth v1.10.18`

Shortly before the Merge, we had an issue connecting teku to geth via Websockets. Our configuration looked like this:

```
TEKU_EE_ENDPOINT=ws://localhost:8551
```

And we were getting the following output:

```
2022-06-08 14:36:24.100 ERROR - Unexpected error while checking TTD
java.util.concurrent.CompletionException: org.java_websocket.exceptions.WebsocketNotConnectedException
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[?:?]
at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347) ~[?:?]
at
java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1141) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:145) ~[teku-infrastructure-async-22.5.2.jar:22.5.2]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
at
java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[?:?]
Caused by: org.java_websocket.exceptions.WebsocketNotConnectedException
at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:664) ~[Java-WebSocket-1.5.2.jar:?]
at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:640) ~[Java-WebSocket-1.5.2.jar:?]
at org.java_websocket.client.WebSocketClient.send(WebSocketClient.java:431) ~[Java-WebSocket-1.5.2.jar:?]
at org.web3j.protocol.websocket.WebSocketService.sendRequest(WebSocketService.java:234) ~[core-4.9.1.jar:?]
at org.web3j.protocol.websocket.WebSocketService.sendAsync(WebSocketService.java:185) ~[core-4.9.1.jar:?]
at org.web3j.protocol.core.Request.sendAsync(Request.java:91) ~[core-4.9.1.jar:?]
at tech.pegasys.teku.ethereum.executionclient.web3j.Web3JExecutionEngineClient.getPowChainHead(Web3JExecutionEngineClient.java:68) ~[teku-ethereum-executionclient-22.5.2.jar:22.5.2]
at tech.pegasys.teku.ethereum.executionclient.ThrottlingExecutionEngineClient.lambda$getPowChainHead$1(ThrottlingExecutionEngineClient.java:56) ~[teku-ethereum-executionclient-22.5.2.jar:22.5.2]
at tech.pegasys.teku.infrastructure.async.ThrottlingTaskQueue.lambda$queueTask$0(ThrottlingTaskQueue.java:42) ~[teku-infrastructure-async-22.5.2.jar:22.5.2]
at tech.pegasys.teku.infrastructure.async.ThrottlingTaskQueue.processQueuedTasks(ThrottlingTaskQueue.java:58) ~[teku-infrastructure-async-22.5.2.jar:22.5.2]
```

Changing to http resolved the issue: `TEKU_EE_ENDPOINT=http://localhost:8551/`

After the Merge, Websockets started working again and we were unable to reproduce the issue.

**Comment by rolfyone** [comment]
It'd be good to get the logs if they're still accessible...

 - did they say "Execution Client is offline" in logs
 - did anything happen to the eth1 client (like a restart?)
 - was it prolonged or a one-off

the exception itself is because a request was made that failed to complete, but to determine if there's value in altering the output, we'd be able to reason better with a lot more context... as a default, reporting the exception trace is giving us context that we wouldn't have otherwise in this instance...

**Comment by zilm13** [comment]
I have one idea what it could be, will try to reproduce when current task is finished.
Our connection was dropped by occasion, but flag `connected` kept true, and there is no strategy to reconnect in this case
