### ISSUE TITLE
AsyncRunner queue length exceeded when calculating duties for 20k validators

### ISSUE THREAD

**Issue by q9f** [Consensys-Incorporated/teku#5790]
My validator keeps running out of disk space and apparently this is due to massive log size.

### Description

```
~ user@nunki
❯ ll ~/.local/share/teku/logs
total 193G
4.0K drwxr-xr-x 2 user users 4.0K Jun 14 00:00 ./
4.0K drwxr-xr-x 5 user users 4.0K May 18 16:55 ../
576K -rw-r--r-- 1 user users 570K May 18 23:59 teku_2022-05-18.log
1.6M -rw-r--r-- 1 user users 1.6M May 19 23:59 teku_2022-05-19.log
1.4M -rw-r--r-- 1 user users 1.4M May 20 23:59 teku_2022-05-20.log
1.4M -rw-r--r-- 1 user users 1.4M May 21 23:59 teku_2022-05-21.log
 19M -rw-r--r-- 1 user users  19M May 22 23:59 teku_2022-05-22.log
6.9M -rw-r--r-- 1 user users 6.9M May 23 23:59 teku_2022-05-23.log
 74M -rw-r--r-- 1 user users  74M May 24 23:59 teku_2022-05-24.log
1.1G -rw-r--r-- 1 user users 1.1G May 25 23:59 teku_2022-05-25.log
2.3G -rw-r--r-- 1 user users 2.3G May 26 23:59 teku_2022-05-26.log
3.4G -rw-r--r-- 1 user users 3.4G May 27 23:59 teku_2022-05-27.log
4.3G -rw-r--r-- 1 user users 4.3G May 28 23:59 teku_2022-05-28.log
5.4G -rw-r--r-- 1 user users 5.4G May 29 23:59 teku_2022-05-29.log
6.8G -rw-r--r-- 1 user users 6.8G May 30 23:59 teku_2022-05-30.log
8.1G -rw-r--r-- 1 user users 8.1G May 31 23:59 teku_2022-05-31.log
9.5G -rw-r--r-- 1 user users 9.5G Jun  1 23:59 teku_2022-06-01.log
 11G -rw-r--r-- 1 user users  11G Jun  2 23:59 teku_2022-06-02.log
 12G -rw-r--r-- 1 user users  12G Jun  3 23:59 teku_2022-06-03.log
 14G -rw-r--r-- 1 user users  14G Jun  4 23:59 teku_2022-06-04.log
 15G -rw-r--r-- 1 user users  15G Jun  5 23:59 teku_2022-06-05.log
 15G -rw-r--r-- 1 user users  15G Jun  6 23:59 teku_2022-06-06.log
 16G -rw-r--r-- 1 user users  16G Jun  7 23:59 teku_2022-06-07.log
 14G -rw-r--r-- 1 user users  14G Jun  8 23:59 teku_2022-06-08.log
 13G -rw-r--r-- 1 user users  13G Jun  9 23:59 teku_2022-06-09.log
 12G -rw-r--r-- 1 user users  12G Jun 10 23:59 teku_2022-06-10.log
4.8G -rw-r--r-- 1 user users 4.8G Jun 11 23:59 teku_2022-06-11.log
8.0G -rw-r--r-- 1 user users 8.0G Jun 12 23:59 teku_2022-06-12.log
 17G -rw-r--r-- 1 user users  17G Jun 13 23:59 teku_2022-06-13.log
4.7G -rw-r--r-- 1 user users 4.7G Jun 14 15:48 teku.log
```

### Steps to Reproduce (Bug)

Choose the Prater testnet, make 20000 deposits, run Besu Goerli and Teku Prater on the same machine, run out of disk space.

### Versions (Add all that apply)
* Software version: [`teku/v22.5.2/linux-x86_64/-na-openjdk64bitservervm-java-18`]
* Java version: [`openjdk version "18.0.1.1" 2022-04-22`]
* OS Name & Version: [`Arch Linux rolling`]
* Bare metal

### Additional Information

The validator logs are full with exceptions like:

```
2022-06-07 00:00:00.407+02:00 | TimeTick-1 | INFO  | teku-event-log | ESC[32mEpoch Event *** Epoch: 99075, Justified checkpoint: 99073, Finalized checkpoint: 99072, Finalized root: 068ae81268201845b692ef033a932c9a6f8f0c7acc03cec18d5cae5373bd8683ESC[0m
2022-06-07 00:00:00.473+02:00 | SlotEventsChannel-7 | INFO  | teku-status-log | Attestation performance: epoch 99073, expected 5010, produced 15268, included 15268 (100%), distance 1 / 2.18 / 18, correct target 15268 (100%), correct head 15268 (100%)
2022-06-07 00:00:00.473+02:00 | SlotEventsChannel-7 | INFO  | teku-status-log | Block performance: epoch 99074, expected 1, produced 1, included 1 (100%)
2022-06-07 00:00:00.474+02:00 | SlotEventsChannel-7 | INFO  | teku-status-log | Sync committee performance: epoch 99074, expected 928, produced 928, correct 928, included 841 (91%)
2022-06-07 00:00:05.467+02:00 | TimeTick-1 | INFO  | teku-event-log | ESC[37mSlot Event  *** Slot: 3170400, Block: 84bea81e9fa5daf999bb784a8cc4378fdcb9aa1e0d17c6dfb5446d9d53b3d12c, Justified: 99074, Finalized: 99073, Peers: 74ESC[0m
2022-06-07 00:00:08.163+02:00 | validator-async-4 | ERROR | AttestationDutyLoader | Failed to schedule aggregation duties
java.util.concurrent.CompletionException: java.util.concurrent.RejectedExecutionException: Task tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner$$Lambda$426/0x000000080045b520@6724bf38 rejected from java.util.concurrent.ThreadPoolExecutor@4a3aa6a6[Running, pool size = 8, active threads = 8, queued tasks = 5000, completed tasks = 66732836]
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[?:?]
at java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:674) ~[?:?]
at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662) ~[?:?]
at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.thenApply(SafeFuture.java:408) ~[teku-infrastructure-async-22.5.0.jar:22.5.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.thenPeek(SafeFuture.java:432) ~[teku-infrastructure-async-22.5.0.jar:22.5.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.alwaysRun(SafeFuture.java:297) ~[teku-infrastructure-async-22.5.0.jar:22.5.0]
at tech.pegasys.teku.core.signatures.DeletableSigner.sign(DeletableSigner.java:116) ~[teku-ethereum-core-22.5.0.jar:22.5.0]
at tech.pegasys.teku.core.signatures.DeletableSigner.signAggregationSlot(DeletableSigner.java:73) ~[teku-ethereum-core-22.5.0.jar:22.5.0]
at tech.pegasys.teku.validator.client.AttestationDutyLoader.lambda$scheduleAggregation$4(AttestationDutyLoader.java:153) ~[teku-validator-client-22.5.0.jar:22.5.0]
at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187) ~[?:?]
at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.thenCompose(SafeFuture.java:470) ~[teku-infrastructure-async-22.5.0.jar:22.5.0]
at tech.pegasys.teku.validator.client.AttestationDutyLoader.scheduleAggregation(AttestationDutyLoader.java:153) ~[teku-validator-client-22.5.0.jar:22.5.0]
at tech.pegasys.teku.validator.client.AttestationDutyLoader.scheduleDuties(AttestationDutyLoader.java:111) ~[teku-validator-client-22.5.0.jar:22.5.0]
at tech.pegasys.teku.validator.client.AttestationDutyLoader.lambda$scheduleAllDuties$0(AttestationDutyLoader.java:82) ~[teku-validator-client-22.5.0.jar:22.5.0]
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
at tech.pegasys.teku.validator.client.AttestationDutyLoader.scheduleAllDuties(AttestationDutyLoader.java:83) ~[teku-validator-client-22.5.0.jar:22.5.0]
at tech.pegasys.teku.validator.client.AttestationDutyLoader.scheduleAllDuties(AttestationDutyLoader.java:37) ~[teku-validator-client-22.5.0.jar:22.5.0]
at tech.pegasys.teku.validator.client.AbstractDutyLoader.lambda$loadDutiesForEpoch$2(AbstractDutyLoader.java:55) ~[teku-validator-client-22.5.0.jar:22.5.0]
at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147) ~[teku-infrastructure-async-22.5.0.jar:22.5.0]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887) ~[?:?]
at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:536) ~[teku-infrastructure-async-22.5.0.jar:22.5.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:32) ~[teku-infrastructure-async-22.5.0.jar:22.5.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:142) ~[teku-infrastructure-async-22.5.0.jar:22.5.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$exceptionallyCompose$27(SafeFuture.java:367) ~[teku-infrastructure-async-22.5.0.jar:22.5.0]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147) ~[teku-infrastructure-async-22.5.0.jar:22.5.0]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateToAsync$13(SafeFuture.java:269) ~[teku-infrastructure-async-22.5.0.jar:22.5.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:81) ~[teku-infrastructure-async-22.5.0.jar:22.5.0]
at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$2(AsyncRunner.java:38) ~[teku-infrastructure-async-22.5.0.jar:22.5.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:73) ~[teku-infrastructure-async-22.5.0.jar:22.5.0]
at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:119) ~[teku-infrastructure-async-22.5.0.jar:22.5.0]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

For now, I will try to pipe all logs to /dev/null. Curious if anyone else has this issue.

**Comment by ajsutton** [comment]
Teku is desperately trying to tell you that it's unable to handle the number of duties it has to calculate with that many validators.

In this particular case it's because of the need for each validator to sign the epoch number to determine if it's an aggregator. So there are 20,000 signing requests all being submitted at once and that queue happens to have a limit of 5000 so it's unable to keep up (doesn't really have much chance in this case to be honest). We'll need to increase the maximum size of that queue. Even after that it will also require a fair bit of CPU to be able to calculate duties quickly enough to get duties calculated in time with that many validators.

**Comment by q9f** [comment]
Thank you. I'll split up the validators for now!
