### ISSUE TITLE
Besu/Teku: Execution Client is offline

### ISSUE THREAD

**Issue by q9f** [Consensys-Incorporated/teku#6002]
### Description
I upgraded Besu from 22.4.2 to 22.4.4 and Teku from 22.6.0. to 22.7.0 and get the following error without changing any configuration:

```
2022-08-01 16:47:57.660 ERROR - Execution Client is offline
java.net.ConnectException: Failed to connect to /127.0.0.1:8550
at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.9.2.jar:?]
at tech.pegasys.teku.ethereum.executionclient.auth.JwtAuthHttpInterceptor.intercept(JwtAuthHttpInterceptor.java:41) ~[teku-ethereum-executionclient-22.7.0.jar:22.7.0]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154) ~[okhttp-4.9.2.jar:?]
at org.web3j.protocol.http.HttpService.performIO(HttpService.java:165) ~[core-4.9.3.jar:?]
at org.web3j.protocol.Service.send(Service.java:48) ~[core-4.9.3.jar:?]
at org.web3j.protocol.Service.lambda$sendAsync$0(Service.java:60) ~[core-4.9.3.jar:?]
at org.web3j.utils.Async.lambda$run$1(Async.java:38) ~[core-4.9.3.jar:?]
at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.net.ConnectException: Connection refused
at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
at sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[?:?]
at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:539) ~[?:?]
at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:594) ~[?:?]
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
at java.net.Socket.connect(Socket.java:633) ~[?:?]
at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128) ~[okhttp-4.9.2.jar:?]
at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295) ~[okhttp-4.9.2.jar:?]
... 25 more
2022-08-01 16:47:57.661 ERROR - An error occurred while querying remote transition configuration
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Invalid remote response: Failed to connect to /127.0.0.1:8550
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147) ~[teku-infrastructure-async-22.7.0.jar:22.7.0]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:145) ~[teku-infrastructure-async-22.7.0.jar:22.7.0]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?] 
at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[?:?]
at org.web3j.utils.Async.lambda$run$1(Async.java:40) ~[core-4.9.3.jar:?]
at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Invalid remote response: Failed to connect to /127.0.0.1:8550
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220) ~[guava-31.1-jre.jar:?]
at tech.pegasys.teku.ethereum.executionlayer.ExecutionLayerManagerImpl.unwrapResponseOrThrow(ExecutionLayerManagerImpl.java:499) ~[teku-ethereum-executionlayer-22.7.0.jar:22.7.0]
at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
... 17 more
```

### Steps to Reproduce (Bug)

Besu Config:

```
  besu \
    --data-path="/home/user/.local/share/besu" \
    --max-peers=512 \
    --rpc-http-enabled=true \
    --identity="Q9f Goerli Prater Tiaki" \
    --network=goerli \
    --engine-jwt-enabled=true \
    --engine-jwt-secret="/home/user/.ethereum/jwtsecret.hex" \
    --engine-rpc-port=8550
```

Teku Config:

```
  teku \
    --network="goerli" \
    --data-path="/home/user/.local/share/teku" \
    --ee-endpoint="http://127.0.0.1:8550" \
    --ee-jwt-secret-file="/home/user/.ethereum/jwtsecret.hex" \
    --eth1-endpoint="http://127.0.0.1:8545" \
    --rest-api-enabled=true \
    --validators-graffiti="Goerli Tiaki @q9f Teku" \
    --validators-proposer-default-fee-recipient="0xe0a2Bd4258D2768837BAa26A28fE71Dc079f84c7" \
    --metrics-enabled=true \
    --log-destination="CONSOLE"
```

**Expected behavior:** Should work as it did previously.

**Actual behavior:** Teku cannot reach Besu's engine API on port 8550.

**Frequency:** Happenend on two machines were I conducted the upgrade. A restart of both clients did not resolve this.

Notably, there are no logs indicating issues on the Besu side, however, it could also be a Besu issue?

### Versions (Add all that apply)
* Software version: `teku/v22.7.0/linux-x86_64/-na-openjdk64bitservervm-java-18`
* Java version: `openjdk version "18.0.2" 2022-07-19`
* OS Name & Version: `NAME="Arch Linux"`
* Docker Version: N/A
* Cloud VM, type, size: Ryzen 7 1700X bare metal, 64GB RAM, 2x

**Comment by ajsutton** [comment]
Is besu listening on port 8550? It seems like Teku can't connect.  Importantly besu 22.4.4 doesn't include the TTD for Goerli so it probably isn't enabling it's engine API endpoint - you'd need at least besu 22.7.0-RC2 (but I suggest using 22.7.0-RC3) or to add the TTD as an override.

**Comment by ajsutton** [comment]
Also worth noting your seeing the errors now because the Teku upgrade did add the merge config for Goerli so it's actually starting to use the `--ee-endpoint` option now, whereas before it wasn't used for anything (only the `--eth1-endpoint` option was used).

**Comment by ajsutton** [comment]
Going to close this one as the issue appears to just be that besu isn't configured correctly and so teku really can't connect to the engine API and is reporting that correctly. Let me know if I've misunderstood something though.

**Comment by q9f** [comment]
Thank you for your explanation. I was assuming that the EE endpoint is always available. 👍🏼
