### ISSUE TITLE
Unexpected error while checking TTD - "powBlock" is null (Goerli)

### ISSUE THREAD

**Issue by siladu** [Consensys-Incorporated/teku#6027]
### Description

Goerli stack of besu + teku + web3signer with 10,000 validators.
Besu and Teku were in sync and experiencing no obvious issues at the time.

```
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "tech.pegasys.teku.spec.datastructures.execution.PowBlock.getTotalDifficulty()" because "powBlock" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateToAsync$15(SafeFuture.java:295)
	at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:81)
	at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$2(AsyncRunner.java:38)
	at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:73)
	at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:119)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "tech.pegasys.teku.spec.datastructures.execution.PowBlock.getTotalDifficulty()" because "powBlock" is null
	at tech.pegasys.teku.statetransition.forkchoice.TerminalPowBlockMonitor.lambda$checkTerminalBlockByTTD$6(TerminalPowBlockMonitor.java:239)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	... 15 more
```

**Frequency:**

Occurred twice since BELLATRIX went live on Goerli. 
Other than those two, it hasn't occurred in the last 14 days (log retention period).
The logging system claims it first saw this error on 28/06/2022 but I'm not sure I trust that.

### Versions (Add all that apply)
* Software version: **22.7.0** (besu version 22.7.0-RC3)

**Comment by siladu** [comment]
> Besu and Teku were in sync and experiencing no obvious issues at the time.

Correction, these errors are preceded by "Execution Client is offline":

```
java.io.IOException: -32603: Internal error
	at tech.pegasys.teku.ethereum.executionclient.web3j.Web3JClient.lambda$doRequest$0(Web3JClient.java:69)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at org.web3j.utils.Async.lambda$run$1(Async.java:38)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by ajsutton** [comment]
Was there a reason this was reopened? #6031 fixed the error and I don't think Teku needs an issue to track besu returning an internal error.

**Comment by ajsutton** [comment]
Going to close this one again - looks like it got reopened accidentally.
