### ISSUE TITLE
Provide correct user message and exit when synced optimistically with wrong chain

### ISSUE THREAD

**Issue by zilm13** [Consensys-Incorporated/teku#6069]
### Description

Sync optimistically for a few finalized epochs and then receive a message from EL that a block before (ancestor) latest finalized is invalid. Teku cycles with exceptions after it but is not exiting. It's not clear what's wrong. 
(logging with extra debug logging next)
```
2022-08-12 16:47:06.080 INFO  - [37mSyncing     *** Target slot: 195, Head slot: 194, Waiting for execution layer sync, Connected peers: 1[0m
2022-08-12 16:47:06.086 WARN  - Payload for child of block root 0x2545ec8b5e0e1302363af2ac2cf365880ad0fec8c9ccbaa7b6f13e28290ce86b was invalid
2022-08-12 16:47:06.086 DEBUG  - node ProtoNode{blockSlot=67, stateRoot=0x9c18c7704ff1b866542d84f435fdcfcb3257a92932e86504737f67284ad10c47, blockRoot=0x92443e1aa5b4d4ae18e1bd64c15a22aa8c4520619dc90c34949a6b1dd643f9e4, parentRoot=0x776b4515e51838e2ace0a876f82530bdede0c73ba8bf148a0d742d8992a0455a, justifiedCheckpoint=Checkpoint{epoch=1, root=0xe419c4e447759bba753a2d38d4728b1449736ce7ab36abbd2741d9498c8d05a4}, finalizedCheckpoint=Checkpoint{epoch=0, root=0x0000000000000000000000000000000000000000000000000000000000000000}, unrealizedJustifiedCheckpoint=Checkpoint{epoch=1, root=0xe419c4e447759bba753a2d38d4728b1449736ce7ab36abbd2741d9498c8d05a4}, unrealizedFinalizedCheckpoint=Checkpoint{epoch=0, root=0x0000000000000000000000000000000000000000000000000000000000000000}, executionBlockHash=0xb8a70649e1187e1005c26279049d6e74a70c3100f20e3b190191837245107490, weight=2048000000000, parentIndex=Optional[66], bestChildIndex=Optional[68], bestDescendantIndex=Optional[194], validationStatus=OPTIMISTIC} marking as invalid, 0x2545ec8b5e0e1302363af2ac2cf365880ad0fec8c9ccbaa7b6f13e28290ce86b, Optional[0x8e08287be11bbbe6fdaeb65b732d3d7d7be9596cdd75326cccb9eb150d6b4689], false
2022-08-12 16:47:06.087 DEBUG  - node marked as invalid
2022-08-12 16:47:06.580 ERROR - Job DEFAULT.Timer-1 threw an unhandled Exception: 
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: ProtoArray: Finalized root is unknown 0x0676ff725c5d59cab13a22fc2d5fc49c4d1884ceefae6cccd91768c1d365ed9a
at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147) ~[teku-infrastructure-async-develop.jar:22.6.1+136-gdb6f9a1]
at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateToAsync$15(SafeFuture.java:295) ~[teku-infrastructure-async-develop.jar:22.6.1+136-gdb6f9a1]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:81) ~[teku-infrastructure-async-develop.jar:22.6.1+136-gdb6f9a1]
at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$2(AsyncRunner.java:38) ~[teku-infrastructure-async-develop.jar:22.6.1+136-gdb6f9a1]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:73) ~[teku-infrastructure-async-develop.jar:22.6.1+136-gdb6f9a1]
at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:119) ~[teku-infrastructure-async-develop.jar:22.6.1+136-gdb6f9a1]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.IllegalArgumentException: ProtoArray: Finalized root is unknown 0x0676ff725c5d59cab13a22fc2d5fc49c4d1884ceefae6cccd91768c1d365ed9a
at tech.pegasys.teku.storage.protoarray.ProtoArray.lambda$maybePrune$2(ProtoArray.java:444) ~[teku-storage-develop.jar:22.6.1+136-gdb6f9a1]
at java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
at tech.pegasys.teku.storage.protoarray.ProtoArray.maybePrune(ProtoArray.java:441) ~[teku-storage-develop.jar:22.6.1+136-gdb6f9a1]
at tech.pegasys.teku.storage.protoarray.ForkChoiceStrategy.applyUpdate(ForkChoiceStrategy.java:466) ~[teku-storage-develop.jar:22.6.1+136-gdb6f9a1]
at tech.pegasys.teku.storage.store.StoreTransactionUpdates.applyToStore(StoreTransactionUpdates.java:121) ~[teku-storage-develop.jar:22.6.1+136-gdb6f9a1]
at tech.pegasys.teku.storage.store.StoreTransaction.lambda$commit$1(StoreTransaction.java:177) ~[teku-storage-develop.jar:22.6.1+136-gdb6f9a1]
... 16 more
2022-08-12 16:47:06.587 ERROR - Job (DEFAULT.Timer-1 threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
at org.quartz.core.JobRunShell.run(JobRunShell.java:213) ~[quartz-2.3.2.jar:?]
at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) ~[quartz-2.3.2.jar:?]
Caused by: java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: ProtoArray: Finalized root is unknown 0x0676ff725c5d59cab13a22fc2d5fc49c4d1884ceefae6cccd91768c1d365ed9a
at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147) ~[teku-infrastructure-async-develop.jar:22.6.1+136-gdb6f9a1]
at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateToAsync$15(SafeFuture.java:295) ~[teku-infrastructure-async-develop.jar:22.6.1+136-gdb6f9a1]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:81) ~[teku-infrastructure-async-develop.jar:22.6.1+136-gdb6f9a1]
at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$2(AsyncRunner.java:38) ~[teku-infrastructure-async-develop.jar:22.6.1+136-gdb6f9a1]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:73) ~[teku-infrastructure-async-develop.jar:22.6.1+136-gdb6f9a1]
at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:119) ~[teku-infrastructure-async-develop.jar:22.6.1+136-gdb6f9a1]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.IllegalArgumentException: ProtoArray: Finalized root is unknown 0x0676ff725c5d59cab13a22fc2d5fc49c4d1884ceefae6cccd91768c1d365ed9a
at tech.pegasys.teku.storage.protoarray.ProtoArray.lambda$maybePrune$2(ProtoArray.java:444) ~[teku-storage-develop.jar:22.6.1+136-gdb6f9a1]
at java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
at tech.pegasys.teku.storage.protoarray.ProtoArray.maybePrune(ProtoArray.java:441) ~[teku-storage-develop.jar:22.6.1+136-gdb6f9a1]
at tech.pegasys.teku.storage.protoarray.ForkChoiceStrategy.applyUpdate(ForkChoiceStrategy.java:466) ~[teku-storage-develop.jar:22.6.1+136-gdb6f9a1]
at tech.pegasys.teku.storage.store.StoreTransactionUpdates.applyToStore(StoreTransactionUpdates.java:121) ~[teku-storage-develop.jar:22.6.1+136-gdb6f9a1]
at tech.pegasys.teku.storage.store.StoreTransaction.lambda$commit$1(StoreTransaction.java:177) ~[teku-storage-develop.jar:22.6.1+136-gdb6f9a1]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147) ~[teku-infrastructure-async-develop.jar:22.6.1+136-gdb6f9a1]
at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateToAsync$15(SafeFuture.java:295) ~[teku-infrastructure-async-develop.jar:22.6.1+136-gdb6f9a1]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:81) ~[teku-infrastructure-async-develop.jar:22.6.1+136-gdb6f9a1]
at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$2(AsyncRunner.java:38) ~[teku-infrastructure-async-develop.jar:22.6.1+136-gdb6f9a1]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:73) ~[teku-infrastructure-async-develop.jar:22.6.1+136-gdb6f9a1]
at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:119) ~[teku-infrastructure-async-develop.jar:22.6.1+136-gdb6f9a1]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
at java.lang.Thread.run(Unknown Source) ~[?:?]
2022-08-12 16:47:07.078 ERROR - Job DEFAULT.Timer-1 threw an unhandled Exception: 
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: ProtoArray: Finalized root is unknown 0x0676ff725c5d59cab13a22fc2d5fc49c4d1884ceefae6cccd91768c1d365ed9a
at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147) ~[teku-infrastructure-async-develop.jar:22.6.1+136-gdb6f9a1]
at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateToAsync$15(SafeFuture.java:295) ~[teku-infrastructure-async-develop.jar:22.6.1+136-gdb6f9a1]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:81) ~[teku-infrastructure-async-develop.jar:22.6.1+136-gdb6f9a1]
at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$2(AsyncRunner.java:38) ~[teku-infrastructure-async-develop.jar:22.6.1+136-gdb6f9a1]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:73) ~[teku-infrastructure-async-develop.jar:22.6.1+136-gdb6f9a1]
at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:119) ~[teku-infrastructure-async-develop.jar:22.6.1+136-gdb6f9a1]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.IllegalArgumentException: ProtoArray: Finalized root is unknown 0x0676ff725c5d59cab13a22fc2d5fc49c4d1884ceefae6cccd91768c1d365ed9a
at tech.pegasys.teku.storage.protoarray.ProtoArray.lambda$maybePrune$2(ProtoArray.java:444) ~[teku-storage-develop.jar:22.6.1+136-gdb6f9a1]
at java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
at tech.pegasys.teku.storage.protoarray.ProtoArray.maybePrune(ProtoArray.java:441) ~[teku-storage-develop.jar:22.6.1+136-gdb6f9a1]
at tech.pegasys.teku.storage.protoarray.ForkChoiceStrategy.applyUpdate(ForkChoiceStrategy.java:466) ~[teku-storage-develop.jar:22.6.1+136-gdb6f9a1]
at tech.pegasys.teku.storage.store.StoreTransactionUpdates.applyToStore(StoreTransactionUpdates.java:121) ~[teku-storage-develop.jar:22.6.1+136-gdb6f9a1]
at tech.pegasys.teku.storage.store.StoreTransaction.lambda$commit$1(StoreTransaction.java:177) ~[teku-storage-develop.jar:22.6.1+136-gdb6f9a1]
... 16 more
```

**Expected behavior:** [What you expect to happen]
Exit with reason message

**Comment by zilm13** [comment]
It's very unusual case btw
I'm not sure it could happen outside test

**Comment by ajsutton** [comment]
I have no idea how we managed to get into that state - normally there is an error that an invalid chain may have been finalized.  If such a case ever happened 1/3rd of validators should be slashed though so it doesn't seem like something we need to particularly polish as the network will have bigger issues if it ever occurs.
