### ISSUE TITLE
Prater sync failure with invalid public key.

### ISSUE THREAD

**Issue by mcdee** [Consensys-Incorporated/teku#6147]
### Description
Teku stops syncing on goerli/prater at slot 3047065.  Truncated error logs are:

```
Caused by: tech.pegasys.teku.bls.impl.BlsException: Deserialization of public key bytes failed: 0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
at tech.pegasys.teku.bls.impl.blst.BlstPublicKey.fromBytes(BlstPublicKey.java:43) ~[teku-infrastructure-bls-22.8.2.jar:22.8.2]
...
Caused by: java.lang.RuntimeException: BLST_ERROR: bad point encoding
at supranational.blst.blstJNI.new_P1_Affine__SWIG_1(Native Method) ~[jblst-0.3.8.jar:?]
...
2022-09-01 00:00:23.263 WARN  - Failed to process block
tech.pegasys.teku.bls.impl.BlsException: Failed to fastAggregateVerify
at tech.pegasys.teku.bls.BLS.fastAggregateVerify(BLS.java:203) ~[teku-infrastructure-bls-22.8.2.jar:22.8.2]
...
2022-09-01 00:00:23.264 WARN  - State transition error while importing block 3047065 (0xb1e4fad4c8b6042ecab18f6e0fbd815d8f3d69496837132dc2b69763323cd4e6)
```

Full log after a restart at [teku.log.gz](https://github.com/ConsenSys/teku/files/9468248/teku.log.gz)

### Steps to Reproduce (Bug)
This is reproducible on the given instance on restart, however I have not seen this on any other instance (either prater or other networks) so is not reproducible outside of this one instance (db available on request).

### Versions (Add all that apply)
Teku 22.8.2

**Comment by asanso** [comment]
@ajsutton  @mcdee was this fixed or why was it closed ?

**Comment by benjaminion** [comment]
I don't have full context any more, but the timing seems consistent with [this PR](https://github.com/ConsenSys/teku/pull/6148) - likely there was a bug that we quietly fixed via that reversion without advertising its existence. The others can comment if they can still remember.

**Comment by ajsutton** [comment]
Yeah Ben's spot on. The BLS library changed from returning `false` when verification failed to throwing an exception which caused the issue.
