### ISSUE TITLE
FATAL: Encountered a problem retrieving deposit events from eth1 endpoint

### ISSUE THREAD

**Issue by remyroy** [Consensys-Incorporated/teku#6155]
### Description
I already synced Teku on Mainnet. I resynced Geth from scratch and at some point during the time that Geth was syncing, Teku started logging a lot of these messages. It kept logging these messages even after Geth was fully in sync:

```
FATAL - PLEASE CHECK YOUR ETH1 NODE | Encountered a problem retrieving deposit events from eth1 endpoint: Expected next deposit at index 9178, but got 429274 tech.pegasys.teku.ethereum.pow.api.InvalidDepositEventsException: Expected next deposit at index 9178, but got 429274 (See log file for full stack trace)
```

I found the full stack trace in teku's own logs:

```
2022-09-04 12:24:16.811+00:00 | pool-3-thread-573 | FATAL | teku-status-log | PLEASE CHECK YOUR ETH1 NODE | Encountered a problem retrieving deposit events from eth1 endpoint: Expected next deposit at index 9178, but got 429274
tech.pegasys.teku.ethereum.pow.api.InvalidDepositEventsException: Expected next deposit at index 9178, but got 429274
at tech.pegasys.teku.ethereum.pow.api.InvalidDepositEventsException.expectedDepositAtIndex(InvalidDepositEventsException.java:26) ~[teku-ethereum-pow-api-22.9.0.jar:22.9.0]
at tech.pegasys.teku.beacon.pow.ValidatingEth1EventsPublisher.assertDepositEventIsValid(ValidatingEth1EventsPublisher.java:56) ~[teku-beacon-pow-22.9.0.jar:22.9.0]
at tech.pegasys.teku.beacon.pow.ValidatingEth1EventsPublisher.onDepositsFromBlock(ValidatingEth1EventsPublisher.java:46) ~[teku-beacon-pow-22.9.0.jar:22.9.0]
at tech.pegasys.teku.beacon.pow.DepositFetcher.postDeposits(DepositFetcher.java:228) ~[teku-beacon-pow-22.9.0.jar:22.9.0]
at tech.pegasys.teku.beacon.pow.DepositFetcher.postEventsForBlock(DepositFetcher.java:194) ~[teku-beacon-pow-22.9.0.jar:22.9.0]
at tech.pegasys.teku.beacon.pow.DepositFetcher.postDepositEvents(DepositFetcher.java:165) ~[teku-beacon-pow-22.9.0.jar:22.9.0]
at tech.pegasys.teku.beacon.pow.DepositFetcher.lambda$postDepositEvents$4(DepositFetcher.java:181) ~[teku-beacon-pow-22.9.0.jar:22.9.0]
at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147) ~[teku-infrastructure-async-22.9.0.jar:22.9.0]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147) ~[teku-infrastructure-async-22.9.0.jar:22.9.0]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887) ~[?:?]
at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:580) ~[teku-infrastructure-async-22.9.0.jar:22.9.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:32) ~[teku-infrastructure-async-22.9.0.jar:22.9.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:142) ~[teku-infrastructure-async-22.9.0.jar:22.9.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$exceptionallyCompose$30(SafeFuture.java:399) ~[teku-infrastructure-async-22.9.0.jar:22.9.0]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147) ~[teku-infrastructure-async-22.9.0.jar:22.9.0]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887) ~[?:?]
at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:580) ~[teku-infrastructure-async-22.9.0.jar:22.9.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:32) ~[teku-infrastructure-async-22.9.0.jar:22.9.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:142) ~[teku-infrastructure-async-22.9.0.jar:22.9.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$exceptionallyCompose$30(SafeFuture.java:399) ~[teku-infrastructure-async-22.9.0.jar:22.9.0]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147) ~[teku-infrastructure-async-22.9.0.jar:22.9.0]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887) ~[?:?]
at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:580) ~[teku-infrastructure-async-22.9.0.jar:22.9.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:32) ~[teku-infrastructure-async-22.9.0.jar:22.9.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:142) ~[teku-infrastructure-async-22.9.0.jar:22.9.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$exceptionallyCompose$30(SafeFuture.java:399) ~[teku-infrastructure-async-22.9.0.jar:22.9.0]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147) ~[teku-infrastructure-async-22.9.0.jar:22.9.0]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
at org.web3j.utils.Async.lambda$run$1(Async.java:38) ~[core-4.9.3.jar:?]
at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Steps to Reproduce (Bug)
I'm not sure exactly how to reproduce it. Here is how I started and configured Teku with systemd:

```ini
[Unit]
Description=Teku Ethereum Client (Mainnet)
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
User=teku
Group=teku
Restart=always
RestartSec=5
ExecStart=/usr/local/bin/teku/bin/teku \
    --network mainnet \
    --data-path /var/lib/teku \
    --validator-keys /var/lib/teku/validator_keys:/var/lib/teku/validator_keys \
    --rest-api-enabled true \
    --ee-endpoint http://127.0.0.1:8551 \
    --metrics-enabled true \
    --validators-proposer-default-fee-recipient 0x0000000000000000000000000000000000000000 \
    --initial-state https://[hidden]@eth2-beacon-mainnet.infura.io/eth/v2/debug/beacon/states/finalized \
    --ee-jwt-secret-file /var/lib/ethereum/jwttoken \
    --p2p-port [hidden]

[Install]
WantedBy=multi-user.target
```

Here is how I started and configured Geth with systemd:

```ini
[Unit]
Description=Go Ethereum Client - Geth (Mainnet)
After=network.target
Wants=network.target

[Service]
User=goeth
Group=goeth
Type=simple
Restart=always
RestartSec=5
TimeoutStopSec=180
ExecStart=geth \
    --mainnet \
    --http \
    --datadir /var/lib/goethereum \
    --metrics \
    --metrics.expensive \
    --pprof \
    --authrpc.jwtsecret=/var/lib/ethereum/jwttoken \
    --port [hidden]

[Install]
WantedBy=default.target
```

**Expected behavior:** No FATAL error in the logs during normal usage.

**Actual behavior:** A lot of FATAL errors in the logs during normal usage.

**Frequency:** It happened once.

It seems like restarting Teku fixed the issue but it kept saying that my eth1 execution client was not in sync which it was.

### Versions
* Software version: `teku/v22.9.0/linux-x86_64/-eclipseadoptium-openjdk64bitservervm-java-17`
* Java version:
```
openjdk 17.0.4.1 2022-08-12
OpenJDK Runtime Environment Temurin-17.0.4.1+1 (build 17.0.4.1+1)
OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (build 17.0.4.1+1, mixed mode, sharing)
```
* OS Name & Version:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
* Geth version:
```
Geth
Version: 1.10.23-stable
Git Commit: d901d85377c2c2f05f09f423c7d739c0feecd90a
Architecture: amd64
Go Version: go1.18.5
Operating System: linux
GOPATH=
GOROOT=go
```

**Comment by rolfyone** [comment]
Thanks for raising this one - is there any further logging that you may still have access to prior to the exception? It might help add some context if  you're able to provide it is all... 

Ideally from teku start, or from prior to it losing eth1 connection through to this message if it's not huge volumes of data? It's possible this is already gone, but I figured I'd ask in case we're lucky :)

I've tried a few different things to replicate this but have had no luck so far, so just hoping to see if anything else is happening that I'm missing...

Happy to get logs privately outside the ticket if thats preferred - i know sometimes there's extra information in there that can be annoying to filter..

**Comment by remyroy** [comment]
Here are the Teku logs: *Ask me again if you want them*
Here are the Geth logs: *Ask me again if you want them*

The Teku logs starts earlier since I tried to sync it with Besu and failed at that too. 09-03|11:46:18.976 is when I switched to Geth.

I suspect that machine might have some faulty memory module so I'm launching a memtest to exclude that cause.

**Comment by rolfyone** [comment]
That sounds like a good idea just to be sure - I'll download the teku log and just see if there's any more clues...

**Comment by rolfyone** [comment]
I've raised a new issue to put onto our backlog to better cater for this scenario, and linked it to this ticket for context, so I'll close this one, but it's really good context when we come to look at the other ticket, and prioritising. Feel free to follow #6170 if you want to track it's progress...

It looks like geth basically restarted at a fairly specific point where we're trying to download deposits in batches, and all of a sudden a batch that should exist is no longer available. In theory it could happen with other eth1 clients, although some do report slightly different which can make it easier to detect the discrepancy... 

Currently the best workaround is to restart, as described, and then the CL will go and rebuild its deposit tree.
