### ISSUE TITLE
Missed block while using teku with mev-boost

### ISSUE THREAD

**Issue by tiagocmachado** [Consensys-Incorporated/teku#6256]
### Description
Missed block while using teku with mev-boost, although not 200% it is a teku issue.

### Steps to Reproduce (Bug)
`Sep 27 21:16:23 mainnet-1 teku[1069242]: 2022-09-27 21:16:23.401 INFO  - Received Builder Bid (Block Number = 15627307, Block Hash = 0x20cd2c152dfc912d806326300d19dc1b2539b8ebbbc3e28058d654278e1aa150, MEV Reward (wei) = 104930938071142305, Gas Limit = 30000000, Gas Used = 13365982)
Sep 27 21:16:23 mainnet-1 teku[1069242]: 2022-09-27 21:16:23.978 INFO  - Received execution payload from Builder (Block Number 15627307, Block Hash = 0x20cd2c152dfc912d806326300d19dc1b2539b8ebbbc3e28058d654278e1aa150)
Sep 27 21:16:24 mainnet-1 teku[1069242]: 2022-09-27 21:16:24.671 WARN  - Payload for child of block root 0x1709fa550443b7a81760873d295d95f946e286c81fbaa25142b0a575c0945089 was invalid
Sep 27 21:16:24 mainnet-1 teku[1069242]: 2022-09-27 21:16:24.676 ERROR - Failed to import proposed block due to FAILED_STATE_TRANSITION: 3b8003dab40b74749ca6b710bb300d30fbcb227c34f02e1745df83e13eeeeecd (4790780)
Sep 27 21:16:24 mainnet-1 teku[1069242]: java.lang.IllegalStateException: Invalid ExecutionPayload: invalid bloom (remote: 74a2e92803085c02b0707008d81b05a67881004e4816a6a748598005ffe31797849221760a265203cc481d11275d1dc5e3beb020ffc33daf422ed16029fae10ca0003690980280fae877e41d9001a36306e0820897e2daee53802d59c96aa337628208420f0afe566645550610723de355975ca4133c9c05824635329decc205fa0261b983c23b5137fc4d554bc0420d04dc0a51bbd670ac68aa0cde6230882cfe0e636fef82e6bb6ac44cec8d1c200f34fdb4db8a1fc3126ca024168cb89a246d1595031a808a7976541442174ed211a396f664bc99809a3b961f93a8786d3c0038e2b82f7120921c06b0a401442a5e86d08ab861d96d4026f43c749c8a7ca3  local: 74a2e92803085c02b0707008d81b05a67881024e4816a6a748598005ffe31797849261760a265203cc481d13275d1dc5e3beb020ffc33daf422ed56029fae10ca0003690980280fae877e41d9001a36306e0820897e2daee53802d59c96aa337628208420f0afe566645550610723fe355975ca4133c9c05824635329decc205fa0261b983c23b5137fc4d554bc0420d04dc0a51bbd672ac68aa0cde6230882cfe0e637fef82e6bb6ac44cfc8d1c200f34fdb4db8a1fc3126ca024168cb89a246d15b5031a808a7976541442174ed211a396f664bc99809a3b961f93a8786d3c0038e2b82f7120925c06b0a401442a5e86d08ab861d96d4826f43c749c8a7ca3)
Sep 27 21:16:24 mainnet-1 teku[1069242]: at tech.pegasys.teku.statetransition.forkchoice.ForkChoice.importBlockAndState(ForkChoice.java:335) ~[teku-ethereum-statetransition-22.9.1.jar:22.9.1]
Sep 27 21:16:24 mainnet-1 teku[1069242]: at tech.pegasys.teku.statetransition.forkchoice.ForkChoice.lambda$onBlock$9(ForkChoice.java:303) ~[teku-ethereum-statetransition-22.9.1.jar:22.9.1]
Sep 27 21:16:24 mainnet-1 teku[1069242]: at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
Sep 27 21:16:24 mainnet-1 teku[1069242]: at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
Sep 27 21:16:24 mainnet-1 teku[1069242]: at tech.pegasys.teku.infrastructure.async.eventthread.AsyncRunnerEventThread.lambda$asSupplier$2(AsyncRunnerEventThread.java:139) ~[teku-infrastructure-async-22.9.1.jar:22.9.1]
Sep 27 21:16:24 mainnet-1 teku[1069242]: at tech.pegasys.teku.infrastructure.async.eventthread.AsyncRunnerEventThread.recordEventThreadIdAndExecute(AsyncRunnerEventThread.java:130) ~[teku-infrastructure-async-22.9.1.jar:22.9.1]
Sep 27 21:16:24 mainnet-1 teku[1069242]: at tech.pegasys.teku.infrastructure.async.eventthread.AsyncRunnerEventThread.lambda$doExecute$1(AsyncRunnerEventThread.java:113) ~[teku-infrastructure-async-22.9.1.jar:22.9.1]
Sep 27 21:16:24 mainnet-1 teku[1069242]: at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:81) ~[teku-infrastructure-async-22.9.1.jar:22.9.1]
Sep 27 21:16:24 mainnet-1 teku[1069242]: at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$2(AsyncRunner.java:47) ~[teku-infrastructure-async-22.9.1.jar:22.9.1]
Sep 27 21:16:24 mainnet-1 teku[1069242]: at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:73) ~[teku-infrastructure-async-22.9.1.jar:22.9.1]
Sep 27 21:16:24 mainnet-1 teku[1069242]: at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:119) ~[teku-infrastructure-async-22.9.1.jar:22.9.1]
Sep 27 21:16:24 mainnet-1 teku[1069242]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
Sep 27 21:16:24 mainnet-1 teku[1069242]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
Sep 27 21:16:24 mainnet-1 teku[1069242]: at java.lang.Thread.run(Thread.java:833) ~[?:?]
Sep 27 21:16:24 mainnet-1 teku[1069242]: 2022-09-27 21:16:24.678 INFO  - Validator   *** Published block              Count: 1, Slot: 4790780, Root: 3b8003dab40b74749ca6b710bb300d30fbcb227c34f02e1745df83e13eeeeecd, 13365982 (44%) gas, EL block:  20cd2c152dfc912d806326300d19dc1b2539b8ebbbc3e28058d654278e1aa150 (15627307)
Sep 27 21:16:27 mainnet-1 teku[1069242]: 2022-09-27 21:16:27.048 INFO  - Validator   *** Published sync_signature     Count: 1, Slot: 4790780, Root: 1709fa550443b7a81760873d295d95f946e286c81fbaa25142b0a575c0945089
Sep 27 21:16:27 mainnet-1 teku[1069242]: 2022-09-27 21:16:27.133 INFO  - Validator   *** Published attestation        Count: 27, Slot: 4790780, Root: 1709fa550443b7a81760873d295d95f946e286c81fbaa25142b0a575c0945089
Sep 27 21:16:27 mainnet-1 teku[1069242]: 2022-09-27 21:16:27.438 INFO  - Slot Event  *** Slot: 4790780, Block:                                                        ... empty, Justified: 149710, Finalized: 149709, Peers: 100
Sep 27 21:16:31 mainnet-1 teku[1069242]: 2022-09-27 21:16:31.078 INFO  - Validator   *** Published aggregate          Count: 4, Slot: 4790780, Root: 1709fa550443b7a81760873d295d95f946e286c81fbaa25142b0a575c0945089`

**Frequency:**
Only once

### Versions (Add all that apply)
* Software version: 22.9.1
* Java version: 17.0.4
* OS Name & Version: Ubuntu 20.04

**Comment by tiagocmachado** [comment]
relayer related issue
