### ISSUE TITLE
Unable to retrieve status for `<n>` validators

### ISSUE THREAD

**Issue by nalepae** [Consensys-Incorporated/teku#6262]
# Configuration
- EL: `geth  v1.10.23`
- BN/VC: `teku 22.9.1-jdk17`
- External Signer: `Web3Signer 22.8.1-jdk17`
- External builder: `MEV-Boost v1.3.2`

Using Geth, Teku, Web3Signer & MEV-Boost (connected to Flashbot relayer)

# Description

When all the validors keys are active, Teku VC shows this kind of logs at boot.
```
2022-09-29 13:53:37.781 INFO  - Proposer config successfully loaded. It contains the default configuration and 0 specific configuration(s).
2022-09-29 13:53:37.811 INFO  - Starting EventSource client using URI: http://mainnet-teku-beacon-b-0.mainnet-teku-beacon-b.ethereum-common:5051/eth/v1/events?topics=head
2022-09-29 13:53:37.823 INFO  - Connected to EventSource stream.
2022-09-29 13:53:37.839 INFO  - Validator   *** Successfully connected to beacon node event stream
2022-09-29 13:53:38.043 INFO  - 391 validators are in active_ongoing state.
2022-09-29 13:53:47.768 INFO  - Validator   *** Slashing protection loaded for validators: xxxxxxx, xxxxxxx, xxxxxxx, xxxxxxx, xxxxxxx, xxxxxxx, xxxxxxx, xxxxxxx, xxxxxxx, xxxxxxx, xxxxxxx, xxxxxxx, xxxxxxx, xxxxxxx, xxxxxxx, xxxxxxx, xxxxxxx, xxxxxxx, xxxxxxx, xxxxxxx… (391 total)
2022-09-29 13:53:51.784 INFO  - 391 out of 391 validator(s) registrations were successfully sent to the Beacon Node.
2022-09-29 13:53:52.275 INFO  - Validator   *** Published attestation        Count: 7, Slot: 4802967, Root: 495d47c7095d3bfaebc4c1585a509aa3879ab7ef50e962a3f9cf231c711e85f6
```

**Observed and expected:** 391/391 successful registrations

However, if I add only one validator key with no deposit at all, then Teku VC shows this kind of logs:
```
2022-09-29 15:10:30.036 INFO  - 391 validators are in active_ongoing state.
2022-09-29 15:10:30.036 WARN  - Unable to retrieve status for 1 validators.
2022-09-29 15:10:35.895 INFO  - Validator   *** Slashing protection loaded for validators: xxxxxxx, xxxxxxx, xxxxxxx, xxxxxxx, xxxxxxx, xxxxxxx, xxxxxxx, xxxxxxx, xxxxxxx, xxxxxxx, xxxxxxx, xxxxxxx, xxxxxxx, xxxxxxx, xxxxxxx, xxxxxxx, xxxxxxx, xxxxxxx, xxxxxxx, xxxxxxx… (391 total)
2022-09-29 15:10:35.897 WARN  - Validator   *** Slashing protection not loaded for validators: yyyyyyy
2022-09-29 15:10:39.667 INFO  - 200 out of 392 validator(s) registrations were successfully sent to the builder network via the Beacon Node.
2022-09-29 15:10:39.672 ERROR - Validator   *** Failed to send validator registrations to the builder network via the Beacon Node
java.util.concurrent.CompletionException: tech.pegasys.teku.api.exceptions.RemoteServiceNotAvailableException: Server error from Beacon Node API (url = http://mainnet-teku-beacon-b-0.mainnet-teku-beacon-b.ethereum-common:5051/eth/v1/validator/register_validator, status = 500, message = java.lang.IllegalArgumentException: Invalid remote response: {"code":502,"message":"no successful relay response"}
)
at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:145) ~[teku-infrastructure-async-22.9.1.jar:22.9.1]
at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.whenComplete(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:580) ~[teku-infrastructure-async-22.9.1.jar:22.9.1]
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:32) ~[teku-infrastructure-async-22.9.1.jar:22.9.1]
at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:142) ~[teku-infrastructure-async-22.9.1.jar:22.9.1]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$exceptionallyCompose$30(SafeFuture.java:399) ~[teku-infrastructure-async-22.9.1.jar:22.9.1]
at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:145) ~[teku-infrastructure-async-22.9.1.jar:22.9.1]
at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.whenComplete(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:580) ~[teku-infrastructure-async-22.9.1.jar:22.9.1]
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:32) ~[teku-infrastructure-async-22.9.1.jar:22.9.1]
at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:142) ~[teku-infrastructure-async-22.9.1.jar:22.9.1]
at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateTo(SafeFuture.java:293) ~[teku-infrastructure-async-22.9.1.jar:22.9.1]
at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:119) ~[teku-infrastructure-async-22.9.1.jar:22.9.1]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: tech.pegasys.teku.api.exceptions.RemoteServiceNotAvailableException: Server error from Beacon Node API (url = http://mainnet-teku-beacon-b-0.mainnet-teku-beacon-b.ethereum-common:5051/eth/v1/validator/register_validator, status = 500, message = java.lang.IllegalArgumentException: Invalid remote response: {"code":502,"message":"no successful relay response"}
)
at tech.pegasys.teku.validator.remote.typedef.ResponseHandler.serviceErrorHandler(ResponseHandler.java:117) ~[teku-validator-remote-22.9.1.jar:22.9.1]
at tech.pegasys.teku.validator.remote.typedef.ResponseHandler.handleResponse(ResponseHandler.java:93) ~[teku-validator-remote-22.9.1.jar:22.9.1]
at tech.pegasys.teku.validator.remote.typedef.handlers.AbstractTypeDefRequest.executeCall(AbstractTypeDefRequest.java:149) ~[teku-validator-remote-22.9.1.jar:22.9.1]
at tech.pegasys.teku.validator.remote.typedef.handlers.AbstractTypeDefRequest.postJson(AbstractTypeDefRequest.java:127) ~[teku-validator-remote-22.9.1.jar:22.9.1]
at tech.pegasys.teku.validator.remote.typedef.handlers.RegisterValidatorsRequest.sendValidatorRegistrationsAsJson(RegisterValidatorsRequest.java:77) ~[teku-validator-remote-22.9.1.jar:22.9.1]
at tech.pegasys.teku.validator.remote.typedef.handlers.RegisterValidatorsRequest.registerValidators(RegisterValidatorsRequest.java:52) ~[teku-validator-remote-22.9.1.jar:22.9.1]
at tech.pegasys.teku.validator.remote.typedef.OkHttpValidatorTypeDefClient.registerValidators(OkHttpValidatorTypeDefClient.java:101) ~[teku-validator-remote-22.9.1.jar:22.9.1]
at tech.pegasys.teku.validator.remote.RemoteValidatorApiHandler.lambda$registerValidators$30(RemoteValidatorApiHandler.java:445) ~[teku-validator-remote-22.9.1.jar:22.9.1]
at tech.pegasys.teku.validator.remote.RemoteValidatorApiHandler.lambda$sendRequest$31(RemoteValidatorApiHandler.java:451) ~[teku-validator-remote-22.9.1.jar:22.9.1]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:81) ~[teku-infrastructure-async-22.9.1.jar:22.9.1]
at tech.pegasys.teku.validator.remote.RemoteValidatorApiHandler.sendRequest(RemoteValidatorApiHandler.java:462) ~[teku-validator-remote-22.9.1.jar:22.9.1]
at tech.pegasys.teku.validator.remote.RemoteValidatorApiHandler.lambda$sendRequest$32(RemoteValidatorApiHandler.java:457) ~[teku-validator-remote-22.9.1.jar:22.9.1]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:73) ~[teku-infrastructure-async-22.9.1.jar:22.9.1]
... 4 more
2022-09-29 15:10:41.864 INFO  - Validator   *** Published attestation        Count: 12, Slot: 4803351, Root: 78cde45eafb70268d818b50a898abcfe4d3c712f688356803fa74b72e89df658
```

**Observed:** 200/392 successful registrations
**Expected:** 391/392 successful registrations

Specific VC configuration:
```
validators-proposer-blinded-blocks-enabled: true
```

Recipients configuration:
```
default_config:
  fee_recipient: zzzzz
  builder:
    enabled: true
```

Specific BN configuration:
```
builder-endpoint: http://mainnet-mev-boost:18550
validators-builder-registration-default-enabled: true
```

# Additional data
I don't really understand where does come from the number 200 (in 200/392).
Maybe Teku stops at the first error it meets.

**Comment by StefanBratanov** [comment]
Hi, this has been fixed recently https://github.com/ConsenSys/teku/pull/6229 . Basically the relays immediately throw an error if there are unknown validators and the Beacon Node did not do any filtering before this change. I suspect this is what happened. You can check the mev-boost logs for more information. 

For the moment before there is a new release with this change, you can set `builder.enabled: false` for the unknown validator in the proposer config and that will ensure no registration for it is sent to the BN.

Let me know if you have any questions. I will close the issue for now, you can reopen it if you are facing any further issues.

**Comment by nalepae** [comment]
> For the moment before there is a new release with this change, you can set builder.enabled: false for the unknown validator in the proposer config and that will ensure no registration for it is sent to the BN.

It's exactly what I did ;)

**Comment by StefanBratanov** [comment]
> > For the moment before there is a new release with this change, you can set builder.enabled: false for the unknown validator in the proposer config and that will ensure no registration for it is sent to the BN.
> 
> It's exactly what I did ;)

Great, by the way regarding `I don't really understand where does come from the number 200 (in 200/392)` Teku sends signed validator registrations in batches of 100 so essentially the third batch failed.
