### ISSUE TITLE
Problem deserializing Capella beacon states

### ISSUE THREAD

**Issue by jtraglia** [Consensys-Incorporated/teku#6588]
### Description

It seems that Teku is unable to deserialize Capella beacon states that were generated from the consensus spec tests. I've spent a little bit of time trying to figure out the issue, but I'm having trouble. So here's everything I know so far.

Am I doing this right? I would use `zcli` for comparison, but it doesn't support Capella yet.

It works for Bellatrix states just fine:

```
$ teku debug-tools pp --network=minimal BELLATRIX BeaconState ~/Projects/ethereum/consensus-spec-tests/tests/minimal/bellatrix/operations/attestation/pyspec_tests/success/pre.ssz_snappy | head
{
  "genesis_time" : "0",
  "genesis_validators_root" : "0x0a08c27fe4ece2483f9e581f78c66379a06f96e9c24cd1390594ff939b26f95b",
  "slot" : "1",
  "fork" : {
    "previous_version" : "0x01000001",
    "current_version" : "0x02000001",
    "epoch" : "0"
  },
  "latest_block_header" : {
```

But when I change it to Capella (command arg & different file path), it fails:

```
$ teku debug-tools pp --network=minimal CAPELLA BeaconState ~/Projects/ethereum/consensus-spec-tests/tests/minimal/capella/operations/attestation/pyspec_tests/success/pre.ssz_snappy
tech.pegasys.teku.infrastructure.ssz.sos.SszDeserializeException: First variable element offset doesn't match the end of fixed part
	at tech.pegasys.teku.infrastructure.ssz.schema.impl.AbstractSszContainerSchema.sszDeserializeTree(AbstractSszContainerSchema.java:305)
	at tech.pegasys.teku.infrastructure.ssz.schema.SszSchema.sszDeserialize(SszSchema.java:80)
	at tech.pegasys.teku.infrastructure.ssz.schema.SszSchema.sszDeserialize(SszSchema.java:84)
	at tech.pegasys.teku.cli.subcommand.debug.PrettyPrintCommand.prettyPrint(PrettyPrintCommand.java:111)
	at tech.pegasys.teku.cli.subcommand.debug.PrettyPrintCommand.call(PrettyPrintCommand.java:104)
	at tech.pegasys.teku.cli.subcommand.debug.PrettyPrintCommand.call(PrettyPrintCommand.java:42)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at tech.pegasys.teku.cli.BeaconNodeCommand.parse(BeaconNodeCommand.java:265)
	at tech.pegasys.teku.Teku.start(Teku.java:63)
	at tech.pegasys.teku.Teku.startFromCLIArgs(Teku.java:86)
	at tech.pegasys.teku.Teku.main(Teku.java:40)
```

This Capella minimal beacon state (zipped so that GitHub will allow it): [pre.ssz_snappy.zip](https://github.com/ConsenSys/teku/files/10211194/pre.ssz_snappy.zip)

The relevant block of code:

https://github.com/ConsenSys/teku/blob/5bf7adeb071b1722a0d017ceaa3e3fd8c66d0867/infrastructure/ssz/src/main/java/tech/pegasys/teku/infrastructure/ssz/schema/impl/AbstractSszContainerSchema.java#L304-L307

When debugging, I see that:

* `variableChildrenOffsets.getInt(0)` is 10233
* `endOffset` is 19665
* `reader.getAvailableBytes()` is 9416

Teku expects the variable sized fields to start at offset 10233, but it actually starts at 10249, which is a difference of 16.

`next_withdrawal_index` and `next_withdrawal_validator_index` (`fixedChildrenSubtrees` 17 and 18) seem wrong too:

<img width="871" alt="image" src="https://user-images.githubusercontent.com/95511699/207129328-f60a9acb-d4ce-427d-b1bc-57297689d8aa.png">

**Comment by jtraglia** [comment]
Hmm I think I found the issue. In pyspec tests, if I print the state, it shows:

```
...
withdrawal_queue: List[Withdrawal, 1099511627776] = List[Withdrawal, 1099511627776]<<len=0>>()
next_withdrawal_index: WithdrawalIndex = 0
next_partial_withdrawal_validator_index: ValidatorIndex = 0
```

And `withdrawal_queue` definitely isn't supposed to be there. That's old.

**Comment by jtraglia** [comment]
Ah man. I accidentally generated these with an old version of consensus-specs... My bad.
