### ISSUE TITLE
debug-tools db commands not working when Eip4844 fork is enabled

### ISSUE THREAD

**Issue by tbenr** [Consensys-Incorporated/teku#6715]
```shell
./teku debug-tools db dump-hot-blocks --Xtrusted-setup: /Users/tbenr/teku/infrastructure/kzg/src/testFixtures/resources/tech/pegasys/teku/kzg/trusted_setups/minimal/trusted_setup.txt
```

```
tech.pegasys.teku.kzg.KZGException: Failed to load trusted setup from /Users/tbenr/teku/infrastructure/kzg/src/testFixtures/resources/tech/pegasys/teku/kzg/trusted_setups/minimal/trusted_setup.txt
        at tech.pegasys.teku.kzg.ckzg4844.CKZG4844.loadTrustedSetup(CKZG4844.java:90)
        at tech.pegasys.teku.spec.logic.versions.eip4844.helpers.MiscHelpersEip4844.initKZG(MiscHelpersEip4844.java:57)
        at tech.pegasys.teku.spec.logic.versions.eip4844.helpers.MiscHelpersEip4844.<init>(MiscHelpersEip4844.java:50)
        at tech.pegasys.teku.spec.logic.versions.eip4844.SpecLogicEip4844.create(SpecLogicEip4844.java:92)
        at tech.pegasys.teku.spec.SpecVersion.createEip4844(SpecVersion.java:96)
        at java.base/java.util.Optional.map(Optional.java:260)
        at tech.pegasys.teku.spec.SpecVersion.create(SpecVersion.java:64)
        at tech.pegasys.teku.spec.Spec.create(Spec.java:118)
        at tech.pegasys.teku.spec.SpecFactory.create(SpecFactory.java:76)
        at tech.pegasys.teku.spec.SpecFactory.create(SpecFactory.java:41)
        at tech.pegasys.teku.networks.Eth2NetworkConfiguration$Builder.build(Eth2NetworkConfiguration.java:259)
        at tech.pegasys.teku.cli.options.Eth2NetworkOptions.createEth2NetworkConfig(Eth2NetworkOptions.java:188)
        at tech.pegasys.teku.cli.options.Eth2NetworkOptions.getNetworkConfiguration(Eth2NetworkOptions.java:178)
        at tech.pegasys.teku.cli.subcommand.debug.DebugDbCommand.createDatabase(DebugDbCommand.java:549)
        at tech.pegasys.teku.cli.subcommand.debug.DebugDbCommand.dumpHotBlocks(DebugDbCommand.java:343)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2066)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at tech.pegasys.teku.cli.BeaconNodeCommand.parse(BeaconNodeCommand.java:273)
        at tech.pegasys.teku.Teku.start(Teku.java:63)
        at tech.pegasys.teku.Teku.startFromCLIArgs(Teku.java:86)
        at tech.pegasys.teku.Teku.main(Teku.java:40)
Caused by: java.lang.RuntimeException: Trusted Setup is already loaded. Free it before loading a new one.
        at ethereum.ckzg4844.CKZG4844JNI.loadTrustedSetup(Native Method)
        at tech.pegasys.teku.kzg.ckzg4844.CKZG4844.loadTrustedSetup(CKZG4844.java:87)
        ... 28 more
```

**Comment by tbenr** [comment]
closed by https://github.com/ConsenSys/teku/pull/6718
