### ISSUE TITLE
Teku (23.1.1) sync committee stop working

### ISSUE THREAD

**Issue by tiagocmachado** [Consensys-Incorporated/teku#6752]
### Description
Suddenly attestations and sync committee  start failing 

```
Jan 31 22:42:19 ip-172-31-14-130 teku[897626]: 2023-01-31 22:42:19.009 INFO  - Validator   *** Published sync_contribution  Count: 1, Slot: 5698409, Root: d2801c36065f9782cead3b26bd2d6d3418b922dbbdb7503ddb78a8e1981e7c26
Jan 31 22:42:25 ip-172-31-14-130 teku[897626]: 2023-01-31 22:42:25.237 INFO  - Validator   *** Published sync_signature     Count: 3, Slot: 5698410, Root: aab53809ca8b315c58316718ed82f0b3d2532098cf9c3e7e9e3617cd53dc4c84
Jan 31 22:42:25 ip-172-31-14-130 teku[897626]:   topicIDs: "/eth2/4a26c58b/sync_committee_1/ssz_snappy"
Jan 31 22:42:25 ip-172-31-14-130 teku[897626]: }
Jan 31 22:42:25 ip-172-31-14-130 teku[897626]: at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:368) ~[?:?]
Jan 31 22:42:25 ip-172-31-14-130 teku[897626]: at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:377) ~[?:?]
Jan 31 22:42:25 ip-172-31-14-130 teku[897626]: at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1152) ~[?:?]
Jan 31 22:42:25 ip-172-31-14-130 teku[897626]: at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
Jan 31 22:42:25 ip-172-31-14-130 teku[897626]: at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) ~[?:?]
Jan 31 22:42:25 ip-172-31-14-130 teku[897626]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
Jan 31 22:42:25 ip-172-31-14-130 teku[897626]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
Jan 31 22:42:25 ip-172-31-14-130 teku[897626]:   topicIDs: "/eth2/4a26c58b/sync_committee_1/ssz_snappy"
Jan 31 22:42:25 ip-172-31-14-130 teku[897626]: }
Jan 31 22:42:25 ip-172-31-14-130 teku[897626]: at io.libp2p.etc.types.AsyncExtKt$anyComplete$1.lambda-1$lambda-0(AsyncExt.kt:73) ~[jvm-libp2p-minimal-0.10.0-RELEASE.jar:?]
Jan 31 22:42:25 ip-172-31-14-130 teku[897626]: at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
Jan 31 22:42:25 ip-172-31-14-130 teku[897626]: at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887) ~[?:?]
Jan 31 22:42:25 ip-172-31-14-130 teku[897626]: at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325) ~[?:?]
Jan 31 22:42:25 ip-172-31-14-130 teku[897626]: at io.libp2p.etc.types.AsyncExtKt$anyComplete$1.<init>(AsyncExt.kt:69) ~[jvm-libp2p-minimal-0.10.0-RELEASE.jar:?]
Jan 31 22:42:25 ip-172-31-14-130 teku[897626]: at io.libp2p.etc.types.AsyncExtKt.anyComplete(AsyncExt.kt:65) ~[jvm-libp2p-minimal-0.10.0-RELEASE.jar:?]
Jan 31 22:42:25 ip-172-31-14-130 teku[897626]: at io.libp2p.etc.types.AsyncExtKt.anyComplete(AsyncExt.kt:61) ~[jvm-libp2p-minimal-0.10.0-RELEASE.jar:?]
Jan 31 22:42:25 ip-172-31-14-130 teku[897626]:   topicIDs: "/eth2/4a26c58b/sync_committee_1/ssz_snappy"
Jan 31 22:42:25 ip-172-31-14-130 teku[897626]: }
```

**Actual behavior:**
Start missing attestations and sync committee participation goes to 0

**Frequency:** 
Only once till now

### Versions
* Software version: 23.1.1
* Java version: openjdk 17.0.5 2022-10-18

**Comment by rolfyone** [comment]
There's 2 aspects that I can see in this ticket
1- the information being output is excessive, largely the stack trace could be skipped, and then it's noisy but not impossible to follow. This error was changed from debug previously, so before 22.12, it would have silently failed, and you'd be missing sync committee contributions and not be aware that that's what's happening, so we've definitely taken a step in the right direction.

2- It does appear that a host disconnects, which was likely the only host on the sync committee subnet we're subscribed to. It's not clear why we don't find a new host on that subnet, but that does seem to correlate to the reason we can't publish.

Fixing the exception spam should be easy enough, and it's reasonable to expect we need to find more subscription hosts in a timely manner. hopefully this isn't something that's super difficult to replicate locally, and I can find a good solution there.

**Comment by rolfyone** [comment]
@Nashatyrev do you recall where we check we've got good subscriptions on each subnet? If not it's no bother, we'll do some discovery...

**Comment by Nashatyrev** [comment]
@rolfyone I believe the central interface is `PeerSelectionStrategy` for that. But I never had deep dive to the actual algorithms.

**Comment by rolfyone** [comment]
The remaining section of this issue is basically what's been outlined etc in #6527

I think just for tracking, we'll close this ticket, and any more work in this area is basically #6527 work.
