### ISSUE TITLE
Exception thrown at every epoch when running artemis

### ISSUE THREAD

**Issue by atoulme** [Consensys-Incorporated/teku#678]
I am running Artemis in the eth2 client test harness. It generates this exception:
```
22:15:25.302 [INFO ] - ESC[1;33m********  Processing new epoch:  ********* ESC[0m
22:15:25.302 [INFO ] - Epoch:                                  42
22:15:25.303 [WARN ] - EpochProcessingException thrown in updateJustification()
22:15:25.303 [WARN ] -   Epoch processing error: tech.pegasys.artemis.statetransition.util.EpochProcessingException: java.lang.IllegalArgumentException: There are no epoch_attestations
May 23, 2019 10:15:25 PM com.google.common.eventbus.EventBus$LoggingHandler handleException
SEVERE: Exception thrown by subscriber method onNewHeadStateEvent(tech.pegasys.artemis.statetransition.HeadStateEvent) on subscriber tech.pegasys.artemis.validator.coordinator.ValidatorCoordinator@46d63dbb when dispatching event: tech.pegasys.artemis.statetransition
.HeadStateEvent@6b1ae2a7
java.lang.IllegalArgumentException
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:127)
        at tech.pegasys.artemis.datastructures.util.BeaconStateUtil.get_block_root(BeaconStateUtil.java:559)
        at tech.pegasys.artemis.datastructures.util.AttestationUtil.createAttestations(AttestationUtil.java:613)
        at tech.pegasys.artemis.validator.coordinator.ValidatorCoordinator.onNewHeadStateEvent(ValidatorCoordinator.java:102)
        at jdk.internal.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144)
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)



```

**Comment by atoulme** [comment]
I reproduce this with 3 nodes. With 4 nodes, I see no problem.

**Comment by jrhea** [comment]
@atoulme this works from master when I run:
`cd scripts && sh run.sh -n=3`
