### ISSUE TITLE
Teku Failed to start : Illegal base64 character 20

### ISSUE THREAD

**Issue by avenbreaks** [Consensys-Incorporated/teku#6857]
### Description
Getting Error on my local testnet running teku with Geth Illegal base64 character 20 

### Steps to Reproduce (Bug)

```
./build/install/teku/bin/teku \
    --network /mnt/block-volume/test-testnet-repo/dist/config.yaml \
    --initial-state /mnt/block-volume/test-testnet-repo/dist/genesis.ssz \
    --data-path /mnt/block-volume/test-testnet-repo/pre-mine \
    --ee-endpoint http://127.0.0.1:8551 \
    --ee-jwt-secret-file /mnt/block-volume/test-testnet-repo/dist/jwtsecret \
    --log-destination console \
    --p2p-discovery-bootnodes "enr:-Iq4QGdecZrX_n9aWd0T0r3w9aVTnjbrO9nyDSMunKwxh6M3fkTuDamFtcu4Ulgq82WA7V10XJJJgDFUqrYEGAonNGiGAYSHF-YRgmlkgnY0gmlwhIjzHgyJc2VjcDI1NmsxoQJDyix-IHa_mVwLBEN9NeG8I-RUjNQK_MGxk9OqRQUAtIN1ZHCCIyg, enr:-Ly4QPOcba3y3swZ21m17fxPbdTWVngYVC7YAl2kzG01IXocTH1t7VVp0XW7O5UHVhUhv_UXPudsscsKc3B6Cw1FxBsBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpDetcgIQAAYGwUAAAAAAAAAgmlkgnY0gmlwhIe1jKiJc2VjcDI1NmsxoQLMdrbOxS8RcB7V_AHVLPQY35c7OAQo3cyks2AI8RbX54hzeW5jbmV0cwCDdGNwgiNQg3VkcIIjUA, enr:-Jq4QEMNuNIl3_LhrwB5lnLpaQ_Iqz5gpyobzYOhcAV1BXg3Dam4LpWdz2kJ6vbPEl_BjIU-oE38k6knMqc3B_2uAzwBhGV0aDKQ3rXICEAAGBsFAAAAAAAAAIJpZIJ2NIJpcISI8x4MiXNlY3AyNTZrMaEDGWOtaLxvxb2HJbUdALfvtL57LmlXp4DNXoQGWSBg61CDdWRwgiMp"
2023-02-23 17:52:43,344 main INFO Configuring logging for destination: console
2023-02-23 17:52:43,351 main INFO Logging includes events: true
2023-02-23 17:52:43,351 main INFO Logging includes validator duties: true
2023-02-23 17:52:43,352 main INFO Logging includes color: true
2023-02-23 17:52:43,376 main INFO Include P2P warnings set to: false
2023-02-23 17:52:43.776 INFO  - Ignoring unknown items in network configuration: EIP4844_FORK_EPOCH,EIP4844_FORK_VERSION
2023-02-23 17:52:44.243 INFO  - Teku version: teku/v23.2.0+21-g7cef493ac/linux-x86_64/-ubuntu-openjdk64bitservervm-java-11
2023-02-23 17:52:44.243 INFO  - This software is licensed under the Apache License, Version 2.0 (the "License"); you may not use this software except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
2023-02-23 17:52:44.261 WARN  - Configuration conflict: there is more than one oshi.properties file on the classpath: [jar:file:/mnt/block-volume/test-testnet-repo/teku/build/install/teku/lib/oshi-core-6.4.0.jar!/oshi.properties, jar:file:/mnt/block-volume/test-testnet-repo/teku/build/install/teku/lib/oshi-core-java11-6.4.0.jar!/oshi.properties]
2023-02-23 17:52:44.489 INFO  - Configuration | Network: empty, Storage Mode: PRUNE
2023-02-23 17:52:44.489 INFO  - Host Configuration | Maximum Heap Size: 29.97 GB, Total Memory: 376.54 GB, CPU Cores: 56
2023-02-23 17:52:44.489 INFO  - Rest Api Configuration | Enabled: false
2023-02-23 17:52:44.489 INFO  - Validator Api Configuration | Listen Address: 127.0.0.1, Port 5052, Allow: [127.0.0.1, localhost]
2023-02-23 17:52:44.783 INFO  - JWT secret loaded from /mnt/block-volume/test-testnet-repo/dist/jwtsecret
2023-02-23 17:52:44.787 INFO  - Using execution engine at http://127.0.0.1:8551
2023-02-23 17:52:44.787 INFO  - Enabling Builder Circuit Breaker
2023-02-23 17:52:44.826 INFO  - Execution Engine version: KILNV2
2023-02-23 17:52:44.851 INFO  - Eth1 endpoint not provided, using execution engine endpoint for eth1 data
2023-02-23 17:52:44.925 INFO  - Storing beacon chain data in: /mnt/block-volume/test-testnet-repo/pre-mine/beacon
2023-02-23 17:52:44.931 INFO  - Loading 0 validator keys...
2023-02-23 17:52:44.936 INFO  - Loaded 0 Validators: 
2023-02-23 17:52:44.942 INFO  - validator-api-enabled is false, not starting rest api.
2023-02-23 17:52:44.983 INFO  - Using optimized BLST library
2023-02-23 17:52:44.993 INFO  - Beacon data directory set to: /mnt/block-volume/test-testnet-repo/pre-mine/beacon
2023-02-23 17:52:45.145 INFO  - Created leveldb2 Hot and Finalized database (leveldb2) at /mnt/block-volume/test-testnet-repo/pre-mine/beacon/db
2023-02-23 17:52:45.216 INFO  - Using default implementation for ThreadExecutor
2023-02-23 17:52:45.232 INFO  - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2023-02-23 17:52:45.232 INFO  - Quartz Scheduler v.2.3.2 created.
2023-02-23 17:52:45.233 INFO  - RAMJobStore initialized.
2023-02-23 17:52:45.234 INFO  - Scheduler meta-data: Quartz Scheduler (v2.3.2) 'QuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 1 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2023-02-23 17:52:45.234 INFO  - Quartz scheduler 'QuartzScheduler' initialized from an externally provided properties instance.
2023-02-23 17:52:45.234 INFO  - Quartz scheduler version: 2.3.2
2023-02-23 17:52:45.267 INFO  - Initializing storage
2023-02-23 17:52:45.560 INFO  - Storage initialization complete
2023-02-23 17:52:45.560 WARN  - Not loading specified initial state as chain data already exists.
2023-02-23 17:52:45.852 INFO  - Loading generated p2p private key from: generated-node-key
2023-02-23 17:52:46.141 FATAL - Teku failed to start
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Illegal base64 character 20
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:148) ~[teku-infrastructure-async-develop.jar:23.2.0+21-g7cef493ac]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883) ~[?:?]
at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:614) ~[teku-infrastructure-async-develop.jar:23.2.0+21-g7cef493ac]
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:33) ~[teku-infrastructure-async-develop.jar:23.2.0+21-g7cef493ac]
at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:143) ~[teku-infrastructure-async-develop.jar:23.2.0+21-g7cef493ac]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$exceptionallyCompose$34(SafeFuture.java:426) ~[teku-infrastructure-async-develop.jar:23.2.0+21-g7cef493ac]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:148) ~[teku-infrastructure-async-develop.jar:23.2.0+21-g7cef493ac]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateToAsync$20(SafeFuture.java:326) ~[teku-infrastructure-async-develop.jar:23.2.0+21-g7cef493ac]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:82) ~[teku-infrastructure-async-develop.jar:23.2.0+21-g7cef493ac]
at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$2(AsyncRunner.java:47) ~[teku-infrastructure-async-develop.jar:23.2.0+21-g7cef493ac]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:74) ~[teku-infrastructure-async-develop.jar:23.2.0+21-g7cef493ac]
at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:124) ~[teku-infrastructure-async-develop.jar:23.2.0+21-g7cef493ac]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Illegal base64 character 20
at java.util.Base64$Decoder.decode0(Base64.java:746) ~[?:?]
at java.util.Base64$Decoder.decode(Base64.java:538) ~[?:?]
at java.util.Base64$Decoder.decode(Base64.java:561) ~[?:?]
at org.ethereum.beacon.discovery.schema.NodeRecordFactory.fromBase64(NodeRecordFactory.java:65) ~[discovery-22.12.0.jar:22.12.0]
at org.ethereum.beacon.discovery.schema.NodeRecordFactory.fromEnr(NodeRecordFactory.java:69) ~[discovery-22.12.0.jar:22.12.0]
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
at tech.pegasys.teku.networking.p2p.discovery.discv5.DiscV5Service.<init>(DiscV5Service.java:98) ~[teku-networking-p2p-develop.jar:23.2.0+21-g7cef493ac]
at tech.pegasys.teku.networking.p2p.discovery.DiscoveryNetworkBuilder.createDiscoveryService(DiscoveryNetworkBuilder.java:120) ~[teku-networking-p2p-develop.jar:23.2.0+21-g7cef493ac]
at tech.pegasys.teku.networking.p2p.discovery.DiscoveryNetworkBuilder.initMissingDefaults(DiscoveryNetworkBuilder.java:59) ~[teku-networking-p2p-develop.jar:23.2.0+21-g7cef493ac]
at tech.pegasys.teku.networking.p2p.discovery.DiscoveryNetworkBuilder.build(DiscoveryNetworkBuilder.java:68) ~[teku-networking-p2p-develop.jar:23.2.0+21-g7cef493ac]
at tech.pegasys.teku.networking.eth2.Eth2P2PNetworkBuilder.buildNetwork(Eth2P2PNetworkBuilder.java:368) ~[teku-networking-eth2-develop.jar:23.2.0+21-g7cef493ac]
at tech.pegasys.teku.networking.eth2.Eth2P2PNetworkBuilder.build(Eth2P2PNetworkBuilder.java:168) ~[teku-networking-eth2-develop.jar:23.2.0+21-g7cef493ac]
at tech.pegasys.teku.services.beaconchain.BeaconChainController.initP2PNetwork(BeaconChainController.java:869) ~[teku-services-beaconchain-develop.jar:23.2.0+21-g7cef493ac]
at tech.pegasys.teku.services.beaconchain.BeaconChainController.initAll(BeaconChainController.java:412) ~[teku-services-beaconchain-develop.jar:23.2.0+21-g7cef493ac]
at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783) ~[?:?]
... 27 more
Teku failed to start: java.lang.IllegalArgumentException: Illegal base64 character 20

To display full help:
teku [COMMAND] --help
```

**Expected behavior:** Connected on Geth and running

**Actual behavior:** [What actually happens]

**Frequency:** [How regularly does it occur?]

### Versions (Add all that apply)
* Software version: [`teku/v23.2.0+21-g7cef493ac/linux-x86_64/-ubuntu-openjdk64bitservervm-java-11`]
* Java version: [ `openjdk version "11.0.17" 2022-10-18` ]
* OS Name & Version: [`ubuntu`]
* Cloud VM, type, size: [`Equinix Baremetal 360GB RAM 120 Core 5TB NVMe`]

**Comment by benjaminion** [comment]
I believe this is due to the list of ENRs not being correctly quoted.

You can either remove the quotes completely as per the docs,

```
--p2p-discovery-bootnodes=enr:-Iu4QG...wgiMo,enr:-Iu4QL...wgiMo
```

or quoting each ENR separately ought to work

```
--p2p-discovery-bootnodes "enr:-Iu4QG...wgiMo", "enr:-Iu4QL...wgiMo"
```

Explanation: character 20 (hex) is a space character in ASCII. The quoted string looks like a single Base64 encoded blob to the command line interpreter, so it tries to decode the entire string as one ENR, including the space between the ENRs, which is not allowed in Base64.

**Comment by rolfyone** [comment]
Thanks for raising.
I had a quick look, and I believe it's going to be the spaces in the `p2p-discovery-bootnodes` between elements, the documentation suggests comma separated, list which looks not tolerant of spaces.
https://docs.teku.consensys.net/Reference/CLI/CLI-Syntax#p2p-discovery-bootnodes

I'd suggest removing the spaces after commas, and you should be up and running... Character 0x20 is the space character...

**Comment by rolfyone** [comment]
We should look at improving the error reporting so that it's less opaque as to what broke, because that message doesn't give anyone much help to see why things broke...

**Comment by benjaminion** [comment]
Agree with nixing the stack trace, but disagree that the message is inherently bad - I mean both you and I tracked down the issue pretty swiftly based only on the message: it did its job. What alternative could we do? "Failed to decode ENR" on it's own is much less helpful as it doesn't point to the root cause.

Suggest something like "Failed to decode ENR" _and_ include the original failure message  "Illegal base64...".

**Comment by avenbreaks** [comment]
thankyou guys! problem solved, sorry im adding space on ENR

**Comment by rolfyone** [comment]
It's no problem to raise a ticket, it's a great way of getting information and it helps the next person that sees this error :) Glad we could help!
