### ISSUE TITLE
Sync committee issues

### ISSUE THREAD

**Issue by yorickdowne** [Consensys-Incorporated/teku#7090]
### Description

I am seeing some sync committee issues with Teku, with missed duties. Logs aren't too instructive, but there is a "failed to process event queue"

**Frequency:**

Semi-regularly during this committee, see validator for history
https://beaconcha.in/validator/444933

Logs

```
eth-main-consensus-1  | 2023-04-30 22:52:40.841 ERROR - Failed to process event queue for client 937039586
eth-main-consensus-1  | java.util.concurrent.CompletionException: java.lang.IllegalStateException: s=OPEN,api=BLOCKED,sc=false,e=null
eth-main-consensus-1  | at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
eth-main-consensus-1  | at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
eth-main-consensus-1  | at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?]
eth-main-consensus-1  | at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
eth-main-consensus-1  | at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
eth-main-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:146) ~[teku-infrastructure-async-23.4.0.jar:23.4.0]
eth-main-consensus-1  | at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
eth-main-consensus-1  | at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(Unknown Source) ~[?:?]
eth-main-consensus-1  | at java.util.concurrent.CompletableFuture.whenComplete(Unknown Source) ~[?:?]
eth-main-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:626) ~[teku-infrastructure-async-23.4.0.jar:23.4.0]
eth-main-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:33) ~[teku-infrastructure-async-23.4.0.jar:23.4.0]
eth-main-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:143) ~[teku-infrastructure-async-23.4.0.jar:23.4.0]
eth-main-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$exceptionallyCompose$34(SafeFuture.java:426) ~[teku-infrastructure-async-23.4.0.jar:23.4.0]
eth-main-consensus-1  | at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
eth-main-consensus-1  | at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
eth-main-consensus-1  | at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
eth-main-consensus-1  | at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
eth-main-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:146) ~[teku-infrastructure-async-23.4.0.jar:23.4.0]
eth-main-consensus-1  | at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
eth-main-consensus-1  | at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(Unknown Source) ~[?:?]
eth-main-consensus-1  | at java.util.concurrent.CompletableFuture.whenComplete(Unknown Source) ~[?:?]
eth-main-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:626) ~[teku-infrastructure-async-23.4.0.jar:23.4.0]
eth-main-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:33) ~[teku-infrastructure-async-23.4.0.jar:23.4.0]
eth-main-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:143) ~[teku-infrastructure-async-23.4.0.jar:23.4.0]
eth-main-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateTo(SafeFuture.java:320) ~[teku-infrastructure-async-23.4.0.jar:23.4.0]
eth-main-consensus-1  | at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:124) ~[teku-infrastructure-async-23.4.0.jar:23.4.0]
eth-main-consensus-1  | at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
eth-main-consensus-1  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
eth-main-consensus-1  | at java.lang.Thread.run(Unknown Source) [?:?]
eth-main-consensus-1  | Caused by: java.lang.IllegalStateException: s=OPEN,api=BLOCKED,sc=false,e=null
eth-main-consensus-1  | at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:813) ~[jetty-server-11.0.14.jar:11.0.14]
eth-main-consensus-1  | at org.eclipse.jetty.server.HttpOutput.print(HttpOutput.java:1126) ~[jetty-server-11.0.14.jar:11.0.14]
eth-main-consensus-1  | at org.eclipse.jetty.server.HttpOutput.print(HttpOutput.java:1053) ~[jetty-server-11.0.14.jar:11.0.14]
eth-main-consensus-1  | at io.javalin.http.sse.Emitter.write(Emitter.kt:44) ~[javalin-5.4.2.jar:5.4.2]
eth-main-consensus-1  | at io.javalin.http.sse.Emitter.emit(Emitter.kt:20) ~[javalin-5.4.2.jar:5.4.2]
eth-main-consensus-1  | at io.javalin.http.sse.SseClient.sendEvent(SseClient.kt:65) ~[javalin-5.4.2.jar:5.4.2]
eth-main-consensus-1  | at io.javalin.http.sse.SseClient.sendEvent$default(SseClient.kt:62) ~[javalin-5.4.2.jar:5.4.2]
eth-main-consensus-1  | at io.javalin.http.sse.SseClient.sendEvent(SseClient.kt) ~[javalin-5.4.2.jar:5.4.2]
eth-main-consensus-1  | at tech.pegasys.teku.beaconrestapi.handlers.v1.events.EventSubscriber.lambda$processEventQueue$1(EventSubscriber.java:122) ~[teku-data-beaconrestapi-23.4.0.jar:23.4.0]
eth-main-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.fromRunnable(SafeFuture.java:155) ~[teku-infrastructure-async-23.4.0.jar:23.4.0]
eth-main-consensus-1  | at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$0(AsyncRunner.java:23) ~[teku-infrastructure-async-23.4.0.jar:23.4.0]
eth-main-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:74) ~[teku-infrastructure-async-23.4.0.jar:23.4.0]
eth-main-consensus-1  | ... 4 more

```
### Versions (Add all that apply)

v23.4.0

Stepped back down to v23.3.1, but committee for this one is about over, so not sure I get a clear read on whether 23.4 was the issue.

**Comment by yorickdowne** [comment]
Likely not a Teku version issue, or maybe even not related to Teku. I saw some 502s earlier from Vouch re sync committee response from Teku, that's why the Teku focus. Still missing things on 23.3.1

**Comment by yorickdowne** [comment]
I'm closing this. The 502 happened and the above stuff happened, but I don't think it was the root cause of my issue.
