### ISSUE TITLE
Jetty version 9.4.45.v20220203 returning java.lang.UnsupportedOperationException during Handshake

### ISSUE THREAD

**Issue by baljeetsingh79** [Consensys-Incorporated/teku#7151]
### Description
[Jetty version 9.4.45.v20220203 returning java.lang.UnsupportedOperationException during Handshake. If Oracle jdk (version 8) is FIPS (Federal Information Processing Standard) enabled then handshake is failing with java.lang.UnsupportedOperationException exception even though JSSE provider is of JDK 8 only.  It is working fine for Non FIPS enabled environments.]

### Steps to Reproduce (Bug)
[When jetty HTTP client calls for handshake using JettyHttpClientTransport class with default SSL context factory (SslContextFactory.Client())  to Jetty Server it fails with java.lang.UnsupportedOperationException). Following is the stack trace-> 
org.cometd.client.http.jetty.JettyHttpClientTransport$ResponseListener.onComplete(JettyHttpClientTransport.java:277)
    at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:218)
    at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:210)
    at org.eclipse.jetty.client.HttpExchange.notifyFailureComplete(HttpExchange.java:276)
    at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:247)
    at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:164)
    at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:819)
    at org.eclipse.jetty.client.HttpDestination.abort(HttpDestination.java:502)
    at org.eclipse.jetty.client.HttpDestination.failed(HttpDestination.java:252)
    at org.eclipse.jetty.client.AbstractConnectionPool$FutureConnection.failed(AbstractConnectionPool.java:570)
    at org.eclipse.jetty.util.Promise$Wrapper.failed(Promise.java:136)
    at org.eclipse.jetty.client.HttpClient$1$1.failed(HttpClient.java:633)
    at org.eclipse.jetty.client.AbstractConnectorHttpClientTransport.connectFailed(AbstractConnectorHttpClientTransport.java:138)
    at org.eclipse.jetty.client.AbstractConnectorHttpClientTransport$ClientSelectorManager.connectionFailed(AbstractConnectorHttpClientTransport.java:188)
    at org.eclipse.jetty.io.ManagedSelector$Connect.failed(ManagedSelector.java:966)
    at org.eclipse.jetty.io.ManagedSelector$CreateEndPoint.run(ManagedSelector.java:1077)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
]

**Expected behavior:** [The handshake should pass without the java.lang.UnsupportedOperationException]

**Actual behavior:** [handshake is failing with java.lang.UnsupportedOperationException]

**Frequency:** [Its consistently happens for every handshake request on the FIPS enabled environment.]

### Versions (Add all that apply)
* Software version: [`Jetty -- version 9.4.45.v20220203` ]
* Java version: [`java -8`]
* OS Name & Version: [Linux]
* Docker Version: [`docker version`]NA
* Cloud VM, type, size: [Amazon Web Services I3-large]NA

**Comment by lucassaldanha** [comment]
Hi! To help us better support you we need more information on what you are trying to do with Teku. Please clarify the version of Teku that you are using and the exact JDK you are running.

Another thing to note is that our minimum supported Java version to run Teku is 11 ([docs](https://docs.teku.consensys.net/get-started/install/build-from-source#prerequisites)) so my first suggestion would be to upgrade your JDK to 11.

**Comment by lucassaldanha** [comment]
Closing this ticket due to inactivity. Feel free to reopen it with the extra info if needed.
