### ISSUE TITLE
Validator retry attestation when detected a future slot

### ISSUE THREAD

**Issue by maxp1256** [Consensys-Incorporated/teku#7232]
### Description

Validator is missing slots because the slot id is too high compared to the chain

Failed to produce aggregate  Slot: 6608897 Validator: [x]
java.lang.IllegalArgumentException: Invalid params response from Beacon Node API (url = http://localhost:5051/eth/v1/validator/attestation_data?slot=6608897&committee_index=50, status = 400, message = Cannot create attestation for future slot. Requested 6608897 but current slot is 6608895)
at tech.pegasys.teku.validator.remote.typedef.ResponseHandler.defaultBadRequestHandler(ResponseHandler.java:129) ~[teku-validator-remote-23.5.0.jar:23.5.0]
at tech.pegasys.teku.validator.remote.typedef.ResponseHandler.handleResponse(ResponseHandler.java:93) ~[teku-validator-remote-23.5.0.jar:23.5.0]
at tech.pegasys.teku.validator.remote.typedef.handlers.AbstractTypeDefRequest.executeCall(AbstractTypeDefRequest.java:149) ~[teku-validator-remote-23.5.0.jar:23.5.0]

### Steps to Reproduce (Bug)

Don't know why it's happening, maybe related to high cpu load / multithreading / timesync issue

**Expected behavior:** [What you expect to happen]
attestation should be retried and not missed

**Actual behavior:** [What actually happens]
attestation is missed

**Frequency:** [How regularly does it occur?] 
10-30 times a day

### Versions (Add all that apply)
* Software version: 23.5.0
* Java version: OpenJDK 19.0.2
* OS Name & Version: Win 10 Hyper-V VM

**Comment by rolfyone** [comment]
Hey there, thanks for raising this one.

It's a bit of a complicated scenario generally, where this would occur.

Some little notes:
 - attestations are due at 4 seconds into a given slot
 - blocks are due at 0 seconds on slot.

A number of things can happen, often regenerating states for example - where the beacon-node isn't ready to accept attestation requests, and this seems to be the most common kind of scenario where this 'future slot' error occurs.
It would be worth just making sure that your BN isn't running low on resources - that you're up to date on teku version etc etc.
It's also worth checking when it happens, whether the BN has any log context about anything - like slow tick events, regenerating states...

If the BN is struggling, it's difficult to resubmit, it could actually exacerbate any issues that may be happening on the BN, so resubmitting can be problematic...

We may be able to do something in this area, I'll have to ponder options...

**Comment by maxp1256** [comment]
I've splitted validator and chain into 2 different processes on the same machine. They are both the same (latest) 23.5 version.
geth is on another VM but on the same hardware. It's definitely possible that's a cpu ressource lack, but I think that there should be a retry logic to address this issue.

Maybe relevant logs related to the chain
`
2023-06-07 11:39:53.243+02:00 | beaconchain-async-0 | INFO  | StateGenerator | Completed regeneration of state for block 0xd357c69dd0d34d3d0facd0b783ba4ef178cb4c773bb0116f08245d697b4a0623 at slot 6608832 by replaying 31 blocks. Took 17359ms

2023-06-07 11:39:53.243+02:00 | TimeTick-1 | INFO  | teku-event-log | [32mEpoch Event *** Epoch: 206528, Justified checkpoint: 206527, Finalized checkpoint: 206526, Finalized root: d357c69dd0d34d3d0facd0b783ba4ef178cb4c773bb0116f08245d697b4a0623[0m

2023-06-07 11:39:53.503+02:00 | TimeTick-1 | INFO  | teku-event-log | [32mEpoch Event *** Epoch: 206528, Justified checkpoint: 206527, Finalized checkpoint: 206526, Finalized root: d357c69dd0d34d3d0facd0b783ba4ef178cb4c773bb0116f08245d697b4a0623[0m

2023-06-07 11:40:05.170+02:00 | beaconchain-async-1 | INFO  | teku-status-log | Attestation performance: epoch 206526, expected 1, produced 0, included 0 (0%), distance 0 / 0,00 / 0, correct target 0 (0%), correct head 0 (0%)

2023-06-07 11:40:22.110+02:00 | beaconchain-async-1 | INFO  | StateGenerator | Completed regeneration of state for block 0x9a93fb4a48b3c007bdbe8f878862e82b5680788fb5b711bee0a42d08c49abd34 at slot 6608896 by replaying 1 blocks. Took 9139ms

2023-06-07 11:40:22.484+02:00 | beaconchain-async-3 | INFO  | StateGenerator | Completed regeneration of state for block 0x06ec26b3b15f28704754a786381276563b51c16ec53e7973cf8d88c8e90ec7ef at slot 6608864 by replaying 63 blocks. Took 50562ms

2023-06-07 11:40:23.147+02:00 | TimeTick-1 | INFO  | teku-event-log | [37mSlot Event  *** Slot: 6608896, Block:                                                        ... empty, Justified: 206527, Finalized: 206526, Peers: 65[0m

2023-06-07 11:40:23.500+02:00 | TimeTick-1 | INFO  | teku-event-log | [37mMiss slots  *** Current slot: 6608900, previous slot: 6608897[0m

2023-06-07 11:40:27.113+02:00 | TimeTick-1 | INFO  | teku-event-log | [37mSlot Event  *** Slot: 6608900, Block: 559b40d6e59a8762ee73877002cb01ff4fffa422e4af2c7a57969bea0df93ad7, Justified: 206527, Finalized: 206526, Peers: 65[0m

2023-06-07 11:40:39.081+02:00 | TimeTick-1 | INFO  | teku-event-log | [37mSlot Event  *** Slot: 6608901, Block: f33918110f67722f95e599a9cfe7d44eae7bcb444cdfd50705f7131136b549dd, Justified: 206527, Finalized: 206526, Peers: 65[0m
`

**Comment by rolfyone** [comment]
Just a heads up on this one, teku `23.6.0` will greatly reduce state regeneration, would be worth seeing if that improves your situation...

**Comment by rolfyone** [comment]
I should also follow up on where we're at regarding discussions.

I think the TL/DR; is that that retrying against a node that's struggling is going to increase the struggles of the BN, and it'll not go well.

Our ideal situation here is that the attached BN isn't struggling.

In situations where we are struggling, the ideal would be a failure from the first BN (current behaviour), and then the VC can decide to call to another connected BN to get an attestation that it can sign. This failover makes a lot of sense and will let the primary BN concentrate on coming back to a 'healthy' state.

The teku VC will likely continue as is in regards to not retrying against the primary node if it's already failed, as a subsequent call is likely to also fail, and we'd be out of time to try other resources that we may have available.

I'm going to put this into the list for investigation, to make sure that the first failure will failover to a secondary BN if it's available, so that we have the best chance to produce an attestation for the duty. If @mehdi-aouadi knows the answer then this may be a very short investigation, otherwise we'll go through the process.

**Comment by mehdi-aouadi** [comment]
> I should also follow up on where we're at regarding discussions.
> 
> I think the TL/DR; is that that retrying against a node that's struggling is going to increase the struggles of the BN, and it'll not go well.
> 
> Our ideal situation here is that the attached BN isn't struggling.
> 
> In situations where we are struggling, the ideal would be a failure from the first BN (current behaviour), and then the VC can decide to call to another connected BN to get an attestation that it can sign. This failover makes a lot of sense and will let the primary BN concentrate on coming back to a 'healthy' state.
> 
> The teku VC will likely continue as is in regards to not retrying against the primary node if it's already failed, as a subsequent call is likely to also fail, and we'd be out of time to try other resources that we may have available.
> 
> I'm going to put this into the list for investigation, to make sure that the first failure will failover to a secondary BN if it's available, so that we have the best chance to produce an attestation for the duty. If @mehdi-aouadi knows the answer then this may be a very short investigation, otherwise we'll go through the process.

That's correct: If there are failover BNs configured, the requests will be sent to the primary BN if marked ready otherwise they will be retried against each configured failover until we get a successful response. If all the requests fail, then a `FailoverRequestException` is thrown and we fail to respond.
Even if the primary BN is marked ready but the request fails it will be retried against the configured failover BNs. In that case you should see logs like this: `Remote request ({}) to the primary Beacon Node {} failed. Will try sending the request to one of the configured failovers.`

When the primary BN is marked not ready and hence the request is retried against configured failover BNs, you should see logs like this: `Remote request ({}) will NOT be sent to the primary Beacon Node {} because it is NOT ready. Will try sending the request to one of the configured failovers.`

**Comment by rolfyone** [comment]
Closing - not planned currently.

As stated above, its an exponential problem if we retry continually.
