### ISSUE TITLE
Failure to start during upgrade 23.5.0 -> 23.6.0

### ISSUE THREAD

**Issue by NoahStahl** [Consensys-Incorporated/teku#7269]
After swapping in the latest `23.6.0` from previous `23.5.0` and starting Teku, encountered the exception below with a failure to start.

I was able to work around by:

1. Starting `23.5.0` again
2. Stopping
3. Switching back to `23.6.0`, starting

It seems to have been transient in my setup, all is working now. Just thought I'd file in case it repros for others or it sparks something to look into. Feel free to close if not actionable.

```
2023-06-17 10:59:41.166-05:00 | beaconchain-async-0 | INFO  | teku-status-log | Initializing storage
2023-06-17 10:59:41.791-05:00 | validator-async-0 | INFO  | teku-status-log | Loaded 1 Validators: xxxxxxx
2023-06-17 10:59:41.791-05:00 | validator-async-0 | INFO  | ValidatorClientService | validator-api-enabled is false, not starting rest api.
2023-06-17 10:59:44.494-05:00 | beaconchain-async-1 | FATAL | teku-status-log | Failed to initialize storage. Check the existing database matches the current network configuration. Set log level to debug for more information.
2023-06-17 10:59:44.510-05:00 | main | FATAL | BeaconNodeCommand | Teku failed to start
java.util.concurrent.CompletionException: java.lang.RuntimeException: org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: D:\teku\data\beacon\db\6330508.sst: Could not create random access file.
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[?:?]
at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347) ~[?:?]
at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:636) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:146) ~[teku-infrastructure-async-23.6.0.jar:23.6.0]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887) ~[?:?]
at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:626) ~[teku-infrastructure-async-23.6.0.jar:23.6.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:33) ~[teku-infrastructure-async-23.6.0.jar:23.6.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:143) ~[teku-infrastructure-async-23.6.0.jar:23.6.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$exceptionallyCompose$34(SafeFuture.java:426) ~[teku-infrastructure-async-23.6.0.jar:23.6.0]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:146) ~[teku-infrastructure-async-23.6.0.jar:23.6.0]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateToAsync$22(SafeFuture.java:329) ~[teku-infrastructure-async-23.6.0.jar:23.6.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:82) ~[teku-infrastructure-async-23.6.0.jar:23.6.0]
at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$2(AsyncRunner.java:47) ~[teku-infrastructure-async-23.6.0.jar:23.6.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:74) ~[teku-infrastructure-async-23.6.0.jar:23.6.0]
at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:124) ~[teku-infrastructure-async-23.6.0.jar:23.6.0]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: D:\teku\data\beacon\db\6330508.sst: Could not create random access file.
at org.fusesource.leveldbjni.internal.JniDBIterator.next(JniDBIterator.java:102) ~[leveldbjni-1.8.jar:1.8]
at org.fusesource.leveldbjni.internal.JniDBIterator.next(JniDBIterator.java:45) ~[leveldbjni-1.8.jar:1.8]
at tech.pegasys.teku.storage.server.leveldb.LevelDbIterator.next(LevelDbIterator.java:64) ~[teku-storage-23.6.0.jar:23.6.0]
at tech.pegasys.teku.storage.server.leveldb.LevelDbIterator.next(LevelDbIterator.java:29) ~[teku-storage-23.6.0.jar:23.6.0]
at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
at tech.pegasys.teku.storage.server.kvstore.KvStoreDatabase.buildHotBlockMetadata(KvStoreDatabase.java:266) ~[teku-storage-23.6.0.jar:23.6.0]
at tech.pegasys.teku.storage.server.kvstore.KvStoreDatabase.createMemoryStore(KvStoreDatabase.java:639) ~[teku-storage-23.6.0.jar:23.6.0]
at tech.pegasys.teku.storage.server.kvstore.KvStoreDatabase.createMemoryStore(KvStoreDatabase.java:619) ~[teku-storage-23.6.0.jar:23.6.0]
at tech.pegasys.teku.storage.server.ChainStorage.getStore(ChainStorage.java:74) ~[teku-storage-23.6.0.jar:23.6.0]
at tech.pegasys.teku.storage.server.ChainStorage.onStoreRequest(ChainStorage.java:90) ~[teku-storage-23.6.0.jar:23.6.0]
... 5 more
Caused by: org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: D:\teku\data\beacon\db\6330508.sst: Could not create random access file.
at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200) ~[leveldbjni-1.8.jar:1.8]
at org.fusesource.leveldbjni.internal.NativeIterator.checkStatus(NativeIterator.java:121) ~[leveldbjni-1.8.jar:1.8]
at org.fusesource.leveldbjni.internal.NativeIterator.next(NativeIterator.java:157) ~[leveldbjni-1.8.jar:1.8]
at org.fusesource.leveldbjni.internal.JniDBIterator.next(JniDBIterator.java:100) ~[leveldbjni-1.8.jar:1.8]
at org.fusesource.leveldbjni.internal.JniDBIterator.next(JniDBIterator.java:45) ~[leveldbjni-1.8.jar:1.8]
at tech.pegasys.teku.storage.server.leveldb.LevelDbIterator.next(LevelDbIterator.java:64) ~[teku-storage-23.6.0.jar:23.6.0]
at tech.pegasys.teku.storage.server.leveldb.LevelDbIterator.next(LevelDbIterator.java:29) ~[teku-storage-23.6.0.jar:23.6.0]
at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
at tech.pegasys.teku.storage.server.kvstore.KvStoreDatabase.buildHotBlockMetadata(KvStoreDatabase.java:266) ~[teku-storage-23.6.0.jar:23.6.0]
at tech.pegasys.teku.storage.server.kvstore.KvStoreDatabase.createMemoryStore(KvStoreDatabase.java:639) ~[teku-storage-23.6.0.jar:23.6.0]
at tech.pegasys.teku.storage.server.kvstore.KvStoreDatabase.createMemoryStore(KvStoreDatabase.java:619) ~[teku-storage-23.6.0.jar:23.6.0]
at tech.pegasys.teku.storage.server.ChainStorage.getStore(ChainStorage.java:74) ~[teku-storage-23.6.0.jar:23.6.0]
at tech.pegasys.teku.storage.server.ChainStorage.onStoreRequest(ChainStorage.java:90) ~[teku-storage-23.6.0.jar:23.6.0]
... 5 more
```

### Steps to Reproduce (Bug)

(Only occurred once)
1. Stop `23.5.0` process
2. Start `23.6.0` process
3. Observe failure to start with above exception in logs

### Versions (Add all that apply)
* Software version: `23.5.0` -> `23.6.0`
* Java version: 17.0.2
* OS Name & Version: Windows 10

**Comment by rolfyone** [comment]
This sounds suspiciously like something wasn't fully shutdown on the first attempt, but the error from leveldb isn't super helpful.
Glad it was resolved, will close this for now but if you see it again we'll have a go at reproducing... I've upgraded a fair few nodes and not seen this so it's a bit of a mystery but the stack trace could be helpful if there's more instances.
