### ISSUE TITLE
Exception in duty generation when a node is way out of sync

### ISSUE THREAD

**Issue by tbenr** [Consensys-Incorporated/teku#7281]
```
2023-06-20 15:35:16.233 ERROR - Failed to request validator duties for epoch 965. Retrying after delay.
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: compute_proposer_index indices must not be empty
at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.uniApplyNow(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.uniApplyStage(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.thenApply(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.thenApply(SafeFuture.java:467) ~[teku-infrastructure-async-develop.jar:23.6.0+11-gb53ae0fe99]
at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.getProposerDuties(ValidatorApiHandler.java:263) ~[teku-beacon-validator-develop.jar:23.6.0+11-gb53ae0fe99]
at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:74) ~[teku-infrastructure-events-develop.jar:23.6.0+11-gb53ae0fe99]
at tech.pegasys.teku.infrastructure.events.DirectEventDeliverer.deliverToWithResponse(DirectEventDeliverer.java:67) ~[teku-infrastructure-events-develop.jar:23.6.0+11-gb53ae0fe99]
at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer.lambda$deliverToWithResponse$1(AsyncEventDeliverer.java:80) ~[teku-infrastructure-events-develop.jar:23.6.0+11-gb53ae0fe99]
at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:125) ~[teku-infrastructure-events-develop.jar:23.6.0+11-gb53ae0fe99]
at tech.pegasys.teku.infrastructure.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:116) ~[teku-infrastructure-events-develop.jar:23.6.0+11-gb53ae0fe99]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalArgumentException: compute_proposer_index indices must not be empty
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.0.0-jre.jar:?]
at tech.pegasys.teku.spec.logic.common.helpers.MiscHelpers.computeProposerIndex(MiscHelpers.java:94) ~[teku-ethereum-spec-develop.jar:23.6.0+11-gb53ae0fe99]
at tech.pegasys.teku.spec.logic.common.helpers.BeaconStateAccessors.lambda$getBeaconProposerIndex$4(BeaconStateAccessors.java:204) ~[teku-ethereum-spec-develop.jar:23.6.0+11-gb53ae0fe99]
at tech.pegasys.teku.infrastructure.collections.cache.LRUCache.get(LRUCache.java:57) ~[teku-infrastructure-collections-develop.jar:23.6.0+11-gb53ae0fe99]
at tech.pegasys.teku.spec.logic.common.helpers.BeaconStateAccessors.getBeaconProposerIndex(BeaconStateAccessors.java:197) ~[teku-ethereum-spec-develop.jar:23.6.0+11-gb53ae0fe99]
at tech.pegasys.teku.spec.Spec.getBeaconProposerIndex(Spec.java:421) ~[teku-ethereum-spec-develop.jar:23.6.0+11-gb53ae0fe99]
at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.getProposalSlotsForEpoch(ValidatorApiHandler.java:845) ~[teku-beacon-validator-develop.jar:23.6.0+11-gb53ae0fe99]
at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.getProposerDutiesFromIndicesAndState(ValidatorApiHandler.java:681) ~[teku-beacon-validator-develop.jar:23.6.0+11-gb53ae0fe99]
at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.lambda$getProposerDuties$7(ValidatorApiHandler.java:265) ~[teku-beacon-validator-develop.jar:23.6.0+11-gb53ae0fe99]
at java.util.Optional.map(Unknown Source) ~[?:?]
at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.lambda$getProposerDuties$8(ValidatorApiHandler.java:265) ~[teku-beacon-validator-develop.jar:23.6.0+11-gb53ae0fe99]
... 16 more
```

**Comment by macfarla** [comment]
Not sure if this is caused by the above but also noticed a division by zero exc
```Caused by: java.lang.IllegalArgumentException: compute_proposer_index indices must not be empty
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.0.1-jre.jar:?]
at tech.pegasys.teku.spec.logic.common.helpers.MiscHelpers.computeProposerIndex(MiscHelpers.java:94) ~[teku-ethereum-spec-develop.jar:23.6.0+18-g7f8afd784]
at tech.pegasys.teku.spec.logic.common.helpers.BeaconStateAccessors.lambda$getBeaconProposerIndex$4(BeaconStateAccessors.java:204) ~[teku-ethereum-spec-develop.jar:23.6.0+18-g7f8afd784]
at tech.pegasys.teku.infrastructure.collections.cache.LRUCache.get(LRUCache.java:57) ~[teku-infrastructure-collections-develop.jar:23.6.0+18-g7f8afd784]
at tech.pegasys.teku.spec.logic.common.helpers.BeaconStateAccessors.getBeaconProposerIndex(BeaconStateAccessors.java:197) ~[teku-ethereum-spec-develop.jar:23.6.0+18-g7f8afd784]
at tech.pegasys.teku.spec.Spec.getBeaconProposerIndex(Spec.java:421) ~[teku-ethereum-spec-develop.jar:23.6.0+18-g7f8afd784]
at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.getProposalSlotsForEpoch(ValidatorApiHandler.java:845) ~[teku-beacon-validator-develop.jar:23.6.0+18-g7f8afd784]
at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.getProposerDutiesFromIndicesAndState(ValidatorApiHandler.java:681) ~[teku-beacon-validator-develop.jar:23.6.0+18-g7f8afd784]
at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.lambda$getProposerDuties$7(ValidatorApiHandler.java:265) ~[teku-beacon-validator-develop.jar:23.6.0+18-g7f8afd784]
at java.util.Optional.map(Unknown Source) ~[?:?]
at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.lambda$getProposerDuties$8(ValidatorApiHandler.java:265) ~[teku-beacon-validator-develop.jar:23.6.0+18-g7f8afd784]
... 16 more
2023-06-20 21:48:51.000 WARN  - Validator   *** Skipped producing sync_signature while node is syncing  Count: 1, Slot: 32767
2023-06-20 21:48:51.001 INFO  - Slot Event  *** Slot: 32767, Block:                                                        ... empty, Justified: 830, Finalized: 829, Peers: 6
2023-06-20 21:48:51.009 ERROR - Failed to calculate payload attributes for slot 32768
java.util.concurrent.CompletionException: java.lang.ArithmeticException: / by zero
at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.uniApplyNow(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.uniApplyStage(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.thenApply(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.thenApply(SafeFuture.java:467) ~[teku-infrastructure-async-develop.jar:23.6.0+18-g7f8afd784]
at tech.pegasys.teku.dataproviders.generators.StateAtSlotTask.performTask(StateAtSlotTask.java:96) ~[teku-ethereum-dataproviders-develop.jar:23.6.0+18-g7f8afd784]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:74) ~[teku-infrastructure-async-develop.jar:23.6.0+18-g7f8afd784]
at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:124) ~[teku-infrastructure-async-develop.jar:23.6.0+18-g7f8afd784]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by tbenr** [comment]
devnet6 was leaking very aggressively and `EJECTION_BALANCE` is set to `31000000000` so we ended up having no active validators on our local fork.

I replicated on a local interop testnet with super high inactivity penalties. This is the moment when last 4 exiting validators are actually kicked out of the network:

<img width="1381" alt="image" src="https://github.com/ConsenSys/teku/assets/15999009/d8111e82-5e6a-43f7-b581-84c4e25b214c">

**Comment by tbenr** [comment]
@macfarla can't find right now where the div by 0 occurs but most likely related to complete absence of active validators.
Don't think is that important to handle this case more gracefully

**Comment by tbenr** [comment]
going to close the issue
