### ISSUE TITLE
Teku fails to start with Capella fork at Epoch 0 in Genesis State

### ISSUE THREAD

**Issue by barnabasbusa** [Consensys-Incorporated/teku#7340]
## Description
As we are approaching Deneb, it would be great if clients would be able to start from a Capella state instead of Bellatrix.

## Present Behaviour
If `capella_fork_epoch=0` teku produces this error message: 
```
2023-07-07 10:29:43.475 INFO  - Loading initial state from /genesis/output/genesis.ssz
  2023-07-07 10:29:43.775 ERROR - Failed to load initial state from /genesis/output/genesis.ssz : 
  tech.pegasys.teku.infrastructure.ssz.sos.SszDeserializeException: First variable element offset doesn't match the end of fixed part
  at tech.pegasys.teku.infrastructure.ssz.schema.impl.AbstractSszContainerSchema.sszDeserializeTree(AbstractSszContainerSchema.java:305) ~[teku-infrastructure-ssz-develop.jar:23.6.1+16-gbc8992932]
  at tech.pegasys.teku.infrastructure.ssz.schema.SszSchema.sszDeserialize(SszSchema.java:80) ~[teku-infrastructure-ssz-develop.jar:23.6.1+16-gbc8992932]
  at tech.pegasys.teku.infrastructure.ssz.schema.SszSchema.sszDeserialize(SszSchema.java:84) ~[teku-infrastructure-ssz-develop.jar:23.6.1+16-gbc8992932]
  at tech.pegasys.teku.spec.Spec.deserializeBeaconState(Spec.java:316) ~[teku-ethereum-spec-develop.jar:23.6.1+16-gbc8992932]
  at tech.pegasys.teku.spec.datastructures.util.ChainDataLoader.loadState(ChainDataLoader.java:24) ~[teku-ethereum-spec-develop.jar:23.6.1+16-gbc8992932]
  at tech.pegasys.teku.services.beaconchain.WeakSubjectivityInitializer.getAnchorPoint(WeakSubjectivityInitializer.java:88) ~[teku-services-beaconchain-develop.jar:23.6.1+16-gbc8992932]
  at tech.pegasys.teku.services.beaconchain.WeakSubjectivityInitializer.lambda$loadInitialAnchorPoint$0(WeakSubjectivityInitializer.java:52) ~[teku-services-beaconchain-develop.jar:23.6.1+16-gbc8992932]
  at java.util.Optional.map(Unknown Source) ~[?:?]
  at tech.pegasys.teku.services.beaconchain.WeakSubjectivityInitializer.loadInitialAnchorPoint(WeakSubjectivityInitializer.java:48) ~[teku-services-beaconchain-develop.jar:23.6.1+16-gbc8992932]
  at tech.pegasys.teku.services.beaconchain.BeaconChainController.setupInitialState(BeaconChainController.java:1180) ~[teku-services-beaconchain-develop.jar:23.6.1+16-gbc8992932]
  at tech.pegasys.teku.services.beaconchain.BeaconChainController.lambda$initialize$11(BeaconChainController.java:392) ~[teku-services-beaconchain-develop.jar:23.6.1+16-gbc8992932]
  at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
  at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
  at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
  at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:148) ~[teku-infrastructure-async-develop.jar:23.6.1+16-gbc8992932]
  at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
  at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
  at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
  at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
  at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateToAsync$20(SafeFuture.java:326) ~[teku-infrastructure-async-develop.jar:23.6.1+16-gbc8992932]
  at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:82) ~[teku-infrastructure-async-develop.jar:23.6.1+16-gbc8992932]
  at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$2(AsyncRunner.java:47) ~[teku-infrastructure-async-develop.jar:23.6.1+16-gbc8992932]
  at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:74) ~[teku-infrastructure-async-develop.jar:23.6.1+16-gbc8992932]
  at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:124) ~[teku-infrastructure-async-develop.jar:23.6.1+16-gbc8992932]
  at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
  at java.lang.Thread.run(Unknown Source) [?:?]
  2023-07-07 10:29:43.816 FATAL - Failed to load initial state from /genesis/output/genesis.ssz : First variable element offset doesn't match the end of fixed part
  tech.pegasys.teku.infrastructure.exceptions.InvalidConfigurationException: Failed to load initial state from /genesis/output/genesis.ssz : First variable element offset doesn't match the end of fixed part
  at tech.pegasys.teku.services.beaconchain.WeakSubjectivityInitializer.lambda$loadInitialAnchorPoint$0(WeakSubjectivityInitializer.java:76) ~[teku-services-beaconchain-develop.jar:23.6.1+16-gbc8992932]
  at java.util.Optional.map(Unknown Source) ~[?:?]
  at tech.pegasys.teku.services.beaconchain.WeakSubjectivityInitializer.loadInitialAnchorPoint(WeakSubjectivityInitializer.java:48) ~[teku-services-beaconchain-develop.jar:23.6.1+16-gbc8992932]
  at tech.pegasys.teku.services.beaconchain.BeaconChainController.setupInitialState(BeaconChainController.java:1180) ~[teku-services-beaconchain-develop.jar:23.6.1+16-gbc8992932]
  at tech.pegasys.teku.services.beaconchain.BeaconChainController.lambda$initialize$11(BeaconChainController.java:392) ~[teku-services-beaconchain-develop.jar:23.6.1+16-gbc8992932]
  at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
  at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
  at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
  at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:148) ~[teku-infrastructure-async-develop.jar:23.6.1+16-gbc8992932]
  at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
  at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
  at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
  at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
  at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateToAsync$20(SafeFuture.java:326) ~[teku-infrastructure-async-develop.jar:23.6.1+16-gbc8992932]
  at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:82) ~[teku-infrastructure-async-develop.jar:23.6.1+16-gbc8992932]
  at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$2(AsyncRunner.java:47) ~[teku-infrastructure-async-develop.jar:23.6.1+16-gbc8992932]
  at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:74) ~[teku-infrastructure-async-develop.jar:23.6.1+16-gbc8992932]
  at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:124) ~[teku-infrastructure-async-develop.jar:23.6.1+16-gbc8992932]
  at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
  at java.lang.Thread.run(Unknown Source) ~[?:?]
  Failed to load initial state from /genesis/output/genesis.ssz : First variable element offset doesn't match the end of fixed part
```

## Expected Behaviour
Teku should be able to handle capella at epoch 0

## Steps to resolve
Create a testnet where you configure the genesis file and set the capella fork epoch at 0. 

## Version
* Docker: "consensys/teku:develop"
* Software version: teku/v23.6.1+16-gbc8992932/linux-x86_64/-eclipseadoptium-openjdk64bitservervm-java-17
* Irrelevant what is it running on

**Comment by barnabasbusa** [comment]
Issue has been resolved. It was a config issue on my end. Sorry for the noise.
