### ISSUE TITLE
Teku fails if web3signer isn't up yet

### ISSUE THREAD

**Issue by yorickdowne** [Consensys-Incorporated/teku#7422]
### Description

Teku `v23.8.0` fails but does not exit with `ERROR - PLEASE FIX OR REPORT | Unexpected exception thrown for validator-async-0` when starting it alongside web3signer and web3signer is not yet up. This keeps validators from being loaded, and Teku from executing their duties.

The parameters for remote signing are `--validators-external-signer-url http://web3signer:9000 --validators-external-signer-public-keys external-signer`

### Steps to Reproduce (Bug)

- Configure Teku and web3signer
- Start both at the same time, so Teku looks for web3signer before it can respond

**Expected behavior:** [What you expect to happen]

Teku continues trying web3signer until it can be reached

**Frequency:** [How regularly does it occur?]

Reproducible

### Versions (Add all that apply)
* Software version: v23.8.0
* web3signer version: v23.6.0

### Logs

```
eth-docker-devel-consensus-1  | 2023-08-15 11:03:39.454 INFO  - Eth1 endpoint not provided, using execution engine endpoint for eth1 data
eth-docker-devel-consensus-1  | 2023-08-15 11:03:39.896 ERROR - External signer is currently not reachable at http://web3signer:9000
eth-docker-devel-consensus-1  | 2023-08-15 11:03:39.914 ERROR - External signer is currently not reachable at http://web3signer:9000
eth-docker-devel-consensus-1  | 2023-08-15 11:03:39.945 INFO  - Storing beacon chain data in: /var/lib/teku/beacon
eth-docker-devel-consensus-1  | 2023-08-15 11:03:39.991 INFO  - Using portable BLST library.
eth-docker-devel-consensus-1  | 2023-08-15 11:03:39.998 INFO  - Starting metrics http service on 0.0.0.0:8008
eth-docker-devel-consensus-1  | 2023-08-15 11:03:39.991 ERROR - PLEASE FIX OR REPORT | Unexpected exception thrown for validator-async-0
eth-docker-devel-consensus-1  | java.util.concurrent.CompletionException: tech.pegasys.teku.infrastructure.exceptions.InvalidConfigurationException: Failed to load public keys from external signer.
eth-docker-devel-consensus-1  | at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:146) ~[teku-infrastructure-async-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.concurrent.CompletableFuture.whenComplete(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:626) ~[teku-infrastructure-async-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:33) ~[teku-infrastructure-async-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:143) ~[teku-infrastructure-async-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateTo(SafeFuture.java:320) ~[teku-infrastructure-async-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:124) ~[teku-infrastructure-async-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
eth-docker-devel-consensus-1  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
eth-docker-devel-consensus-1  | at java.lang.Thread.run(Unknown Source) [?:?]
eth-docker-devel-consensus-1  | Caused by: tech.pegasys.teku.infrastructure.exceptions.InvalidConfigurationException: Failed to load public keys from external signer.
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.loader.PublicKeyLoader.readKeysFromExternalSigner(PublicKeyLoader.java:120) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.loader.PublicKeyLoader.lambda$getPublicKeys$1(PublicKeyLoader.java:81) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.loader.PublicKeyLoader.getPublicKeys(PublicKeyLoader.java:89) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.loader.ExternalValidatorSource.getAvailableReadOnlyValidators(ExternalValidatorSource.java:115) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.loader.ExternalValidatorSource.getAvailableValidators(ExternalValidatorSource.java:105) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.loader.SlashingProtectedValidatorSource.getAvailableValidators(SlashingProtectedValidatorSource.java:40) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.loader.ValidatorLoader.addValidatorsFromSource(ValidatorLoader.java:268) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.loader.ValidatorLoader.lambda$loadValidators$0(ValidatorLoader.java:76) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.loader.ValidatorLoader.loadValidators(ValidatorLoader.java:76) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.ValidatorClientService.initializeValidators(ValidatorClientService.java:359) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.ValidatorClientService.lambda$create$0(ValidatorClientService.java:204) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.fromRunnable(SafeFuture.java:155) ~[teku-infrastructure-async-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$0(AsyncRunner.java:23) ~[teku-infrastructure-async-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:74) ~[teku-infrastructure-async-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | ... 4 more
eth-docker-devel-consensus-1  | Caused by: java.net.ConnectException
eth-docker-devel-consensus-1  | at jdk.internal.net.http.HttpClientImpl.send(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.HttpClientFacade.send(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.loader.PublicKeyLoader.readKeysFromExternalSigner(PublicKeyLoader.java:112) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.loader.PublicKeyLoader.lambda$getPublicKeys$1(PublicKeyLoader.java:81) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.loader.PublicKeyLoader.getPublicKeys(PublicKeyLoader.java:89) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.loader.ExternalValidatorSource.getAvailableReadOnlyValidators(ExternalValidatorSource.java:115) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.loader.ExternalValidatorSource.getAvailableValidators(ExternalValidatorSource.java:105) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.loader.SlashingProtectedValidatorSource.getAvailableValidators(SlashingProtectedValidatorSource.java:40) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.loader.ValidatorLoader.addValidatorsFromSource(ValidatorLoader.java:268) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.loader.ValidatorLoader.lambda$loadValidators$0(ValidatorLoader.java:76) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.loader.ValidatorLoader.loadValidators(ValidatorLoader.java:76) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.ValidatorClientService.initializeValidators(ValidatorClientService.java:359) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.ValidatorClientService.lambda$create$0(ValidatorClientService.java:204) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.fromRunnable(SafeFuture.java:155) ~[teku-infrastructure-async-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$0(AsyncRunner.java:23) ~[teku-infrastructure-async-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:74) ~[teku-infrastructure-async-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | ... 4 more
eth-docker-devel-consensus-1  | Caused by: java.net.ConnectException
eth-docker-devel-consensus-1  | at jdk.internal.net.http.common.Utils.toConnectException(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.PlainHttpConnection.connectAsync(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.PlainHttpConnection.checkRetryConnect(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$1(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.concurrent.CompletableFuture.handle(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.PlainHttpConnection.connectAsync(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.Http1Exchange.sendHeadersAsync(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.Exchange.lambda$responseAsyncImpl0$9(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.Exchange.checkFor407(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.Exchange.lambda$responseAsyncImpl0$10(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.concurrent.CompletableFuture.handle(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.Exchange.responseAsyncImpl0(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.Exchange.responseAsyncImpl(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.Exchange.responseAsync(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.MultiExchange.responseAsyncImpl(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.concurrent.CompletableFuture.handle(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.MultiExchange.responseAsyncImpl(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.MultiExchange.lambda$responseAsync0$2(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at java.util.concurrent.CompletableFuture.completeAsync(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.MultiExchange.responseAsync(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.HttpClientImpl.sendAsync(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.HttpClientImpl.send(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.HttpClientFacade.send(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.loader.PublicKeyLoader.readKeysFromExternalSigner(PublicKeyLoader.java:112) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.loader.PublicKeyLoader.lambda$getPublicKeys$1(PublicKeyLoader.java:81) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.loader.PublicKeyLoader.getPublicKeys(PublicKeyLoader.java:89) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.loader.ExternalValidatorSource.getAvailableReadOnlyValidators(ExternalValidatorSource.java:115) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.loader.ExternalValidatorSource.getAvailableValidators(ExternalValidatorSource.java:105) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.loader.SlashingProtectedValidatorSource.getAvailableValidators(SlashingProtectedValidatorSource.java:40) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.loader.ValidatorLoader.addValidatorsFromSource(ValidatorLoader.java:268) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.loader.ValidatorLoader.lambda$loadValidators$0(ValidatorLoader.java:76) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.loader.ValidatorLoader.loadValidators(ValidatorLoader.java:76) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.ValidatorClientService.initializeValidators(ValidatorClientService.java:359) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.ValidatorClientService.lambda$create$0(ValidatorClientService.java:204) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.fromRunnable(SafeFuture.java:155) ~[teku-infrastructure-async-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$0(AsyncRunner.java:23) ~[teku-infrastructure-async-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:74) ~[teku-infrastructure-async-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | ... 4 more
eth-docker-devel-consensus-1  | Caused by: java.nio.channels.ClosedChannelException
eth-docker-devel-consensus-1  | at sun.nio.ch.SocketChannelImpl.ensureOpen(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at sun.nio.ch.SocketChannelImpl.beginConnect(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at sun.nio.ch.SocketChannelImpl.connect(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$0(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.PlainHttpConnection.connectAsync(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.PlainHttpConnection.checkRetryConnect(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$1(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.concurrent.CompletableFuture.handle(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.PlainHttpConnection.connectAsync(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.Http1Exchange.sendHeadersAsync(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.Exchange.lambda$responseAsyncImpl0$9(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.Exchange.checkFor407(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.Exchange.lambda$responseAsyncImpl0$10(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.concurrent.CompletableFuture.handle(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.Exchange.responseAsyncImpl0(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.Exchange.responseAsyncImpl(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.Exchange.responseAsync(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.MultiExchange.responseAsyncImpl(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.concurrent.CompletableFuture.handle(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.MultiExchange.responseAsyncImpl(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.MultiExchange.lambda$responseAsync0$2(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at java.util.concurrent.CompletableFuture.completeAsync(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.MultiExchange.responseAsync(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.HttpClientImpl.sendAsync(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.HttpClientImpl.send(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at jdk.internal.net.http.HttpClientFacade.send(Unknown Source) ~[java.net.http:?]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.loader.PublicKeyLoader.readKeysFromExternalSigner(PublicKeyLoader.java:112) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.loader.PublicKeyLoader.lambda$getPublicKeys$1(PublicKeyLoader.java:81) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.loader.PublicKeyLoader.getPublicKeys(PublicKeyLoader.java:89) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.loader.ExternalValidatorSource.getAvailableReadOnlyValidators(ExternalValidatorSource.java:115) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.loader.ExternalValidatorSource.getAvailableValidators(ExternalValidatorSource.java:105) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.loader.SlashingProtectedValidatorSource.getAvailableValidators(SlashingProtectedValidatorSource.java:40) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.loader.ValidatorLoader.addValidatorsFromSource(ValidatorLoader.java:268) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.loader.ValidatorLoader.lambda$loadValidators$0(ValidatorLoader.java:76) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.loader.ValidatorLoader.loadValidators(ValidatorLoader.java:76) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.ValidatorClientService.initializeValidators(ValidatorClientService.java:359) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.validator.client.ValidatorClientService.lambda$create$0(ValidatorClientService.java:204) ~[teku-validator-client-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.fromRunnable(SafeFuture.java:155) ~[teku-infrastructure-async-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$0(AsyncRunner.java:23) ~[teku-infrastructure-async-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:74) ~[teku-infrastructure-async-23.8.0.jar:23.8.0]
eth-docker-devel-consensus-1  | ... 4 more
```

**Comment by rolfyone** [comment]
Thanks for raising this, we'll take a look!

**Comment by courtneyeh** [comment]
After some investigation the bug has not be reproduced. Starting Teku and web3signer at the same time did not produce the bug. Also running Teku without starting web3signer, or stopping web3signer while Teku was running did not reproduce it.

Were there any other parameters around external signer that may have been set contributing to this error? @yorickdowne

**Comment by yorickdowne** [comment]
This behavior started when adding `--validators-external-signer-public-keys external-signer`. The parameters in the description are the only remote signer parameters in use; everything else is base Teku.

**Comment by rolfyone** [comment]
> This behavior started when adding `--validators-external-signer-public-keys external-signer`. The parameters in the description are the only remote signer parameters in use; everything else is base Teku.

are you talking about this use-case?
```
--validators-external-signer-public-keys=http://localhost:9900/publicKeys
```
like that?

ref. https://docs.teku.consensys.net/reference/cli#validators-external-signer-public-keys

we've tried some other scenarios but I don't think we tried that one...

**Comment by yorickdowne** [comment]
Yes. Specifically if I do `--validators-external-signer-public-keys http://web3signer:9000` I see a startup note that the remote signer URL and remote signer public keys value are the same and that I should use `external-signer` instead, so I am literally passing `--validators-external-signer-public-keys external-signer`. `external-signer` is the actual value being passed.

This is friendly to users: If they swap VCs from something to Teku, Teku grabs the keys on startup, without the user needing to "register" them manually with Teku
