### ISSUE TITLE
Teku/Besu synced, but my validator appears red on Beaconchan page.

### ISSUE THREAD

**Issue by socopower** [Consensys-Incorporated/teku#7434]
Hi, here is the log.

```
2023-08-20 07:52:54.250+00:00 | validator-async-0 | ERROR | teku-status-log | PLEASE FIX OR REPORT | Unexpected exception thrown for validator-async-0
java.util.concurrent.CompletionException: tech.pegasys.teku.infrastructure.exceptions.InvalidConfigurationException: Failed to decrypt keystore /var/lib/teku/validator>
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[?:?]
at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347) ~[?:?]
at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1141) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:146) ~[teku-infrastructure-async-23.8.0.jar:23.8.0]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887) ~[?:?]
at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:626) ~[teku-infrastructure-async-23.8.0.jar:23.8.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:33) ~[teku-infrastructure-async-23.8.0.jar:23.8.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:143) ~[teku-infrastructure-async-23.8.0.jar:23.8.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateTo(SafeFuture.java:320) ~[teku-infrastructure-async-23.8.0.jar:23.8.0]
at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:124) ~[teku-infrastructure-as>
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: tech.pegasys.teku.infrastructure.exceptions.InvalidConfigurationException: Failed to decrypt keystore /var/lib/teku/validator_keys/keystore-m_12381_3600_0_0>
at tech.pegasys.teku.validator.client.loader.LocalValidatorSource$LocalValidatorProvider.loadBLSPrivateKey(LocalValidatorSource.java:254) ~[teku-validator-client-23.8.>
at tech.pegasys.teku.validator.client.loader.LocalValidatorSource$LocalValidatorProvider.createSigner(LocalValidatorSource.java:236) ~[teku-validator-client-23.8.0.jar>
at tech.pegasys.teku.validator.client.loader.SlashingProtectedValidatorSource$SlashingProtectedValidatorProvider.createSigner(SlashingProtectedValidatorSource.java:97)>
at tech.pegasys.teku.validator.client.loader.MultithreadedValidatorLoader.lambda$loadValidators$0(MultithreadedValidatorLoader.java:64) ~[teku-validator-client-23.8.0.>
at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]

... 3 more
2023-08-20 07:53:03.913+00:00 | beaconchain-async-1 | INFO  | teku-status-log | Loaded initial state at epoch 197938 (state root = 0x37fb4ecb35bbe575ca4d15e249c21ca113>
2023-08-20 07:53:05.411+00:00 | beaconchain-async-1 | ERROR | teku-status-log | PLEASE FIX OR REPORT | Unexpected exception thrown for beaconchain-async-1
java.util.concurrent.CompletionException: java.util.NoSuchElementException: No value present
at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:368) ~[?:?]
at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:377) ~[?:?]
at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1097) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:146) ~[teku-infrastructure-async-23.8.0.jar:23.8.0]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887) ~[?:?]
at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:626) ~[teku-infrastructure-async-23.8.0.jar:23.8.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:33) ~[teku-infrastructure-async-23.8.0.jar:23.8.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:143) ~[teku-infrastructure-async-23.8.0.jar:23.8.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateTo(SafeFuture.java:320) ~[teku-infrastructure-async-23.8.0.jar:23.8.0]
at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:124) ~[teku-infrastructure-as>
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.util.NoSuchElementException: No value present

at java.util.Optional.orElseThrow(Optional.java:377) ~[?:?]
at tech.pegasys.teku.statetransition.forkchoice.ForkChoice.lambda$processHead$4(ForkChoice.java:223) ~[teku-ethereum-statetransition-23.8.0.jar:23.8.0]
at tech.pegasys.teku.infrastructure.async.eventthread.AsyncRunnerEventThread.recordEventThreadIdAndExecute(AsyncRunnerEventThread.java:130) ~[teku-infrastructure-async>
at tech.pegasys.teku.infrastructure.async.eventthread.AsyncRunnerEventThread.lambda$doExecute$1(AsyncRunnerEventThread.java:113) ~[teku-infrastructure-async-23.8.0.jar>
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:82) ~[teku-infrastructure-async-23.8.0.jar:23.8.0]
at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$2(AsyncRunner.java:47) ~[teku-infrastructure-async-23.8.0.jar:23.8.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:74) ~[teku-infrastructure-async-23.8.0.jar:23.8.0]
... 4 more
2023-08-20 07:53:06.418+00:00 | beaconchain-async-1 | INFO  | teku-status-log | Generated new p2p private key and storing in: generated-node-key
2023-08-20 07:53:07.184+00:00 | beaconchain-async-1 | INFO  | teku-status-log | PreGenesis Local ENR: enr:-Iu4QI_Zy1m8ToXfljk-3yA9EVsbDleKFiypHxVKTSrYBrivRapsQqySPauFv>
2023-08-20 07:53:07.211+00:00 | beaconchain-async-1 | INFO  | DefaultSyncServiceFactory | Using multipeer sync
2023-08-20 07:53:07.410+00:00 | beaconchain-async-1 | INFO  | BeaconChainController | rest-api-enabled is false, not starting rest api.
2023-08-20 07:53:07.618+00:00 | beaconchain-async-1 | INFO  | LibP2PNetwork | Starting libp2p network...
2023-08-20 07:53:07.672+00:00 | beaconchain-async-1 | INFO  | teku-status-log | Listening for connections on: /ip4/10.182.0.5/tcp/9000/p2p/16Uiu2HAmM8CQUBHXTBGxVyZG9dP>
2023-08-20 07:53:07.682+00:00 | beaconchain-async-1 | INFO  | NettyDiscoveryServerImpl | Starting discovery server on UDP port 9000
2023-08-20 07:53:07.729+00:00 | beaconchain-async-1 | INFO  | QuartzScheduler | Scheduler QuartzScheduler_$_NON_CLUSTERED started.
2023-08-20 07:53:07.735+00:00 | beaconchain-async-1 | INFO  | teku-status-log | Loading deposit tree snapshot from jar:file:/usr/local/bin/teku/lib/teku-services-powch>
2023-08-20 07:53:07.737+00:00 | beaconchain-async-1 | INFO  | teku-status-log | A deposit snapshot was read with 313267 deposits and 0x17a3e8af4a09f15ecee4c40c7e3d93ae>
2023-08-20 07:53:07.738+00:00 | beaconchain-async-1 | INFO  | teku-status-log | Loading deposit tree snapshot from database
2023-08-20 07:53:07.765+00:00 | powchain-async-0 | INFO  | teku-status-log | Loaded deposits tree state from snapshot with 313267 deposits and 0x17a3e8af4a09f15ecee4c4>
2023-08-20 07:53:07.769+00:00 | beaconchain-async-7 | INFO  | HistoricalBlockSyncService | Begin historical sync of blocks from slot 6334016 to slot 0
2023-08-20 07:53:07.794+00:00 | nioEventLoopGroup-4-1 | INFO  | NettyDiscoveryClientImpl | UDP discovery client started
2023-08-20 07:53:07.883+00:00 | nioEventLoopGroup-4-1 | INFO  | teku-status-log | Local ENR: enr:-Iu4QIISiu75UNsNmhvSD9yX0_2qvskYbvmCUmuZkV-zqAgzbmH35QHojYo5f4F7Qd-u13>
2023-08-20 07:53:07.886+00:00 | nioEventLoopGroup-4-1 | INFO  | ActiveEth2P2PNetwork | Starting eth2 gossip
2023-08-20 07:53:08.213+00:00 | TimeTick-1 | INFO  | teku-event-log | ^[[37mSyncing     *** Target slot: 6334165, Head slot: 6334016, Remaining slots: 149, Connected p>
2023-08-20 07:53:08.484+00:00 | pool-4-thread-5 | INFO  | teku-event-log | ^[[32mExecution Client is online^[[0m
2023-08-20 07:53:08.492+00:00 | pool-4-thread-3 | INFO  | teku-status-log | Loading deposits up to Eth1 block 0
2023-08-20 07:53:12.003+00:00 | TimeTick-1 | INFO  | teku-event-log | ^[[37mSyncing     *** Target slot: 6334166, Head slot: 6334016, Waiting for execution layer sync,>
2023-08-20 07:53:21.479+00:00 | beaconchain-async-2 | INFO  | teku-event-log | ^[[33mSyncing started^[[0m
2023-08-20 07:53:24.002+00:00 | TimeTick-1 | INFO  | teku-event-log | ^[[37mSyncing     *** Target slot: 6334167, Head slot: 6334016, Remaining slots: 151, Connected

```

### Versions 
* Software version: [`teku --23.8.0`]
* Java version: [`17+`]
* OS Name & Version: [`Ubuntu 22.04 LTS`]
* Cloud VM, type, size: [GCP - E2 (vCORE8 /32GB) ]

**Comment by socopower** [comment]
The problem was that I had put the wrong *json* password in the *.txt* file :) (my bad)

I regenerated another json file using the seed phrases, put in a new key, sent it back to the server, and all is well.

Thanks for the support through Discord from the Teku team.
