### ISSUE TITLE
Exception on Deneb Builder Bid Parsing

### ISSUE THREAD

**Issue by marioevz** [Consensys-Incorporated/teku#7467]
### Description
Teku is hitting the following exception on a valid Deneb builder bid:
```
2023-08-28 19:04:59.237 ERROR - Unable to obtain a valid bid from builder. Falling back to local execution engine.
 java.util.concurrent.CompletionException: tech.pegasys.teku.infrastructure.json.exceptions.MissingRequiredFieldException: required fields: (withdrawals_root, blob_gas_used, excess_blob_gas) were not set
 at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?] 
 at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?] 
 at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?] 
 at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) [?:?]
 at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) [?:?]
 at tech.pegasys.teku.ethereum.executionclient.rest.OkHttpRestClient$2.onResponse(OkHttpRestClient.java:163) [teku-ethereum-executionclient-develop.jar:23.8.0+34-g46321bcd4e]
 at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) [okhttp-4.11.0.jar:?]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
 at java.lang.Thread.run(Unknown Source) [?:?]
 Caused by: tech.pegasys.teku.infrastructure.json.exceptions.MissingRequiredFieldException: required fields: (withdrawals_root, blob_gas_used, excess_blob_gas) were not set
 at tech.pegasys.teku.infrastructure.json.types.DeserializableObjectTypeDefinition.deserialize(DeserializableObjectTypeDefinition.java:101) ~[teku-infrastructure-json-develop.jar:23.8.0+34-g46321bcd4e]
 at tech.pegasys.teku.infrastructure.json.types.RequiredDeserializableFieldDefinition.readField(RequiredDeserializableFieldDefinition.java:42) ~[teku-infrastructure-json-develop.jar:23.8.0+34-g46321bcd4e]
 at tech.pegasys.teku.infrastructure.json.types.DeserializableObjectTypeDefinition.deserialize(DeserializableObjectTypeDefinition.java:74) ~[teku-infrastructure-json-develop.jar:23.8.0+34-g46321bcd4e]
 at tech.pegasys.teku.infrastructure.json.types.RequiredDeserializableFieldDefinition.readField(RequiredDeserializableFieldDefinition.java:42) ~[teku-infrastructure-json-develop.jar:23.8.0+34-g46321bcd4e]
 at tech.pegasys.teku.infrastructure.json.types.DeserializableObjectTypeDefinition.deserialize(DeserializableObjectTypeDefinition.java:74) ~[teku-infrastructure-json-develop.jar:23.8.0+34-g46321bcd4e]
 at tech.pegasys.teku.infrastructure.json.types.RequiredDeserializableFieldDefinition.readField(RequiredDeserializableFieldDefinition.java:42) ~[teku-infrastructure-json-develop.jar:23.8.0+34-g46321bcd4e]
 at tech.pegasys.teku.infrastructure.json.types.DeserializableObjectTypeDefinition.deserialize(DeserializableObjectTypeDefinition.java:74) ~[teku-infrastructure-json-develop.jar:23.8.0+34-g46321bcd4e]
 at tech.pegasys.teku.infrastructure.json.JsonUtil.parse(JsonUtil.java:118) ~[teku-infrastructure-json-develop.jar:23.8.0+34-g46321bcd4e]
 at tech.pegasys.teku.infrastructure.json.JsonUtil.parse(JsonUtil.java:110) ~[teku-infrastructure-json-develop.jar:23.8.0+34-g46321bcd4e]
 at tech.pegasys.teku.ethereum.executionclient.rest.OkHttpRestClient$2.onResponse(OkHttpRestClient.java:160) ~[teku-ethereum-executionclient-develop.jar:23.8.0+34-g46321bcd4e]
 ... 4 more
```
The builder bid is as follows:
```json
{
    "version": "deneb",
    "data": {
        "message": {
            "header": {
                "parent_hash": "0xa9507f61bc2f06d7bc4ebe7bf9d6bd54b1172796b92b90e346bd3acc7d91dbd8",
                "fee_recipient": "0x878705ba3f8bc32fcf7f4caa1a35e72af65cf766",
                "state_root": "0xeb6cece5c5e9d29fce1c47138d0059c7ec70f569a9da1addcba4410cbf1c0c88",
                "receipts_root": "0xc538d36ed1acf6c28187110a2de3e5df707d6d38982f436eb0db7a623f9dc2cd",
                "logs_bloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 000000000000000000000000000000000000000000",
                "prev_randao": "0x30fe4a3c5aea79d1862b78ac0b38b3bbcfc6c20ab0b402e2db435e82574fcbdc",
                "block_number": "66",
                "gas_limit": "26663452",
                "gas_used": "210000",
                "timestamp": "1693249499",
                "extra_data": "0x6275696c646572207061796c6f6164",
                "base_fee_per_gas": "598964",
                "block_hash": "0x13047edbab52cf4421a61bfcfc2485b8af48da0f5f1e25439b946680b3bb0154",
                "transactions_root": "0x2f5e224d7af16526048efa4dfcdbe7fc841d7fc3aee99d947b6c46ebd2a82c99",
                "withdrawals_root": "0x792930bbd5baac43bcc798ee49aa8185ef76bb3b44ba62b91d86ae569e4bb535",
                "blob_gas_used": "0",
                "excess_blob_gas": "0"
            },
            "blinded_blobs_bundle": {
                "commitments": [],
                "proofs": [],
                "blob_roots": []
            },
            "value": "1076580166200000",
            "pubkey": "0x95fde78acd5f6886ddaf5d0056610167c513d09c1c0efabbc7cdcc69beea113779c4a81e2d24daafc5387dbf6ac5fe48"
        },
        "signature": "0x9071a79170de126252e8f694c5c3f19390a869a233f4103b93c293f099be83aa632ab6e79dd2fcb9d3bf8f812b6e4e960886810cf8298d0855867e195fc935d91d32e4fd8909520c7e8ce20b631a9007dbe6b3a68c5c6562f9ba3f460e6e3f55"
    }
}
```
Which seems to match what the builder spec describes, and does contain the `withdrawals_root, blob_gas_used, excess_blob_gas` fields in the `message` portion of the response.

### Steps to Reproduce (Bug)
Using the following kurtosis eth2-package branch: https://github.com/marioevz/eth2-package/tree/mock-builder-updates-deneb

Run the following command:
```bash
kurtosis run --enclave eth2 . "$(cat mock_mev_test_teku.json)"
```
Where the json file has the following contents:
```json
 {
   "participants": [
     {   
       "el_client_type": "geth",
       "el_client_image": "ethpandaops/geth:lightclient-devnet-8-edf4ab3",
       "cl_client_type": "teku",
       "cl_client_image": "consensys/teku:develop",
       "count": 2
     }   
   ],  
   "network_params": {
     "capella_fork_epoch": 1,
     "deneb_fork_epoch": 2
   },  
   "launch_additional_services": true,
   "global_client_log_level": "debug",
   "snooper_enabled": true,
   "mev_type": "mock"
 }
```

**Expected behavior:**
After Deneb epoch, Teku should parse the bid and then request the unblinded payload and blob bundle by signing the beacon block and blob sidecars.

**Actual behavior:**
Teku falls-back to local payload building.

**Frequency:**
Always happens.

### Versions
`consensys/teku:develop` docker image, `Digest:sha256:a90150de8269d51382e8df186bc77c0b29854aba90979c902c7f0e85599af4e0`
`teku/v23.8.0+34-g46321bcd4e/linux-x86_64/-eclipseadoptium-openjdk64bitservervm-java-17`

**Comment by marioevz** [comment]
Builder is now fully working on Teku's latest develop and latest commit of this hive's PR: https://github.com/ethereum/hive/pull/838

Closing issue.
