### ISSUE TITLE
Basic auth support in `--ee-endpoint`

### ISSUE THREAD

**Issue by michaelsproul** [Consensys-Incorporated/teku#7512]
### Description

I'm trying to use an HTTP URL containing basic auth parameters with Teku BN, like this:

```
--ee-endpoint "https://username:pass@site.com"
```

Teku is parsing the URL and making the request, but it leaves off the `Authorization` header, so the request fails.

Support for basic auth usernames and passwords in URLs is quite standard, and an old issue https://github.com/Consensys/teku/issues/3609 suggests that it was supported at some point for Teku VC <> BN connections. With HTTPS, transmission of the username & password is safe.

### Steps to Reproduce (Bug)

Run Teku BN with `--ee-endpoint` and a URL guarded by basic auth. It throws this exception:

```
2023-09-14 06:47:01.481 WARN  - Endpoint https://username:password@site.com encountered an issue | Invalid response received: 401; {"error": "401 Unauthorized"}
2023-09-14 06:47:02.597 ERROR - Execution Client request failed. Check the same JWT secret is configured for Teku and the Execution Client.
org.web3j.protocol.exceptions.ClientConnectionException: Invalid response received: 401; {"error": "401 Unauthorized"}
at org.web3j.protocol.http.HttpService.performIO(HttpService.java:172) ~[core-4.10.1.jar:?]
at org.web3j.protocol.Service.send(Service.java:48) ~[core-4.10.1.jar:?]
at org.web3j.protocol.Service.lambda$sendAsync$0(Service.java:60) ~[core-4.10.1.jar:?]
at org.web3j.utils.Async.lambda$run$1(Async.java:38) ~[core-4.10.1.jar:?]
at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
at java.lang.Thread.run(Unknown Source) [?:?]
2023-09-14 06:47:02.822 WARN  - Unable to import blocks because execution client is offline.
```

Logs from the server (Caddy) show the lack of `Authorization` header:

```
Sep 14 06:32:23 site.com caddy[770]: 2023/09/14 06:32:23.449        ERROR        http.log.access.log0        handled request        {"request": {"remote_ip": "X.X.X.X", "remote_port": "38612", "proto": "HTTP/2.0", "method": "POST", "host": "site.com", "uri": "/", "headers": {"Authorization": [], "Content-Type": ["application/json; charset=utf-8"], "Content-Length": ["84"], "Accept-Encoding": ["gzip"], "User-Agent": ["okhttp/4.11.0"]}, "tls": {"resumed": false, "version": 772, "cipher_suite": 4865, "proto": "h2", "server_name": "site.com"}}, "user_id": "", "duration": 0.00002376, "size": 29, "status": 401, "resp_headers": {"Server": ["Caddy"], "Alt-Svc": ["h3=\":443\"; ma=2592000"], "Www-Authenticate": ["Basic realm=\"restricted\""], "Content-Type": ["application/json"]}}
```

### Versions

* Software version: `teku/v23.9.0/linux-x86_64/-eclipseadoptium-openjdk64bitservervm-java-17` (and v23.8.0).
* Java version:

```
openjdk version "17.0.8.1" 2023-08-24
OpenJDK Runtime Environment Temurin-17.0.8.1+1 (build 17.0.8.1+1)
OpenJDK 64-Bit Server VM Temurin-17.0.8.1+1 (build 17.0.8.1+1, mixed mode)
```
* OS Name & Version: `Ubuntu 22.04.3 LTS`
* Docker Version:

```
Client: Docker Engine - Community
 Version:           24.0.5
```

**Comment by michaelsproul** [comment]
Having thought about it, this is insane because the JWT needs to go in the Authorization header. I'm not sure _why_ it was working with Lighthouse but I should probably stop it from working!
