### ISSUE TITLE
Teku needs more heap on non-finalizing chain

### ISSUE THREAD

**Issue by yorickdowne** [Consensys-Incorporated/teku#7518]
### Description

Teku v23.9.0 with a fixed Holesky Nethermind, I see this in logs with 6g heap. That doesn't happen with 7g heap, so far. The increase might be expected.

```
eth-holesky-consensus-1  | 2023-09-17 12:36:30.660 INFO  - Slot Event  *** Slot: 13982, Block:                                                        ... empty, Justified: 0, Finalized: 0, Peers: 44
eth-holesky-consensus-1  | 2023-09-17 12:36:35.148 INFO  - Beacon chain is in activity leak
eth-holesky-consensus-1  | 2023-09-17 12:36:38.880 ERROR - Failed to process event queue for client 1554006542
eth-holesky-consensus-1  | java.util.concurrent.CompletionException: java.lang.IllegalStateException: s=OPEN,api=BLOCKING,sc=true,e=null
eth-holesky-consensus-1  | at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
eth-holesky-consensus-1  | at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
eth-holesky-consensus-1  | at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?]
eth-holesky-consensus-1  | at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
eth-holesky-consensus-1  | at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
eth-holesky-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:146) ~[teku-infrastructure-async-23.9.0.jar:23.9.0]
eth-holesky-consensus-1  | at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
eth-holesky-consensus-1  | at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(Unknown Source) ~[?:?]
eth-holesky-consensus-1  | at java.util.concurrent.CompletableFuture.whenComplete(Unknown Source) ~[?:?]
eth-holesky-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:626) ~[teku-infrastructure-async-23.9.0.jar:23.9.0]
eth-holesky-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:33) ~[teku-infrastructure-async-23.9.0.jar:23.9.0]
eth-holesky-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:143) ~[teku-infrastructure-async-23.9.0.jar:23.9.0]
eth-holesky-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$exceptionallyCompose$34(SafeFuture.java:426) ~[teku-infrastructure-async-23.9.0.jar:23.9.0]
eth-holesky-consensus-1  | at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
eth-holesky-consensus-1  | at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
eth-holesky-consensus-1  | at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
eth-holesky-consensus-1  | at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
eth-holesky-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:146) ~[teku-infrastructure-async-23.9.0.jar:23.9.0]
eth-holesky-consensus-1  | at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
eth-holesky-consensus-1  | at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(Unknown Source) ~[?:?]
eth-holesky-consensus-1  | at java.util.concurrent.CompletableFuture.whenComplete(Unknown Source) ~[?:?]
eth-holesky-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:626) ~[teku-infrastructure-async-23.9.0.jar:23.9.0]
eth-holesky-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:33) ~[teku-infrastructure-async-23.9.0.jar:23.9.0]
eth-holesky-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:143) ~[teku-infrastructure-async-23.9.0.jar:23.9.0]
eth-holesky-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateTo(SafeFuture.java:320) ~[teku-infrastructure-async-23.9.0.jar:23.9.0]
eth-holesky-consensus-1  | at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:124) ~[teku-infrastructure-async-23.9.0.jar:23.9.0]
eth-holesky-consensus-1  | at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
eth-holesky-consensus-1  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
eth-holesky-consensus-1  | at java.lang.Thread.run(Unknown Source) [?:?]
eth-holesky-consensus-1  | Caused by: java.lang.IllegalStateException: s=OPEN,api=BLOCKING,sc=true,e=null
eth-holesky-consensus-1  | at org.eclipse.jetty.server.HttpOutput.updateApiState(HttpOutput.java:363) ~[jetty-server-11.0.15.jar:11.0.15]
eth-holesky-consensus-1  | at org.eclipse.jetty.server.HttpOutput.onWriteComplete(HttpOutput.java:303) ~[jetty-server-11.0.15.jar:11.0.15]
eth-holesky-consensus-1  | at org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:737) ~[jetty-server-11.0.15.jar:11.0.15]
eth-holesky-consensus-1  | at org.eclipse.jetty.server.Response.flushBuffer(Response.java:1167) ~[jetty-server-11.0.15.jar:11.0.15]
eth-holesky-consensus-1  | at io.javalin.http.sse.Emitter.emit(Emitter.kt:27) ~[javalin-5.6.2.jar:5.6.2]
eth-holesky-consensus-1  | at io.javalin.http.sse.SseClient.sendEvent(SseClient.kt:65) ~[javalin-5.6.2.jar:5.6.2]
eth-holesky-consensus-1  | at io.javalin.http.sse.SseClient.sendEvent$default(SseClient.kt:62) ~[javalin-5.6.2.jar:5.6.2]
eth-holesky-consensus-1  | at io.javalin.http.sse.SseClient.sendEvent(SseClient.kt) ~[javalin-5.6.2.jar:5.6.2]
eth-holesky-consensus-1  | at tech.pegasys.teku.beaconrestapi.handlers.v1.events.EventSubscriber.lambda$processEventQueue$1(EventSubscriber.java:122) ~[teku-data-beaconrestapi-23.9.0.jar:23.9.0]
eth-holesky-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.fromRunnable(SafeFuture.java:155) ~[teku-infrastructure-async-23.9.0.jar:23.9.0]
eth-holesky-consensus-1  | at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$0(AsyncRunner.java:23) ~[teku-infrastructure-async-23.9.0.jar:23.9.0]
eth-holesky-consensus-1  | at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:74) ~[teku-infrastructure-async-23.9.0.jar:23.9.0]
eth-holesky-consensus-1  | ... 4 more
```

### Steps to Reproduce (Bug)

Sync Teku on Holesky with -Xmx6g and validators attached

### Versions (Add all that apply)
* Software version: v23.9.0

**Comment by yorickdowne** [comment]
This may still have been an Xmx thing. Hang loose pls. I may close this once I know how to stabilize it

**Comment by yorickdowne** [comment]
It's in much better shape with -Xmx7g, and may be stable with that amount. If not I  can bump to -Xmx8g.

That's a pretty large increase from -Xmx4g in steady state. Do you want this issue open to see where the heap goes, or is this normal and expected behavior during extended non-finality?

**Comment by rolfyone** [comment]
I've got low expectations - its a lot larger network, we'll have issues and i'm looking forward to getting to the bottom of whatever unknown / unknown happens at this point :)
