### ISSUE TITLE
engine API call error due to failure in jwt creation

### ISSUE THREAD

**Issue by tbenr** [Consensys-Incorporated/teku#7559]
User reported this strange stack trace:

```
2023-09-29 14:51:36.274+02:00 | pool-4-thread-11 | ERROR | teku-event-log | Execution Client request failed. Make sure the Execution Client is online and can respond to requests.
java.util.ServiceConfigurationError: io.jsonwebtoken.io.Serializer: Error accessing configuration file
at java.util.ServiceLoader.fail(ServiceLoader.java:586) ~[?:?]
at java.util.ServiceLoader$LazyClassPathLookupIterator.parse(ServiceLoader.java:1180) ~[?:?]
at java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1213) ~[?:?]
at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228) ~[?:?]
at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273) ~[?:?]
at java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309) ~[?:?]
at java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393) ~[?:?]
at io.jsonwebtoken.impl.lang.Services.loadFirst(Services.java:110) ~[jjwt-impl-0.11.5.jar:0.11.5]
at io.jsonwebtoken.impl.lang.Services.loadFirst(Services.java:100) ~[jjwt-impl-0.11.5.jar:0.11.5]
at io.jsonwebtoken.impl.lang.LegacyServices.loadFirst(LegacyServices.java:24) ~[jjwt-impl-0.11.5.jar:0.11.5]
at io.jsonwebtoken.impl.DefaultJwtBuilder.compact(DefaultJwtBuilder.java:291) ~[jjwt-impl-0.11.5.jar:0.11.5]
at tech.pegasys.teku.ethereum.executionclient.auth.TokenProvider.token(TokenProvider.java:38) ~[teku-ethereum-executionclient-23.9.1.jar:23.9.1]
```

**Comment by tbenr** [comment]
doing some reserch I found:

https://github.com/jwtk/jjwt/issues/648

which then referces 
- https://github.com/jwtk/jjwt/issues/648
- https://github.com/jwtk/jjwt/issues/752

seems like the fix is targeted to `0.12.0`. An option would be to switch jwt library.
