### ISSUE TITLE
Deposit simulation fails after Eth2Genesis during PoW simulation from a JSON file

### ISSUE THREAD

**Issue by dangerousfood** [Consensys-Incorporated/teku#770]
When running deposit simulation in `mode = "simulation"` with input file `inputFile = "validator_test_data.json"` the following `java.lang.ArithmeticException: / by zero` error is thrown when in method `get_beacon_proposer_index`.

In our current implementation `v0.7.1` debugging is difficult (4 min wait time). We are waiting until after changes are made to how our `DepositContract` is deployed to begin debugging.

```
> Task :run
Setting logging level to INFO
10:40:58.948 [INFO ] - ******* Eth2Genesis Event detected ******* : 0xD56342AFD67EC47A07545D73D78F1A545D6E294BE7A4BF3D34BF23319355CC80
10:40:58.948 [INFO ] - Node slot: 0
10:40:58.948 [INFO ] - Node time: 0
10:41:00.022 [INFO ] - Initial state root is 0xAA48CB73258733B18CCC90E565074C3D3B8958312CD4346EA441D3CF2BCB8588
10:41:00.022 [INFO ] - Genesis block root is 0x010E77C10B6AD09B59ED1D47A8B6DEC78F93C7B342FE10FEA0BD41B23A7A6ADD
Jul 10, 2019 10:41:00 AM com.google.common.eventbus.EventBus$LoggingHandler handleException
SEVERE: Exception thrown by subscriber method onGenesisHeadStateEvent(tech.pegasys.artemis.statetransition.GenesisHeadStateEvent) on subscriber tech.pegasys.artemis.validator.coordinator.ValidatorCoordinator@3ffb3598 when dispatching event: tech.pegasys.artemis.statetransition.GenesisHeadStateEvent@1f137bcd
java.lang.ArithmeticException: / by zero
	at com.google.common.primitives.UnsignedLongs.remainder(UnsignedLongs.java:294)
	at com.google.common.primitives.UnsignedLong.mod(UnsignedLong.java:171)
	at tech.pegasys.artemis.datastructures.util.BeaconStateUtil.get_beacon_proposer_index(BeaconStateUtil.java:592)
	at tech.pegasys.artemis.validator.coordinator.ValidatorCoordinator.createBlockIfNecessary(ValidatorCoordinator.java:403)
	at tech.pegasys.artemis.validator.coordinator.ValidatorCoordinator.onNewHeadStateEvent(ValidatorCoordinator.java:258)
	at tech.pegasys.artemis.validator.coordinator.ValidatorCoordinator.onGenesisHeadStateEvent(ValidatorCoordinator.java:187)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)


> Task :run FAILED
```

`config.toml`
```
[deposit]
# normal, test, simulation
# "test" pre-production
# "simulation" to run a simulation of deposits with ganache-cli, if a inputFile is included the file will replay the deposits
# "normal" production, must include contractAddr and nodeUrl
mode = "simulation"
inputFile = "validator_test_data.json"
numValidators = 16
numNodes = 1
contractAddr = "0x77f7bED277449F51505a4C54550B074030d989bC"
nodeUrl = "http://localhost:7545"
```

**Comment by dangerousfood** [comment]
@cemozerr debugged this and found the issue was that the was the `bls_verify` method in `BlockProcessorUtil.process_deposits` that is failing to validate the `BLSSignature` from the `validator_test_data.json`.

Any fix should wait until issue #771 is resolved that will allow a more robust tool set to make a fix.
