### ISSUE TITLE
`/eth/v1/beacon/rewards/attestations/{epoch}` endpoint crashes post-Deneb

### ISSUE THREAD

**Issue by eth2353** [Consensys-Incorporated/teku#7957]
### Description
The `/eth/v1/beacon/rewards/attestations/{epoch}` ( and possibly other beacon API endpoints ) crash after the Deneb fork.

### Steps to Reproduce (Bug)

On a Holesky node, call the rewards endpoint `curl -X POST http://localhost:5555/eth/v1/beacon/rewards/attestations/29699`.

**Expected behavior:** [What you expect to happen]

The endpoint returns a 200 status code and rewards data.

**Actual behavior:** [What actually happens]

The endpoint returns a 400 status code with an error message - `Expected class tech.pegasys.teku.spec.logic.versions.altair.helpers.BeaconStateAccessorsAltair but it was class tech.pegasys.teku.spec.logic.versions.deneb.helpers.BeaconStateAccessorsDeneb`

Logs from beacon node:

```
consensus  | 2024-02-07T12:04:45.663723378Z 2024-02-07 12:04:45.661 ERROR - Error calculating detailed rewards and penalties
consensus  | 2024-02-07T12:04:45.663781978Z java.lang.IllegalArgumentException: Expected class tech.pegasys.teku.spec.logic.versions.altair.helpers.BeaconStateAccessorsAltair but it was class tech.pegasys.teku.spec.logic.versions.deneb.helpers.BeaconStateAccessorsDeneb
consensus  | 2024-02-07T12:04:45.663792779Z at com.google.common.base.Preconditions.checkArgument(Preconditions.java:445) ~[guava-32.1.3-jre.jar:?]
consensus  | 2024-02-07T12:04:45.663799459Z at tech.pegasys.teku.spec.logic.versions.altair.helpers.BeaconStateAccessorsAltair.required(BeaconStateAccessorsAltair.java:216) ~[teku-ethereum-spec-24.1.1.jar:24.1.1]
consensus  | 2024-02-07T12:04:45.663805819Z at tech.pegasys.teku.api.rewards.EpochAttestationRewardsCalculator.idealAttestationRewards(EpochAttestationRewardsCalculator.java:104) ~[teku-data-provider-24.1.1.jar:24.1.1]
consensus  | 2024-02-07T12:04:45.663811899Z at tech.pegasys.teku.api.rewards.EpochAttestationRewardsCalculator.calculate(EpochAttestationRewardsCalculator.java:85) ~[teku-data-provider-24.1.1.jar:24.1.1]
consensus  | 2024-02-07T12:04:45.663817779Z at tech.pegasys.teku.api.ChainDataProvider.lambda$calculateAttestationRewardsAtEpoch$39(ChainDataProvider.java:642) ~[teku-data-provider-24.1.1.jar:24.1.1]
consensus  | 2024-02-07T12:04:45.663823739Z at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(Unknown Source) ~[?:?]
consensus  | 2024-02-07T12:04:45.663829139Z at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(Unknown Source) ~[?:?]
consensus  | 2024-02-07T12:04:45.663834539Z at java.base/java.util.concurrent.CompletableFuture.thenApply(Unknown Source) ~[?:?]
consensus  | 2024-02-07T12:04:45.663839939Z at tech.pegasys.teku.infrastructure.async.SafeFuture.thenApply(SafeFuture.java:460) ~[teku-infrastructure-async-24.1.1.jar:24.1.1]
consensus  | 2024-02-07T12:04:45.663867299Z at tech.pegasys.teku.api.ChainDataProvider.calculateAttestationRewardsAtEpoch(ChainDataProvider.java:625) ~[teku-data-provider-24.1.1.jar:24.1.1]
consensus  | 2024-02-07T12:04:45.663873939Z at tech.pegasys.teku.beaconrestapi.handlers.v1.rewards.GetAttestationRewards.handleRequest(GetAttestationRewards.java:125) ~[teku-data-beaconrestapi-24.1.1.jar:24.1.1]
consensus  | 2024-02-07T12:04:45.663879939Z at tech.pegasys.teku.infrastructure.restapi.endpoints.JavalinEndpointAdapter.handle(JavalinEndpointAdapter.java:36) ~[teku-infrastructure-restapi-24.1.1.jar:24.1.1]
consensus  | 2024-02-07T12:04:45.663885739Z at io.javalin.routing.HandlerEntry.handle(HandlerEntry.kt:19) ~[javalin-5.6.3.jar:5.6.3]
consensus  | 2024-02-07T12:04:45.663892699Z at io.javalin.http.servlet.DefaultTasks.HTTP$lambda$8$lambda$6$lambda$5(DefaultTasks.kt:39) ~[javalin-5.6.3.jar:5.6.3]
consensus  | 2024-02-07T12:04:45.663898459Z at io.javalin.http.servlet.JavalinServlet.handleTask(JavalinServlet.kt:88) [javalin-5.6.3.jar:5.6.3]
consensus  | 2024-02-07T12:04:45.663903979Z at io.javalin.http.servlet.JavalinServlet.handleSync(JavalinServlet.kt:53) [javalin-5.6.3.jar:5.6.3]
consensus  | 2024-02-07T12:04:45.663909419Z at io.javalin.http.servlet.JavalinServlet.service(JavalinServlet.kt:41) [javalin-5.6.3.jar:5.6.3]
consensus  | 2024-02-07T12:04:45.663915139Z at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587) [jetty-jakarta-servlet-api-5.0.2.jar:?]
consensus  | 2024-02-07T12:04:45.663920659Z at io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:58) [javalin-5.6.3.jar:5.6.3]
consensus  | 2024-02-07T12:04:45.663927299Z at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587) [jetty-jakarta-servlet-api-5.0.2.jar:?]
consensus  | 2024-02-07T12:04:45.663933019Z at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764) [jetty-servlet-11.0.17.jar:11.0.17]
consensus  | 2024-02-07T12:04:45.663939099Z at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529) [jetty-servlet-11.0.17.jar:11.0.17]
consensus  | 2024-02-07T12:04:45.663944579Z at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221) [jetty-server-11.0.17.jar:11.0.17]
consensus  | 2024-02-07T12:04:45.663950139Z at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570) [jetty-server-11.0.17.jar:11.0.17]
consensus  | 2024-02-07T12:04:45.663955659Z at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221) [jetty-server-11.0.17.jar:11.0.17]
consensus  | 2024-02-07T12:04:45.663961500Z at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381) [jetty-server-11.0.17.jar:11.0.17]
consensus  | 2024-02-07T12:04:45.663967100Z at io.javalin.jetty.JettyServer$start$wsAndHttpHandler$1.doHandle(JettyServer.kt:61) [javalin-5.6.3.jar:5.6.3]
consensus  | 2024-02-07T12:04:45.663972620Z at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176) [jetty-server-11.0.17.jar:11.0.17]
consensus  | 2024-02-07T12:04:45.663978140Z at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484) [jetty-servlet-11.0.17.jar:11.0.17]
consensus  | 2024-02-07T12:04:45.663983660Z at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543) [jetty-server-11.0.17.jar:11.0.17]
consensus  | 2024-02-07T12:04:45.663989500Z at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174) [jetty-server-11.0.17.jar:11.0.17]
consensus  | 2024-02-07T12:04:45.664001260Z at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303) [jetty-server-11.0.17.jar:11.0.17]
consensus  | 2024-02-07T12:04:45.664007260Z at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129) [jetty-server-11.0.17.jar:11.0.17]
consensus  | 2024-02-07T12:04:45.664012860Z at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) [jetty-server-11.0.17.jar:11.0.17]
consensus  | 2024-02-07T12:04:45.664018420Z at org.eclipse.jetty.server.Server.handle(Server.java:563) [jetty-server-11.0.17.jar:11.0.17]
consensus  | 2024-02-07T12:04:45.664023820Z at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598) [jetty-server-11.0.17.jar:11.0.17]
consensus  | 2024-02-07T12:04:45.664029500Z at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753) [jetty-server-11.0.17.jar:11.0.17]
consensus  | 2024-02-07T12:04:45.664037460Z at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501) [jetty-server-11.0.17.jar:11.0.17]
consensus  | 2024-02-07T12:04:45.664042940Z at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287) [jetty-server-11.0.17.jar:11.0.17]
consensus  | 2024-02-07T12:04:45.664048460Z at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314) [jetty-io-11.0.17.jar:11.0.17]
consensus  | 2024-02-07T12:04:45.664054220Z at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) [jetty-io-11.0.17.jar:11.0.17]
consensus  | 2024-02-07T12:04:45.664059780Z at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) [jetty-io-11.0.17.jar:11.0.17]
consensus  | 2024-02-07T12:04:45.664065420Z at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421) [jetty-util-11.0.17.jar:11.0.17]
consensus  | 2024-02-07T12:04:45.664071220Z at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390) [jetty-util-11.0.17.jar:11.0.17]
consensus  | 2024-02-07T12:04:45.664077020Z at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277) [jetty-util-11.0.17.jar:11.0.17]
consensus  | 2024-02-07T12:04:45.664082820Z at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199) [jetty-util-11.0.17.jar:11.0.17]
consensus  | 2024-02-07T12:04:45.664088540Z at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411) [jetty-util-11.0.17.jar:11.0.17]
consensus  | 2024-02-07T12:04:45.664094220Z at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969) [jetty-util-11.0.17.jar:11.0.17]
consensus  | 2024-02-07T12:04:45.664100300Z at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194) [jetty-util-11.0.17.jar:11.0.17]
consensus  | 2024-02-07T12:04:45.664106100Z at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149) [jetty-util-11.0.17.jar:11.0.17]
consensus  | 2024-02-07T12:04:45.664111780Z at java.base/java.lang.Thread.run(Unknown Source) [?:?]
```

**Frequency:** [How regularly does it occur?]

100% of the time

### Versions (Add all that apply)

Using the official 24.1.1 docker image

* Software version: 24.1.1
* Java version: openjdk 17.0.9 2023-10-17
* OS Name & Version: Ubuntu 22.04.3 LTS
* Docker Version: Client 24.0.7
* Cloud VM, type, size: N/A

**Comment by zilm13** [comment]
Thank you @eth2353 for feedback, we have fixed the issue, the fix will be part of the upcoming release
