### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by carameleon** [Consensys-Incorporated/teku#8012]
### Description

Hi. I used teku-nethermind for ethereum full node on `holesky`.

I used ```JAVA_OPTS=-Xms5g -Xmx5g``` and it sometimes errors related heap space.
(https://docs.teku.consensys.io/get-started/manage-memory)

Generally, it was recovered by `restart: unless-stopped` within 5-10mins.

I observed several times.
```
teku  | 2024-02-16T21:30:36.647544708Z 21:30:36.647 FATAL - Exiting due to fatal error in p2p-async-3 java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
teku  | 2024-02-16T21:30:36.648029004Z 21:30:28.102 FATAL - Exiting due to fatal error in ForkJoinPool.commonPool-worker-4 java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
teku  | 2024-02-16T21:30:48.739830874Z 21:30:35.153 FATAL - Exiting due to fatal error in vertx-blocked-thread-checker java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
teku  | 2024-02-16T21:30:50.998104798Z 21:30:45.822 FATAL - Exiting due to fatal error in AggregatingSignatureVerificationService-async-5 java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
teku  | 2024-02-19T19:08:24.302516922Z 19:08:24.301 FATAL - Exiting due to fatal error in qtp1327124814-102354 java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
teku  | 2024-02-19T19:10:31.993739178Z 19:10:29.560 FATAL - Exiting due to fatal error in qtp1327124814-102300 java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
teku  | 2024-02-19T19:12:12.773260250Z 19:12:12.773 FATAL - Exiting due to fatal error in ValidatorApiChannel-3 java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
teku  | 2024-02-19T19:12:12.773281951Z 19:12:12.773 FATAL - Exiting due to fatal error in ValidatorApiChannel-1 java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
teku  | 2024-02-19T19:12:12.780651971Z 19:12:12.780 FATAL - Exiting due to fatal error in SlotEventsChannel-8 java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
teku  | 2024-02-19T19:12:12.818303574Z 19:12:12.817 ERROR - PLEASE FIX OR REPORT | Unexpected exception thrown for pool-4-thread-171 java.util.concurrent.CompletionException: java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
teku  | 2024-02-20T10:31:39.344578665Z 10:31:39.343 FATAL - Exiting due to fatal error in RetryingStorageUpdateChannel tech.pegasys.teku.infrastructure.exceptions.FatalServiceFailureException: java.util.concurrent.CompletionException: java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
teku  | 2024-02-21T22:21:00.810340503Z Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "qtp165796479-51449"
teku  | 2024-02-21T22:23:47.314109229Z 22:23:47.313 FATAL - Exiting due to fatal error in ValidatorApiChannel-5 java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
teku  | 2024-02-21T22:24:16.749947206Z 22:24:16.749 FATAL - Exiting due to fatal error in qtp165796479-51457 java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
teku  | 2024-02-21T22:24:17.884578170Z 22:24:17.884 FATAL - Exiting due to fatal error in qtp165796479-50777 java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
teku  | 2024-02-21T22:24:17.884661561Z 22:24:17.884 FATAL - Exiting due to fatal error in powchain-async-22877 java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
teku  | 2024-02-21T22:24:17.884727962Z 22:24:17.884 FATAL - Exiting due to fatal error in qtp165796479-51495 java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
teku  | 2024-02-21T22:24:17.884794896Z 22:24:17.884 FATAL - Exiting due to fatal error in ForkJoinPool.commonPool-worker-11 java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
teku  | 2024-02-21T22:24:18.966580438Z 22:23:47.313 FATAL - Exiting due to fatal error in RxCachedWorkerPoolEvictor-1 java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
teku  | 2024-02-21T22:24:24.135348643Z 22:24:24.135 FATAL - Exiting due to fatal error in vert.x-acceptor-thread-0 java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
teku  | 2024-02-21T22:24:32.184475010Z  org.apache.logging.log4j.core.appender.AppenderLoggingException: java.lang.OutOfMemoryError: Java heap space
teku  | 2024-02-21T22:24:43.995313348Z Caused by: java.lang.OutOfMemoryError: Java heap space
teku  | 2024-02-21T22:24:43.995603623Z 22:24:18.968 FATAL - Exiting due to fatal error in OkHttp TaskRunner java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
teku  | 2024-02-21T22:26:08.452239683Z 22:26:08.451 FATAL - Exiting due to fatal error in qtp165796479-51494 java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
teku  | 2024-02-21T22:26:52.261807271Z 22:26:52.261 FATAL - Exiting due to fatal error in beaconchain-async-13 java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
teku  | 2024-02-21T22:27:06.176723643Z 22:27:06.176 FATAL - Exiting due to fatal error in RxCachedWorkerPoolEvictor-2 java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
teku  | 2024-02-22T02:35:39.223305540Z Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Okio Watchdog"
teku  | 2024-02-22T02:36:35.992451689Z  02:36:35.990 FATAL - Exiting due to fatal error in qtp1722180384-5467 java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
teku  | 2024-02-22T02:36:35.992860885Z org.apache.logging.log4j.core.appender.AppenderLoggingException: java.lang.OutOfMemoryError: Java heap space
teku  | 2024-02-22T02:36:35.993819141Z Caused by: java.lang.OutOfMemoryError: Java heap space
teku  | 2024-02-22T02:36:35.996424198Z 02:36:35.996 FATAL - Exiting due to fatal error in events-async-1578 java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
teku  | 2024-02-25T04:06:17.888334306Z  04:06:17.887 FATAL - Exiting due to fatal error in qtp865164223-105135 java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
teku  | 2024-02-25T04:06:17.888349801Z 04:06:17.887 FATAL - Exiting due to fatal error in qtp865164223-103991 java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
teku  | 2024-02-25T04:06:17.891316429Z 04:06:17.891 FATAL - Exiting due to fatal error in qtp865164223-104940 java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
teku  | 2024-02-25T04:06:17.896493366Z org.apache.logging.log4j.core.appender.AppenderLoggingException: java.lang.OutOfMemoryError: Java heap space
teku  | 2024-02-25T04:06:17.909507467Z Caused by: java.lang.OutOfMemoryError: Java heap space
teku  | 2024-02-25T04:06:17.911404740Z 04:06:17.900 ERROR - Execution Client request failed. Make sure the Execution Client is online and can respond to requests. java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
teku  | 2024-02-25T04:06:17.911754325Z 04:06:17.900 FATAL - Exiting due to fatal error in Okio Watchdog java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
```

However, in this case, it stuck after following teku logs. (heap space error)

execution client : nethermind:1.25.3
nethermind logs : 
```
nethermind  | 25 Feb 03:44:48 | Processed block is not valid 1014617 (0x66c04eb39de8bb99164eaa2c47dd2e356d664cb837f5727ace510e6d8ad89160)
nethermind  | 25 Feb 03:44:48 | Suggested block TD: 1, Suggested block IsPostMerge True, Block TD: 1, Block IsPostMerge True
nethermind  | 25 Feb 03:44:48 | Created a Receipts trace of invalid block 0x66c04eb39de8bb99164eaa2c47dd2e356d664cb837f5727ace510e6d8ad89160 in file /tmp/receipts_0x66c04eb39de8bb99164eaa2c47dd2e356d664cb837f5727ace510e6d8ad89160.txt
nethermind  | 25 Feb 03:44:48 | Deleting invalid block 0x66c04eb39de8bb99164eaa2c47dd2e356d664cb837f5727ace510e6d8ad89160 at level 1014617
nethermind  | 25 Feb 03:44:48 | Invalid block found. Validation message: Block processing failed.. Result of new block:  1014617 (0x66c04e...d89160).
nethermind  | 25 Feb 03:45:11 | Received ForkChoice: Head: 1014616 (0xbb9f44...e2674a), Safe: 1014573 (0xe8218a...dd73d2), Finalized: 1014544 (0x5f2778...761415)
nethermind  | 25 Feb 03:45:56 | Peers | with best block: 48 | all: 48 | eth66 (10 %), eth67 (15 %), eth68 (75 %) | Active: None | Sleeping: All | Geth (42 %), Erigon (27 %), Nethermind (25 %), Reth (4 %), Besu (2 %)
nethermind  | 25 Feb 03:47:05 | Removing 1875 out of 11875 peer candidates (candidates cleanup).
nethermind  | 25 Feb 03:47:11 | Peers | with best block: 50 | all: 50 | eth66 (12 %), eth67 (14 %), eth68 (74 %) | Active: None | Sleeping: All | Geth (42 %), Erigon (26 %), Nethermind (26 %), Reth (4 %), Besu (2 %)
nethermind  | 25 Feb 03:48:26 | Peers | with best block: 49 | all: 49 | eth66 (12 %), eth67 (14 %), eth68 (73 %) | Active: None | Sleeping: All | Geth (43 %), Erigon (27 %), Nethermind (24 %), Reth (4 %), Besu (2 %)
nethermind  | 25 Feb 03:48:34 | ***** JSON RPC report *****
nethermind  | -------------------------------------------------------------------------------------------------------------------------------------------------------------
nethermind  | method                                  | successes |  avg time (µs) |  max time (µs) |    errors |  avg time (µs) |  max time (µs) | avg size | total size |
nethermind  | -------------------------------------------------------------------------------------------------------------------------------------------------------------
nethermind  | engine_forkchoiceUpdatedV3              |         8 |            771 |           1081 |         0 |              0 |              0 |      202 |       1616 |
nethermind  | engine_newPayloadV3                     |         7 |          92511 |         140777 |         0 |              0 |              0 |      170 |       1193 |
nethermind  | eth_chainId                             |         3 |            274 |            564 |         0 |              0 |              0 |       47 |        141 |
nethermind  | eth_getBlockByNumber                    |        42 |            512 |           1363 |         0 |              0 |              0 |     4858 |     204030 |
nethermind  | eth_getLogs                             |        17 |            311 |            952 |         0 |              0 |              0 |       41 |        690 |
nethermind  | eth_syncing                             |        10 |            101 |            364 |         0 |              0 |              0 |       43 |        433 |
nethermind  | -------------------------------------------------------------------------------------------------------------------------------------------------------------
nethermind  | TOTAL                                   |        87 |           7844 |         140777 |         0 |              0 |              0 |     2392 |     208103 |
nethermind  | -------------------------------------------------------------------------------------------------------------------------------------------------------------
nethermind  |
nethermind  | 25 Feb 03:48:53 | Removing 958 out of 10958 peer candidates (candidates cleanup).
nethermind  | 25 Feb 03:49:41 | Peers | with best block: 49 | all: 49 | eth66 (12 %), eth67 (14 %), eth68 (73 %) | Active: None | Sleeping: All | Geth (43 %), Erigon (27 %), Nethermind (24 %), Reth (4 %), Besu (2 %)
nethermind  | 25 Feb 03:50:19 | No incoming messages from the consensus client that is required for sync.
nethermind  | 25 Feb 03:50:24 | No incoming messages from the consensus client that is required for sync.
nethermind  | 25 Feb 03:50:29 | No incoming messages from the consensus client that is required for sync.
nethermind  | 25 Feb 03:50:34 | No incoming messages from the consensus client that is required for sync.
nethermind  | 25 Feb 03:50:39 | No incoming messages from the consensus client that is required for sync.
```

teku logs : 
```
teku  | 03:45:11.042 INFO  - Slot Event  *** Slot: 1077525, Block:                                                        ... empty, Justified: 33671, Finalized: 33670, Peers: 91
teku  | 03:48:33.500 WARN  - Eth1 service down or still syncing for 48s, retrying
teku  | 03:48:40.298 WARN  - Request for eth1 deposit logs from 10000 blocks failed. Retrying with a smaller block range.
teku  | 03:54:34.917 WARN  - Request for eth1 deposit logs from 10000 blocks failed. Retrying with a smaller block range.
teku  | 04:03:45.774 WARN  - Request for eth1 deposit logs from 10000 blocks failed. Retrying with a smaller block range.
teku  | 04:04:28.181 INFO  - Slot Event  *** Slot: 1077526, Block:                                                        ... empty, Justified: 33671, Finalized: 33670, Peers: 34
teku  | ERROR StatusConsoleListener An exception occurred processing Appender teku-log-appender
teku  |  04:06:17.887 FATAL - Exiting due to fatal error in qtp865164223-105135 java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
teku  | 04:06:17.887 FATAL - Exiting due to fatal error in qtp865164223-103991 java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
teku  | Teku is shutting down
teku  | 04:06:17.891 FATAL - Exiting due to fatal error in qtp865164223-104940 java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
teku  | org.apache.logging.log4j.core.appender.AppenderLoggingException: java.lang.OutOfMemoryError: Java heap space
teku  | 	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:164)
teku  | 	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:133)
teku  | 	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:124)
teku  | 	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:88)
teku  | 	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:705)
teku  | 	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:663)
teku  | 	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:639)
teku  | 	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:575)
teku  | 	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:92)
teku  | 	at org.apache.logging.log4j.core.Logger.log(Logger.java:169)
teku  | 	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2933)
teku  | 	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2886)
teku  | 	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2868)
teku  | 	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2675)
teku  | 	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:2442)
teku  | 	at org.apache.logging.log4j.spi.AbstractLogger.warn(AbstractLogger.java:3685)
teku  | 	at tech.pegasys.teku.networking.eth2.gossip.topics.topichandlers.Eth2TopicHandler.handleMessageProcessingError(Eth2TopicHandler.java:175)
teku  | 	at tech.pegasys.teku.networking.eth2.gossip.topics.topichandlers.Eth2TopicHandler.lambda$handleMessage$4(Eth2TopicHandler.java:124)
teku  | 	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source)
teku  | 	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(Unknown Source)
teku  | 	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
teku  | 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
teku  | 	at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:144)
teku  | 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
teku  | 	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(Unknown Source)
teku  | 	at java.base/java.util.concurrent.CompletableFuture.whenComplete(Unknown Source)
teku  | 	at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:619)
teku  | 	at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:31)
teku  | 	at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:141)
teku  | 	at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateTo(SafeFuture.java:317)
teku  | 	at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:124)
teku  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
teku  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
teku  | 	at java.base/java.lang.Thread.run(Unknown Source)
teku  | Caused by: java.lang.OutOfMemoryError: Java heap space
teku  | 04:06:17.894 WARN  - Eth1 service down or still syncing for 133s, retrying
teku  | 04:06:17.900 ERROR - Execution Client request failed. Make sure the Execution Client is online and can respond to requests. java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
teku  | 04:06:17.900 FATAL - Exiting due to fatal error in Okio Watchdog java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
teku  | 04:06:17.928 INFO  - Miss slots  *** Current slot: 1077631, previous slot: 1077527
teku  | 04:06:18.176 INFO  - Slot Event  *** Slot: 1077631, Block:                                                        ... empty, Justified: 33671, Finalized: 33670, Peers: 7
teku  | 04:06:24.792 INFO  - Epoch Event *** Epoch: 33676, Justified checkpoint: 33671, Finalized checkpoint: 33670, Finalized root: e1f4d278453df4589d75039bc28f7869e1aa228676dcb6a8e50c061ed450369b

teku stuck at this logs.
```

### Steps to Reproduce (Bug)

I have no ideas how to reproduce it.

But I've used `JAVA_OPTS=-Xms5g -Xmx5g`.

And now I changed config to `JAVA_OPTS=-Xmx5g` instead of `JAVA_OPTS=-Xms5g -Xmx5g`.

**Frequency:** [How regularly does it occur?]

2-3times per week

### Versions (Add all that apply)
* Software version: [`teku --version` or look for log lines starting with `Teku version:`]
```
docker
Teku version: teku/v24.1.1/linux-x86_64/-eclipseadoptium-openjdk64bitservervm-java-17
```
* Java version: [`java -version`]
```
docker 
Teku version: teku/v24.1.1/linux-x86_64/-eclipseadoptium-openjdk64bitservervm-java-17
```
* OS Name & Version: [`cat /etc/*release`]
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
```
* Docker Version: [`docker version`] :  
```
Client: Docker Engine - Community
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:52:22 2023
 OS/Arch:           linux/amd64
 Context:           default
```
* Cloud VM, type, size: [Amazon Web Services I3-large]
```
baremetal
- Intel(R) Xeon(R) E-2386G CPU @ 3.50GHz
- 64GB ram
- NVMe ssd
```

**Comment by rolfyone** [comment]
Holesky is getting quite large, we're currently running 6g and it does seem ok (-Xmx).
It's definitely possible for the memory to be not sufficient - 5g used to be sufficient on holesky but as the state does continue to grow, it's possible we may hit this from time to time, even with tweaks to memory usage.
My recommendation would be to increase heap (-Xmx) to 6g, and probably just remove `-Xms`. If you have a stack of spare memory you could raise it higher - or monitor Garbage collection via grafana and try to keep it below 2%, ideally closer to 1%.

**Comment by carameleon** [comment]
Thanks @rolfyone. I also increase the maximum heap size. Also thank you for providing specification on gc monitoring.
