### ISSUE TITLE
Start From Disk Edge Case Bug

### ISSUE THREAD

**Issue by cemozerr** [Consensys-Incorporated/teku#962]
### Description
Currently, any time Artemis is restarted from disk and hadn't finalized in the previous run, it fails to start up. 

### Steps to Reproduce (Bug)
1. Start with a clear disk (i.e. set startFromDisk to false)
2. Stop the run before Artemis starts finalizing again (in about 3 epochs)
3. Start from the disk again (i.e. set startFromDisk to true)

> Task :run
Setting logging level to INFO
12:50:16.775 [INFO ] - Starting with mocked start interoperability mode with genesis time 1572022221 and 64 validators
12:50:19.814 [INFO ] - 2 seconds until genesis.
12:50:20.466 [INFO ] - Using the database to load Store and thus the previously built Store will be overwritten.
Artemis failed to start.
java.lang.NullPointerException
	at org.mapdb.HTreeMap.get(HTreeMap.kt:596)
	at tech.pegasys.artemis.storage.Database.lambda$createMemoryStore$0(Database.java:169)
	at java.base/java.util.stream.Streams$RangeLongSpliterator.forEachRemaining(Streams.java:228)
	at java.base/java.util.stream.LongPipeline$Head.forEach(LongPipeline.java:577)
	at tech.pegasys.artemis.storage.Database.createMemoryStore(Database.java:161)
	at tech.pegasys.artemis.storage.Database.<init>(Database.java:143)
	at tech.pegasys.artemis.storage.ChainStorageServer.<init>(ChainStorageServer.java:35)
	at tech.pegasys.artemis.services.chainstorage.ChainStorageService.init(ChainStorageService.java:27)
	at tech.pegasys.artemis.service.serviceutils.ServiceController.initAll(ServiceController.java:49)
	at tech.pegasys.artemis.BeaconNode.start(BeaconNode.java:80)
	at tech.pegasys.artemis.BeaconNodeCommand.call(BeaconNodeCommand.java:65)
	at tech.pegasys.artemis.BeaconNodeCommand.call(BeaconNodeCommand.java:24)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1743)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2101)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2068)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1935)
	at picocli.CommandLine.execute(CommandLine.java:1864)
	at tech.pegasys.artemis.Artemis.main(Artemis.java:23)

**Comment by rolfyone** [comment]
I've tried a bunch of timings to cause this, but it's proven difficult.

@cemozerr are you still able to produce this issue? the stack looks really different, it's very possible that refactors have made this into a non issue...

**Comment by cemozerr** [comment]
I'm not sure if it's the same exact issue, but I'm having a similar error right now.

```
Teku failed to start.
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: List out of bounds
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:412)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2044)
	at tech.pegasys.artemis.BeaconNode.start(BeaconNode.java:89)
	at tech.pegasys.artemis.BeaconNodeCommand.call(BeaconNodeCommand.java:75)
	at tech.pegasys.artemis.BeaconNodeCommand.call(BeaconNodeCommand.java:27)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
	at picocli.CommandLine.execute(CommandLine.java:1904)
	at tech.pegasys.artemis.Artemis.main(Artemis.java:23)
Caused by: java.lang.IllegalArgumentException: List out of bounds
	at tech.pegasys.artemis.util.SSZTypes.SSZArrayCollection.add(SSZArrayCollection.java:70)
	at tech.pegasys.artemis.datastructures.util.SimpleOffsetSerializer.deserializeFixedElementList(SimpleOffsetSerializer.java:420)
	at tech.pegasys.artemis.datastructures.util.SimpleOffsetSerializer.deserializeVariableParts(SimpleOffsetSerializer.java:332)
	at tech.pegasys.artemis.datastructures.util.SimpleOffsetSerializer.deserializeContainer(SimpleOffsetSerializer.java:232)
	at tech.pegasys.artemis.datastructures.util.SimpleOffsetSerializer.deserializeContainerErrorWrapper(SimpleOffsetSerializer.java:208)
	at tech.pegasys.artemis.datastructures.util.SimpleOffsetSerializer.lambda$deserialize$1(SimpleOffsetSerializer.java:199)
	at org.apache.tuweni.ssz.SSZ.decode(SSZ.java:1255)
	at tech.pegasys.artemis.datastructures.util.SimpleOffsetSerializer.deserialize(SimpleOffsetSerializer.java:197)
	at tech.pegasys.artemis.storage.utils.MapDBSerializer.deserialize(MapDBSerializer.java:41)
	at tech.pegasys.artemis.storage.utils.MapDBSerializer.deserialize(MapDBSerializer.java:24)
	at org.mapdb.StoreDirectAbstract.deserialize(StoreDirectAbstract.kt:229)
	at org.mapdb.StoreWAL.get(StoreWAL.kt:508)
	at org.mapdb.HTreeMap.valueUnwrap(HTreeMap.kt:1198)
	at org.mapdb.HTreeMap$entries$1$iterator$$inlined$map$lambda$1.invoke(HTreeMap.kt:941)
	at org.mapdb.HTreeMap$entries$1$iterator$$inlined$map$lambda$1.invoke(HTreeMap.kt:927)
	at org.mapdb.HTreeMap$htreeIterator$1.moveToNextLeaf(HTreeMap.kt:1058)
	at org.mapdb.HTreeMap$htreeIterator$1.<init>(HTreeMap.kt:1045)
	at org.mapdb.HTreeMap.htreeIterator(HTreeMap.kt:1035)
	at org.mapdb.HTreeMap$entries$1.iterator(HTreeMap.kt:940)
	at java.base/java.util.concurrent.ConcurrentHashMap.putAll(ConcurrentHashMap.java:1088)
	at java.base/java.util.concurrent.ConcurrentHashMap.<init>(ConcurrentHashMap.java:852)
	at tech.pegasys.artemis.storage.Store.<init>(Store.java:75)
	at tech.pegasys.artemis.storage.MapDbDatabase.createMemoryStore(MapDbDatabase.java:325)
	at tech.pegasys.artemis.storage.ChainStorageServer.getStore(ChainStorageServer.java:67)
	at tech.pegasys.artemis.storage.ChainStorageServer.start(ChainStorageServer.java:60)
	at tech.pegasys.artemis.util.async.SafeFuture.fromRunnable(SafeFuture.java:89)
	at tech.pegasys.artemis.services.chainstorage.ChainStorageService.doStart(ChainStorageService.java:30)
	at tech.pegasys.artemis.service.serviceutils.Service.start(Service.java:33)
	at tech.pegasys.artemis.services.ServiceController.doStart(ServiceController.java:41)
	at tech.pegasys.artemis.service.serviceutils.Service.start(Service.java:33)
	... 11 more
```

This one happened after I started Teku, to continue sync to Lighthouse testnet, stopped it quickly after, and restarted again. As a result, it seems like I corrupted the disk somehow by doing that.

**Comment by rolfyone** [comment]
I tried by killing the server with CTRL+C to no avail - were you using kill -9 or something? mine seems to gracefully stand back up every time...

**Comment by macfarla** [comment]
look for lh.config in ziz chat

**Comment by macfarla** [comment]
I am also unable to reproduce this issue. 
09:14:04.454 [INFO ] - Slot Event *** Current slot: 371470, Head block: 0, Justified epoch: 0, Finalized epoch: 0, Finalized root: 0x3c16..59a4
09:14:16.453 [INFO ] - Slot Event *** Current slot: 371471, Head block: 0, Justified epoch: 0, Finalized epoch: 0, Finalized root: 0x3c16..59a4
09:14:24.467 [INFO ] - Sync Event *** Current slot: 371472, Head block: 8, Connected peers: 13
09:14:36.462 [INFO ] - Sync Event *** Current slot: 371473, Head block: 38, Connected peers: 13
09:14:48.481 [INFO ] - Sync Event *** Current slot: 371474, Head block: 76, Connected peers: 13
09:15:00.462 [INFO ] - Sync Event *** Current slot: 371475, Head block: 113, Connected peers: 17
09:15:12.464 [INFO ] - Sync Event *** Current slot: 371476, Head block: 127, Connected peers: 17

**Comment by macfarla** [comment]
from Cem: We now always start from disk when we’re able to find a database, so the problem might still be persisting
The hard part about it is that this bug happened to me only once over the past few week in over 20 runs. So its really hard to reproduce.
9:24
It might just be solved, but I’d say lets keep it for another week or so before we’re confident with deleting the issue.
