### ISSUE TITLE
Better error message when using peer generate

### ISSUE THREAD

**Issue by MadelineMurray** [Consensys-Incorporated/teku#977]
# Description 
As a new user, I want a better error message for `peer generate` so that I know how to generate peer IDs. 

### Acceptance Criteria
* Clear error message when `config` directory doesn't exist when using `peer generate` without the `--outputFile` option. 

### Steps to Reproduce (Bug)
Run `artemis peer generate 3` without first creating `config` directory: 

Following error is displayed: 
```
java.io.FileNotFoundException: ./config/peer-ids.dat (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:292)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:141)
	at tech.pegasys.artemis.PeerCommand.generate(PeerCommand.java:60)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1762)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2101)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2068)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1935)
	at picocli.CommandLine.execute(CommandLine.java:1864)
	at tech.pegasys.artemis.Artemis.main(Artemis.java:23)
```

**Expected behavior:** [What you expect to happen]
Error message displayed indicating that the `config` directory must exist or the `--outputFile` option must be used. 

Also, if the file already exists, the existing keys in the file are overwritten.  Not sure if this is the desired behaviour?

**Comment by macfarla** [comment]
To reproduce:
./bin/teku peer generate --number=3
java.io.FileNotFoundException: ./config/peer-ids.dat (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)

**Comment by macfarla** [comment]
just need to remove the stack trace
